// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2024-present Wired Engine contributors
//
// Native-free deterministic provenance helpers shared by compile.mjs and its
// mutation host. The digest is byte-for-byte compatible with
// Ral_ShaderArtifactDigest and therefore deliberately spells integer encoding
// as little-endian instead of inheriting the host architecture.

const MASK64 = 0xffffffffffffffffn;
const PRIME64 = 0x100000001b3n;
const MAX_ROWS = 4096;
const textEncoder = new TextEncoder();

function newHash() {
	return { lane0: 0xcbf29ce484222325n, lane1: 0x84222325cbf29ce4n };
}

function hashBytesInto(hash, bytes) {
	for (const byte of bytes) {
		hash.lane0 = ((hash.lane0 ^ BigInt(byte)) * PRIME64) & MASK64;
		hash.lane1 = ((hash.lane1 ^ BigInt(byte + 0x9d)) * PRIME64) & MASK64;
		hash.lane1 = (hash.lane1 ^ (hash.lane0 >> 29n)) & MASK64;
	}
}

function u32le(value) {
	if (!Number.isInteger(value) || value < 0 || value > 0xffffffff)
		throw new Error('u32 value out of range');
	return Uint8Array.of(value & 0xff, (value >>> 8) & 0xff,
		(value >>> 16) & 0xff, (value >>> 24) & 0xff);
}

function hashU32(hash, value) { hashBytesInto(hash, u32le(value)); }
function hashString(hash, value) {
	if (typeof value !== 'string') throw new Error('string field required');
	const bytes = textEncoder.encode(value);
	hashU32(hash, bytes.length); hashBytesInto(hash, bytes);
}

function finish(hash) {
	if (hash.lane0 === 0n || hash.lane1 === 0n) throw new Error('zero digest lane');
	return Object.freeze({ lane0: hash.lane0, lane1: hash.lane1 });
}

export function ralShaderArtifactDigest(bytes) {
	if (!(bytes instanceof Uint8Array) || bytes.byteLength === 0)
		throw new Error('non-empty artifact bytes required');
	const hash = newHash();
	hashU32(hash, bytes.byteLength); hashBytesInto(hash, bytes);
	return finish(hash);
}

function shaderInputDigest(entry, sourceBytes) {
	if (!entry || !['vert', 'frag', 'comp'].includes(entry.stage)
			|| typeof entry.source !== 'string' || !entry.source
			|| typeof entry.output !== 'string' || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(entry.output)
			|| !Array.isArray(entry.defines)
			|| !(sourceBytes instanceof Uint8Array) || sourceBytes.byteLength === 0)
		throw new Error('invalid shader provenance input');
	const hash = newHash();
	hashU32(hash, 1); // provenance schema
	hashString(hash, 'glslang:-V');
	hashString(hash, entry.stage);
	hashString(hash, entry.source.replaceAll('\\', '/'));
	hashString(hash, entry.output);
	hashU32(hash, entry.defines.length);
	for (const define of entry.defines) {
		if (typeof define !== 'string' || !/^[A-Za-z_][A-Za-z0-9_]*(=.*)?$/.test(define))
			throw new Error('invalid shader define');
		hashString(hash, define);
	}
	hashU32(hash, sourceBytes.byteLength); hashBytesInto(hash, sourceBytes);
	return finish(hash);
}

export function buildShaderArtifactRow(entry, sourceBytes, spirvBytes, ordinal) {
	const normalized = { ...entry, defines: entry.defines ?? [] };
	if (!Number.isInteger(ordinal) || ordinal < 0 || ordinal >= MAX_ROWS)
		throw new Error('shader ordinal out of range');
	return Object.freeze({
		ordinal,
		output: normalized.output,
		stage: normalized.stage,
		byteCount: spirvBytes.byteLength,
		inputDigest: shaderInputDigest(normalized, sourceBytes),
		artifactDigest: ralShaderArtifactDigest(spirvBytes),
	});
}

function hex64(value) { return `0x${value.toString(16).padStart(16, '0')}ull`; }
function stageToken(stage) {
	return stage === 'vert' ? 'RAL_STAGE_VERTEX'
		: stage === 'frag' ? 'RAL_STAGE_FRAGMENT'
		: stage === 'comp' ? 'RAL_STAGE_COMPUTE' : null;
}

export function renderShaderArtifactCatalog(rows) {
	if (!Array.isArray(rows) || rows.length === 0 || rows.length > MAX_ROWS)
		throw new Error('shader artifact row count out of range');
	const symbols = new Set();
	let text = '// SPDX-License-Identifier: GPL-3.0-or-later\n'
		+ '// SPDX-FileCopyrightText: 2024-present Wired Engine contributors\n'
		+ '/* Generated by compile.mjs from shaders.manifest.mjs. Do not edit. */\n';
	for (let i = 0; i < rows.length; ++i) {
		const row = rows[i]; const stage = row && stageToken(row.stage);
		if (!row || row.ordinal !== i || !stage
				|| !/^[A-Za-z_][A-Za-z0-9_]*$/.test(row.output)
				|| !Number.isInteger(row.byteCount) || row.byteCount <= 0
				|| row.byteCount > 0xffffffff || symbols.has(row.output)
				|| !row.inputDigest || !row.artifactDigest)
			throw new Error('invalid or noncanonical shader artifact row');
		symbols.add(row.output);
		text += `RAL_SHADER_SPIRV_ARTIFACT(${i}u, ${row.output}, ${stage}, ${row.byteCount}u, `
			+ `${hex64(row.inputDigest.lane0)}, ${hex64(row.inputDigest.lane1)}, `
			+ `${hex64(row.artifactDigest.lane0)}, ${hex64(row.artifactDigest.lane1)})\n`;
	}
	return text;
}

export const RAL_SHADER_ARTIFACT_CATALOG_MAX_ROWS = MAX_ROWS;
