// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2024-present Wired Engine contributors

/*
cl_wired_fonts.c -- Wired UI font system (migrated from cg_moderntext.c)
*/
#include "../../client.h"
#include "cl_wired_fonts.h"
#include "cl_wired_msdf.h"
#include "cl_wired_draw.h"
LOG_DECLARE_CHANNEL( ch_ui, "ui" );

#if FEAT_WIRED_UI

/* ── Font family registration table ───────────────────────────────── */

// NOLINTBEGIN(bugprone-invalid-enum-default-initialization) — fixed-size variants[] array zero-fills the tail; tail entries are never read (count field guards), so the 0-weight enum value never reaches consumers
static fontFamily_t wui_fontFamilies[] = {
	// ── Enter Sansman ──────────────────────────────────────────────
	// Each weight is a separate atlas from a FontForge-transformed TTF.
	// Source: entsans.ttf (Bold), entsani.ttf (Bold Italic)
	// Regular/Medium synthesized via changeWeight() at build time.
	// lazy flag (5th field): qtrue atlases are deferred out of the boot load and
	// loaded on first use (measured non-boot-critical in the SL-4c inventory). The
	// regular/main-menu faces (sansman-regular, oxanium, sharetechmono) stay boot-loaded.
	{
		"sansman", {
			{ "sansman-regular",     "sansman-regular",     FONT_WEIGHT_REGULAR, FONT_STYLE_NORMAL,  qfalse, NULL },
			{ "sansman-medium",      "sansman-medium",      FONT_WEIGHT_MEDIUM,  FONT_STYLE_NORMAL,  qtrue,  NULL },
			{ "sansman-bold",        "sansman-bold",         FONT_WEIGHT_BOLD,    FONT_STYLE_NORMAL,  qtrue,  NULL },
			{ "sansman-italic",      "sansman-italic",      FONT_WEIGHT_REGULAR, FONT_STYLE_ITALIC,  qtrue,  NULL },
			{ "sansman-bold-italic", "sansman-bold-italic", FONT_WEIGHT_BOLD,    FONT_STYLE_ITALIC,  qtrue,  NULL },
		}, 5
	},
	// ── Oxanium ────────────────────────────────────────────────────
	// Native Regular + Medium TTFs. No transform needed.
	{
		"oxanium", {
			{ "oxanium-regular",  "oxanium",        FONT_WEIGHT_REGULAR,  FONT_STYLE_NORMAL, qfalse, NULL },
			{ "oxanium-medium",   "oxanium-medium", FONT_WEIGHT_MEDIUM,   FONT_STYLE_NORMAL, qtrue,  NULL },
		}, 2
	},
	// ── Share Tech Mono ────────────────────────────────────────────
	// Single weight, no transform. Modder-facing slot retained; the
	// canonical $font_mono token in _tokens.wui now resolves to JBMono
	// (see entry below) but a mod that explicitly authors
	// `font "sharetechmono"` still resolves through this family.
	{
		"sharetechmono", {
			{ "sharetechmono-regular", "sharetechmono", FONT_WEIGHT_REGULAR, FONT_STYLE_NORMAL, qfalse, NULL },
		}, 1
	},
	// ── JetBrains Mono ─────────────────────────────────────────────
	// Single weight, no transform. Canonical $font_mono target — the
	// v2 design's Mono primitive (qw-shared.jsx) specifies JetBrains
	// Mono; the token re-resolution in _tokens.wui makes every
	// existing $font_mono caller pick this up automatically. Atlas
	// charset covers ASCII printable (0x20..0x7E) plus the punctuation
	// the v2 telemetry strings use (bullet, en/em-dash, smart quotes,
	// diamond/circle markers).
	{
		"jetbrainsmono", {
			{ "jetbrainsmono-regular", "jetbrainsmono", FONT_WEIGHT_REGULAR, FONT_STYLE_NORMAL, qtrue, NULL },
		}, 1
	},
	// ── Wired UI Icons (MSDF icon font) ───────────────────
	// Single weight, PUA codepoints U+E000-U+E007 (see canonical chart in
	// docs/wui-authoring-guide.md §5.3). Atlas is generated by
	// tools/msdf/build_wui_icons.py via `make wui-icons-atlas`; the
	// engine consumes it through the same MSDF pipeline as the text
	// fonts above. The "wui_icons" family is exposed to .wui authors via
	// the `font_icon` token (modfiles/ui/_tokens.wui) so modders can
	// swap the slot in a mod's own _tokens.wui without touching engine
	// code.
	{
		"wui_icons", {
			{ "wui_icons", "wui_icons", FONT_WEIGHT_REGULAR, FONT_STYLE_NORMAL, qtrue, NULL },
		}, 1
	},
};
// NOLINTEND(bugprone-invalid-enum-default-initialization)

#define FONT_FAMILY_COUNT (sizeof(wui_fontFamilies) / sizeof(wui_fontFamilies[0]))

void WiredFonts_InitMSDF( void ) {
	/* ── Family-based loading: iterate families and faces ─────────── */
	int fontsLoadedStart = MSDF_GetFontCount();
	for ( int i = 0; i < (int)FONT_FAMILY_COUNT; i++ ) {
		fontFamily_t *fam = &wui_fontFamilies[i];
		for ( int j = 0; j < fam->faceCount; j++ ) {
			fontFace_t *face = &fam->faces[j];
			msdfFont_t *atlas = NULL;

			/* Check if this atlas is already loaded by a previous face */
			for ( int k = 0; k < i + 1; k++ ) {
				fontFamily_t *prev = &wui_fontFamilies[k];
				int limit = ( k == i ) ? j : prev->faceCount;
				for ( int m = 0; m < limit; m++ ) {
					if ( !Q_stricmp( prev->faces[m].atlasName, face->atlasName ) &&
					     prev->faces[m].atlas != NULL ) {
						atlas = prev->faces[m].atlas;
						break;
					}
				}
				if ( atlas ) break;
			}

			/* Lazy faces are not loaded at boot — their atlas loads on first use
			 * (WiredFont_EnsureAtlas). A lazy face still adopts an atlas a previous
			 * non-lazy face already loaded (shared atlas), but never loads one itself
			 * here, so its first-use cost stays out of the boot burst. */
			if ( !atlas && !face->lazy ) {
				atlas = MSDF_LoadFont( face->atlasName );
			}

			face->atlas = atlas;
		}
	}
	int fontsNew   = MSDF_GetFontCount() - fontsLoadedStart;
	int fontsTotal = MSDF_GetFontCount();
	Com_Log( SEV_INFO, LOG_CH(ch_ui), "MSDF: %d font%s loaded (%d new)\n", fontsTotal, fontsTotal == 1 ? "" : "s", fontsNew );
}

/*
 * WiredFont_Resolve — CSS-like font face resolution.
 *
 * 1. Find the family by name (case-insensitive).
 * 2. Filter faces by style (normal / italic).
 * 3. Exact weight match first.
 * 4. If no exact match: weight >= 500 prefers nearest heavier,
 *    weight < 500 prefers nearest lighter. Falls back to the
 *    nearest in the opposite direction.
 * 5. Returns NULL if family not found.
 */
const fontFace_t *WiredFont_Resolve(
	const char   *familyName,
	fontWeight_t  weight,
	fontStyle_t   style
) {
	const fontFamily_t *family = NULL;
	const fontFace_t   *best = NULL;
	int                 bestDist = 99999;

	/* Find the family */
	for ( int i = 0; i < (int)FONT_FAMILY_COUNT; i++ ) {
		if ( !Q_stricmp( familyName, wui_fontFamilies[i].familyName ) ) {
			family = &wui_fontFamilies[i];
			break;
		}
	}

	if ( !family ) {
		return NULL;
	}

	/* Pass 1: exact weight match among faces with matching style */
	for ( int j = 0; j < family->faceCount; j++ ) {
		const fontFace_t *f = &family->faces[j];
		if ( f->style != style ) {
			continue;
		}
		if ( f->weight == weight ) {
			return f;
		}
	}

	/* Pass 2: score = wrong-side penalty (1000) + abs(diff); pick lowest */
	for ( int j = 0; j < family->faceCount; j++ ) {
		const fontFace_t *f = &family->faces[j];
		int diff, score, pref;

		if ( f->style != style ) continue;

		diff  = (int)f->weight - (int)weight;
		pref  = ( (int)weight >= 500 ) ? 1 : -1;
		score = ( ( diff > 0 ? 1 : -1 ) != pref ? 1000 : 0 ) + ( diff < 0 ? -diff : diff );

		if ( !best || score < bestDist ) {
			best     = f;
			bestDist = score;
		}
	}

	return best;
}

// Ensure a face's atlas is loaded, loading it on first use for lazy faces. Lazy
// fonts are block-until-resident (no garbled first-frame glyphs): the load forces
// the synchronous texture-upload path so the atlas is resident before this returns
// and the glyph is drawn. A one-time cost on the first draw of a lazy face; later
// draws reuse the now-bound atlas. Non-lazy faces (loaded at boot) are unaffected.
msdfFont_t *WiredFont_EnsureAtlas( const fontFace_t *face )
{
	fontFace_t *f = (fontFace_t *)face;   // the registry is mutable; the API hands out const views
	if ( !f ) return NULL;
	if ( f->atlas ) return f->atlas;
	if ( !f->lazy ) return NULL;           // a non-lazy face with no atlas failed to load at boot

	// First use of a lazy face: load its atlas now, block-until-resident. A lazy font
	// must show correct glyphs on its first frame (no placeholder), so its atlas upload
	// must be resident on return. Force the synchronous upload path for just this load by
	// clearing r_asyncTextureUpload around it, then restoring the user's setting — this
	// guarantees resident-on-return regardless of whether the load happens between frames
	// or inside one. Scoped to this one load; the renderer's general in-frame-vs-load-
	// burst async gate is otherwise untouched.
	cvar_t *async = Cvar_Get( "r_asyncTextureUpload", "1", 0 );
	int     savedAsync = async ? async->integer : 0;
	if ( async && savedAsync ) Cvar_Set( "r_asyncTextureUpload", "0" );
	f->atlas = MSDF_LoadFont( f->atlasName );
	if ( async && savedAsync ) Cvar_Set( "r_asyncTextureUpload", "1" );
	return f->atlas;
}

const fontFace_t *WiredFont_ResolveByName( const char *name )
{
	if ( !name || !name[0] ) {
		return NULL;
	}

	for ( int i = 0; i < (int)FONT_FAMILY_COUNT; i++ ) {
		const fontFamily_t *family = &wui_fontFamilies[i];
		if ( !Q_stricmp( name, family->familyName ) ) {
			return WiredFont_Resolve( family->familyName, FONT_WEIGHT_REGULAR, FONT_STYLE_NORMAL );
		}
		for ( int j = 0; j < family->faceCount; j++ ) {
			const fontFace_t *face = &family->faces[j];
			if ( !Q_stricmp( name, face->name ) || !Q_stricmp( name, face->atlasName ) ) {
				return face;
			}
		}
	}

	return NULL;
}

// border frame drawing
void WiredFont_DrawFrame( float x, float y, float w, float h, const float *border, const float *borderColor, qboolean filled ) {
	if ( !border || !borderColor ) return;
	if ( border[0] > 0 ) WUI_FillRect( x, y, w, border[0], borderColor );
	if ( border[2] > 0 ) WUI_FillRect( x, y + h - border[2], w, border[2], borderColor );
	if ( border[3] > 0 ) WUI_FillRect( x, y + border[0], border[3], h - border[0] - border[2], borderColor );
	if ( border[1] > 0 ) WUI_FillRect( x + w - border[1], y + border[0], border[1], h - border[0] - border[2], borderColor );
}

/*
 * ── Hex color parsing ────────────────────────────────────
 */
static qboolean CG_ModernCharHexToInt(char c, int *out)
{
	if (c >= '0' && c <= '9') { *out = c - '0'; return qtrue; }
	if (c >= 'a' && c <= 'f') { *out = c - 'a' + 10; return qtrue; }
	if (c >= 'A' && c <= 'F') { *out = c - 'A' + 10; return qtrue; }
	return qfalse;
}

qboolean CG_Hex16GetColor(const char *str, float *color)
{
	int d1, d2, color_int;
	if (!str) return qfalse;
	if (!CG_ModernCharHexToInt(str[0], &d1)) return qfalse;
	if (!CG_ModernCharHexToInt(str[1], &d2)) return qfalse;
	color_int = d1 * 16 + d2;
	*color = (float)color_int / 255.0f;
	return qtrue;
}

int WiredFont_IdFromName( const char *name )
{
	static const struct { const char *k; int id; } map[] = {
		{ "defaultSerifFont",       FONT_DISPLAY        },
		{ "defaultSerifFontItalic", FONT_DISPLAY_ITALIC },
		{ "defaultSerifFontBold",   FONT_DISPLAY_BOLD   },
		{ "defaultSansFont",        FONT_UI             },
		{ "defaultSansFontMedium",  FONT_UI_MEDIUM      },
		{ "defaultMonoFont",        FONT_MONO           },
		{ "display",                FONT_DISPLAY        },
		{ "displayItalic",          FONT_DISPLAY_ITALIC },
		{ "displayBold",            FONT_DISPLAY_BOLD   },
		{ "ui",                     FONT_UI             },
		{ "uiMedium",               FONT_UI_MEDIUM      },
		{ "mono",                   FONT_MONO           },
		{ "sansman",                FONT_DISPLAY        },
		{ "sansman-regular",        FONT_DISPLAY        },
		{ "sansman-medium",         FONT_DISPLAY        },
		{ "sansman-bold",           FONT_DISPLAY_BOLD   },
		{ "sansman-italic",         FONT_DISPLAY_ITALIC },
		{ "sansman-bold-italic",    FONT_DISPLAY_ITALIC },
		{ "oxanium",                FONT_UI             },
		{ "oxanium-regular",        FONT_UI             },
		{ "oxanium-medium",         FONT_UI_MEDIUM      },
		{ "sharetechmono",          FONT_MONO           },
		{ "sharetechmono-regular",  FONT_MONO           },
		{ "wui_icons",              FONT_UI             },
		{ NULL, 0 }
	};
	if ( !name || !name[0] ) return FONT_DISPLAY;
	for ( int i = 0; map[i].k; i++ ) {
		if ( !Q_stricmp( name, map[i].k ) ) return map[i].id;
	}
	return FONT_UI;
}

/*
 * Convert DS_* flags to TEXT_ALIGN_* alignment value.
 */
int WiredFont_ToAlignment( int dsFlags )
{
	if ( dsFlags & DS_HCENTER ) return TEXT_ALIGN_CENTER;
	if ( dsFlags & DS_HRIGHT )  return TEXT_ALIGN_RIGHT;
	return TEXT_ALIGN_LEFT;
}

/*
 * Convert DS_* flags to Text_Draw flags (TEXT_DROPSHADOW, etc.).
 */
int WiredFont_ToTextFlags( int dsFlags )
{
	int f = 0;
	if ( dsFlags & DS_SHADOW ) f |= TEXT_DROPSHADOW;
	return f;
}


#endif // FEAT_WIRED_UI
