// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2024-present Wired Engine contributors

#include "ral_vulkan_translate.h"
#include <stdio.h>

#define CHECK(expr) do { if ( !(expr) ) { \
	fprintf( stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #expr ); return 1; \
} } while ( 0 )

int main( void ) {
	static const VkFormat formats[ RAL_FORMAT_COUNT ] = {
		VK_FORMAT_UNDEFINED,
		VK_FORMAT_R8_UNORM, VK_FORMAT_R8G8_UNORM,
		VK_FORMAT_R8G8B8A8_UNORM, VK_FORMAT_R8G8B8A8_SRGB,
		VK_FORMAT_B8G8R8A8_UNORM, VK_FORMAT_B8G8R8A8_SRGB,
		VK_FORMAT_A2B10G10R10_UNORM_PACK32, VK_FORMAT_A2R10G10B10_UNORM_PACK32,
		VK_FORMAT_B5G6R5_UNORM_PACK16, VK_FORMAT_R5G6B5_UNORM_PACK16,
		VK_FORMAT_R16_UNORM, VK_FORMAT_R16_SFLOAT, VK_FORMAT_R16G16_SFLOAT,
		VK_FORMAT_R16G16B16A16_SFLOAT, VK_FORMAT_R16G16B16A16_UNORM,
		VK_FORMAT_B10G11R11_UFLOAT_PACK32, VK_FORMAT_R32_SFLOAT,
		VK_FORMAT_R32G32_SFLOAT, VK_FORMAT_R32G32B32_SFLOAT,
		VK_FORMAT_R32G32B32A32_SFLOAT, VK_FORMAT_R8G8B8A8_UINT,
		VK_FORMAT_D16_UNORM, VK_FORMAT_D24_UNORM_S8_UINT, VK_FORMAT_D32_SFLOAT,
		VK_FORMAT_D32_SFLOAT_S8_UINT, VK_FORMAT_D16_UNORM_S8_UINT,
		VK_FORMAT_X8_D24_UNORM_PACK32,
		VK_FORMAT_BC1_RGBA_UNORM_BLOCK, VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
		VK_FORMAT_BC3_UNORM_BLOCK, VK_FORMAT_BC3_SRGB_BLOCK,
		VK_FORMAT_BC4_UNORM_BLOCK, VK_FORMAT_BC5_UNORM_BLOCK,
		VK_FORMAT_BC6H_UFLOAT_BLOCK, VK_FORMAT_BC7_UNORM_BLOCK,
		VK_FORMAT_BC7_SRGB_BLOCK, VK_FORMAT_ASTC_4x4_UNORM_BLOCK,
		VK_FORMAT_ASTC_4x4_SRGB_BLOCK, VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,
		VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK
	};
	static const VkColorSpaceKHR colorSpaces[] = {
		VK_COLOR_SPACE_SRGB_NONLINEAR_KHR,
		VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT,
		VK_COLOR_SPACE_HDR10_ST2084_EXT,
		VK_COLOR_SPACE_HDR10_HLG_EXT,
		VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
	};
	static const VkPresentModeKHR presentModes[] = {
		VK_PRESENT_MODE_FIFO_KHR, VK_PRESENT_MODE_MAILBOX_KHR,
		VK_PRESENT_MODE_IMMEDIATE_KHR, VK_PRESENT_MODE_FIFO_RELAXED_KHR,
		VK_PRESENT_MODE_FIFO_LATEST_READY_EXT
	};
	static const uint32_t rates[][2] = { {1,1}, {2,2}, {2,4}, {4,2}, {4,4} };
	uint32_t i;

	CHECK( sizeof( formats ) / sizeof( formats[0] ) == RAL_FORMAT_COUNT );
	for ( i = 0; i < RAL_FORMAT_COUNT; ++i )
		CHECK( ralVk_TranslateFormat( (ralFormat_t)i ) == formats[i] );
	CHECK( ralVk_TranslateFormat( (ralFormat_t)-1 ) == VK_FORMAT_UNDEFINED );
	CHECK( ralVk_TranslateFormat( RAL_FORMAT_COUNT ) == VK_FORMAT_UNDEFINED );

	for ( i = 0; i < sizeof( colorSpaces ) / sizeof( colorSpaces[0] ); ++i )
		CHECK( ralVk_TranslateColorSpace( (ralColorSpace_t)i ) == colorSpaces[i] );
	CHECK( ralVk_TranslateColorSpace( (ralColorSpace_t)99 ) == VK_COLOR_SPACE_SRGB_NONLINEAR_KHR );

	for ( i = 0; i < sizeof( presentModes ) / sizeof( presentModes[0] ); ++i )
		CHECK( ralVk_TranslatePresentMode( (ralPresentMode_t)i ) == presentModes[i] );
	CHECK( ralVk_TranslatePresentMode( (ralPresentMode_t)99 ) == VK_PRESENT_MODE_FIFO_KHR );

	for ( i = 0; i < sizeof( rates ) / sizeof( rates[0] ); ++i ) {
		VkExtent2D extent = ralVk_TranslateShadingRate( (ralFragmentShadingRate_t)i );
		CHECK( extent.width == rates[i][0] && extent.height == rates[i][1] );
	}
	{
		VkExtent2D extent = ralVk_TranslateShadingRate( (ralFragmentShadingRate_t)99 );
		CHECK( extent.width == 1 && extent.height == 1 );
	}

	CHECK( ralVk_TranslateLoadOp( RAL_LOAD_OP_LOAD ) == VK_ATTACHMENT_LOAD_OP_LOAD );
	CHECK( ralVk_TranslateLoadOp( RAL_LOAD_OP_CLEAR ) == VK_ATTACHMENT_LOAD_OP_CLEAR );
	CHECK( ralVk_TranslateLoadOp( RAL_LOAD_OP_DONT_CARE ) == VK_ATTACHMENT_LOAD_OP_DONT_CARE );
	CHECK( ralVk_TranslateLoadOp( (ralLoadOp_t)99 ) == VK_ATTACHMENT_LOAD_OP_DONT_CARE );
	CHECK( ralVk_TranslateStoreOp( RAL_STORE_OP_STORE ) == VK_ATTACHMENT_STORE_OP_STORE );
	CHECK( ralVk_TranslateStoreOp( RAL_STORE_OP_DONT_CARE ) == VK_ATTACHMENT_STORE_OP_DONT_CARE );
	CHECK( ralVk_TranslateStoreOp( (ralStoreOp_t)99 ) == VK_ATTACHMENT_STORE_OP_DONT_CARE );

	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_TOP_OF_PIPE_BIT ) == 0 );
	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT )
	       == ( VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) );
	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | RAL_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT )
	       == ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ) );
	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_VERTEX_SHADER_BIT | RAL_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | RAL_PIPELINE_STAGE_COMPUTE_SHADER_BIT )
	       == ( VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT ) );
	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_TRANSFER_BIT )
	       == ( VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT ) );
	CHECK( ralVk_TranslateStageAccess( RAL_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | RAL_PIPELINE_STAGE_TRANSFER_BIT )
	       == ( VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT
	          | VK_ACCESS_TRANSFER_READ_BIT | VK_ACCESS_TRANSFER_WRITE_BIT ) );

	{
		static const ralVkBarrierTranslation_t barriers[] = {
			{ VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
			  VK_ACCESS_MEMORY_WRITE_BIT, VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT },
			{ VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
			  VK_PIPELINE_STAGE_VERTEX_INPUT_BIT | VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
			  VK_ACCESS_SHADER_WRITE_BIT,
			  VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT | VK_ACCESS_INDEX_READ_BIT | VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_INDIRECT_COMMAND_READ_BIT },
			{ VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
			  VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT },
			{ VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT | VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
			  VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
			  VK_ACCESS_SHADER_WRITE_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
			  VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT },
			{ VK_PIPELINE_STAGE_TRANSFER_BIT,
			  VK_PIPELINE_STAGE_VERTEX_INPUT_BIT | VK_PIPELINE_STAGE_VERTEX_SHADER_BIT | VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
			  VK_ACCESS_TRANSFER_WRITE_BIT,
			  VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT | VK_ACCESS_INDEX_READ_BIT | VK_ACCESS_UNIFORM_READ_BIT | VK_ACCESS_SHADER_READ_BIT },
			{ VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
			  VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_INDIRECT_COMMAND_READ_BIT }
		};
		for ( i = 0; i < sizeof( barriers ) / sizeof( barriers[0] ); ++i ) {
			ralVkBarrierTranslation_t got = ralVk_TranslateBarrierScope( (ralBarrierScope_t)i );
			CHECK( got.srcStage == barriers[i].srcStage );
			CHECK( got.dstStage == barriers[i].dstStage );
			CHECK( got.srcAccess == barriers[i].srcAccess );
			CHECK( got.dstAccess == barriers[i].dstAccess );
		}
		{
			ralVkBarrierTranslation_t invalid = ralVk_TranslateBarrierScope( (ralBarrierScope_t)99 );
			CHECK( invalid.srcStage == barriers[0].srcStage && invalid.dstStage == barriers[0].dstStage );
			CHECK( invalid.srcAccess == barriers[0].srcAccess && invalid.dstAccess == barriers[0].dstAccess );
		}
	}

	{
		ralVkLayoutTranslation_t t;
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_UNDEFINED );
		CHECK( t.stage == VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT && t.access == 0 );
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_TRANSFER_BIT && t.access == VK_ACCESS_TRANSFER_WRITE_BIT );
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_TRANSFER_BIT && t.access == VK_ACCESS_TRANSFER_READ_BIT );
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
		       && t.access == ( VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) );
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL );
		CHECK( t.stage == ( VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT )
		       && t.access == ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ) );
		t = ralVk_TranslateSourceLayout( VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT && t.access == VK_ACCESS_SHADER_READ_BIT );

		t = ralVk_TranslateDestinationLayout( VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
		       && t.access == ( VK_ACCESS_COLOR_ATTACHMENT_READ_BIT | VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT ) );
		t = ralVk_TranslateDestinationLayout( VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL );
		CHECK( t.stage == ( VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT )
		       && t.access == ( VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT ) );
		t = ralVk_TranslateDestinationLayout( VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL );
		CHECK( t.stage == VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT
		       && t.access == ( VK_ACCESS_MEMORY_READ_BIT | VK_ACCESS_MEMORY_WRITE_BIT ) );
	}

	puts( "PASS exact production RAL-to-Vulkan format/present/render-state/barrier translations" );
	return 0;
}
