#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2024-present Wired Engine contributors

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { ralShaderArtifactDigest } from '../../vulkan/renderer/shaders/shader_artifact_catalog.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_PORTABLE = join(HERE, 'portable');
const DEFAULT_OUTPUT = join(HERE, '..', 'ral_opengl_product_shader_catalog.inc');
const MODULES = [
	{ symbol: 'ral_opengl_product_vert_spv', name: 'Vertex' },
	{ symbol: 'ral_opengl_product_frag_spv', name: 'Fragment' },
	{ symbol: 'atmosphere_froxel_inject_comp_spv', name: 'AtmosphereInject' },
	{ symbol: 'atmosphere_froxel_light_comp_spv', name: 'AtmosphereLight' },
	{ symbol: 'atmosphere_froxel_cloud_comp_spv', name: 'AtmosphereCloud' },
	{ symbol: 'atmosphere_froxel_integrate_comp_spv', name: 'AtmosphereIntegrate' },
	{ symbol: 'atmospheric_integrate_comp_spv', name: 'WeatherIntegrate' },
	{ symbol: 'atmospheric_vert_spv', name: 'WeatherVertex' },
	{ symbol: 'atmospheric_frag_spv', name: 'WeatherFragment' },
];

function parseArgs(argv) {
	const result = { portable: DEFAULT_PORTABLE, output: DEFAULT_OUTPUT, check: false };
	for (let i = 0; i < argv.length; ++i) {
		if (argv[i] === '--check') result.check = true;
		else if (argv[i] === '--portable' || argv[i] === '--output') {
			if (++i >= argv.length) throw new Error(`missing value for ${argv[i - 1]}`);
			result[argv[i - 1].slice(2)] = argv[i];
		} else throw new Error(`unknown argument: ${argv[i]}`);
	}
	return result;
}

function hex64(value) { return value.toString(16).padStart(16, '0'); }
function exact(bytes, expected) {
	const digest = ralShaderArtifactDigest(bytes);
	return hex64(digest.lane0) === expected?.lane0
		&& hex64(digest.lane1) === expected?.lane1;
}
function cBytes(bytes) {
	const values = [...bytes, 0].map((value) => `0x${value.toString(16).padStart(2, '0')}`);
	const lines = [];
	for (let i = 0; i < values.length; i += 12) lines.push(`\t${values.slice(i, i + 12).join(', ')}`);
	return lines.join(',\n');
}

function render(portable) {
	const catalog = JSON.parse(readFileSync(join(portable, 'translation_catalog.json'), 'utf8'));
	if (catalog.schemaVersion !== 2
			|| JSON.stringify(catalog.requiredTargets) !== JSON.stringify(['glsl460'])
			|| !Array.isArray(catalog.entries) || catalog.entries.length !== 299)
		throw new Error('OpenGL GLSL 4.60 catalog is not the exact canonical corpus');
	const rendered = [];
	for (const module of MODULES) {
		const entry = catalog.entries.find((candidate) => candidate.symbol === module.symbol);
		const artifact = entry?.artifacts?.find((candidate) => candidate.target === 'glsl460');
		if (!entry || !artifact || entry.artifacts.length !== 1)
			throw new Error(`missing exact product shader artifact: ${module.symbol}`);
		const bytes = readFileSync(join(portable, `${module.symbol}.glsl460`));
		const source = bytes.toString('utf8');
		if (bytes.length !== artifact.byteCount || !exact(bytes, artifact.digest)
				|| !source.startsWith('#version 460\n')
				|| /layout\([^)]*set\s*=|push_constant|nonuniformEXT|GL_EXT_nonuniform_qualifier/.test(source))
			throw new Error(`invalid product shader artifact: ${module.symbol}`);
		rendered.push({ ...module, bytes, artifact });
	}
	return '// Generated by shaders/generate_product_shader_catalog.mjs; do not edit.\n'
		+ '#ifndef WIRED_RAL_OPENGL_PRODUCT_SHADER_CATALOG_INC\n'
		+ '#define WIRED_RAL_OPENGL_PRODUCT_SHADER_CATALOG_INC\n\n'
		+ rendered.map((module) => `static const unsigned char ralOpenGlProduct${module.name}Source[] = {\n${cBytes(module.bytes)}\n};\n`
			+ `static const unsigned int ralOpenGlProduct${module.name}ByteCount = ${module.bytes.length}u;\n`
			+ `static const unsigned long long ralOpenGlProduct${module.name}DigestLane0 = 0x${module.artifact.digest.lane0}ull;\n`
			+ `static const unsigned long long ralOpenGlProduct${module.name}DigestLane1 = 0x${module.artifact.digest.lane1}ull;\n`).join('\n')
		+ '\n#endif\n';
}

export function generateProductShaderCatalog(options) {
	const output = resolve(options.output);
	const text = render(resolve(options.portable));
	if (options.check) {
		if (!existsSync(output) || readFileSync(output, 'utf8') !== text)
			throw new Error(`OpenGL product shader catalog is stale: ${output}`);
	} else writeFileSync(output, text);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
	try {
		const options = parseArgs(process.argv.slice(2));
		generateProductShaderCatalog(options);
		console.log(`OpenGL product shader catalog: ${options.check ? 'fresh' : 'written'}`);
	} catch (error) { console.error(`ERROR: ${error.message}`); process.exit(1); }
}
