// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {detect} from '../models';
import {engine} from '../models';
import {settings} from '../models';

export function AcceptEula():Promise<void>;

export function BrowseForDirectory():Promise<string>;

export function BuildGameCommand(arg1:Record<string, any>):Promise<string>;

export function CancelImport():Promise<void>;

export function CheckDownloadStatus():Promise<Record<string, any>>;

export function DetectQ1Installations():Promise<Array<detect.Q1Installation>>;

export function DetectQ3Installations():Promise<Array<detect.Q3Installation>>;

export function DownloadFreeResources():Promise<void>;

export function GetAppState():Promise<Record<string, any>>;

export function GetDedCommandPreview(arg1:engine.ServerConfig):Promise<string>;

export function GetDedStatus():Promise<boolean>;

export function GetEulaText():Promise<string>;

export function GetLocalIP():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function HasAcceptedEula():Promise<boolean>;

export function LaunchGame():Promise<void>;

export function LaunchGameWithArgs(arg1:Array<string>):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function StartDedicated(arg1:engine.ServerConfig):Promise<void>;

export function StartImport(arg1:string):Promise<void>;

export function StopDedicated():Promise<void>;
