// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptEula() {
  return window['go']['main']['App']['AcceptEula']();
}

export function BrowseForDirectory() {
  return window['go']['main']['App']['BrowseForDirectory']();
}

export function BuildGameCommand(arg1) {
  return window['go']['main']['App']['BuildGameCommand'](arg1);
}

export function CancelImport() {
  return window['go']['main']['App']['CancelImport']();
}

export function CheckDownloadStatus() {
  return window['go']['main']['App']['CheckDownloadStatus']();
}

export function DetectQ1Installations() {
  return window['go']['main']['App']['DetectQ1Installations']();
}

export function DetectQ3Installations() {
  return window['go']['main']['App']['DetectQ3Installations']();
}

export function DownloadFreeResources() {
  return window['go']['main']['App']['DownloadFreeResources']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetDedCommandPreview(arg1) {
  return window['go']['main']['App']['GetDedCommandPreview'](arg1);
}

export function GetDedStatus() {
  return window['go']['main']['App']['GetDedStatus']();
}

export function GetEulaText() {
  return window['go']['main']['App']['GetEulaText']();
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasAcceptedEula() {
  return window['go']['main']['App']['HasAcceptedEula']();
}

export function LaunchGame() {
  return window['go']['main']['App']['LaunchGame']();
}

export function LaunchGameWithArgs(arg1) {
  return window['go']['main']['App']['LaunchGameWithArgs'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDedicated(arg1) {
  return window['go']['main']['App']['StartDedicated'](arg1);
}

export function StartImport(arg1) {
  return window['go']['main']['App']['StartImport'](arg1);
}

export function StopDedicated() {
  return window['go']['main']['App']['StopDedicated']();
}
