#!/usr/bin/env python3
"""vr_check.py — visual-regression check orchestrator.

For each scene:
  1. read scenes/<scene>.yaml
  2. resolve each region's authored colour (wmenu element / wmenumacros
     macro / rgba literal) and predict its swapchain byte via expected_calc
  3. launch wired.x64.exe under RenderDoc (capture_driver), grab a frame
     + layoutdump.jsonl
  4. for each region, look up its pixel rect in layoutdump.jsonl, pick the
     centre pixel from the capture (readback), compare (diff_harness)
  5. report per-scene + overall pass/fail

The scene YAML encodes the *desired* behaviour. A FAIL means the engine
deviates from intent (e.g. a fullscreen menu that should bypass the
tonemap operator but doesn't — it renders darker than authored).

USAGE
  python tools/visual_regression/vr_check.py --scene menu_main
  python tools/visual_regression/vr_check.py --all
  python tools/visual_regression/vr_check.py --scene arena1 --json
  python tools/visual_regression/vr_check.py --list

Steps 3-5 need RenderDoc (qrenderdoc.exe + renderdoccmd.exe) and a built
wired.x64.exe with WN_RDOC_CAPTURE != 0. Steps 1-2 (expected-value
computation) run anywhere — `--dry-run` does just those and prints the
predicted bytes, no engine launch.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

# sibling modules (this script's directory is sys.path[0])
import capture_driver
import diff_harness
import expected_calc
import readback
import wmenu_parser

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
_SCENES_DIR = os.path.join(_THIS_DIR, "scenes")
_TOLERANCE = os.path.join(_THIS_DIR, "tolerance.yaml")


# ── scene loading ──────────────────────────────────────────────────────


def _require_yaml():
    try:
        import yaml  # type: ignore  # noqa: F401
        return yaml
    except ImportError:
        sys.stderr.write("vr_check: PyYAML is required (pip install pyyaml)\n")
        raise


def list_scenes(scenes_dir=_SCENES_DIR):
    if not os.path.isdir(scenes_dir):
        return []
    return sorted(os.path.splitext(f)[0] for f in os.listdir(scenes_dir)
                  if f.endswith((".yaml", ".yml")))


# ── Phase 6B3'-d8: scene cross-product generator ───────────────────────
# `vr_check.py --gen-scenes --maps a,b,c --operators all --display-modes sdr,hdr10`
# writes scenes/<map>_<operator>_<mode>.yaml from a template. The HUD overlay
# is identity-encoded regardless of the scene's tonemap operator (it composites
# onto the post-tonemap intermediate, then the gamma pass sRGB/PQ-encodes), so
# the expected HUD-region colours don't depend on <operator>; alpha-blended
# regions pick up some of the (operator-tonemapped, then sRGB/PQ-encoded) scene
# underneath, hence the looser per-region tolerance on those.

_OPERATORS = ("identity", "pbr_neutral", "agx", "lottes", "reinhard")
#: operator name -> r_tonemap cvar value (the engine's tonemap-mode int)
_OP_TONEMAP = {"identity": 0, "pbr_neutral": 1, "agx": 2, "lottes": 3, "reinhard": 4}

_SCENE_TEMPLATE = """\
# {name}.yaml — auto-generated by `vr_check.py --gen-scenes` (Phase 6B3'-d8).
#
# HUD overlay over the {map} map; the 3D scene is tonemapped with the
# {operator} operator; the swapchain is in {mode} mode. The HUD is identity-
# encoded (composited onto the post-tonemap LDR intermediate, then the gamma
# pass {encode_note}-encodes), so the expected HUD-region colours below are
# independent of {operator}. Alpha-blended regions pick up some of the
# operator-tonemapped scene underneath, hence the looser tolerance.
#
# NOTE: like the other starter scenes, the expected_regions below are a
# template — they match only once the in-game HUD .wmenu/.whud items carry the
# corresponding `name` tags; until then vr_check reports "no expected regions
# in layoutdump". Treat as scaffolding.
#
# display_mode: {mode}    # sdr | hdr10 — sRGB-byte (8bpc) vs PQ-coded (10bpc, A2B10G10R10) readback/expected
# peak_luminance: {peak}  # nits — HDR10 only; passed to the engine as r_hdrPeakLuminance

name: {name}
operator: identity          # HUD regions are identity-encoded
display_mode: {mode}
peak_luminance: {peak}

cvars:
  s_initsound: 0
  r_brightness: 1
  r_tonemap: {tonemap}      # 0=identity 1=PBR-Neutral 2=AgX 3=Lottes 4=Reinhard
  r_hdrDisplay: {hdrdisplay}
  r_hdrPeakLuminance: {peak}

map: {map}
capture_frame: 600
texture: backbuffer

expected_regions:
  - region: hud.accent
    source: {{ macro: WCOLOR_ACCENT }}
    tolerance: 12
  - region: hud.separator
    source: {{ macro: WCOLOR_SEPARATOR }}
    tolerance: 12
"""


def gen_scenes(maps, operators, display_modes, *, scenes_dir=_SCENES_DIR,
               peak_luminance=1000, overwrite=True):
    """Write scenes/<map>_<operator>_<mode>.yaml for the cross product.
    Returns the list of written (or skipped-existing) scene file paths."""
    if "all" in operators:
        operators = list(_OPERATORS)
    os.makedirs(scenes_dir, exist_ok=True)
    written = []
    for mp in maps:
        for op in operators:
            if op not in _OP_TONEMAP:
                raise ValueError(f"unknown operator {op!r} (known: {', '.join(_OPERATORS)})")
            for mode in display_modes:
                if mode not in ("sdr", "hdr10"):
                    raise ValueError(f"unknown display mode {mode!r} (known: sdr, hdr10)")
                name = f"{mp}_{op}_{mode}"
                path = os.path.join(scenes_dir, name + ".yaml")
                if os.path.exists(path) and not overwrite:
                    written.append(path)
                    continue
                text = _SCENE_TEMPLATE.format(
                    name=name, map=mp, operator=op, mode=mode,
                    tonemap=_OP_TONEMAP[op],
                    hdrdisplay=(1 if mode == "hdr10" else 0),
                    peak=int(peak_luminance),
                    encode_note=("BT.2020/PQ" if mode == "hdr10" else "sRGB"))
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(text)
                written.append(path)
    return written


def load_scene(name, scenes_dir=_SCENES_DIR):
    yaml = _require_yaml()
    for ext in (".yaml", ".yml"):
        p = os.path.join(scenes_dir, name + ext)
        if os.path.isfile(p):
            with open(p, "r", encoding="utf-8") as fh:
                cfg = yaml.safe_load(fh) or {}
            cfg.setdefault("name", name)
            return cfg, p
    raise FileNotFoundError(f"scene {name!r} not found in {scenes_dir}")


# ── expected-value resolution ──────────────────────────────────────────


def _region_entries(scene_cfg):
    """Normalise `expected_regions` into a list of dicts:
       {region, source, operator, tolerance?}"""
    out = []
    default_op = scene_cfg.get("operator", "identity")
    for ent in scene_cfg.get("expected_regions") or []:
        if not isinstance(ent, dict):
            raise ValueError(f"expected_regions entry must be a mapping, got {ent!r}")
        # Backwards-friendly: allow {region: ..., source: {...}} or the
        # short {name: {...source...}} forms.
        if "region" in ent:
            region = ent["region"]
            source = ent.get("source")
            op = ent.get("operator", default_op)
            tol = ent.get("tolerance")
        else:
            # {some_region_name: {<source keys>, operator?, tolerance?}}
            if len(ent) != 1:
                raise ValueError(f"ambiguous expected_regions entry: {ent!r}")
            region, body = next(iter(ent.items()))
            body = dict(body or {})
            op = body.pop("operator", default_op)
            tol = body.pop("tolerance", None)
            source = body
        if source is None:
            raise ValueError(f"region {region!r}: missing 'source'")
        # If a wmenu source omits 'element', default it to the region name.
        if isinstance(source, dict) and "wmenu" in source and "element" not in source:
            source = dict(source, element=region)
        out.append({"region": region, "source": source, "operator": op, "tolerance": tol})
    return out


def compute_expected(scene_cfg, *, macros_path=None):
    """Return ({region: expected_byte_rgba}, [per-region detail dicts])."""
    eb = float(scene_cfg.get("exposure_bias", 1.0))
    te = float(scene_cfg.get("tonemap_exposure", 1.0))
    # Phase 6B3'-d8: display_mode / peak_luminance are scene-level. For
    # display_mode == "hdr10" the expected values are 10-bit PQ code values
    # (A2B10G10R10) instead of 8-bit sRGB bytes; readback must decode the
    # captured texture the same way for the diff to be meaningful (the hdr10
    # readback path is scaffolded — these scenes SKIP on environments whose
    # surface doesn't expose VK_COLOR_SPACE_HDR10_ST2084_EXT to the engine).
    display_mode = str(scene_cfg.get("display_mode", "sdr")).lower()
    peak_lum = int(scene_cfg.get("peak_luminance", 1000))
    expected = {}
    details = []
    for ent in _region_entries(scene_cfg):
        authored = wmenu_parser.resolve_authored_color(ent["source"], macros_path)
        res = expected_calc.expected_byte_rgba(authored, operator=ent["operator"],
                                               exposure_bias=eb, tonemap_exposure=te,
                                               display_mode=display_mode, peak_luminance=peak_lum)
        expected[ent["region"]] = res["byte"]
        details.append({
            "region": ent["region"], "source": ent["source"], "operator": ent["operator"],
            "authored": authored, "expected_byte": res["byte"],
            "linear_in": res["linear_in"], "tolerance_override": ent["tolerance"],
        })
    return expected, details


# ── one scene, full pipeline ───────────────────────────────────────────


def _sample_point(rect, w_clamp=None, h_clamp=None):
    """Centre pixel of a layoutdump rect, rounded to int and clamped."""
    px = int(round(rect["x"] + rect["w"] / 2.0))
    py = int(round(rect["y"] + rect["h"] / 2.0))
    if w_clamp:
        px = max(0, min(int(w_clamp) - 1, px))
    if h_clamp:
        py = max(0, min(int(h_clamp) - 1, py))
    return px, py


def run_scene(scene_cfg, *, macros_path=None, tolerance_path=_TOLERANCE,
              binary=None, workdir=None, qrenderdoc=None, renderdoccmd=None,
              timeout=90, dry_run=False, verbose=True):
    name = scene_cfg.get("name", "?")
    expected, details = compute_expected(scene_cfg, macros_path=macros_path)

    out = {"scene": name, "expected": expected, "details": details}

    if dry_run:
        out["dry_run"] = True
        return out

    # 1. capture
    cap = capture_driver.run_capture(scene_cfg, binary=binary, workdir=workdir,
                                     renderdoccmd=renderdoccmd, timeout=timeout, verbose=verbose)
    out["capture"] = {k: v for k, v in cap.items() if k not in ("stdout", "stderr")}
    if not cap["rdc"]:
        out["error"] = ("no .rdc produced — is wired.x64.exe built with WN_RDOC_CAPTURE != 0 "
                        "and is renderdoccmd working?")
        out["ok"] = False
        return out
    if not cap["layoutdump"]:
        out["error"] = "no layoutdump.jsonl produced — is r_layoutDump being set? (the driver sets it)"
        out["ok"] = False
        return out

    # 2. layout coords
    layout = capture_driver.load_layoutdump(cap["layoutdump"])
    out["layout_regions"] = sorted(layout)

    # 3. determine sample pixels per region
    texture = scene_cfg.get("texture", "backbuffer")
    samples = []      # list of (region, (px, py))
    missing = []
    for region in expected:
        if region not in layout:
            missing.append(region)
            continue
        samples.append((region, _sample_point(layout[region])))
    if missing:
        out["warning_missing_layout"] = missing
    if not samples:
        out["error"] = (f"none of the expected regions {sorted(expected)} appeared in layoutdump "
                        f"(saw {sorted(layout)}). Did the menu author add matching `name` tags to "
                        f"the .wmenu items?")
        out["ok"] = False
        return out

    # 4. readback
    rb = readback.read_pixels(cap["rdc"], [pt for _, pt in samples], texture=texture,
                              qrenderdoc=qrenderdoc, timeout=max(timeout, 120))
    out["readback_texture"] = rb.get("texture")
    if not rb.get("ok"):
        out["error"] = f"readback failed: {rb.get('error')}"
        out["readback_available"] = rb.get("available")
        out["ok"] = False
        return out

    actual = {}
    for (region, _pt), pix in zip(samples, rb["pixels"]):
        if pix.get("byte") is not None:
            actual[region] = pix["byte"]
        else:
            actual[region] = None
            out.setdefault("warning_pixel_errors", []).append({"region": region, **pix})

    # 5. diff
    cfg = diff_harness.load_tolerance(tolerance_path)
    overrides = {d["region"]: d["tolerance_override"] for d in details
                 if d["tolerance_override"] is not None}
    shoulder_set = set(scene_cfg.get("shoulder_regions") or [])
    regions = [{"region": r, "expected": expected[r], "actual": actual[r]}
               for r in expected if actual.get(r) is not None]
    ok, results = diff_harness.run_diff(regions, cfg, per_region_overrides=overrides,
                                        shoulder_set=shoulder_set)
    out["actual"] = actual
    out["results"] = results
    out["ok"] = ok and not missing and "warning_pixel_errors" not in out
    return out


# ── reporting ──────────────────────────────────────────────────────────


def print_scene_report(out, *, as_json=False):
    if as_json:
        print(json.dumps(out, indent=2, default=str))
        return
    name = out["scene"]
    print(f"\n========== scene: {name} ==========")
    print("expected (authored colour -> predicted swapchain byte):")
    for d in out["details"]:
        src = d["source"]
        src_s = (f"rgba {src['rgba']}" if "rgba" in src else
                 f"macro {src['macro']}" if "macro" in src else
                 f"wmenu {src.get('wmenu')}::{src.get('element')}.{src.get('channel','backcolor')}"
                 if "wmenu" in src else str(src))
        print(f"  {d['region']:24.24s}  {src_s:<48.48s}  op={d['operator']:<12s}"
              f" authored={[round(c,4) for c in d['authored']]} -> byte {d['expected_byte']}")
    if out.get("dry_run"):
        print("(dry run — no engine launch / capture)")
        return
    cap = out.get("capture") or {}
    print(f"capture: rdc={cap.get('rdc')}  layoutdump={cap.get('layoutdump')}  "
          f"elapsed={cap.get('elapsed_s', 0):.1f}s  wn_rdoc_marker={cap.get('wn_rdoc_marker')}")
    if out.get("error"):
        print(f"ERROR: {out['error']}")
        if out.get("readback_available"):
            print("  available textures:\n    " + "\n    ".join(out["readback_available"]))
        return
    if out.get("warning_missing_layout"):
        print(f"WARNING: regions not found in layoutdump: {out['warning_missing_layout']}")
    if out.get("readback_texture"):
        t = out["readback_texture"]
        print(f"readback texture: {t.get('name')}  ({t.get('width')}x{t.get('height')})")
    if out.get("results"):
        print(diff_harness.format_table(out["results"], scene=name))
    print(f"scene result: {'PASS' if out.get('ok') else 'FAIL'}")


# ── CLI ────────────────────────────────────────────────────────────────


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Visual-regression check: predict authored colours, capture a frame, diff.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--scene", help="run a single scene by name (see --list)")
    g.add_argument("--all", action="store_true", help="run every scene in the scenes/ dir")
    g.add_argument("--list", action="store_true", help="list available scenes and exit")
    g.add_argument("--gen-scenes", action="store_true",
                   help="generate scenes/<map>_<operator>_<mode>.yaml for the cross product and exit (Phase 6B3'-d8)")
    ap.add_argument("--maps", default="arena1,arena17,e1m1,arenam3",
                    help="--gen-scenes: comma-separated map list")
    ap.add_argument("--operators", default="all",
                    help="--gen-scenes: comma-separated operators (identity,pbr_neutral,agx,lottes,reinhard) or 'all'")
    ap.add_argument("--display-modes", default="sdr,hdr10",
                    help="--gen-scenes: comma-separated display modes (sdr,hdr10)")
    ap.add_argument("--peak-luminance", type=int, default=1000,
                    help="--gen-scenes: HDR10 peak luminance (nits) for generated hdr10 scenes")
    ap.add_argument("--scenes-dir", default=_SCENES_DIR)
    ap.add_argument("--tolerance", default=_TOLERANCE)
    ap.add_argument("--macros", default=None, help="path to wmenumacros.h (default: modfiles/ui/wmenumacros.h)")
    ap.add_argument("--binary", default=None, help="path to wired.x64.exe")
    ap.add_argument("--workdir", default=None, help="engine working dir (default build/debug)")
    ap.add_argument("--qrenderdoc", default=None, help="path to qrenderdoc.exe")
    ap.add_argument("--renderdoccmd", default=None, help="path to renderdoccmd.exe")
    ap.add_argument("--timeout", type=int, default=90, help="seconds to wait for the engine to self-quit")
    ap.add_argument("--dry-run", action="store_true",
                    help="only compute expected values (no engine launch / capture)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--quiet", action="store_true", help="less chatter from the capture driver")
    args = ap.parse_args(argv)

    if getattr(args, "gen_scenes", False):
        maps = [m.strip() for m in args.maps.split(",") if m.strip()]
        ops = [o.strip() for o in args.operators.split(",") if o.strip()]
        modes = [m.strip() for m in args.display_modes.split(",") if m.strip()]
        try:
            written = gen_scenes(maps, ops, modes, scenes_dir=args.scenes_dir,
                                 peak_luminance=args.peak_luminance)
        except ValueError as e:
            sys.stderr.write(f"vr_check --gen-scenes: {e}\n")
            return 2
        if args.json:
            print(json.dumps({"generated": [os.path.basename(p) for p in written]}))
        else:
            print(f"vr_check --gen-scenes: wrote {len(written)} scene file(s) to {args.scenes_dir}:")
            for p in written:
                print("  +", os.path.basename(p))
        return 0

    if args.list or (not args.scene and not args.all):
        scenes = list_scenes(args.scenes_dir)
        if args.json:
            print(json.dumps({"scenes": scenes}))
        else:
            print("available scenes in", args.scenes_dir + ":")
            for s in scenes:
                print("  -", s)
            if not args.list:
                print("\n(use --scene <name> or --all)")
        return 0

    names = list_scenes(args.scenes_dir) if args.all else [args.scene]
    if args.all and not names:
        sys.stderr.write(f"vr_check: no scenes found in {args.scenes_dir}\n")
        return 2

    all_out = []
    overall_ok = True
    for nm in names:
        try:
            cfg, _path = load_scene(nm, args.scenes_dir)
        except FileNotFoundError as e:
            sys.stderr.write(f"vr_check: {e}\n")
            return 2
        try:
            out = run_scene(cfg, macros_path=args.macros, tolerance_path=args.tolerance,
                            binary=args.binary, workdir=args.workdir, qrenderdoc=args.qrenderdoc,
                            renderdoccmd=args.renderdoccmd, timeout=args.timeout,
                            dry_run=args.dry_run, verbose=not args.quiet)
        except RuntimeError as e:
            out = {"scene": nm, "ok": False, "error": str(e), "details": []}
        all_out.append(out)
        if not out.get("dry_run") and not out.get("ok", False):
            overall_ok = False
        print_scene_report(out, as_json=args.json)

    if not args.dry_run:
        n_fail = sum(1 for o in all_out if not o.get("ok", False))
        if not args.json:
            print(f"\n=== {len(all_out)} scene(s): {len(all_out) - n_fail} pass, {n_fail} fail ===")
        return 0 if overall_ok else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
