-- Visor bot personality data — cybernetic duelist, railgun specialist.
-- Shallow-merged onto _base/bot/main.lua by q3now.load_bot().
-- Top-level keys here replace the corresponding base keys wholesale.
--
-- Values aligned to Q3 visor_c.c baseline (Q3 skill-1 → low, skill-5 → high).
-- Q3 visor had flat characteristics across all skill levels; flat tuples {x, x}
-- preserve that with no lerp effect.
return {
  traits = {
    attack_skill     = {0.75, 0.75},
    view_factor      = {1.00, 1.00},
    view_maxchange   = {120, 120},
    reaction_time    = {3.00, 1.00},
    grapple_user     = {0.20, 0.45},
    aggression       = {0.95, 0.95},
    selfpreservation = {0.20, 0.20},
    vengefulness     = {0.95, 0.95},
    camper           = 0.10,
    easy_fragger     = {0.10, 0.10},
    alertness        = {0.50, 0.50},
    firethrottle     = {0.30, 1.00},
    walker           = 0.05,
  },

  aim = {
    accuracy                  = {0.40, 0.85},
    accuracy_machinegun_pri       = {0.30, 0.70},
    accuracy_shotgun_pri          = {0.30, 0.70},
    accuracy_grenade_launcher_pri = {0.25, 0.65},
    accuracy_rocket_launcher_pri  = {0.35, 0.80},
    accuracy_lightning_gun_pri    = {0.40, 0.85},
    accuracy_railgun_pri          = {0.55, 1.00},
    accuracy_plasma_rifle_pri     = {0.30, 0.70},
    skill                     = {0.40, 0.85},
    skill_machinegun          = {0.25, 0.65},
    skill_shotgun             = {0.25, 0.65},
    skill_grenade_launcher    = {0.25, 0.65},
    skill_rocket_launcher     = {0.35, 0.80},
    skill_lightning_gun       = {0.40, 0.85},
    skill_railgun             = {0.55, 1.00},
    skill_plasma_rifle        = {0.30, 0.70},
    weapon_bias_mg            = 0.85,
    weapon_bias_sg            = 1.00,
    weapon_bias_gl            = 0.90,
    weapon_bias_rl            = 1.05,
    weapon_bias_lg            = 1.15,
    weapon_bias_rg            = 1.30,
    weapon_bias_pg            = 0.95,
  },

  movement = {
    strafe_jump      = 0.30,
    weapon_jumping   = {0.30, 0.65}, -- 0.30 at low, 0.65 at high (continuous)
    jumper           = 0.35,
    dodging          = {0.20, 0.60},
    use_jumppads     = true,
    swim             = true,
    navigation_skill = {0.50, 0.90},
  },

  attacks = {
    { "rg1", aim_height = 36 },
    { "lg1", aim_height = 28 },
    { "lg2", aim_height = 28 },
    { "rl1", aim_height = 0  },
    { "sg1", aim_height = 28 },
    { "pr1", aim_height = 28 },
    { "gl1", aim_height = 0  },
    { "mg1", aim_height = 28 },
  },

  items = {
    "powerup_quad",
    "armor_red",
    "weapon_rg",
    "health_mega",
    "weapon_lg",
    "weapon_rl",
    "armor_yellow",
    "health_large",
    "powerup_haste",
    "powerup_invis",
    "weapon_gl",
    "weapon_sg",
    "weapon_pr",
    "ammo_rg",
    "ammo_lg",
    "ammo_rl",
    "health_medium",
    "ammo_gl",
    "ammo_pr",
    "ammo_sg",
    "ammo_mg",
    "health_small",
    "powerup_regen",
    "powerup_battlesuit",
  },

  chats = {
    -- Core events — keys match WiredBots_Chat event names
    -- insult/misc: Q3-path sub-rate only; WiredBots tone is handled in Lua
    insult         = 0.50,
    misc           = 0.30,
    kill           = 0.40,
    death          = 0.20,
    random         = 0.25,
    reply          = {0.30, 0.08},  -- {low_skill_rate, high_skill_rate}
    message        = 0.30,
    enemy_suicide  = 0.30,
    hit_talking    = 0.10,
    hit_nodeath    = 0.30,
    hit_nokill     = 0.35,
    level_start    = 0.40,
    level_end      = 0.40,
    level_end_eliminated = 0.45,
    game_enter     = 0.35,
    game_exit      = 0.35,
    -- Team broadcasts (teamplay only)
    team_need_health         = 0.70,
    team_need_weapon         = 0.55,
    team_cover_me            = 0.60,
    team_follow_me           = 0.65,
    team_enemy_base_attack   = 0.60,
    team_defending_base      = 0.55,
    team_got_flag_need_support = 0.80,
    -- Powerup events
    powerup_quad          = 0.75,
    powerup_haste         = 0.55,
    powerup_invis         = 0.60,
    powerup_regen         = 0.45,
    powerup_battlesuit    = 0.45,
    powerup_enemy_quad    = 0.60,
    powerup_enemy_any     = 0.35,
    -- Kill streaks
    kill_double          = 0.50,
    kill_streak_5        = 0.80,
    kill_streak_10       = 0.90,
    kill_rampage         = 0.95,
    -- Score milestones
    score_first_place    = 0.80,
    score_falling_back   = 0.55,
    score_last_place     = 0.40,
    score_frag_milestone = 0.65,
    -- CTF events
    ctf_got_flag      = 0.80,
    ctf_enemy_got_flag = 0.50,
    ctf_returning_flag = 0.75,
    ctf_capture       = 0.90,
    ctf_flag_dropped  = 0.55,
    ctf_attack        = 0.35,
    ctf_defend        = 0.35,
  },
}
