#include "ral_opengl_pipeline.h"
#include <limits.h>
#include <string.h>
static qboolean Has(const char*b,uint32_t n,const char*s){size_t m=strlen(s);uint32_t i;if(!m||m>n)return qfalse;for(i=0;i<=n-m;i++)if(!memcmp(b+i,s,m))return qtrue;return qfalse;}
static qboolean Glsl(const char*b,uint32_t n){return b&&n>=13&&!memcmp(b,"#version 460\n",13)&&!Has(b,n,"set =")&&!Has(b,n,"push_constant")&&!Has(b,n,"nonuniformEXT")&&!Has(b,n,"GL_EXT_nonuniform_qualifier")&&!Has(b,n,"#version 3");}
static ralOpenGlBindingNamespace_t Ns(ralShaderBindingClass_t c){switch(c){case RAL_SHADER_BIND_UNIFORM_BUFFER:return RAL_OPENGL_BIND_UNIFORM;case RAL_SHADER_BIND_STORAGE_BUFFER_READ:case RAL_SHADER_BIND_STORAGE_BUFFER_READ_WRITE:return RAL_OPENGL_BIND_STORAGE;case RAL_SHADER_BIND_SAMPLED_TEXTURE:return RAL_OPENGL_BIND_TEXTURE;case RAL_SHADER_BIND_STORAGE_TEXTURE_READ:case RAL_SHADER_BIND_STORAGE_TEXTURE_WRITE:return RAL_OPENGL_BIND_IMAGE;case RAL_SHADER_BIND_FILTERING_SAMPLER:case RAL_SHADER_BIND_COMPARISON_SAMPLER:return RAL_OPENGL_BIND_SAMPLER;default:return 0;}}
static qboolean Valid(const ralOpenGlPipelineReceipt_t*r){uint32_t i,next[RAL_OPENGL_BIND_COUNT]={0};if(!r||r->schemaVersion!=1||r->backendType!=RAL_BACKEND_OPENGL||!r->manifestGeneration||r->manifestGeneration==UINT64_MAX||!r->generation||r->generation==UINT64_MAX||!r->identity||!Ral_ShaderDigestValid(&r->catalogDigest)||!Ral_ShaderDigestValid(&r->glslDigests[0])||!Ral_ShaderDigestValid(&r->glslDigests[1])||r->bindingCount>RAL_SHADER_ABI_MAX_BINDINGS||r->ready!=qtrue)return qfalse;for(i=0;i<r->bindingCount;i++){const ralOpenGlBindingReceipt_t*b=&r->bindings[i];if(b->bindingNamespace<=0||b->bindingNamespace>=RAL_OPENGL_BIND_COUNT||b->glBinding!=next[b->bindingNamespace]++||!b->portableArrayCount||!b->loweredArrayCount||b->loweredArrayCount>64||b->loweredArrayCount>b->portableArrayCount)return qfalse;}return qtrue;}
qboolean RalOpenGl_PipelineBuild(const ralOpenGlPipelineInfo_t*i,ralOpenGlPipelineReceipt_t*out){ralOpenGlPipelineReceipt_t c;uint32_t n,next[RAL_OPENGL_BIND_COUNT]={0};if(!i||!out||!i->manifest||!Ral_ShaderAbiManifestValid(i->manifest)||i->manifest->pipelineKind!=RAL_SHADER_PIPELINE_GRAPHICS||!i->generation||i->generation==UINT64_MAX||!Ral_ShaderDigestValid(&i->catalogDigest)||!Glsl(i->vertex,i->vertexBytes)||!Glsl(i->fragment,i->fragmentBytes))return qfalse;memset(&c,0,sizeof(c));c.schemaVersion=1;c.backendType=RAL_BACKEND_OPENGL;c.manifestGeneration=i->manifest->generation;c.generation=i->generation;c.catalogDigest=i->catalogDigest;if(Ral_ShaderArtifactDigest(i->vertex,i->vertexBytes,&c.glslDigests[0])!=ralSuccess||Ral_ShaderArtifactDigest(i->fragment,i->fragmentBytes,&c.glslDigests[1])!=ralSuccess)return qfalse;c.bindingCount=i->manifest->bindingCount;for(n=0;n<c.bindingCount;n++){const ralShaderBindingAbi_t*s=&i->manifest->bindings[n];ralOpenGlBindingReceipt_t*b=&c.bindings[n];b->set=s->set;b->binding=s->binding;b->bindingClass=s->bindingClass;b->bindingNamespace=Ns(s->bindingClass);if(!b->bindingNamespace)return qfalse;b->glBinding=next[b->bindingNamespace]++;b->portableArrayCount=s->arrayCount;b->loweredArrayCount=s->arrayCount>64?64:s->arrayCount;}c.identity=(uintptr_t)(c.glslDigests[0].lane0^c.glslDigests[1].lane1^c.generation);if(!c.identity)c.identity=1;c.ready=qtrue;if(!Valid(&c))return qfalse;*out=c;return qtrue;}
qboolean RalOpenGl_PipelineExact(const ralOpenGlPipelineReceipt_t*a,const ralOpenGlPipelineReceipt_t*b){return Valid(a)&&Valid(b)&&!memcmp(a,b,sizeof(*a));}
