#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors

set -euo pipefail
cd "$(dirname "$0")"

mode="${1:-}"
if [ -n "$mode" ] && [ "$mode" != "--check" ]; then
	echo "usage: $0 [--check]" >&2
	exit 64
fi

if ! command -v glslangValidator >/dev/null 2>&1; then
	echo "glslangValidator is required" >&2
	exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
	echo "python3 is required" >&2
	exit 1
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

glslangValidator --quiet -V --target-env vulkan1.2 \
	-S vert wired_profile_imgui.vert.glsl -o "$tmp_dir/vert.spv"
glslangValidator --quiet -V --target-env vulkan1.2 \
	-S frag wired_profile_imgui.frag.glsl -o "$tmp_dir/frag.spv"

generated_header="$tmp_dir/wired_profile_imgui_spv.h"
python3 - "$tmp_dir/vert.spv" "$tmp_dir/frag.spv" > "$generated_header" <<'PY'
import pathlib
import struct
import sys

def emit(name: str, path: pathlib.Path) -> None:
    data = path.read_bytes()
    if len(data) % 4:
        raise SystemExit(f"{path}: SPIR-V byte count is not a multiple of four")
    words = struct.unpack(f"<{len(data) // 4}I", data)
    print(f"static const uint32_t {name}[{len(words)}] = {{")
    for offset in range(0, len(words), 6):
        row = ", ".join(f"0x{word:08x}u" for word in words[offset:offset + 6])
        print(f"\t{row},")
    print("};")
    print(f"static const uint32_t {name}_size = {len(data)}u;\n")

print("// SPDX-License-Identifier: GPL-3.0-or-later")
print("// SPDX-FileCopyrightText: 2026 Wired Engine contributors")
print("// Generated by code/tools/profile_imgui/shaders/regen.sh. DO NOT EDIT.\n")
print("#ifndef WIRED_PROFILE_IMGUI_SPV_H")
print("#define WIRED_PROFILE_IMGUI_SPV_H\n")
print("#include <stdint.h>\n")
emit("wired_profile_imgui_vert_spv", pathlib.Path(sys.argv[1]))
emit("wired_profile_imgui_frag_spv", pathlib.Path(sys.argv[2]))
print("#endif // WIRED_PROFILE_IMGUI_SPV_H")
PY

if [ "$mode" = "--check" ]; then
	if ! cmp -s "$generated_header" wired_profile_imgui_spv.h; then
		echo "wired_profile_imgui_spv.h is stale; run $0" >&2
		exit 1
	fi
	exit 0
fi

mv "$generated_header" wired_profile_imgui_spv.h
