// Code generated from the curated Q3 demo base asset entries.
// To update, modify the source list and regenerate.
package pipeline

var QuakeDataDemoQ3DownloadUri = "https://objects.eser.live/quakedata/demoq3/pak0.pk3"

// Q3CopyPax01Entries contains files available in the Q3 demo pak.
// Paths are lowercase for case-insensitive matching.
var Q3CopyPax01Entries = map[string]ProcessorEntry{
	"botfiles/bots/daemia_c.c": {},
	"botfiles/bots/daemia_i.c": {},
	"botfiles/bots/daemia_t.c": {},
	"botfiles/bots/daemia_w.c": {},
	"botfiles/bots/grunt_c.c":  {},
	"botfiles/bots/grunt_i.c":  {},
	"botfiles/bots/grunt_t.c":  {},
	"botfiles/bots/grunt_w.c":  {},
	"botfiles/bots/major_c.c":  {},
	"botfiles/bots/major_i.c":  {},
	"botfiles/bots/major_t.c":  {},
	"botfiles/bots/major_w.c":  {},
	"botfiles/bots/sarge_c.c":  {},
	"botfiles/bots/sarge_i.c":  {},
	"botfiles/bots/sarge_t.c":  {},
	"botfiles/bots/sarge_w.c":  {},
	"botfiles/bots/stripe_c.c": {},
	"botfiles/bots/stripe_i.c": {},
	"botfiles/bots/stripe_t.c": {},
	"botfiles/bots/stripe_w.c": {},
	"botfiles/bots/visor_c.c":  {},
	"botfiles/bots/visor_i.c":  {},
	"botfiles/bots/visor_t.c":  {},
	"botfiles/bots/visor_w.c":  {},
	"botfiles/game.h":          {},
	// "gfx/2d/backtile.jpg":       {},
	// "gfx/2d/colorbar.jpg":       {},
	// "gfx/2d/lag.jpg":                 {},
	// "gfx/2d/net.jpg":                 {},
	// "gfx/colors/black.jpg":           {},
	// "gfx/damage/bullet_mrk.jpg":      {},
	// "gfx/damage/burn_med_mrk.jpg":    {},
	// "gfx/damage/hole_lg_mrk.jpg":     {},
	"gfx/misc/console01.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "gfx/misc/console01.png"},
	"gfx/misc/console02.jpg": {},
	// "gfx/misc/flare.jpg":             {},
	"gfx/misc/lightning3.jpg": {},
	// "gfx/misc/railcorethin_mono.jpg": {},
	// "gfx/misc/raildisc_mono2.jpg":    {},
	// "gfx/misc/sun.jpg":              {},
	"gfx/misc/teleporteffect2.jpg": {},
	// "gfx/misc/tracer2.jpg":         {},
	"icons/envirosuit.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/envirosuit.png"},
	"icons/flight.tga":     {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/flight.png"},
	"icons/haste.tga":      {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/haste.png"},
	// "icons/icona_bfg.tga":                               {},
	"icons/icona_grenade.tga":    {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/icona_grenade.png"},
	"icons/icona_lightning.tga":  {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/icona_lightning.png"},
	"icons/icona_machinegun.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/icona_machinegun.png"},
	"icons/icona_plasma.tga":     {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/icona_plasma.png"},
	"icons/iconf_blu.tga":        {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconf_blu.png"},
	"icons/iconf_red.tga":        {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconf_red.png"},
	// "icons/iconh_mega.tga":       {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconh_mega.png"},
	"icons/iconh_red.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconh_red.png"},
	"icons/iconr_red.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconr_red.png"},
	// "icons/iconr_shard.tga":  {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconr_shard.png"},
	// "icons/iconw_bfg.tga":                               {},
	// "icons/iconw_grapple.tga":                           {},
	"icons/iconw_grenade.tga":   {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconw_grenade.png"},
	"icons/iconw_lightning.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconw_lightning.png"},
	"icons/iconw_plasma.tga":    {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/iconw_plasma.png"},
	"icons/invis.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/invis.png"},
	"icons/medkit.tga":          {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/medkit.png"},
	"icons/quad.tga":            {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/quad.png"},
	"icons/regen.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/regen.png"},
	"icons/teleporter.tga":      {Mode: ModeConvert, TargetFmt: "png", TargetPath: "icons/teleporter.png"},
	"levelshots/q3dm17.jpg":     {},
	"levelshots/q3dm7.jpg":      {},
	"levelshots/q3tourney2.jpg": {},
	"maps/q3dm1.aas":            {},
	"maps/q3dm1.bsp":            {},
	"maps/q3dm17.aas":           {},
	"maps/q3dm17.bsp":           {},
	"maps/q3dm7.aas":            {},
	"maps/q3dm7.bsp":            {},
	"maps/q3tourney2.aas":       {},
	"maps/q3tourney2.bsp":       {},
	// "menu/art/3_cursor2.tga":                            {},
	// "menu/art/accept_0.tga":                             {},
	// "menu/art/accept_1.tga":                             {},
	// "menu/art/addbotframe.tga":                          {},
	// "menu/art/arrows_horz_0.tga":                        {},
	// "menu/art/arrows_horz_left.tga":                     {},
	// "menu/art/arrows_horz_right.tga":                    {},
	// "menu/art/arrows_vert_0.tga":                        {},
	// "menu/art/arrows_vert_bot.tga":                      {},
	// "menu/art/arrows_vert_top.tga":                      {},
	// "menu/art/back_0.tga":                               {},
	// "menu/art/back_1.tga":                               {},
	// "menu/art/create_0.tga":                             {},
	// "menu/art/create_1.tga":                             {},
	// "menu/art/cut_frame.tga":                            {},
	// "menu/art/delete_0.tga":                             {},
	// "menu/art/delete_1.tga":                             {},
	// "menu/art/fight_0.tga":                              {},
	// "menu/art/fight_1.tga":                              {},
	// "menu/art/font1_prop.tga":                           {},
	// "menu/art/font1_prop_glo.tga":                       {},
	// "menu/art/font2_prop.tga":                           {},
	// "menu/art/frame1_l.tga":                             {},
	// "menu/art/frame1_r.tga":                             {},
	// "menu/art/frame2_l.tga":                             {},
	// "menu/art/fx_base.tga":                              {},
	// "menu/art/fx_blue.tga":                              {},
	// "menu/art/fx_cyan.tga":                              {},
	// "menu/art/fx_grn.tga":                               {},
	// "menu/art/fx_red.tga":                               {},
	// "menu/art/fx_teal.tga":                              {},
	// "menu/art/fx_white.tga":                             {},
	// "menu/art/fx_yel.tga":                               {},
	// "menu/art/gs_arrows_0.tga":                          {},
	// "menu/art/gs_arrows_l.tga":                          {},
	// "menu/art/gs_arrows_r.tga":                          {},
	// "menu/art/level_complete1.tga":                      {},
	// "menu/art/level_complete2.tga":                      {},
	// "menu/art/level_complete3.tga":                      {},
	// "menu/art/level_complete4.tga":                      {},
	// "menu/art/level_complete5.tga":                      {},
	// "menu/art/load_0.tga":                               {},
	// "menu/art/load_1.tga":                               {},
	// "menu/art/maps_select.tga":                          {},
	// "menu/art/maps_selected.tga":                        {},
	// "menu/art/menu_0.tga":                               {},
	// "menu/art/menu_1.tga":                               {},
	// "menu/art/model_0.tga":                              {},
	// "menu/art/model_1.tga":                              {},
	// "menu/art/narrow_0.tga":                             {},
	// "menu/art/narrow_1.tga":                             {},
	// "menu/art/next_0.tga":                               {},
	// "menu/art/next_1.tga":                               {},
	// "menu/art/opponents_select.tga":                     {},
	// "menu/art/opponents_selected.tga":                   {},
	// "menu/art/play_0.tga":                               {},
	// "menu/art/play_1.tga":                               {},
	// "menu/art/player_models_ports.tga":                  {},
	// "menu/art/refresh_0.tga":                            {},
	// "menu/art/refresh_1.tga":                            {},
	// "menu/art/replay_0.tga":                             {},
	// "menu/art/replay_1.tga":                             {},
	// "menu/art/reset_0.tga":                              {},
	// "menu/art/reset_1.tga":                              {},
	// "menu/art/save_0.tga":                               {},
	// "menu/art/save_1.tga":                               {},
	// "menu/art/skill1.tga":                               {},
	// "menu/art/skill2.tga":                               {},
	// "menu/art/skill3.tga":                               {},
	// "menu/art/skill4.tga":                               {},
	// "menu/art/skill5.tga":                               {},
	// "menu/art/skirmish_0.tga":                           {},
	// "menu/art/skirmish_1.tga":                           {},
	// "menu/art/slider2.tga":                              {},
	// "menu/art/sliderbutt_0.tga":                         {},
	// "menu/art/sliderbutt_1.tga":                         {},
	// "menu/art/specify_0.tga":                            {},
	// "menu/art/specify_1.tga":                            {},
	// "menu/art/switch_off.tga":                           {},
	// "menu/art/switch_on.tga":                            {},
	// "menu/art/unknownmap.jpg":                           {},
	// "menu/medals/medal_accuracy.tga":                    {},
	// "menu/medals/medal_excellent.tga":                   {},
	// "menu/medals/medal_frags.tga":                       {},
	// "menu/medals/medal_gauntlet.tga":                    {},
	// "menu/medals/medal_impressive.tga":                  {},
	// "menu/medals/medal_victory.tga":                     {},
	// "menu/tab/name.tga":                                 {},
	// "menu/tab/ping.tga":                                 {},
	// "menu/tab/score.tga":                                {},
	// "menu/tab/time.tga":                                 {},
	"models/ammo/grenade.jpg":   {},
	"models/ammo/grenade1.md3":  {},
	"models/ammo/grenade_g.jpg": {},
	"models/ammo/grenade_r.jpg": {},
	// "models/gibs/gibs.jpg":                              {},
	"models/mapobjects/banner/banner5.md3":              {},
	"models/mapobjects/banner/q3banner02.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/banner/q3banner02.png"},
	"models/mapobjects/banner/q3banner02x.tga":          {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/banner/q3banner02x.png"},
	"models/mapobjects/baph/baphomet_gold.tga":          {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/baph/baphomet_gold.png"},
	"models/mapobjects/bitch/hologirl2.jpg":             {},
	"models/mapobjects/chain/chain.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/chain/chain.png"},
	"models/mapobjects/corpse/corpse.jpg":               {},
	"models/mapobjects/eagleban.jpg":                    {},
	"models/mapobjects/flag/banner_strgg.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/flag/banner_strgg.png"},
	"models/mapobjects/gargoyle.jpg":                    {},
	"models/mapobjects/gratelamp/gratetorch2.jpg":       {},
	"models/mapobjects/gratelamp/gratetorch2b.tga":      {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/gratelamp/gratetorch2b.png"},
	"models/mapobjects/kmlamp1.jpg":                     {},
	"models/mapobjects/lamps/bot_flare.jpg":             {},
	"models/mapobjects/lamps/bot_flare2.jpg":            {},
	"models/mapobjects/lamps/bot_lamp.jpg":              {},
	"models/mapobjects/lamps/bot_lamp2.jpg":             {},
	"models/mapobjects/lamps/bot_wing.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/lamps/bot_wing.png"},
	"models/mapobjects/lamps/flare03.jpg":               {},
	"models/mapobjects/major_h_st.jpg":                  {},
	"models/mapobjects/major_st.jpg":                    {},
	"models/mapobjects/podium/podium.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/podium/podium.png"},
	"models/mapobjects/podium/podium4.md3":              {},
	"models/mapobjects/podium/podiumfx1.jpg":            {},
	"models/mapobjects/podium/podiumfx1b.jpg":           {},
	"models/mapobjects/podium/podiumglo.tga":            {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/podium/podiumglo.png"},
	"models/mapobjects/podium/podskull.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/podium/podskull.png"},
	"models/mapobjects/podium/podskullfx.jpg":           {},
	"models/mapobjects/portal_2/portal_3.jpg":           {},
	"models/mapobjects/portal_2/portal_3_edge.jpg":      {},
	"models/mapobjects/portal_2/portal_3_edge_glo.jpg":  {},
	"models/mapobjects/portal_2/portal_3_glo.jpg":       {},
	"models/mapobjects/skel/skel.tga":                   {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/skel/skel.png"},
	"models/mapobjects/skull/skull.jpg":                 {},
	"models/mapobjects/spotlamp/beam.jpg":               {},
	"models/mapobjects/spotlamp/spotlamp.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/spotlamp/spotlamp.png"},
	"models/mapobjects/spotlamp/spotlamp_l.jpg":         {},
	"models/mapobjects/storch/storch.jpg":               {},
	"models/mapobjects/storch/storch_tall.jpg":          {},
	"models/mapobjects/teleporter/energy.jpg":           {},
	"models/mapobjects/teleporter/energy2.jpg":          {},
	"models/mapobjects/teleporter/energy3.jpg":          {},
	"models/mapobjects/teleporter/pad.jpg":              {},
	"models/mapobjects/teleporter/teleporter.jpg":       {},
	"models/mapobjects/teleporter/teleporter_edge.jpg":  {},
	"models/mapobjects/teleporter/teleporter_edge2.jpg": {},
	"models/mapobjects/teleporter/transparency.jpg":     {},
	"models/mapobjects/teleporter/transparency2.jpg":    {},
	"models/mapobjects/teleporter/widget.jpg":           {},
	"models/mapobjects/timlamp/timlamp.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/timlamp/timlamp.png"},
	"models/mapobjects/visor_st.jpg":                    {},
	"models/mapobjects/wall_lamp3.jpg":                  {},
	"models/mapobjects/wallhead/lion.jpg":               {},
	"models/mapobjects/wallhead/lion_m.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/mapobjects/wallhead/lion_m.png"},
	"models/mapobjects/wallhead/wallhead02.jpg":         {},
	"models/misc/telep.md3":                             {},
	"models/players/grunt/animation.cfg":                {},
	"models/players/grunt/blue.jpg":                     {},
	"models/players/grunt/blue_h.jpg":                   {},
	"models/players/grunt/grunt.jpg":                    {},
	"models/players/grunt/grunt_h.jpg":                  {},
	"models/players/grunt/head.md3":                     {},
	"models/players/grunt/head_1.md3":                   {},
	"models/players/grunt/head_2.md3":                   {},
	"models/players/grunt/head_blue.skin":               {},
	"models/players/grunt/head_default.skin":            {},
	"models/players/grunt/head_red.skin":                {},
	"models/players/grunt/head_stripe.skin":             {},
	"models/players/grunt/icon_blue.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/grunt/icon_blue.png"},
	"models/players/grunt/icon_default.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/grunt/icon_default.png"},
	"models/players/grunt/icon_red.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/grunt/icon_red.png"},
	"models/players/grunt/icon_stripe.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/grunt/icon_stripe.png"},
	"models/players/grunt/lower.md3":                    {},
	"models/players/grunt/lower_1.md3":                  {},
	"models/players/grunt/lower_2.md3":                  {},
	"models/players/grunt/lower_blue.skin":              {},
	"models/players/grunt/lower_default.skin":           {},
	"models/players/grunt/lower_red.skin":               {},
	"models/players/grunt/lower_stripe.skin":            {},
	"models/players/grunt/red.jpg":                      {},
	"models/players/grunt/red_h.jpg":                    {},
	"models/players/grunt/stripe.jpg":                   {},
	"models/players/grunt/stripe_h.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/grunt/stripe_h.png"},
	"models/players/grunt/upper.md3":                    {},
	"models/players/grunt/upper_1.md3":                  {},
	"models/players/grunt/upper_2.md3":                  {},
	"models/players/grunt/upper_blue.skin":              {},
	"models/players/grunt/upper_default.skin":           {},
	"models/players/grunt/upper_red.skin":               {},
	"models/players/grunt/upper_stripe.skin":            {},
	"models/players/major/animation.cfg":                {},
	"models/players/major/blue.jpg":                     {},
	"models/players/major/blue_h.jpg":                   {},
	"models/players/major/daemia.tga":                   {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/major/daemia.png"},
	"models/players/major/daemia2_h.jpg":                {},
	"models/players/major/head.md3":                     {},
	"models/players/major/head_1.md3":                   {},
	"models/players/major/head_2.md3":                   {},
	"models/players/major/head_blue.skin":               {},
	"models/players/major/head_daemia.skin":             {},
	"models/players/major/head_default.skin":            {},
	"models/players/major/head_red.skin":                {},
	"models/players/major/icon_blue.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/major/icon_blue.png"},
	"models/players/major/icon_daemia.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/major/icon_daemia.png"},
	"models/players/major/icon_default.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/major/icon_default.png"},
	"models/players/major/icon_red.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/major/icon_red.png"},
	"models/players/major/lower.md3":                    {},
	"models/players/major/lower_1.md3":                  {},
	"models/players/major/lower_2.md3":                  {},
	"models/players/major/lower_blue.skin":              {},
	"models/players/major/lower_daemia.skin":            {},
	"models/players/major/lower_default.skin":           {},
	"models/players/major/lower_red.skin":               {},
	"models/players/major/major.jpg":                    {},
	"models/players/major/major_h.jpg":                  {},
	"models/players/major/red.jpg":                      {},
	"models/players/major/red_h.jpg":                    {},
	"models/players/major/upper.md3":                    {},
	"models/players/major/upper_1.md3":                  {},
	"models/players/major/upper_2.md3":                  {},
	"models/players/major/upper_blue.skin":              {},
	"models/players/major/upper_daemia.skin":            {},
	"models/players/major/upper_default.skin":           {},
	"models/players/major/upper_red.skin":               {},
	"models/players/sarge/blue.jpg":                     {},
	"models/players/sarge/head_blue.skin":               {},
	"models/players/sarge/head_krusade.skin":            {},
	"models/players/sarge/head_red.skin":                {},
	"models/players/sarge/icon_blue.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/sarge/icon_blue.png"},
	"models/players/sarge/icon_red.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/sarge/icon_red.png"},
	"models/players/sarge/krusade.tga":                  {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/sarge/krusade.png"},
	"models/players/sarge/lower_blue.skin":              {},
	"models/players/sarge/lower_krusade.skin":           {},
	"models/players/sarge/lower_red.skin":               {},
	"models/players/sarge/null.jpg":                     {},
	"models/players/sarge/red.jpg":                      {},
	"models/players/sarge/upper_blue.skin":              {},
	"models/players/sarge/upper_krusade.skin":           {},
	"models/players/sarge/upper_red.skin":               {},
	"models/players/visor/animation.cfg":                {},
	"models/players/visor/blue.jpg":                     {},
	"models/players/visor/head.md3":                     {},
	"models/players/visor/head_1.md3":                   {},
	"models/players/visor/head_2.md3":                   {},
	"models/players/visor/head_blue.skin":               {},
	"models/players/visor/head_default.skin":            {},
	"models/players/visor/head_red.skin":                {},
	"models/players/visor/icon_blue.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/visor/icon_blue.png"},
	"models/players/visor/icon_default.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/visor/icon_default.png"},
	"models/players/visor/icon_red.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/players/visor/icon_red.png"},
	"models/players/visor/lower.md3":                    {},
	"models/players/visor/lower_1.md3":                  {},
	"models/players/visor/lower_2.md3":                  {},
	"models/players/visor/lower_blue.skin":              {},
	"models/players/visor/lower_default.skin":           {},
	"models/players/visor/lower_red.skin":               {},
	"models/players/visor/red.jpg":                      {},
	"models/players/visor/upper.md3":                    {},
	"models/players/visor/upper_1.md3":                  {},
	"models/players/visor/upper_2.md3":                  {},
	"models/players/visor/upper_blue.skin":              {},
	"models/players/visor/upper_default.skin":           {},
	"models/players/visor/upper_red.skin":               {},
	"models/players/visor/visor.jpg":                    {},
	// "models/powerups/ammo/bfgam.md3":                    {},
	// "models/powerups/ammo/bfgam_1.md3":                  {},
	// "models/powerups/ammo/bfgammo.tga":                  {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/powerups/ammo/bfgammo.png"},
	// "models/powerups/ammo/bfgammo2.jpg":                 {},
	"models/powerups/ammo/grenadeam.md3":          {},
	"models/powerups/ammo/grenadeam_1.md3":        {},
	"models/powerups/ammo/grenammo.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/powerups/ammo/grenammo.png"},
	"models/powerups/ammo/grenammo2.jpg":          {},
	"models/powerups/ammo/lighammo.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/powerups/ammo/lighammo.png"},
	"models/powerups/ammo/lighammo2.jpg":          {},
	"models/powerups/ammo/lightningam.md3":        {},
	"models/powerups/ammo/lightningam_1.md3":      {},
	"models/powerups/ammo/plasammo.tga":           {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/powerups/ammo/plasammo.png"},
	"models/powerups/ammo/plasammo2.jpg":          {},
	"models/powerups/ammo/plasmaam.md3":           {},
	"models/powerups/ammo/plasmaam_1.md3":         {},
	"models/powerups/armor/armor_red.md3":         {},
	"models/powerups/armor/armor_red_1.md3":       {},
	"models/powerups/armor/armor_red_2.md3":       {},
	"models/powerups/armor/energy_red1.jpg":       {},
	"models/powerups/armor/newred.tga":            {Mode: ModeConvert, TargetFmt: "png", TargetPath: "models/powerups/armor/newred.png"},
	"models/powerups/health/large_cross.md3":      {},
	"models/powerups/health/large_sphere.md3":     {},
	"models/powerups/health/large_sphere_1.md3":   {},
	"models/powerups/health/large_sphere_2.md3":   {},
	"models/powerups/health/mega_cross.md3":       {},
	"models/powerups/health/mega_sphere.md3":      {},
	"models/powerups/health/mega_sphere_1.md3":    {},
	"models/powerups/health/mega_sphere_2.md3":    {},
	"models/powerups/holdable/medkit.md3":         {},
	"models/powerups/holdable/medkit_1.md3":       {},
	"models/powerups/holdable/medkit_fluid.jpg":   {},
	"models/powerups/holdable/teleport_fluid.jpg": {},
	"models/powerups/holdable/teleporter.md3":     {},
	"models/powerups/holdable/teleporter_1.md3":   {},
	"models/powerups/instant/enviro.md3":          {},
	"models/powerups/instant/enviro_1.md3":        {},
	"models/powerups/instant/enviro_ring.md3":     {},
	"models/powerups/instant/enviro_ring_1.md3":   {},
	"models/powerups/instant/flight.md3":          {},
	"models/powerups/instant/flight_1.md3":        {},
	"models/powerups/instant/flight_ring.md3":     {},
	"models/powerups/instant/flight_ring_1.md3":   {},
	"models/powerups/instant/haste.md3":           {},
	"models/powerups/instant/haste_1.md3":         {},
	"models/powerups/instant/haste_ring.md3":      {},
	"models/powerups/instant/haste_ring_1.md3":    {},
	"models/powerups/instant/invis.md3":           {},
	"models/powerups/instant/invis_1.md3":         {},
	"models/powerups/instant/invis_ring.md3":      {},
	"models/powerups/instant/invis_ring_1.md3":    {},
	"models/powerups/instant/quad.md3":            {},
	"models/powerups/instant/quad_1.md3":          {},
	"models/powerups/instant/quad_ring.md3":       {},
	"models/powerups/instant/quad_ring_1.md3":     {},
	"models/powerups/instant/regen.md3":           {},
	"models/powerups/instant/regen_1.md3":         {},
	"models/powerups/instant/regen_ring.md3":      {},
	"models/powerups/instant/regen_ring_1.md3":    {},
	// "models/weaphits/bfg.md3":                           {},
	// "models/weaphits/bfg01.jpg":                         {},
	// "models/weaphits/bfg02.jpg":                         {},
	// "models/weaphits/bfg03.jpg":                         {},
	"models/weaphits/crackle.md3":    {},
	"models/weaphits/electric.jpg":   {},
	"models/weaphits/plasmaboom.jpg": {},
	// "models/weapons2/gauntlet/gauntlet.md3":              {},
	// "models/weapons2/gauntlet/gauntlet1.jpg":             {},
	// "models/weapons2/gauntlet/gauntlet2.tga":             {},
	// "models/weapons2/gauntlet/gauntlet3.jpg":             {},
	// "models/weapons2/gauntlet/gauntlet4.jpg":             {},
	// "models/weapons2/gauntlet/gauntlet_barrel.md3":       {},
	// "models/weapons2/gauntlet/gauntlet_flash.md3":        {},
	// "models/weapons2/gauntlet/gauntlet_hand.md3":         {},
	// "models/weapons2/lightning/button.jpg":               {},
	// "models/weapons2/lightning/f_lightning.jpg":          {},
	// "models/weapons2/lightning/glass.jpg":                {},
	// "models/weapons2/lightning/lightning.md3":            {},
	// "models/weapons2/lightning/lightning2.jpg":           {},
	// "models/weapons2/lightning/lightning_1.md3":          {},
	// "models/weapons2/lightning/lightning_2.md3":          {},
	// "models/weapons2/lightning/lightning_flash.md3":      {},
	// "models/weapons2/lightning/lightning_hand.md3":       {},
	// "models/weapons2/lightning/trail2.jpg":               {},
	// "models/weapons2/machinegun/f_machinegun.jpg":        {},
	// "models/weapons2/machinegun/machinegun.jpg":          {},
	// "models/weapons2/machinegun/machinegun.md3":          {},
	// "models/weapons2/machinegun/machinegun_1.md3":        {},
	// "models/weapons2/machinegun/machinegun_2.md3":        {},
	// "models/weapons2/machinegun/machinegun_barrel.md3":   {},
	// "models/weapons2/machinegun/machinegun_barrel_1.md3": {},
	// "models/weapons2/machinegun/machinegun_barrel_2.md3": {},
	// "models/weapons2/machinegun/machinegun_flash.md3":    {},
	// "models/weapons2/machinegun/machinegun_hand.md3":     {},
	// "models/weapons2/plasma/f_plasma.jpg":                {},
	// "models/weapons2/plasma/plasma.jpg":                  {},
	// "models/weapons2/plasma/plasma.md3":                  {},
	// "models/weapons2/plasma/plasma_1.md3":                {},
	// "models/weapons2/plasma/plasma_2.md3":                {},
	// "models/weapons2/plasma/plasma_flash.md3":            {},
	// "models/weapons2/plasma/plasma_glo.jpg":              {},
	// "models/weapons2/plasma/plasma_hand.md3":             {},
	// "models/weapons2/railgun/f_railgun2.jpg":             {},
	// "models/weapons2/railgun/railgun.md3":                {},
	// "models/weapons2/railgun/railgun1.jpg":               {},
	// "models/weapons2/railgun/railgun2.glow.jpg":          {},
	// "models/weapons2/railgun/railgun3.glow.jpg":          {},
	// "models/weapons2/railgun/railgun3.jpg":               {},
	// "models/weapons2/railgun/railgun4.jpg":               {},
	// "models/weapons2/railgun/railgun_flash.md3":          {},
	// "models/weapons2/railgun/railgun_hand.md3":           {},
	// "models/weapons2/rocketl/f_rocketl.jpg":              {},
	// "models/weapons2/rocketl/rocketl.jpg":                {},
	// "models/weapons2/rocketl/rocketl.md3":                {},
	// "models/weapons2/rocketl/rocketl2.jpg":               {},
	// "models/weapons2/rocketl/rocketl_1.md3":              {},
	// "models/weapons2/rocketl/rocketl_2.md3":              {},
	// "models/weapons2/rocketl/rocketl_flash.md3":          {},
	// "models/weapons2/rocketl/rocketl_hand.md3":           {},
	// "models/weapons2/shotgun/f_shotgun.jpg":              {},
	// "models/weapons2/shotgun/shotgun.jpg":                {},
	// "models/weapons2/shotgun/shotgun.md3":                {},
	// "models/weapons2/shotgun/shotgun_1.md3":              {},
	// "models/weapons2/shotgun/shotgun_2.md3":              {},
	// "models/weapons2/shotgun/shotgun_flash.md3":          {},
	// "models/weapons2/shotgun/shotgun_hand.md3":           {},
	// "models/weapons2/shotgun/shotgun_laser.jpg":          {},
	"music/loss.wav":                                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "music/loss.opus"},
	"scripts/arenas.txt":                                 {},
	"sound/feedback/accuracy.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/accuracy.opus"},
	"sound/feedback/excellent_a.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/excellent_a.opus"},
	"sound/feedback/frags.wav":                           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/frags.opus"},
	"sound/feedback/gauntlet.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/gauntlet.opus"},
	"sound/feedback/impressive_a.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/impressive_a.opus"},
	"sound/feedback/perfect.wav":                         {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/feedback/perfect.opus"},
	"sound/items/poweruprespawn.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/items/poweruprespawn.opus"},
	"sound/misc/ar3_pkup.wav":                            {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/ar3_pkup.opus"},
	"sound/misc/menu1.wav":                               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/menu1.opus"},
	"sound/misc/menu3.wav":                               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/menu3.opus"},
	"sound/misc/menu4.wav":                               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/menu4.opus"},
	"sound/misc/nightmare.wav":                           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/nightmare.opus"},
	"sound/misc/silence.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/misc/silence.opus"},
	"sound/movers/doors/dr1_end.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/movers/doors/dr1_end.opus"},
	"sound/movers/doors/dr1_strt.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/movers/doors/dr1_strt.opus"},
	"sound/movers/switches/butn2.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/movers/switches/butn2.opus"},
	"sound/player/announce/anarki_wins.wav":              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/anarki_wins.opus"},
	"sound/player/announce/bitterman_wins.wav":           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/bitterman_wins.opus"},
	"sound/player/announce/crash_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/crash_wins.opus"},
	"sound/player/announce/daemia.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/daemia.opus"},
	"sound/player/announce/daemia_wins.wav":              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/daemia_wins.opus"},
	"sound/player/announce/doom_wins.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/doom_wins.opus"},
	"sound/player/announce/flisk_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/flisk_wins.opus"},
	"sound/player/announce/gorre_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/gorre_wins.opus"},
	"sound/player/announce/grunt.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/grunt.opus"},
	"sound/player/announce/grunt_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/grunt_wins.opus"},
	"sound/player/announce/keel_wins.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/keel_wins.opus"},
	"sound/player/announce/klesk_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/klesk_wins.opus"},
	"sound/player/announce/krusade_wins.wav":             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/krusade_wins.opus"},
	"sound/player/announce/major.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/major.opus"},
	"sound/player/announce/major_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/major_wins.opus"},
	"sound/player/announce/mynx_wins.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/mynx_wins.opus"},
	"sound/player/announce/patriot_wins.wav":             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/patriot_wins.opus"},
	"sound/player/announce/phobos_wins.wav":              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/phobos_wins.opus"},
	"sound/player/announce/ranger_wins.wav":              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/ranger_wins.opus"},
	"sound/player/announce/razor_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/razor_wins.opus"},
	"sound/player/announce/sarge.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/sarge.opus"},
	"sound/player/announce/slammer_wins.wav":             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/slammer_wins.opus"},
	"sound/player/announce/slash_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/slash_wins.opus"},
	"sound/player/announce/stripe.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/stripe.opus"},
	"sound/player/announce/stripe_wins.wav":              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/stripe_wins.opus"},
	"sound/player/announce/uriel_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/uriel_wins.opus"},
	"sound/player/announce/visor.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/visor.opus"},
	"sound/player/announce/visor_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/visor_wins.opus"},
	"sound/player/announce/wrack_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/wrack_wins.opus"},
	"sound/player/announce/xaero_wins.wav":               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/xaero_wins.opus"},
	"sound/player/announce/xray_wins.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/xray_wins.opus"},
	"sound/player/announce/youwin.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/announce/youwin.opus"},
	"sound/player/grunt/death1.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/death1.opus"},
	"sound/player/grunt/death2.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/death2.opus"},
	"sound/player/grunt/death3.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/death3.opus"},
	"sound/player/grunt/drown.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/drown.opus"},
	"sound/player/grunt/fall1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/fall1.opus"},
	"sound/player/grunt/falling1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/falling1.opus"},
	"sound/player/grunt/gasp.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/gasp.opus"},
	"sound/player/grunt/jump1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/jump1.opus"},
	"sound/player/grunt/pain100_1.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/pain100_1.opus"},
	"sound/player/grunt/pain25_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/pain25_1.opus"},
	"sound/player/grunt/pain50_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/pain50_1.opus"},
	"sound/player/grunt/pain75_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/pain75_1.opus"},
	"sound/player/grunt/taunt.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/grunt/taunt.opus"},
	"sound/player/gurp1.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/gurp1.opus"},
	"sound/player/gurp2.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/gurp2.opus"},
	"sound/player/major/death1.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/death1.opus"},
	"sound/player/major/death2.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/death2.opus"},
	"sound/player/major/death3.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/death3.opus"},
	"sound/player/major/drown.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/drown.opus"},
	"sound/player/major/fall1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/fall1.opus"},
	"sound/player/major/falling1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/falling1.opus"},
	"sound/player/major/gasp.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/gasp.opus"},
	"sound/player/major/jump1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/jump1.opus"},
	"sound/player/major/pain100_1.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/pain100_1.opus"},
	"sound/player/major/pain25_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/pain25_1.opus"},
	"sound/player/major/pain50_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/pain50_1.opus"},
	"sound/player/major/pain75_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/pain75_1.opus"},
	"sound/player/major/taunt.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/major/taunt.opus"},
	"sound/player/sarge/death1.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/death1.opus"},
	"sound/player/sarge/death2.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/death2.opus"},
	"sound/player/sarge/death3.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/death3.opus"},
	"sound/player/sarge/drown.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/drown.opus"},
	"sound/player/sarge/fall1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/fall1.opus"},
	"sound/player/sarge/falling1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/falling1.opus"},
	"sound/player/sarge/gasp.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/gasp.opus"},
	"sound/player/sarge/jump1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/jump1.opus"},
	"sound/player/sarge/pain100_1.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/pain100_1.opus"},
	"sound/player/sarge/pain25_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/pain25_1.opus"},
	"sound/player/sarge/pain50_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/pain50_1.opus"},
	"sound/player/sarge/pain75_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/pain75_1.opus"},
	"sound/player/sarge/taunt.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/sarge/taunt.opus"},
	"sound/player/visor/death1.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/death1.opus"},
	"sound/player/visor/death2.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/death2.opus"},
	"sound/player/visor/death3.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/death3.opus"},
	"sound/player/visor/drown.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/drown.opus"},
	"sound/player/visor/fall1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/fall1.opus"},
	"sound/player/visor/falling1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/falling1.opus"},
	"sound/player/visor/gasp.wav":                        {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/gasp.opus"},
	"sound/player/visor/jump1.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/jump1.opus"},
	"sound/player/visor/pain100_1.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/pain100_1.opus"},
	"sound/player/visor/pain25_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/pain25_1.opus"},
	"sound/player/visor/pain50_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/pain50_1.opus"},
	"sound/player/visor/pain75_1.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/pain75_1.opus"},
	"sound/player/visor/taunt.wav":                       {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/player/visor/taunt.opus"},
	"sound/teamplay/flagcap_blu.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagcap_blu.opus"},
	"sound/teamplay/flagcap_red.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagcap_red.opus"},
	"sound/teamplay/flagret_blu.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagret_blu.opus"},
	"sound/teamplay/flagret_red.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagret_red.opus"},
	"sound/teamplay/flagtk_blu.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagtk_blu.opus"},
	"sound/teamplay/flagtk_red.wav":                      {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/teamplay/flagtk_red.opus"},
	"sound/weapons/lightning/lg_fire.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/lightning/lg_fire.opus"},
	"sound/weapons/lightning/lg_hit.wav":                 {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/lightning/lg_hit.opus"},
	"sound/weapons/lightning/lg_hit2.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/lightning/lg_hit2.opus"},
	"sound/weapons/lightning/lg_hit3.wav":                {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/lightning/lg_hit3.opus"},
	"sound/weapons/lightning/lg_hum.wav":                 {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/lightning/lg_hum.opus"},
	"sound/weapons/melee/fsthum.wav":                     {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/melee/fsthum.opus"},
	"sound/weapons/plasma/hyprbf1a.wav":                  {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/plasma/hyprbf1a.opus"},
	"sound/weapons/plasma/lasfly.wav":                    {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/weapons/plasma/lasfly.opus"},
	"sound/world/ambient/x_ominous.wav":                  {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/ambient/x_ominous.opus"},
	"sound/world/drone6.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/drone6.opus"},
	"sound/world/evil.wav":                               {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/evil.opus"},
	"sound/world/fire1.wav":                              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/fire1.opus"},
	"sound/world/fireloud.wav":                           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/fireloud.opus"},
	"sound/world/firesoft.wav":                           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/firesoft.opus"},
	"sound/world/growl1.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/growl1.opus"},
	"sound/world/growl2.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/growl2.opus"},
	"sound/world/growl3.wav":                             {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/growl3.opus"},
	"sound/world/machinerydrone02.wav":                   {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/machinerydrone02.opus"},
	"sound/world/portal01.wav":                           {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/portal01.opus"},
	"sound/world/suck1.wav":                              {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/suck1.opus"},
	"sound/world/xchoir1.wav":                            {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/xchoir1.opus"},
	"sound/world/xchoir2.wav":                            {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/xchoir2.opus"},
	"sound/world/xforce2.wav":                            {Mode: ModeConvert, TargetFmt: "opus", TargetPath: "sound/world/xforce2.opus"},
	"textures/base_floor/diamond2c.jpg":                  {},
	"textures/base_floor/diamond2c_ow.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_floor/diamond2c_ow.png"},
	"textures/base_floor/pjgrate2.tga":                   {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_floor/pjgrate2.png"},
	"textures/base_light/baslt4_1.blend.jpg":             {},
	"textures/base_light/baslt4_1.jpg":                   {},
	"textures/base_light/ceil1_37.blend.jpg":             {},
	"textures/base_light/ceil1_37.jpg":                   {},
	"textures/base_light/ceil1_38.blend.jpg":             {},
	"textures/base_light/ceil1_38.jpg":                   {},
	"textures/base_light/ceil1_39.blend.jpg":             {},
	"textures/base_light/ceil1_39.jpg":                   {},
	"textures/base_light/light1.blend.jpg":               {},
	"textures/base_light/light1.jpg":                     {},
	"textures/base_light/light2.blend.jpg":               {},
	"textures/base_light/light2.jpg":                     {},
	"textures/base_light/light5.jpg":                     {},
	"textures/base_support/cable.jpg":                    {},
	"textures/base_support/cable_trans.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_support/cable_trans.png"},
	"textures/base_support/metal14_1.jpg":                {},
	"textures/base_trim/basemetalsupport.jpg":            {},
	"textures/base_trim/border11b.jpg":                   {},
	"textures/base_trim/border11light.glow.jpg":          {},
	"textures/base_trim/border11light.jpg":               {},
	"textures/base_trim/pewter_shiney.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_trim/pewter_shiney.png"},
	"textures/base_trim/spiderbit4.jpg":                  {},
	"textures/base_wall/atech1_a.jpg":                    {},
	"textures/base_wall/atech1_alpha.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_wall/atech1_alpha.png"},
	"textures/base_wall/atech1_e.jpg":                    {},
	"textures/base_wall/bluemetal2.jpg":                  {},
	"textures/base_wall/c_met5_2.jpg":                    {},
	"textures/base_wall/c_met7_2.jpg":                    {},
	"textures/base_wall/comp3text.jpg":                   {},
	"textures/base_wall/comp3textb.jpg":                  {},
	"textures/base_wall/main_q3abanner.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_wall/main_q3abanner.png"},
	"textures/base_wall/metalblack03.jpg":                {},
	"textures/base_wall/metalfloor_wall_10.jpg":          {},
	"textures/base_wall/metalfloor_wall_15.jpg":          {},
	"textures/base_wall/metalfloor_wall_15ow.tga":        {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_wall/metalfloor_wall_15ow.png"},
	"textures/base_wall/metaltech06final.jpg":            {},
	"textures/base_wall/metaltech12darkfinal.jpg":        {},
	"textures/base_wall/metaltech12final.jpg":            {},
	"textures/base_wall/metaltech13final.jpg":            {},
	"textures/base_wall/metfloor_block_3.jpg":            {},
	"textures/base_wall/patch10_beatup2.jpg":             {},
	"textures/base_wall/patch10_beatup4.jpg":             {},
	"textures/base_wall/protobanner.tga":                 {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_wall/protobanner.png"},
	"textures/base_wall/steed1ge.jpg":                    {},
	"textures/base_wall/steed1gf.tga":                    {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/base_wall/steed1gf.png"},
	"textures/effects/envmap.jpg":                        {},
	"textures/effects/envmapbfg.jpg":                     {},
	"textures/effects/envmapblue2.jpg":                   {},
	"textures/effects/envmapdim.jpg":                     {},
	"textures/effects/envmapgold.jpg":                    {},
	"textures/effects/envmapligh.jpg":                    {},
	"textures/effects/envmapplas.jpg":                    {},
	"textures/effects/envmappurp.jpg":                    {},
	"textures/effects/envmapred.jpg":                     {},
	"textures/effects/tinfx2.jpg":                        {},
	"textures/effects/tinfx3.jpg":                        {},
	"textures/effects/tinfxb.jpg":                        {},
	"textures/gothic_block/blocks10.jpg":                 {},
	"textures/gothic_block/blocks11b.jpg":                {},
	"textures/gothic_block/blocks11bbroke3.jpg":          {},
	"textures/gothic_block/blocks15.jpg":                 {},
	"textures/gothic_block/blocks17.jpg":                 {},
	"textures/gothic_block/blocks17_ow.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_block/blocks17_ow.png"},
	"textures/gothic_block/blocks17e.jpg":                {},
	"textures/gothic_block/blocks17g.jpg":                {},
	"textures/gothic_block/blocks18b.jpg":                {},
	"textures/gothic_block/blocks18c.jpg":                {},
	"textures/gothic_block/blocks18c_3.jpg":              {},
	"textures/gothic_block/blocks18cblood.jpg":           {},
	"textures/gothic_block/blocks18cgeomtrn2.tga":        {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_block/blocks18cgeomtrn2.png"},
	"textures/gothic_block/blocks20b.jpg":                {},
	"textures/gothic_block/demon_block15fx.tga":          {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_block/demon_block15fx.png"},
	"textures/gothic_block/evil2ckillblockglow.jpg":      {},
	"textures/gothic_block/gkc15b.jpg":                   {},
	"textures/gothic_block/gkc15c.jpg":                   {},
	"textures/gothic_block/gkc19a.jpg":                   {},
	"textures/gothic_block/gkc19b.jpg":                   {},
	"textures/gothic_block/gkc20a.jpg":                   {},
	"textures/gothic_block/gkc20b.jpg":                   {},
	"textures/gothic_block/killblock.jpg":                {},
	"textures/gothic_block/killblock_i.jpg":              {},
	"textures/gothic_block/killblock_i4.jpg":             {},
	"textures/gothic_block/killblockgeomtrn.tga":         {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_block/killblockgeomtrn.png"},
	"textures/gothic_block/largerblock3blood.tga":        {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_block/largerblock3blood.png"},
	"textures/gothic_block/windowevil2c_killblock.jpg":   {},
	"textures/gothic_button/timbutton.jpg":               {},
	"textures/gothic_button/timbutton2.jpg":              {},
	"textures/gothic_button/timbuttonside.jpg":           {},
	"textures/gothic_ceiling/ceilingtech01_f.jpg":        {},
	"textures/gothic_ceiling/ceilingtech02_a.jpg":        {},
	"textures/gothic_ceiling/ceilingtech02_b.jpg":        {},
	"textures/gothic_ceiling/ceilingtech02_c2.jpg":       {},
	"textures/gothic_ceiling/ceilingtech02_d.jpg":        {},
	"textures/gothic_ceiling/ceilingtech03_afinal.jpg":   {},
	"textures/gothic_ceiling/ceilingtechplain.jpg":       {},
	"textures/gothic_ceiling/stucco7top.jpg":             {},
	"textures/gothic_ceiling/woodceiling1a.jpg":          {},
	"textures/gothic_ceiling/woodceiling1b_dark.jpg":     {},
	"textures/gothic_door/archpart1.jpg":                 {},
	"textures/gothic_door/archpart10.jpg":                {},
	"textures/gothic_door/archpart2.jpg":                 {},
	"textures/gothic_door/archpart6.jpg":                 {},
	"textures/gothic_door/archpart7.jpg":                 {},
	"textures/gothic_door/archpart9.jpg":                 {},
	"textures/gothic_door/km_arena1archfinalc_top.jpg":   {},
	"textures/gothic_door/km_arena1archfinald_bot.jpg":   {},
	"textures/gothic_door/km_arena1archfinald_mid.jpg":   {},
	"textures/gothic_door/km_arena1columna2r.jpg":        {},
	"textures/gothic_door/skull_door_a.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_a.png"},
	"textures/gothic_door/skull_door_b.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_b.png"},
	"textures/gothic_door/skull_door_c.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_c.png"},
	"textures/gothic_door/skull_door_d.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_d.png"},
	"textures/gothic_door/skull_door_e.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_e.png"},
	"textures/gothic_door/skull_door_f.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skull_door_f.png"},
	"textures/gothic_door/skullarch_a.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skullarch_a.png"},
	"textures/gothic_door/skullarch_b.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skullarch_b.png"},
	"textures/gothic_door/skullarch_c.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_door/skullarch_c.png"},
	"textures/gothic_door/xian_tourneyarch_bottom2.jpg":  {},
	"textures/gothic_door/xian_tourneyarch_inside2.jpg":  {},
	"textures/gothic_door/xian_tourneyarch_med1b.jpg":    {},
	"textures/gothic_door/xian_tourneyarch_tall1c.jpg":   {},
	"textures/gothic_door/xian_tourneyarch_tall2b.jpg":   {},
	"textures/gothic_floor/blocks17floor2.jpg":           {},
	"textures/gothic_floor/blocks17floor3.jpg":           {},
	"textures/gothic_floor/center2trn.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_floor/center2trn.png"},
	"textures/gothic_floor/goopq1metal7_98e.jpg":         {},
	"textures/gothic_floor/largeblockfloor3.jpg":         {},
	"textures/gothic_floor/largeblockfloor4.jpg":         {},
	"textures/gothic_floor/largeblockfloor4broke.jpg":    {},
	"textures/gothic_floor/largerblock3b.jpg":            {},
	"textures/gothic_floor/largerblock3b3.jpg":           {},
	"textures/gothic_floor/largerblock3b4.jpg":           {},
	"textures/gothic_floor/largerblock3b_ow.tga":         {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_floor/largerblock3b_ow.png"},
	"textures/gothic_floor/metalbridge06.jpg":            {},
	"textures/gothic_floor/metalbridge06b.jpg":           {},
	"textures/gothic_floor/metalbridge06broke.jpg":       {},
	"textures/gothic_floor/q1metal7_99.jpg":              {},
	"textures/gothic_floor/q1metal7_99_broke.jpg":        {},
	"textures/gothic_floor/q1metal7_99stair.jpg":         {},
	"textures/gothic_floor/q1metal7_99stair2.jpg":        {},
	"textures/gothic_floor/q1metal7_99stair3.jpg":        {},
	"textures/gothic_floor/xstairtop4.jpg":               {},
	"textures/gothic_floor/xstairtop4bbrn.jpg":           {},
	"textures/gothic_floor/xstairtop7.jpg":               {},
	"textures/gothic_floor/xstairtop8.jpg":               {},
	"textures/gothic_floor/xstepborder10.jpg":            {},
	"textures/gothic_floor/xstepborder12.jpg":            {},
	"textures/gothic_floor/xstepborder13.jpg":            {},
	"textures/gothic_floor/xstepborder3.jpg":             {},
	"textures/gothic_floor/xstepborder3brn.jpg":          {},
	"textures/gothic_floor/xstepborder9.jpg":             {},
	"textures/gothic_light/ironcrosslt2.blend.jpg":       {},
	"textures/gothic_light/ironcrosslt2.jpg":             {},
	"textures/gothic_light/pentagram_light1.jpg":         {},
	"textures/gothic_light/pentagram_light1_blend.jpg":   {},
	"textures/gothic_trim/baseboard04.jpg":               {},
	"textures/gothic_trim/baseboard07.jpg":               {},
	"textures/gothic_trim/baseboard08_d.jpg":             {},
	"textures/gothic_trim/baseboard09.jpg":               {},
	"textures/gothic_trim/baseboard09_c3.jpg":            {},
	"textures/gothic_trim/baseboard09_e.jpg":             {},
	"textures/gothic_trim/baseboard09_e2.jpg":            {},
	"textures/gothic_trim/baseboard09_g.jpg":             {},
	"textures/gothic_trim/baseboard09_g3.jpg":            {},
	"textures/gothic_trim/baseboard09_l.jpg":             {},
	"textures/gothic_trim/baseboard09_l2.jpg":            {},
	"textures/gothic_trim/baseboard09_o3.jpg":            {},
	"textures/gothic_trim/baseboard10_d.jpg":             {},
	"textures/gothic_trim/border12.jpg":                  {},
	"textures/gothic_trim/column2c_test.jpg":             {},
	"textures/gothic_trim/columnsupportbottoms.jpg":      {},
	"textures/gothic_trim/columnsupportops.jpg":          {},
	"textures/gothic_trim/km_arena1tower4.jpg":           {},
	"textures/gothic_trim/km_arena1tower4_a.jpg":         {},
	"textures/gothic_trim/km_arena1tower_short.tga":      {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_trim/km_arena1tower_short.png"},
	"textures/gothic_trim/metalbase8a_brick.jpg":         {},
	"textures/gothic_trim/metaldemonkillblock.jpg":       {},
	"textures/gothic_trim/metalsupport4b.jpg":            {},
	"textures/gothic_trim/metalsupsolid.jpg":             {},
	"textures/gothic_trim/pitted_rust.jpg":               {},
	"textures/gothic_trim/pitted_rust2.jpg":              {},
	"textures/gothic_trim/pitted_rust3.jpg":              {},
	"textures/gothic_trim/q1metal7.jpg":                  {},
	"textures/gothic_trim/skullsvertgray02b.jpg":         {},
	"textures/gothic_trim/supportborder.jpg":             {},
	"textures/gothic_trim/supportborderside.jpg":         {},
	"textures/gothic_trim/tower_front.jpg":               {},
	"textures/gothic_trim/tower_side2.jpg":               {},
	"textures/gothic_trim/tower_side2b.jpg":              {},
	"textures/gothic_trim/tower_top.jpg":                 {},
	"textures/gothic_trim/window_a1.jpg":                 {},
	"textures/gothic_trim/window_a2.jpg":                 {},
	"textures/gothic_trim/window_a_base.jpg":             {},
	"textures/gothic_trim/window_a_bottom1.jpg":          {},
	"textures/gothic_trim/window_a_bottom2.jpg":          {},
	"textures/gothic_trim/x_noblight.tga":                {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_trim/x_noblight.png"},
	"textures/gothic_trim/x_noblightfx.jpg":              {},
	"textures/gothic_trim/xian_tourney_trim.jpg":         {},
	"textures/gothic_trim/xsupportborderside_shiney.tga": {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_trim/xsupportborderside_shiney.png"},
	"textures/gothic_wall/crack5c.jpg":                   {},
	"textures/gothic_wall/iron01_b.jpg":                  {},
	"textures/gothic_wall/iron01_e.jpg":                  {},
	"textures/gothic_wall/iron01_m.tga":                  {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_wall/iron01_m.png"},
	"textures/gothic_wall/iron01_ndark.tga":              {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/gothic_wall/iron01_ndark.png"},
	"textures/gothic_wall/iron01_ntech3.jpg":             {},
	"textures/gothic_wall/iron01_p2.jpg":                 {},
	"textures/gothic_wall/purptileb.jpg":                 {},
	"textures/gothic_wall/skull4.jpg":                    {},
	"textures/gothic_wall/slateroofc.jpg":                {},
	"textures/gothic_wall/streetbricks10.jpg":            {},
	"textures/gothic_wall/streetbricks11.jpg":            {},
	"textures/gothic_wall/supportborder_blue_b.jpg":      {},
	"textures/gothic_wall/supportborder_blue_c.jpg":      {},
	"textures/gothic_wall/window_evil6a.jpg":             {},
	"textures/gothic_wall/window_evil6a_glow.jpg":        {},
	"textures/gothic_wall/xiantourneycolumn_b4.jpg":      {},
	"textures/gothic_wall/xiantourneywall_c1.jpg":        {},
	"textures/gothic_wall/xiantourneywall_r1.jpg":        {},
	"textures/liquids/kc_fogcloud3.jpg":                  {},
	"textures/liquids/lavahell.jpg":                      {},
	"textures/liquids/proto_gruel3.jpg":                  {},
	"textures/liquids/proto_grueldark2.jpg":              {},
	"textures/organics/dirt.jpg":                         {},
	"textures/organics/dirt2.jpg":                        {},
	"textures/sfx/beam.jpg":                              {},
	"textures/sfx/beam_1.jpg":                            {},
	"textures/sfx/bolts.jpg":                             {},
	"textures/sfx/bouncepad01_diamond2ctga.jpg":          {},
	"textures/sfx/bouncepad01b_layer1.jpg":               {},
	"textures/sfx/bouncepad01block18b.jpg":               {},
	"textures/sfx/bouncepad1q1metal7_99.jpg":             {},
	"textures/sfx/compscreen/letters1.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/compscreen/letters1.png"},
	"textures/sfx/compscreen/letters2.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/compscreen/letters2.png"},
	"textures/sfx/compscreen/letters3.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/compscreen/letters3.png"},
	"textures/sfx/compscreen/letters4.tga":               {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/compscreen/letters4.png"},
	"textures/sfx/compscreen/letters5.jpg":               {},
	"textures/sfx/computer_blocks17.jpg":                 {},
	"textures/sfx/computerpurptileb.jpg":                 {},
	"textures/sfx/detail.jpg":                            {},
	"textures/sfx/electricgrade3.jpg":                    {},
	"textures/sfx/electricslime.jpg":                     {},
	"textures/sfx/firegorre.tga":                         {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/firegorre.png"},
	"textures/sfx/firegorre2.jpg":                        {},
	"textures/sfx/fireswirl2.jpg":                        {},
	"textures/sfx/firewalla.tga":                         {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/firewalla.png"},
	"textures/sfx/flame1.jpg":                            {},
	"textures/sfx/flame2.jpg":                            {},
	"textures/sfx/flame3.jpg":                            {},
	"textures/sfx/flame4.jpg":                            {},
	"textures/sfx/flame5.jpg":                            {},
	"textures/sfx/flame6.jpg":                            {},
	"textures/sfx/flame7.jpg":                            {},
	"textures/sfx/flame8.jpg":                            {},
	"textures/sfx/flameball.jpg":                         {},
	"textures/sfx/hologirl.jpg":                          {},
	"textures/sfx/jumppadsmall.jpg":                      {},
	"textures/sfx/kenelectric.jpg":                       {},
	"textures/sfx/launchpad_arrow.tga":                   {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/launchpad_arrow.png"},
	"textures/sfx/launchpad_arrow2.jpg":                  {},
	"textures/sfx/launchpad_diamond.jpg":                 {},
	"textures/sfx/launchpad_dot.jpg":                     {},
	"textures/sfx/logo512.jpg":                           {},
	"textures/sfx/metalbridge06_bounce.jpg":              {},
	"textures/sfx/pentagramfloor_red_glow.jpg":           {},
	"textures/sfx/pentdirt2_@256.jpg":                    {},
	"textures/sfx/pentfloor_diamond2c.jpg":               {},
	"textures/sfx/pentfloorq1metal7_99.jpg":              {},
	"textures/sfx/portal_sfx.jpg":                        {},
	"textures/sfx/portal_sfx1.tga":                       {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/portal_sfx1.png"},
	"textures/sfx/portal_sfx3.tga":                       {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/portal_sfx3.png"},
	"textures/sfx/portal_sfx_ring.jpg":                   {},
	"textures/sfx/portal_sfx_ring_blue1.tga":             {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/sfx/portal_sfx_ring_blue1.png"},
	"textures/sfx/portal_sfx_ring_electric.jpg":          {},
	"textures/sfx/portalfog.jpg":                         {},
	"textures/sfx/proto_zzzt.jpg":                        {},
	"textures/sfx/proto_zzztblu2.jpg":                    {},
	"textures/sfx/snow.jpg":                              {},
	"textures/sfx/x_conduit.jpg":                         {},
	"textures/sfx/x_conduit2.jpg":                        {},
	"textures/sfx/x_conduit3.jpg":                        {},
	"textures/skies/inteldimclouds.jpg":                  {},
	"textures/skies/intelredclouds.jpg":                  {},
	"textures/skies/killsky_1.jpg":                       {},
	"textures/skies/killsky_2.jpg":                       {},
	"textures/skin/chapthroat.jpg":                       {},
	"textures/skin/chapthroat2.jpg":                      {},
	"textures/skin/chapthroatooz.tga":                    {Mode: ModeConvert, TargetFmt: "png", TargetPath: "textures/skin/chapthroatooz.png"},
	"textures/skin/skin6.jpg":                            {},
	"textures/skin/skin7_teeth.jpg":                      {},
	"textures/skin/surface8.jpg":                         {},
	"textures/skin/tongue.jpg":                           {},
}
