IF(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED SYMBOL)
	MESSAGE(FATAL_ERROR "embed_binary.cmake requires INPUT, OUTPUT and SYMBOL")
ENDIF()
FILE(READ "${INPUT}" _binary_hex HEX)
STRING(LENGTH "${_binary_hex}" _hex_length)
MATH(EXPR _byte_count "${_hex_length} / 2")
SET(_body "// Generated from ${INPUT}; do not edit.\n#pragma once\n")
STRING(APPEND _body "static const unsigned char ${SYMBOL}[] = {\n")
SET(_index 0)
WHILE(_index LESS _hex_length)
	STRING(SUBSTRING "${_binary_hex}" ${_index} 2 _byte)
	STRING(APPEND _body "0x${_byte},")
	MATH(EXPR _index "${_index} + 2")
ENDWHILE()
STRING(APPEND _body "\n};\nstatic const unsigned long ${SYMBOL}_size = ${_byte_count}ul;\n")
FILE(WRITE "${OUTPUT}" "${_body}")
