# SPDX-License-Identifier: GPL-3.0-or-later
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_planar_water.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_planar_water.c" CORE)
file(READ "${ROOT}/tests/ral_planar_water_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "malloc(" "free(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "planar water leaked native/unbounded API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_PLANAR_CLIP_KEEP_POSITIVE" "RAL_PLANAR_CLIP_KEEP_NEGATIVE" "maxPixelWork" "dudvStrengthQ16")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "planar water contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "PlaneValid" "Better" "pixels>q->maxPixelWork-v.totalPixelWork" "count>=capacity")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "planar water invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_BACKEND_VULKAN" "RAL_BACKEND_WEBGPU" "targetGraphGeneration++" "clipPolicy==RAL_PLANAR_CLIP_KEEP_POSITIVE")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "planar water hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL planar water policy: PASS")
