# SPDX-License-Identifier: GPL-3.0-or-later
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/render/ral/core/ral_ssr_policy.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_ssr_policy.c" CORE)
file(READ "${ROOT}/tests/ral_ssr_policy_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "malloc(" "free(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "SSR policy leaked native/unbounded API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_SSR_TIER_OFF" "RAL_SSR_REJECT_ROUGHNESS" "RAL_SSR_REJECT_HISTORY" "ralReflectionProbeReceipt_t")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "SSR contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RequestValid" "RAL_SSR_REJECT_BUDGET" "q->maxRayPixels-v.totalRayPixels" "RAL_SSR_RESULT_PROBE_FALLBACK")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "SSR invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_BACKEND_VULKAN" "RAL_BACKEND_WEBGPU" "RAL_SSR_TIER_OFF" "RAL_SSR_REJECT_HISTORY")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "SSR hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL SSR policy: PASS")
