# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_shader_abi.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_shader_abi.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_pipeline.c" VULKAN)
file(READ "${ROOT}/tests/ral_shader_abi_test.c" HOST)
file(READ "${ROOT}/tests/ral_webgpu_shader_abi_test.c" WEBGPU_HOST)

function(require_text HAYSTACK NEEDLE LABEL)
	string(FIND "${${HAYSTACK}}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "missing ${LABEL}: ${NEEDLE}")
	endif()
endfunction()

foreach(token VkDescriptor VkShaderModule MTLFunction WGPUShaderModule)
	string(FIND "${HEADER}" "${token}" POS)
	if(NOT POS EQUAL -1)
		message(FATAL_ERROR "native shader token escaped public ABI: ${token}")
	endif()
endforeach()
require_text(HEADER "RAL_SHADER_ABI_SCHEMA_VERSION 1u" "versioned schema")
require_text(HEADER "RAL_SHADER_ABI_MAX_BIND_GROUPS 8u" "portable bind-group ceiling")
require_text(HEADER "RAL_SHADER_ABI_MAX_BINDING_ARRAY_COUNT 4096u" "bounded resource arrays")
require_text(HEADER "RAL_SHADER_ARTIFACT_WGSL" "WGSL artifact provenance")
require_text(HEADER "webgpuUniformSet" "inline-data uniform lowering")
require_text(CORE "manifest->bindings[i - 1].binding >= manifest->bindings[i].binding" "canonical binding order")
require_text(CORE "manifest->specConstants[i - 1].constantId >= manifest->specConstants[i].constantId" "canonical specialization order")
require_text(CORE "Ral_GraphicsPipelineSemanticDigest" "graphics semantic state key")
require_text(CORE "Ral_ComputePipelineSemanticDigest" "compute semantic state key")
require_text(VULKAN "Ral_ShaderAbiMatchesGraphicsPipeline" "Vulkan graphics opt-in validator")
require_text(VULKAN "Ral_ShaderAbiMatchesComputePipeline" "Vulkan compute opt-in validator")
string(FIND "${VULKAN}" "Ral_ShaderAbiMatchesGraphicsPipeline" GRAPHICS_VALIDATE)
string(FIND "${VULKAN}" "modVert = ralVk_MakeShaderModule" GRAPHICS_CREATE)
if(GRAPHICS_VALIDATE EQUAL -1 OR GRAPHICS_CREATE EQUAL -1 OR NOT GRAPHICS_VALIDATE LESS GRAPHICS_CREATE)
	message(FATAL_ERROR "graphics ABI validation must precede native shader-module creation")
endif()
require_text(HOST "Ral_ShaderAbiMatchesGraphicsPipeline" "exact Vulkan-shaped create-info host")
require_text(HOST "Ral_ShaderAbiMatchesComputePipeline" "exact compute create-info host")
require_text(HOST "f.pipeline.raster.cullMode = RAL_CULL_BACK" "fixed-state key mutation")
require_text(HOST "f.manifest.generation = UINT64_MAX" "generation saturation mutation")
require_text(WEBGPU_HOST "RAL_SHADER_ARTIFACT_WGSL" "WebGPU artifact selection")
require_text(WEBGPU_HOST "binding.minBufferBindingSize = 8" "WebGPU inline-uniform bounds mutation")
string(FIND "${WEBGPU_HOST}" "Vk" WEBGPU_NATIVE)
if(NOT WEBGPU_NATIVE EQUAL -1)
	message(FATAL_ERROR "Vulkan token escaped WebGPU-shaped shader ABI fixture")
endif()

message(STATUS "RAL shader ABI policy: PASS")
