# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_irradiance_runtime.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_irradiance_runtime.c" CORE)
file(READ "${ROOT}/tests/ral_irradiance_runtime_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral irradiance runtime policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "ralIrradianceVolumePlacement_t" "typed placement authority")
req(HEADER "priority" "placement priority")
req(HEADER "blendDistanceQ16" "blend bound")
req(HEADER "Ral_IrradianceVolumeSelect" "priority volume selection")
req(HEADER "ralIrradianceEntitySampleReceipt_t" "entity/debug receipt")
req(HEADER "blendedCoefficientsQ16" "GPU-consumable blended L1 coefficients")
req(HEADER "fallbackIrradianceQ16" "explicit fallback irradiance")
req(HEADER "ralIrradianceDebugReceipt_t" "bounded probe debug receipt")
req(HEADER "Ral_IrradianceDebugBuild" "debug inspection builder")
req(CORE "Ral_IrradianceProbeResolve" "validity-aware eight-probe selection")
req(CORE "RAL_IRRADIANCE_FALLBACK" "explicit fallback")
req(CORE "contributorHash" "debug contributor identity")
req(CORE "coefficientHash" "coefficient receipt identity")
req(CORE "validProbeCount" "debug validity catalog")
req(TEST "receipt.probes.sampleCount == 8u" "eight-probe blend")
req(TEST "receipt.usedFallback" "outside-volume fallback")
req(TEST "receipt.blendedCoefficientsQ16[3][0]" "directional coefficient preservation")
req(TEST "selection.volumeId == 10u" "deterministic priority winner")
req(TEST "debug.selected[0].coefficientsQ16" "selected coefficient inspection")
req(BUILD "ADD_EXECUTABLE(ral_irradiance_runtime_test" "host target")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral irradiance runtime policy: backend type leaked")
endif()
message(STATUS "ral irradiance runtime source policy: PASS")
