# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/renderer/ral/ral_command_lifecycle.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_command_lifecycle.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_command.c" VULKAN)
file(READ "${ROOT}/tests/ral_command_lifecycle_test.c" HOST)
file(READ "${ROOT}/tests/ral_webgpu_command_lifecycle_test.c" WEBGPU_HOST)

function(require_text HAYSTACK NEEDLE LABEL)
	string(FIND "${${HAYSTACK}}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "missing ${LABEL}: ${NEEDLE}")
	endif()
endfunction()

foreach(native_token VkCommandBuffer VkQueue WGPUCommandEncoder WGPUQueue)
	string(FIND "${HEADER}" "${native_token}" POS)
	if(NOT POS EQUAL -1)
		message(FATAL_ERROR "native command type escaped public lifecycle: ${native_token}")
	endif()
endforeach()

require_text(HEADER "const ralBackend_t *backendIdentity;" "opaque backend identity")
require_text(HEADER "const ralCommandBuffer_t *commandIdentity;" "opaque command identity")
require_text(HEADER "uint64_t generation;" "monotonic generation")
require_text(HEADER "ralQueueType_t queue;" "logical queue")
require_text(CORE "submission->generation >= UINT64_MAX - 1u" "submit saturation gate")
require_text(CORE "commands[j] == commands[i]" "duplicate command rejection")
require_text(VULKAN "result = ralVk_QueueSubmit2( b, q, &si2, fence );" "native submission")
require_text(VULKAN "Ral_SubmissionLifecyclePublish( &b->submissionLifecycle[q]" "post-native publication")
string(FIND "${VULKAN}" "result = ralVk_QueueSubmit2( b, q, &si2, fence );" SUBMIT_POS)
string(FIND "${VULKAN}" "Ral_SubmissionLifecyclePublish( &b->submissionLifecycle[q]" PUBLISH_POS)
if(SUBMIT_POS EQUAL -1 OR PUBLISH_POS EQUAL -1 OR NOT SUBMIT_POS LESS PUBLISH_POS)
	message(FATAL_ERROR "submitted receipt must publish only after native queue success")
endif()
require_text(HOST "RunQueue( RAL_QUEUE_GRAPHICS" "graphics lifecycle")
require_text(HOST "RunQueue( RAL_QUEUE_COMPUTE" "compute lifecycle")
require_text(HOST "RunQueue( RAL_QUEUE_TRANSFER" "transfer lifecycle")
require_text(HOST "RunWebGpuCancelShape" "shared WebGPU-shaped cancel lifecycle")
require_text(WEBGPU_HOST "BeginEncoder" "WebGPU createCommandEncoder shape")
require_text(WEBGPU_HOST "FinishEncoder" "WebGPU encoder finish shape")
require_text(WEBGPU_HOST "QueueSubmit" "WebGPU queue submit shape")
string(FIND "${WEBGPU_HOST}" "Vk" WEBGPU_NATIVE)
if(NOT WEBGPU_NATIVE EQUAL -1)
	message(FATAL_ERROR "Vulkan token escaped WebGPU-shaped command fixture")
endif()

message(STATUS "RAL command lifecycle policy: PASS")
