# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors

file(READ "${ROOT}/code/render/ral/core/ral_lighting.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_shade.c" VK_SHADE)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_frag.tmpl" VK_FRAGMENT)
file(READ "${ROOT}/code/render/ral/backends/opengl/ral_opengl_world.c" GL_WORLD)
file(READ "${ROOT}/code/render/ral/backends/metal/ral_metal_present.mm" METAL_WORLD)
file(READ "${ROOT}/code/render/ral/backends/webgpu/ral_webgpu_product.c" WEBGPU_PRODUCT)
file(READ "${ROOT}/code/render/ral/backends/webgpu/ral_webgpu_renderer_module.c" WEBGPU_MODULE)

function(require_text haystack needle label)
	string(FIND "${${haystack}}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "ral lighting policy: missing ${label}: ${needle}")
	endif()
endfunction()

require_text(HEADER "RAL_LIGHT_MOBILITY_STATIC" "typed mobility")
require_text(HEADER "RAL_LIGHT_MOBILITY_STATIONARY" "stationary mobility")
require_text(HEADER "RAL_LIGHT_MOBILITY_DYNAMIC" "dynamic mobility")
require_text(HEADER "RAL_LIGHT_INJECT_ATMOSPHERE" "atmosphere authority")
require_text(HEADER "RAL_LIGHT_CONTRIBUTE_BAKE" "bake authority")
require_text(HEADER "RAL_EMISSIVE_PROXY_MAX_PER_SURFACE 4u" "bounded emissive proxies")
require_text(HEADER "RAL_CASTER_MAX_AFFECTED_LOCAL_LIGHTS 32u" "bounded moving-caster shadow work")
require_text(HEADER "Ral_LightingCacheDirtyMask" "exact cache invalidation")
require_text(HEADER "Ral_CasterUpdatePlanBuild" "moving-caster affected-region planner")
require_text(CORE "dynamicRuntimeHash" "runtime-only dynamic hash")
require_text(CORE "RAL_EMISSIVE_PROXY_REJECT_GLOBAL_BUDGET" "global proxy rejection")
require_text(TEST "Ral_LightingCacheDirtyMask(&base,&next)==0u" "dynamic changes preserve derived caches")
require_text(TEST "plan.droppedLightCount==3u" "deterministic caster budget coverage")
require_text(BUILD "ADD_EXECUTABLE(ral_lighting_test" "host contract target")
require_text(BUILD "code/render/ral/core/ral_lighting.c" "product library ownership")
require_text(VK_SHADE "tess.shader->emissionRadiance" "Vulkan typed surface emission upload")
require_text(VK_FRAGMENT "color0.rgb * emissionRadiance.rgb" "Vulkan HDR emission consumption")
require_text(GL_WORLD "emissiveRadiance" "OpenGL typed surface emission")
require_text(METAL_WORLD "emissionRadianceQ16" "Metal typed surface emission")
require_text(WEBGPU_PRODUCT "worldMaterialData" "WebGPU typed world-material upload")
require_text(WEBGPU_MODULE "color.rgb * emission" "WebGPU WGSL HDR emission consumption")

if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting policy: native backend type leaked into public contract")
endif()

message(STATUS "ral lighting source policy: PASS")
