IF(NOT DEFINED SOURCE_ROOT)
	MESSAGE(FATAL_ERROR "SOURCE_ROOT is required")
ENDIF()

SET(_vk_path "${SOURCE_ROOT}/code/renderervk/vk.c")
SET(_vk_h_path "${SOURCE_ROOT}/code/renderervk/vk.h")
SET(_core_path "${SOURCE_ROOT}/code/renderervk/vk_ral_pool_render.c")
SET(_header_path "${SOURCE_ROOT}/code/renderervk/vk_ral_pool_render.h")
SET(_adopt_path "${SOURCE_ROOT}/code/renderervk/vk_ral_textures.c")
SET(_test_path "${SOURCE_ROOT}/tests/vk_ral_pool_render_test.c")
SET(_smoke_path "${SOURCE_ROOT}/tests/ral-effects-dynamic-bind-smoke.sh")
FOREACH(_path IN ITEMS "${_vk_path}" "${_vk_h_path}" "${_core_path}" "${_header_path}" "${_adopt_path}" "${_test_path}" "${_smoke_path}")
	IF(NOT EXISTS "${_path}")
		MESSAGE(FATAL_ERROR "missing RAL pool-render source: ${_path}")
	ENDIF()
ENDFOREACH()
FILE(READ "${_vk_path}" _vk)
FILE(READ "${_vk_h_path}" _vk_h)
FILE(READ "${_core_path}" _core)
FILE(READ "${_header_path}" _header)
FILE(READ "${_adopt_path}" _adopt)
FILE(READ "${_test_path}" _test)
FILE(READ "${_smoke_path}" _smoke)

FUNCTION(slice_between out body begin_marker end_marker)
	STRING(FIND "${body}" "${begin_marker}" _begin)
	IF(_begin EQUAL -1)
		MESSAGE(FATAL_ERROR "cannot isolate product span: ${begin_marker} -> ${end_marker}")
	ENDIF()
	STRING(LENGTH "${body}" _body_length)
	MATH(EXPR _tail_length "${_body_length} - ${_begin}")
	STRING(SUBSTRING "${body}" ${_begin} ${_tail_length} _tail)
	STRING(FIND "${_tail}" "${end_marker}" _relative_end)
	IF(_relative_end EQUAL -1)
		MESSAGE(FATAL_ERROR "cannot isolate product span: ${begin_marker} -> ${end_marker}")
	ENDIF()
	MATH(EXPR _end "${_begin} + ${_relative_end}")
	MATH(EXPR _length "${_end} - ${_begin}")
	STRING(SUBSTRING "${body}" ${_begin} ${_length} _slice)
	SET(${out} "${_slice}" PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(require_text body needle label)
	STRING(FIND "${body}" "${needle}" _hit)
	IF(_hit EQUAL -1)
		MESSAGE(FATAL_ERROR "${label}: missing '${needle}'")
	ENDIF()
ENDFUNCTION()

FUNCTION(forbid_text body needle label)
	STRING(FIND "${body}" "${needle}" _hit)
	IF(NOT _hit EQUAL -1)
		MESSAGE(FATAL_ERROR "${label}: forbidden '${needle}'")
	ENDIF()
ENDFUNCTION()

FUNCTION(require_call_count body regex expected label)
	STRING(REGEX MATCHALL "${regex}" _hits "${body}")
	LIST(LENGTH _hits _count)
	IF(NOT _count EQUAL expected)
		MESSAGE(FATAL_ERROR "${label}: expected ${expected} matches of '${regex}', found ${_count}")
	ENDIF()
ENDFUNCTION()

slice_between(_decal "${_vk}" "void RB_DrawDecals( void )" "void RB_RunParticleCompute( void )")
slice_between(_compute "${_vk}" "void RB_RunParticleCompute( void )" "void RB_DrawParticles( void )")
slice_between(_particle "${_vk}" "void RB_DrawParticles( void )" "#if FEAT_IQM")
slice_between(_atm_compute "${_vk}" "void RB_RunAtmosphericCompute( void )" "void RB_DrawAtmospheric( void )")
slice_between(_atm_render "${_vk}" "void RB_DrawAtmospheric( void )" "void RB_DrawDecals( void )")

FOREACH(_span_name IN ITEMS _decal _particle _atm_render)
	forbid_text("${${_span_name}}" "qvkCmd" "${_span_name} raw command purge")
	require_call_count("${${_span_name}}" "VK_RalPoolRenderExecute[(]" 1 "${_span_name} portable execute")
	require_text("${${_span_name}}" "plan.commandBuffer = vk.cmd->ral_cmd;" "${_span_name} command authority")
	require_text("${${_span_name}}" "plan.viewport.maxDepth = 1.0f;" "${_span_name} viewport depth")
	require_text("${${_span_name}}" "plan.vertexCount = 6u;" "${_span_name} pool quad")
ENDFOREACH()
require_text("${_decal}" "plan.pipelineCount = 3u;" "decal blend cohorts")
require_text("${_decal}" "plan.instanceCount = DECALS_PER_POOL;" "decal instance bound")
require_text("${_decal}" "vk.decal.ral_render_descriptor[frameIdx]" "decal retained group")
require_text("${_decal}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_DECAL, \"decal\", 3u, 0u );" "decal native receipt")
require_text("${_particle}" "plan.pipelineCount = 2u;" "particle blend cohorts")
require_text("${_particle}" "plan.instanceCount = PARTICLES_PER_POOL;" "particle instance bound")
require_text("${_particle}" "vk.particle.ral_render_descriptor[renderIdx]" "particle retained group")
require_text("${_particle}" "backEnd.pc.c_particleDraws += 2;" "particle counter parity")
require_text("${_particle}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_PARTICLE, \"particle\", 2u, 0u );" "particle native receipt")
require_text("${_atm_render}" "plan.pipelineCount = 1u;" "atmospheric single blend cohort")
require_text("${_atm_render}" "plan.instanceCount = ATM_PARTICLES_PER_POOL;" "atmospheric instance bound")
require_text("${_atm_render}" "vk.atm.ral_render_descriptor[renderIdx]" "atmospheric retained group")
require_text("${_atm_render}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_ATMOSPHERIC," "atmospheric native receipt")

forbid_text("${_compute}" "qvkCmd" "particle compute raw command purge")
require_call_count("${_compute}" "VK_RalComputeExecute[(]" 1 "particle portable compute execute")
require_text("${_compute}" "plan.pipeline = vk.particle.ral_compute_pipeline;" "particle compute pipeline authority")
require_text("${_compute}" "plan.bindGroup = vk.particle.ral_compute_descriptor[pingRead];" "particle compute group authority")
require_text("${_compute}" "plan.groupCountX = ( PARTICLES_PER_POOL + 63u ) / 64u;" "particle compute dispatch bound")
require_text("${_compute}" "vk_particle_compute_smoke_receipt();" "particle compute native receipt")

forbid_text("${_atm_compute}" "qvkCmd" "atmospheric compute raw command purge")
require_call_count("${_atm_compute}" "VK_RalComputeExecute[(]" 1 "atmospheric portable compute execute")
require_text("${_atm_compute}" "plan.pipeline = vk.atm.ral_compute_pipeline;" "atmospheric compute pipeline authority")
require_text("${_atm_compute}" "plan.bindGroup = vk.atm.ral_compute_descriptor[pingRead];" "atmospheric compute group authority")
require_text("${_atm_compute}" "plan.groupCountX = ( ATM_PARTICLES_PER_POOL + 63u ) / 64u;" "atmospheric compute dispatch bound")
require_text("${_atm_compute}" "vk_atmospheric_compute_smoke_receipt();" "atmospheric compute native receipt")

# Core validates the complete plan before emitting viewport/scissor or draws.
require_text("${_header}" "VK_RAL_POOL_RENDER_MAX_PIPELINES 3u" "portable pipeline cap")
require_text("${_header}" "qboolean VK_RalPoolRenderExecute" "portable executor API")
require_text("${_header}" "VK_RAL_COMPUTE_MAX_GROUPS_PER_DIMENSION 65535u" "portable compute dimension cap")
require_text("${_header}" "qboolean VK_RalComputeExecute" "portable compute API")
require_text("${_core}" "for ( i = 0; i < plan->pipelineCount; i++ )" "pipeline preflight")
require_call_count("${_core}" "Ral_CmdSetViewport[(]" 1 "portable viewport")
require_call_count("${_core}" "Ral_CmdSetScissor[(]" 1 "portable scissor")
require_call_count("${_core}" "Ral_CmdBindPipeline[(]" 2 "portable render and compute pipeline binds")
require_call_count("${_core}" "Ral_CmdBindBindGroup[(]" 2 "portable render and compute group binds")
require_call_count("${_core}" "Ral_CmdDraw[(]" 1 "portable draw loop")
require_call_count("${_core}" "Ral_CmdDispatch[(]" 1 "portable compute dispatch")
require_call_count("${_core}" "Ral_CmdPipelineBarrier[(]" 1 "portable compute barrier")
require_text("${_core}" "RAL_BARRIER_COMPUTE_TO_GRAPHICS" "semantic compute barrier")
forbid_text("${_core}" "Vk" "pool executor backend neutrality")
forbid_text("${_core}" "qvk" "pool executor backend neutrality")

# Named wrappers, not anonymous adoption, carry command-time authority and are
# released before their borrowed layouts/descriptors disappear.
require_call_count("${_vk_h}" "ral_render_descriptor" 3 "retained render groups")
require_call_count("${_vk_h}" "ral_compute_descriptor" 2 "retained compute groups")
require_call_count("${_vk_h}" "ral_compute_pipeline" 4 "retained compute pipelines/layouts")
require_text("${_adopt}" "RETAIN_ADOPT( vk.particle.ral_compute_descriptor[i]" "particle compute retained adoption")
require_text("${_adopt}" "RETAIN_ADOPT( vk.particle.ral_render_descriptor[i]" "particle retained adoption")
require_text("${_adopt}" "RETAIN_ADOPT( vk.decal.ral_render_descriptor[i]" "decal retained adoption")
require_text("${_vk}" "vk.decal.ral_bgl_render = Ral_AdoptBindGroupLayout(" "decal layout adoption")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.particle.ral_render_descriptor[i] );" "particle retained teardown")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.particle.ral_compute_descriptor[i] );" "particle compute retained teardown")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.decal.ral_render_descriptor[i] );" "decal retained teardown")
require_text("${_vk}" "vk.atm.ral_bgl_compute = Ral_AdoptBindGroupLayout(" "atmospheric compute layout adoption")
require_text("${_vk}" "vk.atm.ral_bgl_render = Ral_AdoptBindGroupLayout(" "atmospheric render layout adoption")
require_text("${_vk}" "vk.atm.ral_compute_descriptor[i] = Ral_AdoptBindGroup(" "atmospheric compute group adoption")
require_text("${_vk}" "vk.atm.ral_render_descriptor[i] = Ral_AdoptBindGroup(" "atmospheric render group adoption")
require_text("${_vk}" "vk_init_atmospheric_compute_ral_pipeline();" "atmospheric compute pipeline construction")
require_text("${_vk}" "vk_ral_create_pipeline_from_gpinfo( &gpInfo, vk.atm.ral_render_pipeline_layout," "atmospheric render pipeline construction")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.atm.ral_compute_descriptor[i] );" "atmospheric compute retained teardown")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.atm.ral_render_descriptor[i] );" "atmospheric render retained teardown")
require_text("${_adopt}" "KILL_PL( vk.atm.ral_compute_pipeline_layout );" "atmospheric compute layout child teardown")
require_text("${_adopt}" "KILL_PL( vk.atm.ral_render_pipeline_layout );" "atmospheric render layout child teardown")
require_text("${_adopt}" "KILL_BGL( vk.atm.ral_bgl_compute );" "atmospheric compute BGL teardown")
require_text("${_adopt}" "KILL_BGL( vk.atm.ral_bgl_render );" "atmospheric render BGL teardown")
forbid_text("${_vk}" "atmospheric_integrate_cs" "atmospheric raw compute shader module retirement")

# Host proves 2- and 3-pipeline command traces and fail-before-emission for the
# complete boundary mutation family.
FOREACH(_needle IN ITEMS
	"CheckSuccess( 1u )" "CheckSuccess( 2u )" "CheckSuccess( 3u )"
	"capture.eventCount == 2u + pipelineCount * 3u"
	"plan.pipelineCount = 4u" "plan.pipelines[1] = NULL"
	"plan.viewport.minDepth = -0.1f" "plan.viewport.maxDepth = 1.1f"
	"plan.viewport.minDepth = 0.8f" "plan.scissor.width = 0u"
	"plan.vertexCount = 0u" "plan.instanceCount = 0u"
	"capture.eventCount == 0u")
	require_text("${_test}" "${_needle}" "pool-render host mutation")
ENDFOREACH()
FOREACH(_needle IN ITEMS
	"CheckComputeSuccess()" "EV_PIPELINE, EV_GROUP, EV_DISPATCH, EV_BARRIER"
	"capture.barrierScope == RAL_BARRIER_COMPUTE_TO_GRAPHICS"
	"compute.commandBuffer = NULL" "compute.pipeline = NULL" "compute.bindGroup = NULL"
	"compute.groupCountX = 0u" "compute.groupCountY = 0u" "compute.groupCountZ = 0u"
	"VK_RAL_COMPUTE_MAX_GROUPS_PER_DIMENSION + 1u")
	require_text("${_test}" "${_needle}" "pool-compute host mutation")
ENDFOREACH()
require_text("${_smoke}" "'set r_particles 1' 'set r_gpuDecals 1'" "native pool-render gates")
require_text("${_smoke}" "\"particle\",\"decal\"" "native pool-render receipt families")
require_text("${_smoke}" "else 0" "native nondynamic-offset receipt")
require_text("${_smoke}" "ral-particle-compute schema=1" "native particle compute receipt")
require_text("${_smoke}" "'set r_atmosphericGPU 1'" "native atmospheric gate")
require_text("${_smoke}" "ral-atmospheric-compute schema=1" "native atmospheric compute receipt")
require_text("${_smoke}" "\"atmospheric\"" "native atmospheric render receipt")
require_text("${_smoke}" "compute-to-graphics" "native particle compute barrier")

MESSAGE(STATUS "particle, decal, and atmospheric cohorts use backend-neutral RAL pool commands")
