# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_lighting_runtime.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_runtime.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_runtime_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting runtime policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "ralLightingRuntimePlanePlan_t" "typed upload plane")
req(CORE "Ral_LightingArtifactRead" "exact artifact validation")
req(CORE "RAL_FORMAT_E5B9G9R9_UFLOAT" "primary radiance format")
req(CORE "RAL_FORMAT_R16G16_SNORM" "fallback direction format")
req(TEST "RAL_BACKEND_COUNT" "four-backend semantic plan")
req(BUILD "ADD_EXECUTABLE(ral_lighting_runtime_test" "host target")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting runtime policy: backend type leaked")
endif()
message(STATUS "ral lighting runtime source policy: PASS")
