# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_reflection_probe.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_reflection_probe.c" CORE)
file(READ "${ROOT}/tests/ral_reflection_probe_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "malloc(" "free(" "sqrt(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "reflection probe leaked native/unbounded API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_REFLECTION_PROBE_MAX_SELECTED" "globalWeightQ16" "parallaxDirection" "catalogGeneration")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "reflection probe contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "Coverage" "Better" "Parallax" "capacity<count" "sum==RAL_REFLECTION_PROBE_Q16_ONE")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "reflection probe invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_BACKEND_VULKAN" "RAL_BACKEND_WEBGPU" "q.catalogGeneration++" "selectedCount==0u")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "reflection probe hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL reflection probe policy: PASS")
