IF(NOT DEFINED SOURCE_ROOT)
	MESSAGE(FATAL_ERROR "SOURCE_ROOT is required")
ENDIF()

SET(_vk_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/vk.c")
SET(_vk_h_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/vk.h")
SET(_core_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/vk_ral_pool_render.c")
SET(_header_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/vk_ral_pool_render.h")
SET(_adopt_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/vk_ral_textures.c")
SET(_test_path "${SOURCE_ROOT}/tests/vk_ral_pool_render_test.c")
SET(_smoke_path "${SOURCE_ROOT}/tests/ral-effects-dynamic-bind-smoke.sh")
SET(_particle_compute_path "${SOURCE_ROOT}/code/render/ral/backends/vulkan/renderer/shaders/particle_integrate.comp")
FOREACH(_path IN ITEMS "${_vk_path}" "${_vk_h_path}" "${_core_path}" "${_header_path}" "${_adopt_path}" "${_test_path}" "${_smoke_path}" "${_particle_compute_path}")
	IF(NOT EXISTS "${_path}")
		MESSAGE(FATAL_ERROR "missing RAL pool-render source: ${_path}")
	ENDIF()
ENDFOREACH()
FILE(READ "${_vk_path}" _vk)
FILE(READ "${_vk_h_path}" _vk_h)
FILE(READ "${_core_path}" _core)
FILE(READ "${_header_path}" _header)
FILE(READ "${_adopt_path}" _adopt)
FILE(READ "${_test_path}" _test)
FILE(READ "${_smoke_path}" _smoke)
FILE(READ "${_particle_compute_path}" _particle_compute_shader)

FUNCTION(slice_between out body begin_marker end_marker)
	STRING(FIND "${body}" "${begin_marker}" _begin)
	IF(_begin EQUAL -1)
		MESSAGE(FATAL_ERROR "cannot isolate product span: ${begin_marker} -> ${end_marker}")
	ENDIF()
	STRING(LENGTH "${body}" _body_length)
	MATH(EXPR _tail_length "${_body_length} - ${_begin}")
	STRING(SUBSTRING "${body}" ${_begin} ${_tail_length} _tail)
	STRING(FIND "${_tail}" "${end_marker}" _relative_end)
	IF(_relative_end EQUAL -1)
		MESSAGE(FATAL_ERROR "cannot isolate product span: ${begin_marker} -> ${end_marker}")
	ENDIF()
	MATH(EXPR _end "${_begin} + ${_relative_end}")
	MATH(EXPR _length "${_end} - ${_begin}")
	STRING(SUBSTRING "${body}" ${_begin} ${_length} _slice)
	SET(${out} "${_slice}" PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(require_text body needle label)
	STRING(FIND "${body}" "${needle}" _hit)
	IF(_hit EQUAL -1)
		MESSAGE(FATAL_ERROR "${label}: missing '${needle}'")
	ENDIF()
ENDFUNCTION()

FUNCTION(forbid_text body needle label)
	STRING(FIND "${body}" "${needle}" _hit)
	IF(NOT _hit EQUAL -1)
		MESSAGE(FATAL_ERROR "${label}: forbidden '${needle}'")
	ENDIF()
ENDFUNCTION()

FUNCTION(require_call_count body regex expected label)
	STRING(REGEX MATCHALL "${regex}" _hits "${body}")
	LIST(LENGTH _hits _count)
	IF(NOT _count EQUAL expected)
		MESSAGE(FATAL_ERROR "${label}: expected ${expected} matches of '${regex}', found ${_count}")
	ENDIF()
ENDFUNCTION()

FUNCTION(require_order body first second label)
	STRING(FIND "${body}" "${first}" _first)
	STRING(FIND "${body}" "${second}" _second)
	IF(_first EQUAL -1 OR _second EQUAL -1 OR NOT _first LESS _second)
		MESSAGE(FATAL_ERROR "${label}: expected '${first}' before '${second}'")
	ENDIF()
ENDFUNCTION()

slice_between(_decal "${_vk}" "void RB_DrawDecals( void )" "void RB_RunParticleCompute( void )")
slice_between(_compute "${_vk}" "void RB_RunParticleCompute( void )" "void RB_DrawParticles( void )")
slice_between(_particle "${_vk}" "void RB_DrawParticles( void )" "#if FEAT_IQM")
slice_between(_particle_render_refresh "${_vk}" "qboolean vk_ral_refresh_particle_render_bindgroups( uint32_t slotMask )" "void vk_ral_release_decal_render_bindgroups")
slice_between(_decal_render_refresh "${_vk}" "qboolean vk_ral_refresh_decal_render_bindgroups( uint32_t slotMask )" "qboolean vk_particle_shadow_get_class")
slice_between(_particle_texture_init "${_vk}" "void vk_init_particle_textures( void )" "void vk_particle_set_class_image")
slice_between(_particle_class_image "${_vk}" "void vk_particle_set_class_image( int handle, image_t *image )" "void vk_particle_set_frame_image")
slice_between(_particle_frame_image "${_vk}" "void vk_particle_set_frame_image( int frameSlot, image_t *image )" "void vk_decal_set_texture_image")
slice_between(_decal_class_image "${_vk}" "void vk_decal_set_texture_image( int slot, image_t *image )" "qboolean vk_decal_flush_pending_images")
slice_between(_decal_flush "${_vk}" "qboolean vk_decal_flush_pending_images( void )" "// ── shared primitive shader image registry")
slice_between(_decal_init "${_vk}" "void vk_init_decal( void )" "void vk_init_decal_textures( void )")
slice_between(_decal_texture_init "${_vk}" "void vk_init_decal_textures( void )" "void vk_shutdown_decal( void )")
slice_between(_decal_reset "${_vk}" "// Decal render groups borrow image views" "// Atmospheric weather descriptor sets")
slice_between(_hdr_rebuild "${_vk}" "static void vk_rebuild_fbo_for_hdr_change( void )" "static void vk_rebuild_for_fbo_change( void )")
slice_between(_fbo_rebuild "${_vk}" "static void vk_rebuild_for_fbo_change( void )" "static qboolean vk_show_ao_source_ready( void )")
slice_between(_atm_compute "${_vk}" "void RB_RunAtmosphericCompute( void )" "void RB_DrawAtmospheric( void )")
slice_between(_atm_render "${_vk}" "void RB_DrawAtmospheric( void )" "void RB_DrawDecals( void )")
slice_between(_atm_shutdown "${_vk}" "void vk_shutdown_atmospheric( void )" "// Store the cgame weather descriptor")

FOREACH(_span_name IN ITEMS _decal _particle _atm_render)
	forbid_text("${${_span_name}}" "qvkCmd" "${_span_name} raw command purge")
	require_call_count("${${_span_name}}" "VK_RalPoolRenderExecute[(]" 1 "${_span_name} portable execute")
	require_text("${${_span_name}}" "plan.commandBuffer = vk.cmd->ral_cmd;" "${_span_name} command authority")
	require_text("${${_span_name}}" "vk_render_domain_viewport_scissor( &plan.viewport, &plan.scissor );" "${_span_name} render-domain viewport")
	require_text("${${_span_name}}" "plan.vertexCount = 6u;" "${_span_name} pool quad")
ENDFOREACH()
require_text("${_decal}" "plan.pipelineCount = 3u;" "decal blend cohorts")
require_text("${_decal}" "plan.instanceCount = DECALS_PER_POOL;" "decal instance bound")
require_text("${_decal}" "vk.decal.ral_render_descriptor[frameIdx]" "decal retained group")
require_text("${_decal}" "if ( !vk_decal_flush_pending_images() )" "decal current-slot publication gate")
require_text("${_decal}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_DECAL, \"decal\", 3u, 0u );" "decal native receipt")
require_text("${_particle}" "plan.pipelineCount = 2u;" "particle blend cohorts")
require_text("${_particle}" "plan.instanceCount = PARTICLES_PER_POOL;" "particle instance bound")
require_text("${_particle}" "vk.particle.ral_render_descriptor[frameIdx][renderPool]" "particle frame/pool retained group")
require_text("${_particle}" "renderGroupTextureGeneration[frameIdx][renderPool]" "particle frame/pool generation join")
require_text("${_particle}" "vk_ral_refresh_particle_render_bindgroups( 1u << frameIdx )" "particle current-frame immutable replacement")
require_text("${_particle}" "backEnd.pc.c_particleDraws += 2;" "particle counter parity")
require_text("${_particle}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_PARTICLE, \"particle\", 2u, 0u );" "particle native receipt")
require_text("${_atm_render}" "plan.pipelineCount = 1u;" "atmospheric single blend cohort")
require_text("${_atm_render}" "plan.instanceCount = activePoolSize;" "atmospheric coverage bound")
require_text("${_atm_render}" "vk.atm.ral_render_descriptor[renderIdx]" "atmospheric retained group")
require_text("${_atm_render}" "vk_effects_smoke_receipt( VK_EFFECT_SMOKE_ATMOSPHERIC," "atmospheric native receipt")

forbid_text("${_compute}" "qvkCmd" "particle compute raw command purge")
require_call_count("${_compute}" "VK_RalComputeExecute[(]" 3 "particle spawn + integrate + child-finalize portable compute executes")
require_text("${_compute}" "plan.pipeline = vk.particle.ral_spawn_pipeline;" "particle GPU spawn authority")
require_text("${_compute}" "plan.groupCountX = vk.particle.spawnRequestCount;" "bounded emitter dispatch")
require_text("${_compute}" "RAL_BARRIER_COMPUTE_TO_COMPUTE" "spawn-to-integrate visibility")
require_text("${_compute}" "plan.pipeline = vk.particle.ral_compute_pipeline;" "particle compute pipeline authority")
require_text("${_compute}" "vk.particle.ral_compute_descriptor[frameIdx][pingRead]" "particle frame/pool compute group authority")
require_text("${_compute}" "plan.groupCountX = ( PARTICLES_PER_POOL + 63u ) / 64u;" "particle compute dispatch bound")
require_text("${_compute}" "PARTICLE_CHILD_PARTICLE_MAX" "particle child frame budget")
require_text("${_compute}" "plan.pipeline = vk.particle.ral_child_finalize_pipeline;" "particle child-event finalizer")
require_text("${_compute}" "Ral_CmdDispatchIndirect( vk.cmd->ral_cmd, childEventBuffer, 0u );" "particle bounded indirect child dispatch")
require_text("${_compute}" "RAL_BARRIER_INDIRECT" "particle child indirect visibility")
require_text("${_compute}" "vk_particle_compute_smoke_receipt();" "particle compute native receipt")
require_text("${_particle_compute_shader}" "layout(std430, set = 0, binding = 5) readonly buffer AtmosphereProfiles" "particle immutable atmosphere profile binding")
require_text("${_particle_compute_shader}" "layout(std430, set = 0, binding = 6) buffer ChildEvents" "particle GPU child-event binding")
require_text("${_particle_compute_shader}" "uint stageParticles[512]" "particle child stage budget counters")
require_text("${_particle_compute_shader}" "uint profileParticles[64]" "particle child profile budget counters")
require_text("${_particle_compute_shader}" "layout(set = 0, binding = 7) uniform sampler2D collisionHeightgrid;" "particle shared heightgrid collision binding")
require_text("${_particle_compute_shader}" "atomicAdd( eventCount, 1u )" "particle GPU-local child event append")
require_text("${_particle_compute_shader}" "if ( PARTICLE_PASS == 2u )" "particle child expansion specialization")
require_text("${_particle_compute_shader}" "if ( PARTICLE_PASS == 3u )" "particle indirect finalizer specialization")

forbid_text("${_atm_compute}" "qvkCmd" "atmospheric compute raw command purge")
require_call_count("${_atm_compute}" "VK_RalComputeExecute[(]" 1 "atmospheric portable compute execute")
require_text("${_atm_compute}" "plan.pipeline = vk.atm.ral_compute_pipeline;" "atmospheric compute pipeline authority")
require_text("${_atm_compute}" "plan.bindGroup = vk.atm.ral_compute_descriptor[pingRead];" "atmospheric compute group authority")
require_text("${_atm_compute}" "plan.groupCountX = ( activePoolSize + 63u ) / 64u;" "atmospheric coverage dispatch bound")
require_text("${_atm_compute}" "vk_atmospheric_compute_smoke_receipt();" "atmospheric compute native receipt")

# Core validates the complete plan before emitting viewport/scissor or draws.
require_text("${_header}" "VK_RAL_POOL_RENDER_MAX_PIPELINES 3u" "portable pipeline cap")
require_text("${_header}" "qboolean VK_RalPoolRenderExecute" "portable executor API")
require_text("${_header}" "VK_RAL_COMPUTE_MAX_GROUPS_PER_DIMENSION 65535u" "portable compute dimension cap")
require_text("${_header}" "qboolean VK_RalComputeExecute" "portable compute API")
require_text("${_core}" "for ( i = 0; i < plan->pipelineCount; i++ )" "pipeline preflight")
require_call_count("${_core}" "Ral_CmdSetViewport[(]" 1 "portable viewport")
require_call_count("${_core}" "Ral_CmdSetScissor[(]" 1 "portable scissor")
require_call_count("${_core}" "Ral_CmdBindPipeline[(]" 2 "portable render and compute pipeline binds")
require_call_count("${_core}" "Ral_CmdBindBindGroup[(]" 2 "portable render and compute group binds")
require_call_count("${_core}" "Ral_CmdDraw[(]" 1 "portable draw loop")
require_call_count("${_core}" "Ral_CmdDispatch[(]" 1 "portable compute dispatch")
require_call_count("${_core}" "Ral_CmdPipelineBarrier[(]" 1 "portable compute barrier")
require_text("${_core}" "RAL_BARRIER_COMPUTE_TO_GRAPHICS" "semantic compute barrier")
forbid_text("${_core}" "Vk" "pool executor backend neutrality")
forbid_text("${_core}" "qvk" "pool executor backend neutrality")

# Named wrappers, not anonymous adoption, carry command-time authority and are
# released before their borrowed layouts/descriptors disappear.
require_call_count("${_vk_h}" "ral_render_descriptor" 3 "retained render groups")
require_call_count("${_vk_h}" "ral_compute_descriptor" 2 "retained compute groups")
require_call_count("${_vk_h}" "ral_compute_pipeline" 4 "retained compute pipelines/layouts")
require_text("${_vk}" "vk_ral_refresh_particle_compute_bindgroups()" "particle direct compute group refresh")
require_text("${_particle_render_refresh}" ".type=RAL_BIND_TEXTURE_ARRAY" "particle direct texture array")
require_text("${_particle_render_refresh}" ".textureArrayCount=PARTICLE_SAMPLER_COUNT, .sampler=vk.particle.ral_sampler" "particle combined array sampler")
require_text("${_particle_render_refresh}" ".textureView=vk.sceneDepth.ral_view, .sampler=vk.sceneDepth.ral_sampler" "particle depth cohort")
require_text("${_particle_render_refresh}" "Ral_GetBindGroupLayoutHandle( vk.particle.ral_bgl_render )" "particle render layout identity")
require_text("${_particle_render_refresh}" "Ral_GetSamplerHandle( vk.particle.ral_sampler )" "particle sampler identity")
require_text("${_particle_render_refresh}" "Ral_GetTextureViewHandle( vk.sceneDepth.ral_view )" "particle depth-view identity")
require_text("${_particle_render_refresh}" "Ral_GetBufferSize( poolReceipt.buffers[i] ) != poolBytes" "particle buffer range identity")
require_text("${_particle_render_refresh}" "candidates[i][pool] = Ral_CreateBindGroup( backend, &createInfo );" "particle direct frame/pool render group")
require_text("${_particle_render_refresh}" "vk.particle.ral_render_descriptor[i][pool];" "particle candidate-first publication")
require_text("${_particle_render_refresh}" "vk.particle.renderGroupTextureGeneration[i][pool] =" "particle frame/pool generation publication")
forbid_text("${_particle_render_refresh}" "qvk" "particle render refresh raw descriptor purge")
require_call_count("${_particle_texture_init}" "vk_ral_refresh_particle_render_bindgroups[(]" 1 "particle eager RAL render cohort")
forbid_text("${_particle_texture_init}" "qvk" "particle texture init raw descriptor purge")
FOREACH(_registry_span IN ITEMS _particle_class_image _particle_frame_image)
	require_text("${${_registry_span}}" "++vk.particle.textureGeneration;" "${_registry_span} generation advance")
	forbid_text("${${_registry_span}}" "qvk" "${_registry_span} raw descriptor purge")
ENDFOREACH()
forbid_text("${_adopt}" "RETAIN_ADOPT( vk.particle.ral_render_descriptor[i]" "particle render compatibility adoption retirement")
require_text("${_decal_render_refresh}" ".type=RAL_BIND_TEXTURE_ARRAY" "decal direct texture array")
require_text("${_decal_render_refresh}" ".textureArrayCount=MAX_DECAL_TEXTURES, .sampler=vk.decal.ral_sampler" "decal combined array sampler")
require_text("${_decal_render_refresh}" ".textureView=vk.sceneDepth.ral_view, .sampler=vk.sceneDepth.ral_sampler" "decal depth cohort")
require_text("${_decal_render_refresh}" "Ral_GetBindGroupLayoutHandle( vk.decal.ral_bgl_render )" "decal render layout identity")
require_text("${_decal_render_refresh}" "Ral_GetSamplerHandle( vk.decal.ral_sampler )" "decal sampler identity")
require_text("${_decal_render_refresh}" "Ral_GetTextureViewHandle( vk.sceneDepth.ral_view )" "decal depth-view identity")
require_text("${_decal_render_refresh}" "Ral_GetBufferSize( poolReceipt.buffers[0] ) != poolBytes" "decal buffer range identity")
require_text("${_decal_render_refresh}" "candidates[i] = Ral_CreateBindGroup( backend, &createInfo );" "decal direct render group")
require_text("${_decal_render_refresh}" "retired = vk.decal.ral_render_descriptor[i];" "decal candidate-first publication")
require_text("${_decal_render_refresh}" "vk.decal.renderGroupTextureGeneration[i] = vk.decal.textureGeneration;" "decal generation publication")
forbid_text("${_decal_render_refresh}" "qvk" "decal render refresh raw descriptor purge")
require_text("${_decal_init}" "ralBindEntry_t entries[5];" "decal exact five-binding layout")
require_text("${_decal_init}" "MAX_DECAL_TEXTURES, RAL_STAGE_FRAGMENT, RAL_BIND_TEXTURE_VIEW_2D" "decal bounded texture-array layout")
require_text("${_decal_init}" "entries[4] = (ralBindEntry_t){ 4u, RAL_BIND_STORAGE_BUFFER" "decal bounded surface-climate layout")
require_text("${_decal_init}" "vk.decal.ral_sampler = vk_ral_sampler_for_definition( &sd );" "decal shared RAL sampler")
forbid_text("${_decal_init}" "qvkAllocateDescriptorSets" "decal init raw allocation purge")
forbid_text("${_decal_init}" "qvkUpdateDescriptorSets" "decal init raw update purge")
require_call_count("${_decal_texture_init}" "vk_ral_refresh_decal_render_bindgroups[(]" 1 "decal eager RAL render cohort")
forbid_text("${_decal_texture_init}" "qvk" "decal texture init raw descriptor purge")
require_text("${_decal_class_image}" "++vk.decal.textureGeneration;" "decal registry generation advance")
forbid_text("${_decal_class_image}" "qvk" "decal registry raw descriptor purge")
require_text("${_decal_flush}" "vk.decal.renderGroupTextureGeneration[idx]" "decal current-slot generation join")
require_text("${_decal_flush}" "vk_ral_refresh_decal_render_bindgroups( 1u << idx )" "decal current-slot immutable replacement")
forbid_text("${_decal_flush}" "qvk" "decal current-slot raw descriptor purge")
require_text("${_decal_reset}" "vk_ral_release_decal_render_bindgroups();" "decal arena-reset child retirement")
forbid_text("${_decal_reset}" "qvkAllocateDescriptorSets" "decal reset raw allocation purge")
forbid_text("${_decal_reset}" "qvkUpdateDescriptorSets" "decal reset raw update purge")
FOREACH(_rebuild IN ITEMS _hdr_rebuild _fbo_rebuild)
	require_order("${${_rebuild}}" "vk_ral_release_decal_render_bindgroups();" "vk_destroy_attachments();" "${_rebuild} decal child-before-parent")
	require_order("${${_rebuild}}" "vk_ral_refresh_internal_texture_dependents();" "vk_init_decal_textures();" "${_rebuild} decal parent-before-child recreation")
ENDFOREACH()
forbid_text("${_adopt}" "RETAIN_ADOPT( vk.decal.ral_render_descriptor[i]" "decal compatibility adoption retirement")
require_text("${_vk}" "\"wired-decal-render-set-layout\", &vk.decal.ral_bgl_render," "decal exact direct layout")
require_text("${_adopt}" "vk_ral_release_particle_render_bindgroups();" "particle direct render teardown")
require_text("${_adopt}" "vk_ral_release_decal_render_bindgroups();" "decal direct render teardown")
require_text("${_vk}" "vk_ral_release_particle_compute_bindgroups();" "particle compute retained teardown")
forbid_text("${_adopt}" "DESTROY_RETAINED_BG( vk.decal.ral_render_descriptor[i] );" "decal compatibility teardown retirement")
require_text("${_vk}" "\"wired-atmospheric-compute-set-layout\"," "atmospheric compute direct layout")
require_text("${_vk}" "\"wired-atmospheric-render-set-layout\"," "atmospheric render direct layout")
require_text("${_vk}" "computeCandidates[i] = Ral_CreateBindGroup( backend, &createInfo );" "atmospheric direct compute group")
require_text("${_vk}" "renderCandidates[i] = Ral_CreateBindGroup( backend, &createInfo );" "atmospheric direct render group")
forbid_text("${_vk}" "vk.atm.ral_compute_descriptor[i] = Ral_AdoptBindGroup(" "atmospheric compute group adoption retirement")
forbid_text("${_vk}" "vk.atm.ral_render_descriptor[i] = Ral_AdoptBindGroup(" "atmospheric render group adoption retirement")
require_text("${_vk}" "vk_init_atmospheric_compute_ral_pipeline();" "atmospheric compute pipeline construction")
require_text("${_vk}" "vk_ral_create_pipeline_from_gpinfo( &gpInfo, vk.atm.ral_render_pipeline_layout," "atmospheric render pipeline construction")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.atm.ral_compute_descriptor[i] );" "atmospheric compute retained teardown")
require_text("${_adopt}" "DESTROY_RETAINED_BG( vk.atm.ral_render_descriptor[i] );" "atmospheric render retained teardown")
require_text("${_atm_shutdown}" "Ral_DestroyPipelineLayout( vk.atm.ral_compute_pipeline_layout );" "atmospheric compute layout child teardown")
require_text("${_atm_shutdown}" "Ral_DestroyPipelineLayout( vk.atm.ral_render_pipeline_layout );" "atmospheric render layout child teardown")
require_text("${_atm_shutdown}" "Ral_DestroyBindGroupLayout( vk.atm.ral_bgl_compute );" "atmospheric compute BGL teardown")
require_text("${_atm_shutdown}" "Ral_DestroyBindGroupLayout( vk.atm.ral_bgl_render );" "atmospheric render BGL teardown")
forbid_text("${_vk}" "atmospheric_integrate_cs" "atmospheric raw compute shader module retirement")

# Host proves 2- and 3-pipeline command traces and fail-before-emission for the
# complete boundary mutation family.
FOREACH(_needle IN ITEMS
	"CheckSuccess( 1u )" "CheckSuccess( 2u )" "CheckSuccess( 3u )"
	"capture.eventCount == 2u + pipelineCount * 3u"
	"plan.pipelineCount = 4u" "plan.pipelines[1] = NULL"
	"plan.viewport.minDepth = -0.1f" "plan.viewport.maxDepth = 1.1f"
	"plan.viewport.minDepth = 0.8f" "plan.scissor.width = 0u"
	"plan.vertexCount = 0u" "plan.instanceCount = 0u"
	"capture.eventCount == 0u")
	require_text("${_test}" "${_needle}" "pool-render host mutation")
ENDFOREACH()
FOREACH(_needle IN ITEMS
	"CheckComputeSuccess()" "EV_PIPELINE, EV_GROUP, EV_DISPATCH, EV_BARRIER"
	"capture.barrierScope == RAL_BARRIER_COMPUTE_TO_GRAPHICS"
	"compute.commandBuffer = NULL" "compute.pipeline = NULL" "compute.bindGroup = NULL"
	"compute.groupCountX = 0u" "compute.groupCountY = 0u" "compute.groupCountZ = 0u"
	"VK_RAL_COMPUTE_MAX_GROUPS_PER_DIMENSION + 1u")
	require_text("${_test}" "${_needle}" "pool-compute host mutation")
ENDFOREACH()
require_text("${_smoke}" "'set r_particles 1' 'set r_gpuDecals 1'" "native pool-render gates")
require_text("${_smoke}" "\"particle\",\"decal\"" "native pool-render receipt families")
require_text("${_smoke}" "else 0" "native nondynamic-offset receipt")
require_text("${_smoke}" "ral-particle-compute schema=1" "native particle compute receipt")
require_text("${_smoke}" "'set r_atmosphericGPU 1'" "native atmospheric gate")
require_text("${_smoke}" "ral-atmospheric-compute schema=1" "native atmospheric compute receipt")
require_text("${_smoke}" "\"atmospheric\"" "native atmospheric render receipt")
require_text("${_smoke}" "compute-to-graphics" "native particle compute barrier")

MESSAGE(STATUS "particle, decal, and atmospheric cohorts use backend-neutral RAL pool commands")
