# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors

if(NOT DEFINED ROOT OR NOT IS_DIRECTORY "${ROOT}")
	message(FATAL_ERROR "ROOT must name the q3now source tree")
endif()

function(require_text body needle label)
	string(FIND "${body}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "RAL swapchain policy lost ${label}: ${needle}")
	endif()
endfunction()

file(READ "${ROOT}/code/render/ral/core/ral_swapchain.h" PUBLIC)
file(READ "${ROOT}/code/render/ral/core/ral_presentation_policy.c" POLICY)
file(READ "${ROOT}/code/render/ral/backends/vulkan/ral_vulkan_swapchain.c" VULKAN)
file(READ "${ROOT}/code/render/ral/backends/vulkan/ral_vulkan_bridge.c" BRIDGE)
file(READ "${ROOT}/code/render/ral/backends/metal/ral_metal_present.mm" METAL)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" RENDERER)
file(READ "${ROOT}/code/sdl/sdl_metal_ral.mm" SDL_METAL)
file(READ "${ROOT}/code/render/ral/backends/metal/ral_metal_module.mm" METAL_MODULE)
file(READ "${ROOT}/code/tools/profile_imgui/wired_profile_host_main.cpp" PROFILE)
file(READ "${ROOT}/tests/ral_swapchain_policy_test.c" TEST)
file(READ "${ROOT}/tests/ral_metal_present_test.mm" METAL_TEST)
if(DEFINED PROBE_TEXT)
	string(APPEND RENDERER "\n${PROBE_TEXT}\n")
endif()

require_text("${PUBLIC}" "ralPresentMode_t mode;" "preference mode")
require_text("${PUBLIC}" "uint32_t desiredImageCount;" "bounded image count")
require_text("${PUBLIC}" "uint32_t unboundedImageCount;" "unlimited-surface image count")
require_text("${PUBLIC}" "const ralPresentPreference_t *presentPreferences;" "ordered preferences")
require_text("${PUBLIC}" "uint32_t                  presentPreferenceCount;" "preference count")
require_text("${PUBLIC}" "uint32_t          requestedImageCount;" "selected request receipt")
require_text("${PUBLIC}" "ralSurfaceFormatSelectionInfo_t" "portable surface-format query")
require_text("${PUBLIC}" "ralSurfaceFormatSelection_t" "surface-format receipt")
require_text("${PUBLIC}" "ralResult_t Ral_SelectSurfaceFormat" "portable format-selection entry point")
require_text("${VULKAN}" "GetPhysicalDeviceSurfaceFormats2KHR" "backend extended colorspace query")
require_text("${VULKAN}" "surfaceInfo.pNext = extensionChain;" "backend query extension chain")
require_text("${VULKAN}" "ralVk_QuerySurfaceFormats2( b, b->surface, ci->backendExtensionChain" "create/query cohort join")
require_text("${VULKAN}" "candidate.selectedPreference = p;" "ordered preference receipt")
require_text("${BRIDGE}" "RalVulkan_SurfaceFormatToNative" "typed migration translation bridge")
require_text("${METAL}" "ralResult_t Ral_SelectSurfaceFormat" "Metal portable selection")
require_text("${VULKAN}" "GetPhysicalDeviceSurfaceCapabilitiesKHR( b->physicalDevice, b->surface, &caps )" "backend capability query")
require_text("${VULKAN}" "ralVk_QueryPresentModes( b, b->surface, &modes, &modeCount )" "backend mode query")
require_text("${VULKAN}" "caps.maxImageCount == 0u && selectedPresentPreference.unboundedImageCount != 0u" "unlimited-surface count")
require_text("${VULKAN}" "sc->requestedImageCount = desiredCount;" "Vulkan request publication")
require_text("${METAL}" "selected.requestedImageCount = preference->desiredImageCount" "Metal request selection")
require_text("${METAL}" "r->selected.requestedImageCount == r->selected.imageCount" "Metal receipt join")
require_text("${RENDERER}" "Ral_PresentationPolicyRequestFromLegacySwapInterval" "renderer policy adapter")
require_text("${RENDERER}" "Ral_ResolvePresentationPolicy" "renderer ordered policy")
require_text("${POLICY}" "RAL_PRESENT_FIFO_LATEST_READY, queuedImages" "latest-ready preference")
require_text("${POLICY}" "queuedImages + 1u" "FIFO unlimited policy")
require_text("${RENDERER}" "sci.presentPreferences      = presentationPolicy.preferences;" "renderer RAL delegation")
require_text("${RENDERER}" "image_count               = actual.requestedImageCount;" "renderer selected receipt")
require_text("${RENDERER}" "Ral_FinalizePresentationPolicy" "generation-bound pacing receipt")
require_text("${RENDERER}" "result = Ral_SelectSurfaceFormat( backend, &query, &selected );" "renderer RAL format delegation")
require_text("${RENDERER}" "RAL_FORMAT_A2B10G10R10_UNORM, RAL_COLORSPACE_HDR10_ST2084" "portable HDR10 preference")
require_text("${RENDERER}" "query.useExtendedQuery = qtrue;" "colorspace-aware query request")
require_text("${RENDERER}" "vk_native_surface_format( &selected.selected" "selected receipt consumption")
require_text("${SDL_METAL}" "outInfo->presentPreferences = outPreference;" "SDL consumer")
require_text("${METAL_MODULE}" "createInfo->presentPreferences = policy->preferences;" "Metal module consumer")
require_text("${PROFILE}" "ci.presentPreferences = preferences;" "tool consumer")
require_text("${TEST}" "RAL_SWAPCHAIN_MAX_REQUESTED_IMAGES + 1u" "invalid-count mutation")
require_text("${TEST}" "modePreferences[1].unboundedImageCount = RAL_SWAPCHAIN_MAX_REQUESTED_IMAGES + 1u;" "invalid unlimited-count mutation")
require_text("${TEST}" "ralPresentPreference_t fifoUnlimited = { RAL_PRESENT_FIFO, 6u, 7u };" "unlimited test")
require_text("${TEST}" "CHECK( info.requestedImageCount == 7u );" "unlimited receipt assertion")
require_text("${TEST}" "formatSelection.extendedQuery == qtrue" "Vulkan extended-query assertion")
require_text("${TEST}" "g_extendedFormatCalls == 2u && g_legacyFormatCalls == 0u" "HDR create/query cohort test")
require_text("${TEST}" "!memcmp( &formatSelection, &untouchedSelection" "format output atomicity")
require_text("${METAL_TEST}" "selected.selectedPreference == 1u" "Metal ordered-selection test")

foreach(retired IN ITEMS
	qvkGetPhysicalDeviceSurfaceCapabilitiesKHR
	qvkGetPhysicalDeviceSurfacePresentModesKHR
	qvkGetPhysicalDeviceSurfaceFormatsKHR
	qvkGetPhysicalDeviceSurfaceFormats2KHR
	presentModePreferences
	presentModePreferenceCount)
	string(REGEX MATCH "(^|[^A-Za-z0-9_])${retired}([^A-Za-z0-9_]|$)" hit "${RENDERER}")
	if(hit)
		message(FATAL_ERROR "RAL swapchain policy accepted retired renderer ownership: ${retired}")
	endif()
endforeach()

message(STATUS "RAL swapchain policy: portable format/colorspace and per-mode count ownership PASS")
