# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_lighting_bake.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_bake.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_bake_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting bake policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "RAL_LIGHTING_BAKE_MAX_BOUNCES 16u" "bounded bounce count")
req(HEADER "energyClampQ16" "energy clamp")
req(HEADER "Ral_LightingPatchGraphBuild" "geometry extraction contract")
req(CORE "formFactorQ16" "radiosity transfer")
req(CORE "FormFactor" "deterministic geometric coupling")
req(TEST "!memcmp(out1,out2" "deterministic output")
req(BUILD "ADD_EXECUTABLE(ral_lighting_bake_test" "host target")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum|float[ ]")
	message(FATAL_ERROR "ral lighting bake policy: backend type or float leaked into deterministic contract")
endif()
message(STATUS "ral lighting bake source policy: PASS")
