if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_memory_recovery.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_memory.c" VK)
file(READ "${ROOT}/tests/ral_memory_recovery_test.c" HOST)
function(req var needle label)
  string(FIND "${${var}}" "${needle}" p)
  if(p EQUAL -1)
    message(FATAL_ERROR "memory recovery policy lost ${label}: ${needle}")
  endif()
endfunction()
req(CORE "event->attempt == event->maxAttempts" "bounded retry ceiling")
req(CORE "RAL_MEMORY_RECOVERY_RECREATE_BACKEND" "device-loss recreation")
req(CORE "receipt->preserveLiveParent == receipt->event.liveParent" "live-parent preservation")
req(CORE "Ral_MemoryFailureLedgerPublish" "monotonic output-atomic telemetry ledger")
req(VK "RAL_MEMORY_FAILURE_NO_COMPATIBLE_TYPE" "memory-type failure publication")
req(VK "VK_ERROR_OUT_OF_HOST_MEMORY" "host OOM classification")
req(VK "VK_ERROR_DEVICE_LOST" "device-loss classification")
req(VK "VK_ERROR_FRAGMENTED_POOL" "fragmentation classification")
req(VK "RAL_MEMORY_FAILURE_DEVICE_OOM" "device OOM classification")
req(VK "RAL_MEMORY_FAILURE_PRESSURE" "budget pressure classification")
req(VK "Ral_GetLastMemoryFailure" "queryable exact telemetry")
req(HOST "RAL_BACKEND_WEBGPU" "managed unknown-budget fixture")
req(HOST "RAL_MEMORY_FAILURE_RESIZE" "resize fixture")
req(HOST "RAL_MEMORY_RECOVERY_EVICT_AND_RETRY" "bounded eviction fixture")
req(HOST "event.attempt=0" "invalid retry epoch mutation")
message(STATUS "RAL memory recovery policy: PASS")
