# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
set(BACKEND "${ROOT}/code/render/ral/backends/webgpu")
foreach(FILE IN ITEMS ral_webgpu_command.h ral_webgpu_command.c ral_webgpu_presentation.h ral_webgpu_presentation.c)
	if(NOT EXISTS "${BACKEND}/${FILE}")
		message(FATAL_ERROR "missing canonical WebGPU command/presentation file: ${FILE}")
	endif()
	file(READ "${BACKEND}/${FILE}" TEXT)
	foreach(FORBIDDEN IN ITEMS "WebGL2" "WEBGL2" "GLES" "glsl300" "SDL_Window" "vulkan.h" "OpenGL/")
		string(FIND "${TEXT}" "${FORBIDDEN}" POSITION)
		if(NOT POSITION EQUAL -1)
			message(FATAL_ERROR "forbidden fallback/native window dependency in ${FILE}: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
file(READ "${BACKEND}/ral_webgpu_command.c" COMMAND_SOURCE)
file(READ "${BACKEND}/ral_webgpu_presentation.c" PRESENT_SOURCE)
foreach(NEEDLE IN ITEMS "beginEncoder" "beginPass" "recordIndexedDraw" "RalWebGpu_CommandRecordIndexedDraw" "finishEncoder" "pollSubmission" "Ral_SubmissionLifecyclePublish")
	string(FIND "${COMMAND_SOURCE}" "${NEEDLE}" POSITION)
	if(POSITION EQUAL -1)
		message(FATAL_ERROR "WebGPU command layer is missing transaction authority: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "canvasIdentity" "dprQ16" "configure" "acquire" "present" "suspended")
	string(FIND "${PRESENT_SOURCE}" "${NEEDLE}" POSITION)
	if(POSITION EQUAL -1)
		message(FATAL_ERROR "WebGPU presentation layer is missing canvas authority: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL WebGPU command/canvas presentation ownership policy: PASS")
