# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
set(HOST "${ROOT}/code/render/ral/backends/webgpu/ral_webgpu_browser_host.mjs")
set(TEST "${ROOT}/tests/ral_webgpu_browser_host_test.mjs")
foreach(FILE IN ITEMS "${HOST}" "${TEST}")
	if(NOT EXISTS "${FILE}")
		message(FATAL_ERROR "missing WebGPU browser-host contract file: ${FILE}")
	endif()
	file(READ "${FILE}" TEXT)
	foreach(FORBIDDEN IN ITEMS "WebGL2" "webgl2" "getContext(\"webgl" "SDL_" "code/renderer" "code/renderer2")
		string(FIND "${TEXT}" "${FORBIDDEN}" POSITION)
		if(NOT POSITION EQUAL -1)
			message(FATAL_ERROR "forbidden browser fallback/deprecated ownership in ${FILE}: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
file(READ "${HOST}" SOURCE)
foreach(NEEDLE IN ITEMS "requestAdapter" "requestDevice" "device.lost" "createRenderPipelineAsync" "writeBuffer" "writeTexture" "getContext(\"webgpu\")" "drawIndexed" "onSubmittedWorkDone" "devicePixelRatio" "stale-generation" "device-lost")
	string(FIND "${SOURCE}" "${NEEDLE}" POSITION)
	if(POSITION EQUAL -1)
		message(FATAL_ERROR "WebGPU browser host misses required authority: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL WebGPU browser-native host ownership policy: PASS")
