# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
set(BACKEND "${ROOT}/code/render/ral/backends/webgpu")
foreach(FILE IN ITEMS ral_webgpu_product.h ral_webgpu_product.c)
	file(READ "${BACKEND}/${FILE}" TEXT)
	foreach(FORBIDDEN IN ITEMS "vulkan.h" "VkDevice" "OpenGL" "Metal/" "WebGL2" "WEBGL2" "GLES" "code/renderer" "code/renderer2")
		string(FIND "${TEXT}" "${FORBIDDEN}" POSITION)
		if(NOT POSITION EQUAL -1)
			message(FATAL_ERROR "forbidden backend/deprecated ownership in ${FILE}: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
file(READ "${BACKEND}/ral_webgpu_product.c" SOURCE)
foreach(NEEDLE IN ITEMS "RalWebGpu_FrontendPlanBuild" "RalWebGpu_WriteTexture" "RalWebGpu_WriteBuffer" "RalWebGpu_CommandRecordIndexedDraw" "RalWebGpu_CommandSubmit" "BuildEntityGeometry" "BuildMiscGeometry" "model.positions" "RT_SPRITE" "RT_BEAM" "RenderSubmission_EffectSnapshots" "RenderSubmission_UiPrimitives" "RAL_WEBGPU_DRAW_EFFECT" "RAL_WEBGPU_DRAW_UI" "lightmapMaterial" "world.batchCount")
	string(FIND "${SOURCE}" "${NEEDLE}" POSITION)
	if(POSITION EQUAL -1)
		message(FATAL_ERROR "WebGPU product world lowering misses authority: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL WebGPU product world/entity/effect/UI ownership policy: PASS")
