if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/renderer/ral/ral_readback.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_readback.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_readback.c" VULKAN)
file(READ "${ROOT}/tests/ral_readback_owner_test.c" HOST)

function(require_text haystack needle label)
  string(FIND "${${haystack}}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "ral readback policy lost ${label}: ${needle}")
  endif()
endfunction()

require_text(HEADER "ralTransferReceipt_t transfer;" "generation-bound transfer receipt")
require_text(HEADER "ralAllocationReceipt_t stagingAllocation;" "staging allocation receipt")
require_text(HEADER "uintptr_t submissionIdentity;" "submission identity")
require_text(HEADER "ralResult_t (*mapCancel)" "managed pending-map cancel")
require_text(HEADER "qboolean (*candidateAllowed)" "typed ownership oracle")
require_text(CORE "receipt->transfer.request.direction != RAL_TRANSFER_READBACK" "readback-only owner")
require_text(CORE "allocation.ownerIdentity != (uintptr_t)staging" "staging allocation join")
require_text(CORE "!live->receipt.ready || live->mapActive" "release completion/map gate")
require_text(CORE "live->ops->retireStaging" "staging-before-submission release")
require_text(CORE "live->ops->retireSubmission" "submission release")
require_text(VULKAN "RAL_BUFFER_TRANSFER_DST | RAL_BUFFER_MAP_READ" "portable staging flags")
require_text(VULKAN "Ral_CmdTransitionResources" "portable transition commands")
require_text(VULKAN "Ral_CmdCopyBuffer(" "buffer copy command")
require_text(VULKAN "Ral_CmdCopyTextureToBuffer(" "texture copy command")
require_text(VULKAN "Ral_SubmitExact(" "exact submission")
require_text(VULKAN "Ral_FenceSignaled(" "completion fence")
require_text(VULKAN "Ral_BufferMapBegin(" "typed read map")
require_text(VULKAN "Ral_DestroyBuffer( staging )" "staging retirement")
require_text(VULKAN "RestorePortableState( context )" "failed-record rollback")
require_text(HOST "ticket.status==RAL_BUFFER_MAP_PENDING" "WebGPU pending map fixture")
require_text(HOST "Ral_ReadbackMapCancel(owner,&ticket)" "pending-map cancel mutation")
require_text(HOST "!Ral_ReadbackRelease(&owner)" "mapped/early release rejection")
require_text(HOST "!memcmp(f.retired,\"SF\",2)" "child-before-fence retirement")

string(REGEX MATCHALL "Ral_BufferReadbackBegin[(]" BUFFER_BEGIN "${VULKAN}")
list(LENGTH BUFFER_BEGIN BUFFER_BEGIN_COUNT)
if(NOT BUFFER_BEGIN_COUNT EQUAL 1)
  message(FATAL_ERROR "ral readback policy requires exactly one Vulkan buffer adapter")
endif()
string(REGEX MATCHALL "Ral_TextureReadbackBegin[(]" TEXTURE_BEGIN "${VULKAN}")
list(LENGTH TEXTURE_BEGIN TEXTURE_BEGIN_COUNT)
if(NOT TEXTURE_BEGIN_COUNT EQUAL 1)
  message(FATAL_ERROR "ral readback policy requires exactly one Vulkan texture adapter")
endif()

message(STATUS "RAL readback policy: PASS")
