# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors

file(READ "${ROOT}/code/render/ral/core/ral_lighting_artifact.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_artifact.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_artifact_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting artifact policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "RAL_LIGHTING_ARTIFACT_WIRE_HEADER_BYTES 240u" "fixed canonical header")
req(HEADER "RAL_LIGHTING_ARTIFACT_STATIC_DIFFUSE_INDIRECT_ONLY" "term ownership flag")
req(HEADER "RAL_LIGHTING_PAYLOAD_SH_COEFFICIENTS" "probe payload")
req(CORE "RAL_LIGHTING_ARTIFACT_MAGIC" "wire magic")
req(CORE "HashBytes" "payload integrity")
req(CORE "ExpectedPayloadBytes" "encoding-specific semantic size")
req(TEST "!memcmp( a, b" "byte determinism")
req(TEST "a[size - 1u] ^= 1u" "corruption rejection")
req(BUILD "ADD_EXECUTABLE(ral_lighting_artifact_test" "host contract target")
req(BUILD "code/render/ral/core/ral_lighting_artifact.c" "product library ownership")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting artifact policy: native backend type leaked")
endif()
message(STATUS "ral lighting artifact source policy: PASS")
