cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_suballocation.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_suballocation.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_internal.h" VK_HEADER)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_memory.c" VK_MEMORY)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_resource.c" VK_RESOURCE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_transient.c" VK_TRANSIENT)
file(READ "${ROOT}/tests/ral_suballocation_test.c" HOST)
file(READ "${ROOT}/tests/ral_vulkan_suballocation_test.c" VK_HOST)
file(READ "${ROOT}/CMakeLists.txt" CMAKE_TEXT)

function(require_text variable needle label)
  string(FIND "${${variable}}" "${needle}" position)
  if(position EQUAL -1)
    message(FATAL_ERROR "RAL suballocation policy lost ${label}: ${needle}")
  endif()
endfunction()

foreach(forbidden "Vk[A-Z]" "VK_" "WGPU" "MTL")
  if(HEADER MATCHES "${forbidden}" OR CORE MATCHES "${forbidden}")
    message(FATAL_ERROR "portable suballocation contract leaked native API: ${forbidden}")
  endif()
endforeach()

require_text(HEADER "RAL_SUBALLOCATION_MAX_SLICES 128u" "bounded block ledger")
require_text(CORE "allocator->backendType == RAL_BACKEND_WEBGPU" "managed WebGPU exclusion")
require_text(CORE "Ral_SuballocatorAllocate" "aligned deterministic allocation")
require_text(CORE "Ral_SuballocatorFree" "exact slice release")
require_text(CORE "candidate.freeRanges" "output-atomic free-range mutation")
require_text(VK_HEADER "RAL_VK_ALLOC_RESOURCE_BUFFER" "buffer/image block separation")
require_text(VK_HEADER "ralVkMemoryBlock_t *memoryBlocks" "backend-owned block lifetime")
require_text(VK_MEMORY "RAL_VK_DEVICE_BLOCK_BYTES" "device-local block policy")
require_text(VK_MEMORY "RAL_VK_HOST_BLOCK_BYTES" "host-visible block policy")
require_text(VK_MEMORY "memoryTypeIndex != typeIndex || block->resourceKind != resourceKind" "compatible block reuse")
require_text(VK_MEMORY "memoryClass != RAL_ALLOCATION_TRANSIENT" "transient dedicated gate")
require_text(VK_MEMORY "VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT" "lazy dedicated gate")
require_text(VK_MEMORY "Ral_SuballocatorGetStats( &block->allocator, &stats )" "last-slice block release")
require_text(VK_MEMORY "a->block->mappedBase + a->offset" "slice-relative persistent mapping")
require_text(VK_MEMORY "Ral_BufferGetSuballocationReceipt" "buffer slice receipt query")
require_text(VK_MEMORY "Ral_TextureGetSuballocationReceipt" "texture slice receipt query")
require_text(VK_RESOURCE "buf->alloc->offset" "buffer bind offset")
require_text(VK_RESOURCE "tex->alloc->offset" "image bind offset")
require_text(VK_TRANSIENT "RAL_VK_ALLOC_RESOURCE_TRANSIENT" "transient dedicated role")
require_text(HOST "stats.freeRangeCount==2u" "fragmentation fixture")
require_text(HOST "d.offset==256u" "hole reuse fixture")
require_text(HOST "stats.freeRangeCount==1u" "full coalescing fixture")
require_text(HOST "RAL_BACKEND_WEBGPU" "managed-placement fixture")
require_text(VK_HOST "bufferA->block == bufferB->block" "Vulkan block reuse fixture")
require_text(VK_HOST "imageA->block != bufferA->block" "buffer/image separation fixture")
require_text(VK_HOST "mapCalls == 1u" "shared host block mapping fixture")
require_text(VK_HOST "freeCalls == allocateCalls" "last-child physical release fixture")
require_text(VK_HOST "failNextAllocation = 1u" "preferred-block OOM fallback fixture")
require_text(VK_HOST "resizeOld && resizeNew" "candidate-first resize fixture")
require_text(CMAKE_TEXT "ral_suballocation_test" "host target registration")
require_text(CMAKE_TEXT "ral_vulkan_suballocation_test" "Vulkan host target registration")
require_text(CMAKE_TEXT "ral_suballocation_source_policy_contract" "policy registration")
message(STATUS "RAL suballocation policy: PASS")
