# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_lighting_composition.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_composition.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_composition_test.c" TEST)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/lighting_composition.glsl" SHADER)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_frag.tmpl" GENERIC_FRAGMENT)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting composition policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "RAL_LIGHTING_DIFFUSE_AUTHORITY_DIRECTIONAL_STATIC" "modern diffuse authority")
req(HEADER "RAL_LIGHTING_DIFFUSE_AUTHORITY_LOCAL_SH" "moving-object diffuse authority")
req(HEADER "RAL_LIGHTING_DEBUG_STATIC_INDIRECT" "static debug isolation")
req(HEADER "RAL_LIGHTING_DEBUG_SPECULAR_IBL" "specular debug isolation")
req(HEADER "ralLightingSurfaceBindingReceipt_t" "surface binding receipt")
req(CORE "legacyLightmapBound && r->directionalStaticBound" "dual-authority rejection")
req(CORE "compositionWriteCount" "exact-one write receipt")
req(CORE "ModernPlaneCatalog" "modern plane-role mapping")
req(CORE "(uint32_t)request->lightmapIndex >= layers" "surface layer bounds")
req(TEST "RAL_LIGHTING_DEBUG_LOCAL_SH" "local SH debug contract")
req(TEST "Ral_LightingSurfaceBindingBuild" "surface binding contract")
req(TEST "staticProductDiffuseIndirectOnly = qfalse" "direct/specular contamination rejection")
req(SHADER "wired_lighting_directional_static_indirect" "normal-responsive static indirect")
req(SHADER "wired_lighting_compose" "single portable composition function")
req(SHADER "WIRED_LIGHTING_DEBUG_LOCAL_SH" "portable local SH debug isolation")
req(GENERIC_FRAGMENT "#include \"lighting_composition.glsl\"" "real base-pass inclusion")
req(BUILD "ADD_EXECUTABLE(ral_lighting_composition_test" "host target")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting composition policy: backend type leaked")
endif()
message(STATUS "ral lighting composition source policy: PASS")
