# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook.c" CORE)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook_pipeline.h" PIPELINE_HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook_pipeline.c" PIPELINE)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook_driver.c" DRIVER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_cook_producer.c" PRODUCER)
file(READ "${ROOT}/code/tools/lighting_cook/lighting_cook_fs.c" FILESYSTEM)
file(READ "${ROOT}/code/tools/lighting_cook/lighting_cook_opfs.mjs" OPFS)
file(READ "${ROOT}/code/render/frontend/render_lighting_project_source.c" PROJECT_SOURCE)
file(READ "${ROOT}/code/render/frontend/render_lighting_project_cook.c" PROJECT_COOK)
file(READ "${ROOT}/code/render/frontend/tr_public.h" RENDER_ABI)
file(READ "${ROOT}/code/client/cl_main.c" CLIENT)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_init.c" VULKAN_MODULE)
file(READ "${ROOT}/code/render/ral/backends/opengl/ral_opengl_module.c" OPENGL_MODULE)
file(READ "${ROOT}/code/render/ral/backends/metal/ral_metal_module.mm" METAL_MODULE)
file(READ "${ROOT}/code/render/ral/backends/webgpu/ral_webgpu_renderer_module.c" WEBGPU_MODULE)
file(READ "${ROOT}/tests/ral_lighting_cook_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting cook policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "RAL_LIGHTING_COOK_MAX_DIRTY_REGIONS 256u" "bounded regions")
req(HEADER "RAL_LIGHTING_COOK_PUBLISHED" "publish lifecycle")
req(HEADER "RAL_LIGHTING_CACHE_PREVIEW" "explicit preview mode")
req(HEADER "RAL_LIGHTING_CACHE_BLOCKED" "fail-closed runtime mode")
req(CORE "workerRegionBudget" "bounded scheduling")
req(CORE "stagedManifestHash" "staged identity")
req(TEST "RAL_LIGHTING_COOK_CANCELLED" "cancellation coverage")
req(PIPELINE_HEADER "ralLightingCookProgressFn" "progress callback")
req(PIPELINE "Ral_LightingArtifactCacheStore" "atomic artifact store")
req(PIPELINE "Ral_LightingArtifactCacheLoad" "read-back verification")
req(PIPELINE "deferredRegionCount" "deferred-region publication guard")
req(DRIVER "produceBatch" "deferred batch producer driver")
req(DRIVER "completedRegionCount" "bounded incremental completion receipt")
req(PRODUCER "Ral_LightingBakeRun" "headless radiosity producer")
req(PRODUCER "texelPatchIndices" "lightmap texel-to-patch lowering")
req(PRODUCER "Ral_LightingProductWrite" "directional artifact production")
req(PRODUCER "Ral_IrradianceProductWrite" "SH artifact production")
req(FILESYSTEM "O_EXCL" "exclusive same-directory staging")
req(FILESYSTEM "fsync" "durable native staging")
req(FILESYSTEM "rename" "atomic native publication")
req(FILESYSTEM ".wlight" "native directional sidecar publication")
req(FILESYSTEM ".wprobe" "native irradiance sidecar publication")
req(OPFS "temporary.move" "OPFS atomic publication")
req(OPFS "publication refused" "OPFS fail-closed fallback")
req(PROJECT_SOURCE "RenderSubmission_ExtractLightingTriangles" "retained BSP triangle source")
req(PROJECT_SOURCE "CM_BoxTrace" "collision visibility authority")
req(PROJECT_SOURCE "texelPatchIndices" "real lightmap UV rasterization")
req(PROJECT_SOURCE "wired_probe_volume" "authored probe placement")
req(PROJECT_COOK "Ral_LightingCookDriverExecute" "incremental driver orchestration")
req(PROJECT_COOK "RenderLightingSidecar_PackIrradiance" "multi-volume probe bundle")
req(PROJECT_COOK "WiredLightingCookFilesystem_PublishSidecar" "atomic derived publication")
req(RENDER_ABI "CookLightingProject" "explicit renderer ABI cook surface")
req(CLIENT "projectCookLighting" "explicit project command")
req(VULKAN_MODULE "FrontendCookLightingProject" "Vulkan project adapter")
req(OPENGL_MODULE "CookLightingProject" "OpenGL project adapter")
req(METAL_MODULE "CookLightingProject" "Metal project adapter")
req(WEBGPU_MODULE "WASM_MODULE" "browser authoring-write rejection")
req(TEST "RAL_LIGHTING_CACHE_LEGACY_COMPATIBILITY" "legacy migration coverage")
req(BUILD "ADD_EXECUTABLE(ral_lighting_cook_test" "host contract target")
req(BUILD "LIST(REMOVE_ITEM RENDERER_COMMON_SRCS code/render/frontend/render_lighting_project_source.c)" "deprecated renderer project-source exclusion")
req(BUILD "LIST(REMOVE_ITEM RENDERER_COMMON_SRCS code/render/frontend/render_lighting_project_cook.c)" "deprecated renderer project-cook exclusion")
if("${HEADER}${PIPELINE_HEADER}" MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting cook policy: native backend type leaked")
endif()
if("${PROJECT_SOURCE}${PROJECT_COOK}" MATCHES "q3map2|Q3MAP2|LightWorld\\(|LIGHT\\(")
	message(FATAL_ERROR "ral lighting cook policy: legacy mapper/compiler control leaked into project cook")
endif()
message(STATUS "ral lighting cook source policy: PASS")
