# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors

FOREACH(_required SOURCE_ROOT COMPILE_COMMANDS BUILD_NINJA TOOLS_ENABLED)
	IF(NOT DEFINED ${_required})
		MESSAGE(FATAL_ERROR "${_required} is required")
	ENDIF()
ENDFOREACH()
IF(NOT EXISTS "${BUILD_NINJA}")
	MESSAGE("SKIP: RAL profile host ownership policy requires a Ninja build")
	RETURN()
ENDIF()
FILE(READ "${COMPILE_COMMANDS}" _commands)
FILE(READ "${BUILD_NINJA}" _ninja)
SET(_sources
	"${SOURCE_ROOT}/code/tools/profile_imgui/wired_profile_host_lifecycle.cpp"
	"${SOURCE_ROOT}/code/tools/profile_imgui/wired_profile_host_main.cpp"
	"${SOURCE_ROOT}/code/tools/profile_imgui/wired_profile_telemetry_udp.cpp"
	"${SOURCE_ROOT}/code/render/frontend/r_profile_telemetry.c")
STRING(JSON _count LENGTH "${_commands}")
SET(_seen_host)
SET(_host_target_sources)
SET(_telemetry_sender_owners)
SET(_telemetry_receiver_owners)
SET(_telemetry_codec_owners)
MATH(EXPR _last "${_count} - 1")
FOREACH(_index RANGE 0 ${_last})
	STRING(JSON _file GET "${_commands}" ${_index} file)
	STRING(JSON _output GET "${_commands}" ${_index} output)
	STRING(REGEX MATCH "CMakeFiles/([^/]+)\\.dir/" _owner_match "${_output}")
	SET(_owner "${CMAKE_MATCH_1}")
	IF(_file STREQUAL "${SOURCE_ROOT}/code/client/cl_profile_telemetry.c")
		LIST(APPEND _telemetry_sender_owners "${_owner}")
	ELSEIF(_file STREQUAL "${SOURCE_ROOT}/code/tools/profile_imgui/wired_profile_telemetry_udp.cpp")
		LIST(APPEND _telemetry_receiver_owners "${_owner}")
	ELSEIF(_file STREQUAL "${SOURCE_ROOT}/code/render/frontend/r_profile_telemetry.c")
		LIST(APPEND _telemetry_codec_owners "${_owner}")
	ENDIF()
	IF(_output MATCHES "CMakeFiles/wired_profile_host\\.dir/")
		LIST(APPEND _host_target_sources "${_file}")
	ENDIF()
	LIST(FIND _sources "${_file}" _source_index)
	IF(_source_index GREATER -1)
		STRING(JSON _command GET "${_commands}" ${_index} command)
		IF(_output MATCHES "CMakeFiles/wired_profile_host\\.dir/")
			IF(_command MATCHES "(^| )-DHEADLESS(=| |$)")
				MESSAGE(FATAL_ERROR "HEADLESS leaked into standalone profile host")
			ENDIF()
			LIST(APPEND _seen_host "${_file}")
		ELSEIF(_file MATCHES "wired_profile_host_main\\.cpp$")
			MESSAGE(FATAL_ERROR "profile host main leaked outside tool target: ${_output}")
		ENDIF()
	ENDIF()
ENDFOREACH()
LIST(SORT _seen_host)
LIST(REMOVE_DUPLICATES _seen_host)
LIST(SORT _host_target_sources)
LIST(REMOVE_DUPLICATES _host_target_sources)
LIST(SORT _sources)
LIST(SORT _telemetry_sender_owners)
LIST(REMOVE_DUPLICATES _telemetry_sender_owners)
LIST(SORT _telemetry_receiver_owners)
LIST(REMOVE_DUPLICATES _telemetry_receiver_owners)
LIST(SORT _telemetry_codec_owners)
LIST(REMOVE_DUPLICATES _telemetry_codec_owners)
SET(_expected_sender client)
SET(_expected_receiver wired_profile_telemetry_udp_test)
SET(_expected_codec client r_profile_telemetry_codec_test wired_profile_telemetry_udp_test)
IF(TOOLS_ENABLED)
	LIST(APPEND _expected_receiver wired_profile_host)
	LIST(APPEND _expected_codec wired_profile_host)
ENDIF()
LIST(SORT _expected_receiver)
LIST(SORT _expected_codec)
IF(NOT _telemetry_sender_owners STREQUAL _expected_sender)
	MESSAGE(FATAL_ERROR "profile telemetry sender ownership mismatch: ${_telemetry_sender_owners}")
ENDIF()
IF(NOT _telemetry_receiver_owners STREQUAL _expected_receiver)
	MESSAGE(FATAL_ERROR "profile telemetry receiver ownership mismatch: ${_telemetry_receiver_owners}")
ENDIF()
IF(NOT _telemetry_codec_owners STREQUAL _expected_codec)
	MESSAGE(FATAL_ERROR "profile telemetry codec ownership mismatch: ${_telemetry_codec_owners}")
ENDIF()
IF(TOOLS_ENABLED)
	IF(NOT _seen_host STREQUAL _sources)
		MESSAGE(FATAL_ERROR "tools-on profile host source ownership mismatch")
	ENDIF()
	IF(NOT _host_target_sources STREQUAL _sources)
		MESSAGE(FATAL_ERROR "tools-on profile host has an unexpected source owner")
	ENDIF()
	IF(NOT _ninja MATCHES "build wired_profile_host:")
		MESSAGE(FATAL_ERROR "tools-on profile host executable missing")
	ENDIF()
	STRING(REGEX MATCH "build wired_profile_host:[^\n]*" _host_link_line "${_ninja}")
	IF(NOT _host_link_line MATCHES "libral_vulkan\\.a")
		MESSAGE(FATAL_ERROR "profile host does not link RAL")
	ENDIF()
	IF(NOT _host_link_line MATCHES "SDL3")
		MESSAGE(FATAL_ERROR "profile host does not link SDL3")
	ENDIF()
	IF(NOT _host_link_line MATCHES "libwired_profile_imgui\\.a")
		MESSAGE(FATAL_ERROR "profile host does not link the tool-only ImGui/RAL adapter")
	ENDIF()
	IF(_host_link_line MATCHES "(renderervk|renderer_|qcommon|wired\\.arm64|wired-headless)")
		MESSAGE(FATAL_ERROR "profile host leaked a renderer/product dependency")
	ENDIF()
ELSE()
	IF(_seen_host OR _ninja MATCHES "build wired_profile_host:")
		MESSAGE(FATAL_ERROR "tools-off product graph contains standalone profile host")
	ENDIF()
ENDIF()
MESSAGE(STATUS "RAL profile host policy PASS: tool-only isolation preserved")
