# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/renderer/ral/ral_command_lifecycle.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_command.h" COMMAND_HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_sync.h" SYNC_HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_command_lifecycle.c" CORE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_command.c" VULKAN)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_bridge.h" BRIDGE)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_internal.h" INTERNAL_HEADER)
file(READ "${ROOT}/code/renderer/ral_vulkan/ral_vulkan_sync.c" SYNC)
file(READ "${ROOT}/tests/ral_command_lifecycle_test.c" HOST)
file(READ "${ROOT}/tests/ral_submission_lifecycle_test.c" SYNC_HOST)
file(READ "${ROOT}/tests/ral_webgpu_command_lifecycle_test.c" WEBGPU_HOST)
file(READ "${ROOT}/code/renderervk/vk.c" RENDERER)

function(require_text HAYSTACK NEEDLE LABEL)
	string(FIND "${${HAYSTACK}}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "missing ${LABEL}: ${NEEDLE}")
	endif()
endfunction()

foreach(native_token VkCommandBuffer VkQueue WGPUCommandEncoder WGPUQueue)
	string(FIND "${HEADER}" "${native_token}" POS)
	if(NOT POS EQUAL -1)
		message(FATAL_ERROR "native command type escaped public lifecycle: ${native_token}")
	endif()
endforeach()

require_text(HEADER "const ralBackend_t *backendIdentity;" "opaque backend identity")
require_text(HEADER "const ralCommandBuffer_t *commandIdentity;" "opaque command identity")
require_text(HEADER "uint64_t generation;" "monotonic generation")
require_text(HEADER "ralQueueType_t queue;" "logical queue")
require_text(HEADER "Ral_CommandLifecycleRecycle" "portable submitted-to-idle recycle")
require_text(COMMAND_HEADER "Ral_RecycleCommandBufferExact" "backend command recycle surface")
require_text(CORE "submitted->state != RAL_COMMAND_SUBMITTED" "submitted recycle authority")
require_text(CORE "lifecycle->state = RAL_COMMAND_IDLE;" "portable recycle publication")
require_text(CORE "submission->generation >= UINT64_MAX - 1u" "submit saturation gate")
require_text(CORE "commands[j] == commands[i]" "duplicate command rejection")
require_text(VULKAN "result = ralVk_QueueSubmit2( b, q, &si2, fence );" "native submission")
require_text(VULKAN "Ral_SubmissionLifecyclePublish( &b->submissionLifecycle[q]" "post-native publication")
require_text(VULKAN "cb->backend->vk.ResetCommandBuffer( cb->cb, 0 )" "Vulkan recycle lowering")
require_text(VULKAN "Ral_CommandLifecycleRecycle( &cb->lifecycle, submitted )" "post-native recycle publication")
require_text(RENDERER "void vk_wait_idle( void )" "renderer device-idle seam")
require_text(RENDERER "Ral_WaitIdleAndDrainDeferred( vk_ral_get_backend() ) != ralSuccess"
	"backend-owned all-queue idle and deferred drain")
require_text(RENDERER "RAL device-idle/deferred-drain transaction failed"
	"renderer idle failure contract")
require_text(SYNC "s->ownsSemaphore = qtrue;" "RAL-owned semaphore publication")
require_text(SYNC "ralVk_DeferDestroy( s->backend, RAL_RES_SEMAPHORE" "deferred owned semaphore teardown")
require_text(SYNC "f->ownsFence   = qtrue;" "RAL-owned fence publication")
require_text(SYNC "ralVk_DeferDestroy( f->backend, RAL_RES_FENCE" "deferred owned fence teardown")
require_text(SYNC_HEADER "ralResult_t Ral_WaitFenceExact" "checked fence wait surface")
require_text(SYNC_HEADER "ralResult_t Ral_ResetFenceExact" "checked fence reset surface")
require_text(SYNC "case VK_TIMEOUT:" "native fence timeout mapping")
require_text(SYNC "case VK_NOT_READY: return ralTimeout;" "native fence not-ready mapping")
require_text(SYNC "case VK_ERROR_DEVICE_LOST: return ralErrorDeviceLost;" "native fence device-lost mapping")
require_text(SYNC "return ralVk_FenceResult( f->backend->vk.WaitForFences(" "backend-owned checked fence wait")
require_text(SYNC "return ralVk_FenceResult( f->backend->vk.ResetFences(" "backend-owned checked fence reset")
require_text(SYNC "(void)Ral_WaitFenceExact( f, timeoutNs );" "void wait compatibility wrapper")
require_text(SYNC "(void)Ral_ResetFenceExact( f );" "void reset compatibility wrapper")
require_text(RENDERER "static ralSemaphore_t *vk_create_binary_semaphore(" "renderer binary semaphore owner helper")
require_text(RENDERER "*outNative = VK_NULL_HANDLE;" "output-atomic native mirror reset")
require_text(RENDERER "owner = Ral_CreateSemaphore( vk_ral_get_backend(), RAL_SEMAPHORE_BINARY );" "portable semaphore creation")
require_text(RENDERER "identity = Ral_GetSemaphoreHandle( owner );" "borrowed native identity derivation")
require_text(RENDERER "Ral_DestroySemaphore( owner );" "partial publication cleanup")
require_text(RENDERER "*outNative = (VkSemaphore)identity;" "borrowed native mirror publication")
require_text(RENDERER "vk.ral_swapchain_rendering_finished[i] = vk_create_binary_semaphore(" "swapchain generation semaphore owner")
require_text(RENDERER "vk.tess[i].ral_image_acquired = vk_create_binary_semaphore(" "frame-acquire semaphore owner")
require_text(RENDERER "if ( vk.ral_image_uploaded2 ) { Ral_DestroySemaphore( vk.ral_image_uploaded2 ); vk.ral_image_uploaded2 = NULL; }\n\tvk.image_uploaded2 = VK_NULL_HANDLE;" "upload owner-before-mirror teardown")
require_text(RENDERER "if ( vk.tess[i].ral_image_acquired ) { Ral_DestroySemaphore( vk.tess[i].ral_image_acquired ); vk.tess[i].ral_image_acquired = NULL; }\n\t\tvk.tess[i].image_acquired = VK_NULL_HANDLE;" "frame owner-before-mirror teardown")
require_text(RENDERER "if ( vk.tess[i].ral_rendering_finished2 ) { Ral_DestroySemaphore( vk.tess[i].ral_rendering_finished2 ); vk.tess[i].ral_rendering_finished2 = NULL; }\n\t\tvk.tess[i].rendering_finished2 = VK_NULL_HANDLE;" "optional upload-ring owner-before-mirror teardown")
require_text(RENDERER "Ral_DestroySemaphore( vk.ral_swapchain_rendering_finished[i] );\n\t\t\tvk.ral_swapchain_rendering_finished[i] = NULL;" "swapchain semaphore teardown")
require_text(RENDERER "\t\t}\n\t\tvk.swapchain_rendering_finished[i] = VK_NULL_HANDLE;" "swapchain mirror clear after owner teardown")
string(REGEX MATCHALL "vk_create_binary_semaphore[(]" BINARY_SEMAPHORE_CALLS "${RENDERER}")
list(LENGTH BINARY_SEMAPHORE_CALLS BINARY_SEMAPHORE_CALL_COUNT)
if(NOT BINARY_SEMAPHORE_CALL_COUNT EQUAL 5)
	message(FATAL_ERROR "renderer binary semaphore owner inventory drifted: ${BINARY_SEMAPHORE_CALL_COUNT}/5")
endif()
string(FIND "${RENDERER}" "static ralSemaphore_t *vk_create_binary_semaphore(" BINARY_HELPER_BEGIN)
string(FIND "${RENDERER}" "static void vk_apply_hdr_metadata" BINARY_HELPER_END)
if(BINARY_HELPER_BEGIN EQUAL -1 OR BINARY_HELPER_END EQUAL -1 OR NOT BINARY_HELPER_BEGIN LESS BINARY_HELPER_END)
	message(FATAL_ERROR "renderer binary semaphore helper span is malformed")
endif()
math(EXPR BINARY_HELPER_LENGTH "${BINARY_HELPER_END} - ${BINARY_HELPER_BEGIN}")
string(SUBSTRING "${RENDERER}" ${BINARY_HELPER_BEGIN} ${BINARY_HELPER_LENGTH} BINARY_HELPER)
string(FIND "${BINARY_HELPER}" "owner = Ral_CreateSemaphore" BINARY_CREATE_POS)
string(FIND "${BINARY_HELPER}" "identity = Ral_GetSemaphoreHandle" BINARY_GET_POS)
string(FIND "${BINARY_HELPER}" "*outNative = (VkSemaphore)identity;" BINARY_PUBLISH_POS)
if(BINARY_CREATE_POS EQUAL -1 OR BINARY_GET_POS EQUAL -1 OR BINARY_PUBLISH_POS EQUAL -1
		OR NOT BINARY_CREATE_POS LESS BINARY_GET_POS OR NOT BINARY_GET_POS LESS BINARY_PUBLISH_POS)
	message(FATAL_ERROR "renderer binary semaphore create/get/publish order drifted")
endif()
foreach(retired_semaphore IN ITEMS qvkCreateSemaphore qvkDestroySemaphore Ral_AdoptSemaphore)
	string(FIND "${RENDERER}" "${retired_semaphore}" RETIRED_SEMAPHORE_POS)
	if(NOT RETIRED_SEMAPHORE_POS EQUAL -1)
		message(FATAL_ERROR "raw/adopted renderer semaphore ownership returned: ${retired_semaphore}")
	endif()
endforeach()
require_text(RENDERER "static ralFence_t *vk_create_fence(" "renderer fence owner helper")
require_text(RENDERER "owner = Ral_CreateFence( vk_ral_get_backend() );" "portable fence creation")
require_text(RENDERER "identity = Ral_GetFenceHandle( owner );" "borrowed fence identity derivation")
require_text(RENDERER "vk.tess[i].ral_rendering_finished_fence = vk_create_fence(" "per-frame fence owner")
require_text(RENDERER "vk.tess[i].rendering_finished_fence = Ral_GetFenceHandle(" "per-frame borrowed fence mirror")
require_text(RENDERER "vk.ral_aux_fence = vk_create_fence( \"aux fence\" );" "optional upload fence owner")
require_text(RENDERER "vk.aux_fence = Ral_GetFenceHandle( vk.ral_aux_fence );" "optional borrowed fence mirror")
require_text(RENDERER "Ral_DestroyFence( vk.tess[i].ral_rendering_finished_fence );\n\t\t\tvk.tess[i].ral_rendering_finished_fence = NULL;\n\t\t}\n\t\tvk.tess[i].rendering_finished_fence = VK_NULL_HANDLE;" "frame fence owner-before-mirror teardown")
require_text(RENDERER "if ( vk.ral_aux_fence ) { Ral_DestroyFence( vk.ral_aux_fence ); vk.ral_aux_fence = NULL; }\n\tvk.aux_fence = VK_NULL_HANDLE;" "optional fence owner-before-mirror teardown")
string(REGEX MATCHALL "vk_create_fence[(]" FENCE_OWNER_CALLS "${RENDERER}")
list(LENGTH FENCE_OWNER_CALLS FENCE_OWNER_CALL_COUNT)
if(NOT FENCE_OWNER_CALL_COUNT EQUAL 3)
	message(FATAL_ERROR "renderer fence owner inventory drifted: ${FENCE_OWNER_CALL_COUNT}/3")
endif()
string(FIND "${RENDERER}" "static ralFence_t *vk_create_fence(" FENCE_HELPER_BEGIN)
string(FIND "${RENDERER}" "static void vk_apply_hdr_metadata" FENCE_HELPER_END)
if(FENCE_HELPER_BEGIN EQUAL -1 OR FENCE_HELPER_END EQUAL -1 OR NOT FENCE_HELPER_BEGIN LESS FENCE_HELPER_END)
	message(FATAL_ERROR "renderer fence owner helper span is malformed")
endif()
math(EXPR FENCE_HELPER_LENGTH "${FENCE_HELPER_END} - ${FENCE_HELPER_BEGIN}")
string(SUBSTRING "${RENDERER}" ${FENCE_HELPER_BEGIN} ${FENCE_HELPER_LENGTH} FENCE_HELPER)
string(FIND "${FENCE_HELPER}" "owner = Ral_CreateFence" FENCE_CREATE_POS)
string(FIND "${FENCE_HELPER}" "identity = Ral_GetFenceHandle" FENCE_GET_POS)
string(FIND "${FENCE_HELPER}" "SET_OBJECT_NAME( (uint64_t)(uintptr_t)identity" FENCE_PUBLISH_POS)
if(FENCE_CREATE_POS EQUAL -1 OR FENCE_GET_POS EQUAL -1 OR FENCE_PUBLISH_POS EQUAL -1
		OR NOT FENCE_CREATE_POS LESS FENCE_GET_POS OR NOT FENCE_GET_POS LESS FENCE_PUBLISH_POS)
	message(FATAL_ERROR "renderer fence create/get/publish order drifted")
endif()
foreach(retired_fence IN ITEMS qvkCreateFence qvkDestroyFence Ral_AdoptFence)
	string(FIND "${RENDERER}" "${retired_fence}" RETIRED_FENCE_POS)
	if(NOT RETIRED_FENCE_POS EQUAL -1)
		message(FATAL_ERROR "raw/adopted renderer fence ownership returned: ${retired_fence}")
	endif()
endforeach()
foreach(retired_fence_op IN ITEMS qvkWaitForFences qvkResetFences)
	string(FIND "${RENDERER}" "${retired_fence_op}" RETIRED_FENCE_OP_POS)
	if(NOT RETIRED_FENCE_OP_POS EQUAL -1)
		message(FATAL_ERROR "raw renderer fence operation returned: ${retired_fence_op}")
	endif()
endforeach()
require_text(RENDERER "ralResult_t waitResult = Ral_WaitFenceExact( vk.ral_aux_fence," "checked staging wait")
require_text(RENDERER "Ral_ResetFenceExact( vk.ral_aux_fence ) != ralSuccess" "checked staging reset")
require_text(RENDERER "ralFence_t *fence;" "RAL fence worker queue identity")
require_text(RENDERER "wait_result = Ral_WaitFenceExact( fence, 10000000000ULL );" "checked worker wait")
require_text(RENDERER "reset_result = Ral_ResetFenceExact( fence );" "checked worker reset")
require_text(RENDERER "vk_fence_submit( vk.cmd_index, vk.cmd->ral_rendering_finished_fence );" "RAL fence queue handoff")
require_text(RENDERER "vk.cmd->ral_rendering_finished_fence, 10000000000ULL" "checked Windows frame wait")
string(FIND "${RENDERER}" "qvkDeviceWaitIdle" RENDERER_RAW_IDLE)
if(NOT RENDERER_RAW_IDLE EQUAL -1)
	message(FATAL_ERROR "raw device-idle dispatch escaped renderer lifecycle seam")
endif()
string(FIND "${VULKAN}" "result = ralVk_QueueSubmit2( b, q, &si2, fence );" SUBMIT_POS)
string(FIND "${VULKAN}" "Ral_SubmissionLifecyclePublish( &b->submissionLifecycle[q]" PUBLISH_POS)
if(SUBMIT_POS EQUAL -1 OR PUBLISH_POS EQUAL -1 OR NOT SUBMIT_POS LESS PUBLISH_POS)
	message(FATAL_ERROR "submitted receipt must publish only after native queue success")
endif()
require_text(HOST "RunQueue( RAL_QUEUE_GRAPHICS" "graphics lifecycle")
require_text(HOST "RunQueue( RAL_QUEUE_COMPUTE" "compute lifecycle")
require_text(HOST "RunQueue( RAL_QUEUE_TRANSFER" "transfer lifecycle")
require_text(HOST "RunWebGpuCancelShape" "shared WebGPU-shaped cancel lifecycle")
require_text(HOST "Ral_CommandLifecycleRecycle( &commands[0], &stale ) == ralErrorInvalidArgument" "stale recycle rejection")
require_text(HOST "recording[0].generation == 2u" "recycled generation advances")
require_text(SYNC_HOST "g_semaphoreCreateResult = VK_ERROR_OUT_OF_HOST_MEMORY;" "binary semaphore creation failure")
require_text(SYNC_HOST "binarySemaphore->ownsSemaphore == qtrue" "binary semaphore ownership receipt")
require_text(SYNC_HOST "g_deviceIdleCalls == 1u && g_semaphoreDestroyCalls == 1u" "exact semaphore teardown")
require_text(SYNC_HOST "g_fenceCreateResult = VK_ERROR_OUT_OF_DEVICE_MEMORY;" "fence creation failure")
require_text(SYNC_HOST "ownedFence->ownsFence == qtrue" "fence ownership receipt")
require_text(SYNC_HOST "g_deviceIdleCalls == 2u && g_fenceDestroyCalls == 1u" "exact fence teardown")
require_text(SYNC_HOST "Ral_WaitFenceExact( ownedFence, 0u ) == ralSuccess" "zero-timeout checked wait")
require_text(SYNC_HOST "Ral_WaitFenceExact( ownedFence, 1234u ) == ralTimeout" "finite timeout mapping")
require_text(SYNC_HOST "Ral_WaitFenceExact( ownedFence, RAL_TIMEOUT_INFINITE ) == ralTimeout" "infinite timeout forwarding")
require_text(SYNC_HOST "Ral_WaitFenceExact( ownedFence, 1u ) == ralErrorDeviceLost" "device-lost wait mapping")
require_text(SYNC_HOST "Ral_ResetFenceExact( ownedFence ) == ralErrorDeviceLost" "device-lost reset mapping")
require_text(WEBGPU_HOST "BeginEncoder" "WebGPU createCommandEncoder shape")
require_text(WEBGPU_HOST "FinishEncoder" "WebGPU encoder finish shape")
require_text(WEBGPU_HOST "QueueSubmit" "WebGPU queue submit shape")
require_text(WEBGPU_HOST "Ral_CommandLifecycleRecycle( &shape.command" "WebGPU completed command recycle")
require_text(WEBGPU_HOST "recording.generation == 4u" "WebGPU encoder generation advances")
require_text(SYNC_HOST "Ral_RecycleCommandBufferExact( &cb, &staleCommand ) == ralErrorInvalidArgument" "Vulkan stale recycle rejection")
require_text(SYNC_HOST "Ral_RecycleCommandBufferExact( &cb, &submitted.commands[0] ) == ralErrorDeviceLost" "Vulkan recycle device-lost mapping")
require_text(SYNC_HOST "Ral_RecycleCommandBufferExact( &cb, &submitted.commands[0] ) == ralSuccess" "Vulkan recycle success")
foreach(retired_command_op IN ITEMS qvkBeginCommandBuffer qvkEndCommandBuffer qvkResetCommandBuffer)
	string(FIND "${RENDERER}" "${retired_command_op}" RETIRED_COMMAND_POS)
	if(NOT RETIRED_COMMAND_POS EQUAL -1)
		message(FATAL_ERROR "raw renderer command lifecycle returned: ${retired_command_op}")
	endif()
endforeach()
require_text(RENDERER "vk_ral_begin_command_exact( vk.cmd->ral_cmd, \"vk_begin_frame\" );" "exact frame begin")
require_text(RENDERER "vk_ral_end_command_exact( vk.cmd->ral_cmd, \"vk_end_frame\" );" "exact frame end")
require_text(RENDERER "#endif\n\t\t\tif ( slotFenceCompleted )\n\t\t\t\tvk_ral_recycle_completed_command( vk.cmd->ral_cmd," "platform-common post-fence frame recycle")
require_text(RENDERER "vk_ral_recycle_completed_command( vk.ral_staging_cmd," "post-fence staging recycle")
foreach(retired_external_surface IN ITEMS Ral_SetCommandBufferExternalLifecycle Ral_ResetExternalCommandState externalLifecycle)
	string(FIND "${BRIDGE}${VULKAN}${INTERNAL_HEADER}${RENDERER}" "${retired_external_surface}" RETIRED_EXTERNAL_POS)
	if(NOT RETIRED_EXTERNAL_POS EQUAL -1)
		message(FATAL_ERROR "retired external command-lifecycle bypass returned: ${retired_external_surface}")
	endif()
endforeach()
string(FIND "${WEBGPU_HOST}" "Vk" WEBGPU_NATIVE)
if(NOT WEBGPU_NATIVE EQUAL -1)
	message(FATAL_ERROR "Vulkan token escaped WebGPU-shaped command fixture")
endif()

message(STATUS "RAL command lifecycle policy: PASS")
