# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/render/ral/core/ral_material_proxy.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_material_proxy.c" CORE)
file(READ "${ROOT}/tests/ral_material_proxy_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}" "${TEST}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "sin(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "material proxy leaked native/nondeterministic API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_MATERIAL_PROXY_Q16_ONE" "RAL_MATERIAL_PROXY_SINE"
	"ralMaterialProxyEvaluationReceipt_t" "RAL_MATERIAL_PROXY_DOMAIN_PREVIEW")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material proxy contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "sineQ16" "hasWriter" "ProgramHash" "capacity<RAL_MATERIAL_PROXY_VALUE_COUNT")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material proxy invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_MATERIAL_PROXY_DOMAIN_RUNTIME" "RAL_MATERIAL_PROXY_DOMAIN_PREVIEW"
	"RAL_MATERIAL_PROXY_VALUE_COUNT-1u" "stale.artifactHash++" "INT32_MAX")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material proxy hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL material proxy policy: PASS")
