# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_irradiance_product.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_irradiance_product.c" CORE)
file(READ "${ROOT}/tests/ral_irradiance_product_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
foreach(needle IN ITEMS "ralIrradianceProductSample_t" "Ral_IrradianceProductWrite")
	string(FIND "${HEADER}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "irradiance product policy: missing ${needle}")
	endif()
endforeach()
foreach(needle IN ITEMS "RAL_LIGHTING_PAYLOAD_SH_COEFFICIENTS" "RAL_LIGHTING_PAYLOAD_PROBE_VALIDITY" "occluded")
	string(FIND "${CORE}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "irradiance product policy: missing ${needle}")
	endif()
endforeach()
string(FIND "${TEST}" "Ral_LightingArtifactRead" test_at)
string(FIND "${BUILD}" "ADD_EXECUTABLE(ral_irradiance_product_test" build_at)
if(test_at EQUAL -1 OR build_at EQUAL -1)
	message(FATAL_ERROR "irradiance product policy: missing roundtrip/build contract")
endif()
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "irradiance product policy: backend type leaked")
endif()
message(STATUS "ral irradiance product source policy: PASS")
