if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

foreach(BACKEND IN ITEMS vulkan metal opengl webgpu)
	set(STEM "ral_${BACKEND}_lighting")
	if(BACKEND STREQUAL "vulkan")
		set(TOKEN "RalVulkan_LightingUpload")
	elseif(BACKEND STREQUAL "metal")
		set(TOKEN "RalMetal_LightingUpload")
	elseif(BACKEND STREQUAL "opengl")
		set(TOKEN "RalOpenGl_LightingUpload")
	else()
		set(TOKEN "RalWebGpu_LightingUpload")
	endif()
	set(EXT "c")
	if(BACKEND STREQUAL "metal")
		set(EXT "mm")
	endif()
	set(HEADER "${ROOT}/code/render/ral/backends/${BACKEND}/${STEM}.h")
	set(SOURCE "${ROOT}/code/render/ral/backends/${BACKEND}/${STEM}.${EXT}")
	if(NOT EXISTS "${HEADER}" OR NOT EXISTS "${SOURCE}")
		message(FATAL_ERROR "missing ${BACKEND} lighting uploader")
	endif()
	file(READ "${HEADER}" HEADER_TEXT)
	file(READ "${SOURCE}" SOURCE_TEXT)
	string(FIND "${HEADER_TEXT}${SOURCE_TEXT}" "${TOKEN}" FOUND)
	if(FOUND EQUAL -1)
		message(FATAL_ERROR "${BACKEND} lighting upload entry point missing")
	endif()
endforeach()

file(GLOB FRONTEND_CORE
	"${ROOT}/code/render/frontend/*.c" "${ROOT}/code/render/frontend/*.h"
	"${ROOT}/code/render/ral/core/*.c" "${ROOT}/code/render/ral/core/*.h")
foreach(FILE IN LISTS FRONTEND_CORE)
	file(READ "${FILE}" TEXT)
	foreach(NATIVE_HEADER IN ITEMS
		"ral_vulkan_lighting.h" "ral_metal_lighting.h"
		"ral_opengl_lighting.h" "ral_webgpu_lighting.h")
		string(FIND "${TEXT}" "${NATIVE_HEADER}" FOUND)
		if(NOT FOUND EQUAL -1)
			message(FATAL_ERROR "backend lighting ownership leaked into ${FILE}")
		endif()
	endforeach()
endforeach()
