if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/renderercommon/tr_types.h" TYPES)
file(READ "${ROOT}/code/cgame/cg_draw.c" CG_DRAW)
file(READ "${ROOT}/code/renderervk/tr_temporal_input.c" INPUT)
file(READ "${ROOT}/code/renderervk/tr_backend.c" BACKEND)
file(READ "${ROOT}/code/renderervk/tr_scene.c" SCENE)
file(READ "${ROOT}/code/renderervk/vk.c" VK)
file(READ "${ROOT}/code/renderervk/tr_cmds.c" COMMANDS)
file(READ "${ROOT}/code/renderer2/tr_extratypes.h" RENDERER2_TYPES)
file(READ "${ROOT}/code/client/cl_cgame.c" CLIENT)

function(require_text haystack needle label)
	string(FIND "${${haystack}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "missing ${label}: ${needle}")
	endif()
endfunction()

require_text(TYPES "RDF_TEMPORAL_PRIMARY\t0x0040" "non-colliding primary-scene flag")
require_text(CG_DRAW "stereoView == STEREO_CENTER" "center-eye producer gate")
require_text(CG_DRAW "stereoView == STEREO_CENTER && !cl_splitScreen.integer" "single-view producer gate")
require_text(CG_DRAW "cg.refdef.rdflags |= RDF_TEMPORAL_PRIMARY" "primary mark")
require_text(CG_DRAW "cg.refdef.rdflags &= ~RDF_TEMPORAL_PRIMARY" "primary clear")
require_text(INPUT "!( tr.refdef.rdflags & RDF_TEMPORAL_PRIMARY )" "primary consumer gate")
require_text(INPUT "view->portalView != PV_NONE" "portal rejection")
require_text(INPUT "view->stereoFrame != STEREO_CENTER" "stereo rejection")
require_text(INPUT "view->viewportWidth != glConfig.vidWidth" "full-target width gate")
require_text(INPUT "view->viewportHeight != glConfig.vidHeight" "full-target height gate")
require_text(SCENE "fd->rdflags & RDF_HYPERSPACE" "worldless-visible camera cut observation")
require_text(SCENE "R_TemporalMarkCameraCut( worldIndex )" "sticky camera cut mark")
require_text(INPUT "s_temporalCameraCutPending[worldIndex]" "sticky camera cut consumption")
require_text(INPUT "R_TemporalEntityCacheStageCamera" "unjittered camera staging")
require_text(INPUT "view->temporalCameraReceipt = diagnostic.cameraReceipt" "backend camera receipt")
require_text(INPUT "camera-previous=%d" "camera receipt observability")
require_text(INPUT "temporal-continuity schema=1" "raw continuity receipt")
require_text(INPUT "camera-previous-frame=%llu" "camera predecessor identity")
require_text(INPUT "entity-previous-frame=%llu" "entity predecessor identity")
require_text(BACKEND "RB_RecordTemporalEntityReceipts( cmd )" "backend draw receipt adapter")
require_text(BACKEND "R_TemporalEntityCacheRecord" "production cache record")
require_text(BACKEND "R_TemporalBackendEntityReceiptsBegin()" "single receipt scan per replay cohort")
require_text(BACKEND "R_GetModelByHandle" "renderer model topology stamp")
require_text(BACKEND "data->num_frames" "IQM frame topology")
require_text(BACKEND "data->num_joints" "IQM joint topology")
require_text(BACKEND "data->num_poses" "IQM pose topology")
require_text(BACKEND "data->num_surfaces" "IQM surface topology")
require_text(BACKEND "data->num_vertexes" "IQM vertex topology")
require_text(BACKEND "data->num_triangles" "IQM triangle topology")
require_text(RENDERER2_TYPES "RDF_NOFOG\t\t0x0008" "renderer2 no-fog bit")
require_text(RENDERER2_TYPES "RDF_EXTRA\t\t0x0010" "renderer2 extended-refdef bit")
require_text(RENDERER2_TYPES "RDF_SUNLIGHT    0x0020" "renderer2 sunlight bit")
math(EXPR RDF_OVERLAP "0x0040 & (0x0008 | 0x0010 | 0x0020)")
if(NOT RDF_OVERLAP EQUAL 0)
	message(FATAL_ERROR "RDF_TEMPORAL_PRIMARY overlaps renderer2 rdflags")
endif()
string(FIND "${INPUT}" "s_temporalStates[worldIndex].pending\n\t\t\t\t&& s_temporalDiagnostics[worldIndex].queued" stale_cancel_gate)
if(NOT stale_cancel_gate EQUAL -1)
	message(FATAL_ERROR "temporal cancellation must not depend on diagnostic queued state")
endif()
require_text(VK "R_TemporalBackendSubmitted( submitResult == ralSuccess )" "submit-bound commit")
require_text(COMMANDS "R_TemporalCancelQueuedFrames();" "command allocation/dispatch cancellation")
require_text(CLIENT "temporal-entity-capability glconfig-generation=%u key=trap_R_AddRefEntityToSceneTemporal expected=232 discovered=232 route=native-syscall export=1" "slot232 capability receipt")
require_text(CLIENT "temporal-entity-slot glconfig-generation=%u trap=232 owner=%u entity-generation=%u role=%u accepted=1 export=1" "validated slot232 ingress receipt")

string(FIND "${BACKEND}" "RB_RecordTemporalEntityReceipts( cmd )" record_pos)
string(FIND "${BACKEND}" "vk_forwardplus_capture_dlights" draw_pos)
if(record_pos GREATER draw_pos)
	message(FATAL_ERROR "temporal receipt scan must precede renderer draw setup")
endif()

string(FIND "${VK}" "R_TemporalBackendSubmitted( submitResult == ralSuccess )" callback_pos)
string(FIND "${VK}" "ri.Terminate( TERM_UNRECOVERABLE, \"Ral_Submit failed\" )" terminate_pos)
if(callback_pos GREATER terminate_pos)
	message(FATAL_ERROR "submit result must reach temporal authority before termination")
endif()

message(STATUS "RAL temporal entity source policy contract: ok")
