# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_material.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_material.c" CORE)
file(READ "${ROOT}/tests/ral_material_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}" "${TEST}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "material schema leaked native type: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_MATERIAL_SCHEMA_VERSION" "RAL_MATERIAL_SOURCE_Q3"
	"RAL_MATERIAL_SOURCE_GLTF" "RAL_MATERIAL_TEXTURE_ORM"
	"RAL_MATERIAL_CHANNEL_GB_ROUGHNESS_METALLIC" "artifactHash")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material schema contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "Ral_TextureCacheKeyValid" "orm && split"
	"FloatBits" "FNV64_PRIME" "d->textures[i-1u].role >=")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material compile invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "keyHash++" "bad.factors.roughness=NAN"
	"second.variantKey==before.variantKey" "RAL_MATERIAL_SOURCE_GLTF")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL material schema policy: PASS")
