# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2024-present Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
set(BACKEND "${ROOT}/code/render/ral/backends/webgpu")
foreach(FILE IN ITEMS ral_webgpu_frontend.h ral_webgpu_frontend.c)
	file(READ "${BACKEND}/${FILE}" TEXT)
	foreach(FORBIDDEN IN ITEMS "vulkan.h" "VkDevice" "OpenGL" "Metal/" "WebGL2" "WEBGL2" "GLES/" "code/renderer" "code/renderer2")
		string(FIND "${TEXT}" "${FORBIDDEN}" POSITION)
		if(NOT POSITION EQUAL -1)
			message(FATAL_ERROR "forbidden backend/deprecated ownership in ${FILE}: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
file(READ "${BACKEND}/ral_webgpu_frontend.c" SOURCE)
foreach(NEEDLE IN ITEMS "RenderSubmission_ReceiptExact" "RenderSubmission_WorldSnapshot" "RenderSubmission_ModelSnapshot" "RenderSubmission_EffectSnapshots" "RenderSubmission_UiPrimitives" "RalWebGpu_RuntimeResources")
	string(FIND "${SOURCE}" "${NEEDLE}" POSITION)
	if(POSITION EQUAL -1)
		message(FATAL_ERROR "WebGPU frontend plan misses shared payload authority: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL WebGPU sealed frontend ownership policy: PASS")
