# SPDX-License-Identifier: GPL-3.0-or-later
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/render/ral/core/ral_ui_presentation.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_ui_presentation.c" CORE)
file(READ "${ROOT}/tests/ral_ui_presentation_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "malloc(" "free(" "exp(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "UI presentation leaked native/nondeterministic API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_UI_STAGE_SCENE_TONEMAP" "RAL_UI_STAGE_CONSOLE" "RAL_UI_EFFECT_ALL" "ralUiInertiaState_t")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "UI presentation contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "UI_DT_Q16" "for(i=0u;i<delta;i++)" "generation<=s->transactionGeneration" "effectWorkPixels")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "UI presentation invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_UI_OUTPUT_SDR" "RAL_UI_OUTPUT_HDR" "RAL_UI_PROFILE_COMPETITIVE" "Ral_UiInertiaStateExact")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "UI presentation hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL UI presentation policy: PASS")
