# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_lighting_product.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_lighting_product.c" CORE)
file(READ "${ROOT}/tests/ral_lighting_product_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral lighting product policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "Ral_LightingProductWrite" "bake-to-artifact producer")
req(CORE "Ral_StaticLightingEncodeRgb9e5" "primary encoding")
req(CORE "Ral_StaticLightingEncodeRgba16f" "fallback encoding")
req(CORE "RAL_LIGHTING_ARTIFACT_STATIC_DIFFUSE_INDIRECT_ONLY" "term ownership")
req(TEST "Ral_LightingArtifactRead" "round-trip verification")
req(BUILD "ADD_EXECUTABLE(ral_lighting_product_test" "host target")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral lighting product policy: backend type leaked")
endif()
message(STATUS "ral lighting product source policy: PASS")
