# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
file(READ "${ROOT}/code/render/ral/core/ral_static_lighting.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_static_lighting.c" CORE)
file(READ "${ROOT}/tests/ral_static_lighting_test.c" TEST)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
function(req hay needle label)
	string(FIND "${${hay}}" "${needle}" at)
	if(at EQUAL -1)
		message(FATAL_ERROR "ral static lighting policy: missing ${label}: ${needle}")
	endif()
endfunction()
req(HEADER "RAL_STATIC_LIGHTING_ENCODING_RGB9E5_OCT8" "compact HDR directional encoding")
req(HEADER "RAL_STATIC_LIGHTING_ENCODING_RGBA16F_OCT16" "portable HDR fallback")
req(HEADER "staticDiffuseIndirectOnly" "term ownership")
req(HEADER "RAL_IRRADIANCE_SH_L1_COEFFICIENTS 4u" "L1 SH contract")
req(HEADER "RAL_IRRADIANCE_FALLBACK_LIGHTGRID" "deterministic compatibility fallback")
req(HEADER "Ral_StaticLightingEncodeRgb9e5" "primary HDR radiance encoder")
req(HEADER "Ral_StaticLightingEncodeOct8" "primary directional encoder")
req(HEADER "Ral_StaticLightingEncodeRgba16f" "portable HDR fallback encoder")
req(HEADER "Ral_StaticLightingEncodeOct16" "portable direction fallback encoder")
req(TEST "r.sampleCount==8u" "trilinear probe selection")
req(BUILD "ADD_EXECUTABLE(ral_static_lighting_test" "host target")
req(BUILD "code/render/ral/core/ral_static_lighting.c" "product library ownership")
if(HEADER MATCHES "Vk[A-Z]|MTL[A-Z]|WGPU[A-Z]|GLuint|GLenum")
	message(FATAL_ERROR "ral static lighting policy: native backend type leaked")
endif()
message(STATUS "ral static lighting source policy: PASS")
