# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderer/ral/ral_material_reload.h" HEADER)
file(READ "${ROOT}/code/renderer/ral/ral_material_reload.c" CORE)
file(READ "${ROOT}/tests/ral_material_reload_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_" "malloc(" "free(")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "material reload leaked native/unbounded API: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "ralMaterialReloadOwner_t" "ralMaterialReloadCandidate_t"
	"ralMaterialReloadReceipt_t" "Ral_MaterialReloadAcknowledge")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material reload contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "DeriveRetirements" "retirementPending" "usingFallback"
	"generation <= owner->transactionGeneration" "Ral_MaterialReloadReceiptExact")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material reload invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_BACKEND_VULKAN" "RAL_BACKEND_WEBGPU" "owner.usingFallback"
	"wrong.retirements[0].resourceGeneration++" "receipt.retirementCount==2u")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material reload hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL material reload policy: PASS")
