# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/render/ral/core/ral_material_runtime.h" HEADER)
file(READ "${ROOT}/code/render/ral/core/ral_material_runtime.c" CORE)
file(READ "${ROOT}/tests/ral_material_runtime_test.c" TEST)
foreach(TEXT IN ITEMS "${HEADER}" "${CORE}" "${TEST}")
	foreach(FORBIDDEN IN ITEMS "Vk" "WGPU" "MTL" "SDL_")
		string(FIND "${TEXT}" "${FORBIDDEN}" POS)
		if(NOT POS EQUAL -1)
			message(FATAL_ERROR "material runtime leaked native type: ${FORBIDDEN}")
		endif()
	endforeach()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_MATERIAL_RUNTIME_SCHEMA_VERSION" "ralMaterialRuntimeBinding_t"
	"ralMaterialDependencyEvent_t" "Ral_MaterialRuntimeInvalidate")
	string(FIND "${HEADER}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material runtime contract lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "ResourceMatches" "bindingSlot" "cacheKeyHash"
	"RAL_MATERIAL_RUNTIME_INVALIDATED" "resources[j].textureIdentity")
	string(FIND "${CORE}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material runtime invariant lost: ${NEEDLE}")
	endif()
endforeach()
foreach(NEEDLE IN ITEMS "RAL_BACKEND_WEBGPU" "bad[1].textureIdentity"
	"event.textureIdentity=(uintptr_t)0x9999u" "!memcmp(&cohort,&cohortBefore")
	string(FIND "${TEST}" "${NEEDLE}" POS)
	if(POS EQUAL -1)
		message(FATAL_ERROR "material runtime hostile fixture lost: ${NEEDLE}")
	endif()
endforeach()
message(STATUS "RAL material runtime policy: PASS")
