file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_temporal_motion_payload.h" PAYLOAD_H)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_temporal_motion_payload.c" PAYLOAD_C)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.h" VKH)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_init.c" INIT)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_vert.tmpl" GEN_VERT)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_frag.tmpl" GEN_FRAG)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "temporal payload policy: missing ${why}: ${needle}")
	endif()
endfunction()

function(forbid_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(NOT found EQUAL -1)
		message(FATAL_ERROR "temporal payload policy: forbidden ${why}: ${needle}")
	endif()
endfunction()

function(require_count haystack regex expected why)
	string(REGEX MATCHALL "${regex}" matches "${${haystack}}")
	list(LENGTH matches count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "temporal payload policy: ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

require_text(PAYLOAD_H "float currentMvp[16];\n\tfloat previousMvp[16];\n\tuint32_t outcome;\n\tuint32_t reserved[3];" "exact 144-byte GPU record")
require_text(PAYLOAD_H "offsetof( temporalMotionGpuPayload_t, previousMvp ) == 64" "previous MVP offset")
require_text(PAYLOAD_H "offsetof( temporalMotionGpuPayload_t, outcome ) == 128" "outcome offset")
require_text(PAYLOAD_H "sizeof( temporalMotionGpuPayload_t ) == 144" "std430 stride")
require_text(PAYLOAD_H "TEMPORAL_MOTION_WRITE_VALID == 1" "WRITE_VALID GPU enum ABI")
require_text(PAYLOAD_H "TEMPORAL_MOTION_INVALIDATE_OPAQUE == 2" "INVALIDATE_OPAQUE GPU enum ABI")
require_text(PAYLOAD_H "TEMPORAL_MOTION_PAYLOAD_MAX_SLOTS 65536u" "bounded 9MiB storage range")
require_text(PAYLOAD_H "uint32_t entityAllocationGeneration;" "generation-safe borrowed entity identity")

require_text(PAYLOAD_C "entries[0].binding = 0;\n\tentries[0].type = RAL_BIND_STORAGE_BUFFER;" "entity buffer binding zero")
require_text(PAYLOAD_C "entries[1].binding = 1;\n\tentries[1].type = RAL_BIND_STORAGE_BUFFER;" "temporal buffer binding one")
require_count(PAYLOAD_C "stageFlags = RAL_STAGE_VERTEX" 2 "both composite bindings vertex-only")
require_text(PAYLOAD_C "bci.usage = RAL_BUFFER_STORAGE | RAL_BUFFER_TRANSFER_DST;\n\t\tbci.memory = RAL_MEMORY_DEVICE_LOCAL;" "WebGPU-valid device-local payload allocation")
require_text(PAYLOAD_C "candidateShadow = (byte *)calloc( 1, (size_t)bytes );" "CPU payload authority")
require_text(PAYLOAD_C "frame->entityAllocationGeneration == entityAllocationGeneration" "entity identity key includes generation")
require_text(PAYLOAD_C "frame->ready && ( !frame->resetAfterFence || frame->begun )" "replacement requires fence authority")
require_text(PAYLOAD_C "entityBuffer == owner->frames[i].buffer" "borrowed entity cannot alias any temporal buffer")
require_text(PAYLOAD_C "entityBuffer == owner->frames[i].entityBuffer" "borrowed entity cannot alias another frame entity allocation")
require_text(PAYLOAD_C "candidateBuffer == entityBuffer" "candidate temporal cannot alias requested entity allocation")
require_text(PAYLOAD_C "candidateBuffer == owner->frames[i].buffer" "cross-frame buffer alias rejection")
require_text(PAYLOAD_C "candidateBuffer == owner->frames[i].entityBuffer" "candidate temporal versus borrowed entity alias rejection")
require_text(PAYLOAD_C "candidateGroup == owner->frames[i].bindGroup" "cross-frame group alias rejection")
require_text(PAYLOAD_C "R_TemporalMotionPayloadDetachEntityBuffer" "borrowed entity detach authority")
require_text(PAYLOAD_C "!frame->resetAfterFence || frame->begun" "detach requires completed-fence authority and no begun frame")
require_text(PAYLOAD_C "frame->entityBuffer = NULL;\n\tframe->entityAllocationGeneration = 0;" "detached borrowed identity publication")
require_text(PAYLOAD_C "case TEMPORAL_MOTION_WRITE_VALID:" "write-valid admission")
require_text(PAYLOAD_C "case TEMPORAL_MOTION_INVALIDATE_OPAQUE:" "opaque invalidation admission")
require_text(PAYLOAD_C "if ( matrices ) return qfalse;" "canonical zero invalidation input")
require_count(PAYLOAD_C "isfinite\\(" 2 "both matrix streams finite")
require_text(PAYLOAD_C "absoluteEntMatSlot <= frame->lastSlot" "strict monotonic absolute slots")
require_text(PAYLOAD_C "Ral_BufferUploadAsync( frame->buffer, offset,\n\t\t&candidate, sizeof( candidate ) )" "exact written-range staging upload")
require_text(PAYLOAD_C "Ral_WaitFence( upload, ~(uint64_t)0 );" "upload completion before draw-visible publication")
require_text(PAYLOAD_C "memcpy( frame->cpuShadow + offset, &candidate, sizeof( candidate ) );" "CPU shadow publication after upload")
require_text(PAYLOAD_C "free( owner->frames[i].cpuShadow );" "CPU shadow teardown")
forbid_text(PAYLOAD_C "Ral_MapBuffer(" "legacy persistent map")
forbid_text(PAYLOAD_C "Ral_UnmapBuffer(" "legacy persistent unmap")
require_text(PAYLOAD_C "if ( owner->frames[i].bindGroup )" "all groups destroyed before buffers")

# The ordinary product ABI/layout remains byte-for-byte authoritative. This
# owner is callable in production only through the bounded A2a runtime seam;
# it still has no draw, bind, pass, or payload-recording authority there.
require_text(VKH "vec4_t advancedFogColorDensity;                   // offset 608, 16 B\n\tvec4_t advancedFogTypeFarEnabled;                 // offset 624, 16 B\n} vkUniform_t;" "intentional 640-byte vkUniform fog tail")
forbid_text(VKH "temporalMotionPayload" "payload owner in ordinary renderer state")
require_text(VKC "vk_create_layout_binding( 0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,\n\t\tVK_SHADER_STAGE_VERTEX_BIT, &vk.ral_bgl_entmat,\n\t\t&vk.set_layout_entmat, \"wired-set-layout-entmat\" );" "ordinary portable set3 entity layout with adopted native layout")
require_text(VKC "set_layouts[WIRED_ENTITY_MAT_SET] = vk.set_layout_entmat;" "ordinary pipeline set3")
require_text(VKC "Ral_CmdBindBindGroupDynamicExact( vk.cmd->ral_cmd,\n\t\t\t\t\t\tWIRED_ENTITY_MAT_SET, vk.cmd->ral_entMatDesc,\n\t\t\t\t\t\tNULL, 0u )" "ordinary portable entity descriptor bind")
forbid_text(INIT "r_temporalMotionTest" "runtime payload cvar")
# Representative embedded shader interfaces are permitted; this payload owner
# remains inert because the temporal shader policy forbids module/call authority.
forbid_text(PAYLOAD_C "Ral_CmdBindBindGroup" "runtime payload bind")
forbid_text(PAYLOAD_C "Ral_BeginRendering" "runtime temporal pass")

file(GLOB PRODUCT_C "${ROOT}/code/render/ral/backends/vulkan/renderer/*.c")
foreach(path IN LISTS PRODUCT_C)
	get_filename_component(name "${path}" NAME)
	file(READ "${path}" PRODUCT_SOURCE)
	if(name STREQUAL "tr_temporal_motion_payload.c")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadInit" 1 "Init definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadEnsure" 1 "Ensure definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadResetAfterFence" 1 "Reset definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadBeginFrame" 1 "Begin definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadDetachEntityBuffer" 1 "Detach definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadAppendAt" 1 "Append definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadGetBindGroup" 1 "Get definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadGetLayout" 1 "layout getter definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadRelease" 1 "Release definition token count")
	elseif(name STREQUAL "vk_temporal_motion_materialization.c")
		require_count(PRODUCT_SOURCE "R_TemporalMotionPayloadGetLayout" 1 "A2b layout getter authority")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionPayloadBeginFrame" "A2b payload begin authority")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionPayloadAppendAt" "A2b payload append authority")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionPayloadGetBindGroup" "A2b payload bind-group authority")
	elseif(NOT name STREQUAL "vk_temporal_entmat_runtime.c")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionPayload" "payload runtime authority in ${name}")
	endif()
endforeach()

require_text(BUILD "AUX_SOURCE_DIRECTORY(code/render/ral/backends/vulkan/renderer RENDERER_VK_SRCS)" "renderer product source ownership")
require_text(BUILD "ADD_EXECUTABLE(tr_temporal_motion_payload_test" "compiled payload owner contract")
require_text(BUILD "tr_temporal_motion_payload_source_policy_contract" "payload policy registration")

message(STATUS "A2a-owner-only temporal motion payload policy: PASS")
