# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Wired Engine contributors

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/renderervk/tr_model_iqm.c" LOADER)
file(READ "${ROOT}/code/renderervk/tr_temporal_iqm_motion.c" CORE)
file(READ "${ROOT}/code/renderervk/tr_temporal_iqm_motion.h" ABI)
file(READ "${ROOT}/code/renderervk/vk_temporal_iqm_geometry.c" GEOMETRY)
file(READ "${ROOT}/code/renderervk/vk.c" VK)
file(READ "${ROOT}/tests/tr_temporal_iqm_motion_test.c" TEST)

function(require_text haystack needle label)
	string(FIND "${${haystack}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "missing ${label}: ${needle}")
	endif()
endfunction()
function(forbid_text haystack needle label)
	string(FIND "${${haystack}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "forbidden ${label}: ${needle}")
	endif()
endfunction()

require_text(ABI "TEMPORAL_IQM_RECORD_SIZE 12480u" "fixed record ABI")
require_text(ABI "TEMPORAL_IQM_SLOT_BYTES" "fixed 256-record slot ABI")
require_text(ABI "uint32_t sourceDrawSurfOrdinal;" "absolute sorted draw-surf ordinal ABI")
require_text(ABI "const temporalIqmSequence_t *expected;" "compact borrowed verifier")
require_text(ABI "R_TemporalIqmSequenceVerifierPeek" "non-consuming verifier observation")
require_text(ABI "R_TemporalIqmSequenceVerifierCommit" "post-command verifier advance")
require_text(ABI "temporalIqmProductAdmissionFacts_t" "product admission facts ABI")
require_text(ABI "TEMPORAL_IQM_PRODUCT_POISON" "product poison result")
require_text(LOADER "joint->parent < -1 || joint->parent >= i" "forward/self parent rejection")
require_text(LOADER "pose->parent != ((iqmJoint_t *)" "pose/joint parent join")
require_text(LOADER "if ( !isfinite( value ) ) return qfalse;" "decoded frame finite preflight")
require_text(LOADER "if ( !isfinite( quaternionLength ) ) return qfalse;" "decoded quaternion normalization preflight")
require_text(LOADER "&& !IQM_Finite( (const float *)" "vertex finite preflight")
require_text(LOADER "header->num_framechannels && ( header->ofs_frames & 1u )" "frame alignment preflight")
require_text(LOADER "if( ( vertexarray->offset & 3u )" "vertex scalar alignment preflight")
require_text(LOADER "R_TemporalIqmDecodeInfluence(" "canonical influence preflight")
require_text(LOADER "data->influences," "per-vertex influence digest")
require_text(LOADER "R_TemporalIqmBuildPaletteTuple( &temporalModel" "ordinary shared palette")
require_text(LOADER "R_TemporalMotionBuildCanonicalMvp( backEnd.or.modelMatrix" "ordinary canonical raster MVP")
require_text(LOADER "temporalStructuralValidated = IQM_TemporalPaletteValid" "ordinary structural validation")
require_text(LOADER "IQM_TemporalH5Valid( iqmData )" "separate strict H5 admission")
require_text(LOADER "temporalH5Eligible = qtrue" "separate H5 provenance publication")
require_text(LOADER "_Static_assert( IQM_UBYTE == TEMPORAL_IQM_SCALAR_UBYTE" "UBYTE ABI pin")
require_text(LOADER "_Static_assert( IQM_INT == TEMPORAL_IQM_SCALAR_INT" "INT ABI pin")
require_text(LOADER "_Static_assert( IQM_FLOAT == TEMPORAL_IQM_SCALAR_FLOAT" "FLOAT ABI pin")
require_text(CORE "out[3] = a[0] * b[3] + a[1] * b[7] + a[2] * b[11] + a[3]" "exact unrolled matrix order")
require_text(CORE "if ( oldframe == frame )" "exact direct-copy pose fast path")
require_text(CORE "a->sourceDrawSurfOrdinal == b->sourceDrawSurfOrdinal" "draw-surf ordinal equality")
require_text(CORE "&f->sourceDrawSurfOrdinal" "draw-surf ordinal ordered digest")
require_text(CORE "<= draws[i - 1u].sourceDrawSurfOrdinal" "strict source order admission")
require_text(CORE "candidate = verifier->expected->entries[verifier->cursor]" "Peek immutable expected entry")
require_text(CORE "verifier->cursor++;" "Commit-only verifier advance")
require_text(CORE "if ( facts->gpuDirect != qtrue ) return TEMPORAL_IQM_PRODUCT_NONE;" "CPU IQM remains generic")
require_text(CORE "facts->entityIndex == facts->worldEntityIndex" "world entity rejection")
require_text(CORE "(uint32_t)facts->entityIndex >= TEMPORAL_IQM_ENTITY_INDEX_LIMIT" "entity bound rejection")
require_text(CORE "facts->ordinaryAvailable == qtrue" "GPU-direct ordinary availability gate")
foreach(field IN ITEMS h5Eligible entityExact modelExact geometryExact
	opaqueStage0Exact bindlessExact)
	require_text(CORE "facts->${field} == qtrue" "GPU-direct exact admission field")
endforeach()
require_text(TEST "CHECK( verifier.cursor == 0 )" "Peek does not consume")
require_text(TEST "CHECK( verifier.cursor == 1 )" "Commit consumes exactly one")
require_text(TEST "sourceDrawSurfOrdinal = draws[0].sourceDrawSurfOrdinal" "duplicate source order mutation")
require_text(TEST "temporalIqmSequence_t replacement;" "same-address coherent sequence replacement mutation")
require_text(TEST "&& verifier.poisoned" "stale borrowed verifier fails closed")
require_text(TEST "TestProductAdmission" "product admission mutation host")
require_text(TEST "mutation.gpuDirect = qfalse" "CPU IQM NONE mutation")
require_text(TEST "facts.entityIndex = 0" "entity zero admission")
require_text(TEST "mutation.entityIndex = mutation.worldEntityIndex" "world entity rejection mutation")
require_text(TEST "temporalIqmProductAdmissionFacts_t mixed[2]" "mixed CPU/GPU list host")
require_text(TEST "CHECK( admitted == 1u )" "CPU IQM exclusion from admitted bound")
require_text(TEST "== TEMPORAL_IQM_PRODUCT_POISON" "GPU-direct partial poison mutation")
require_text(GEOMETRY "ops->matchesNative" "native wrapper identity proof")
require_text(GEOMETRY "ops->candidateOwned" "candidate ownership proof")
forbid_text(GEOMETRY "vk_ral_lookup_buffer" "shadow buffer lookup")
forbid_text(LOADER "vk_ral_lookup_buffer" "shadow buffer lookup")
forbid_text(LOADER "VK_TemporalIqmGeometryEnsureAfterIdle" "premature geometry materialization")
forbid_text(LOADER "VK_TemporalIqmGeometryGetReceipt" "premature geometry publication")
forbid_text(LOADER "VK_TemporalIqmGeometryReleaseAfterIdle" "premature geometry lifecycle wiring")
file(GLOB RENDERER_PRODUCT_C "${ROOT}/code/renderervk/*.c")
foreach(product_file IN LISTS RENDERER_PRODUCT_C)
	if(product_file STREQUAL "${ROOT}/code/renderervk/vk_temporal_iqm_geometry.c")
		continue()
	endif()
	file(READ "${product_file}" product_source)
	if(product_file STREQUAL "${ROOT}/code/renderervk/vk.c")
		foreach(api IN ITEMS VK_TemporalIqmGeometryEnsureAfterIdle
			VK_TemporalIqmGeometryGetReceipt VK_TemporalIqmGeometryReleaseAfterIdle)
			string(REGEX MATCHALL "${api}[(]" bridge_calls "${product_source}")
			list(LENGTH bridge_calls bridge_count)
			if(NOT bridge_count EQUAL 1)
				message(FATAL_ERROR "geometry product bridge inventory drifted ${api}: ${bridge_count}")
			endif()
		endforeach()
		foreach(needle IN ITEMS
			"return Ral_AdoptBuffer( backend, native, bytes, debugName );"
			"ops.destroy = Ral_DestroyBuffer;"
			"Ral_GetBufferHandle( candidate ) == native"
			"Ral_GetBufferSize( candidate ) == (uint64_t)bytes"
			"if ( !wasLive && vk_temporal_iqm_geometry_live_count == UINT32_MAX )")
			require_text(VK "${needle}" "direct geometry product bridge")
		endforeach()
		string(FIND "${VK}" "static ralBuffer_t *vk_temporal_iqm_geometry_adopt" bridge_begin)
		string(FIND "${VK}" "#include \"shaders/spirv/shader_data.c\"" bridge_end)
		if(bridge_begin EQUAL -1 OR bridge_end EQUAL -1 OR NOT bridge_begin LESS bridge_end)
			message(FATAL_ERROR "cannot isolate direct geometry product bridge")
		endif()
		math(EXPR bridge_len "${bridge_end}-${bridge_begin}")
		string(SUBSTRING "${VK}" ${bridge_begin} ${bridge_len} GEOMETRY_BRIDGE)
		forbid_text(GEOMETRY_BRIDGE "vk_ral_lookup_buffer" "shadow geometry adoption")
		continue()
	endif()
	foreach(api IN ITEMS VK_TemporalIqmGeometryEnsureAfterIdle
		VK_TemporalIqmGeometryGetReceipt VK_TemporalIqmGeometryReleaseAfterIdle)
		string(FIND "${product_source}" "${api}(" product_call)
		if(NOT product_call EQUAL -1)
			message(FATAL_ERROR "premature geometry product caller ${api} in ${product_file}")
		endif()
	endforeach()
endforeach()
require_text(VK "vk_destroy_iqm_vbo( outVertBuf, outVertMem, outIdxBuf, outIdxMem );" "command-acquire failure rollback")

string(FIND "${LOADER}" "if ( data->vk_gpu_skinning && data->num_poses > 0 )" gpu_pos)
string(FIND "${LOADER}" "\t\treturn; // skip CPU tessellation" gpu_end)
if(gpu_pos EQUAL -1 OR gpu_end EQUAL -1 OR gpu_end LESS gpu_pos)
	message(FATAL_ERROR "cannot isolate ordinary GPU IQM branch")
endif()
math(EXPR gpu_len "${gpu_end} - ${gpu_pos}")
string(SUBSTRING "${LOADER}" ${gpu_pos} ${gpu_len} GPU_BRANCH)
forbid_text(GPU_BRANCH "myGlMultMatrix" "legacy unflipped GPU MVP")
forbid_text(GPU_BRANCH "ComputePoseMats" "legacy duplicate GPU palette")

# All newly fallible validation is complete before Hunk publication. The tail
# may degrade H5 eligibility, but it cannot return a partially published model.
string(FIND "${LOADER}" "mod->type = MOD_IQM;" publish_pos)
string(FIND "${LOADER}" "\n\treturn qtrue;\n}\n\n/*\n=============\nR_CullIQM" finish_pos)
if(publish_pos EQUAL -1 OR finish_pos EQUAL -1 OR finish_pos LESS publish_pos)
	message(FATAL_ERROR "cannot isolate R_LoadIQM publication tail")
endif()
math(EXPR tail_len "${finish_pos} - ${publish_pos}")
string(SUBSTRING "${LOADER}" ${publish_pos} ${tail_len} PUBLISHED_TAIL)
forbid_text(PUBLISHED_TAIL "return qfalse" "fallible exit after model publication")

message(STATUS "Temporal IQM motion source policy contract: ok")
