file(READ "${ROOT}/code/renderervk/tr_temporal_motion_targets.c" TARGETS)
file(READ "${ROOT}/code/renderervk/vk_temporal_pipeline_cohort.c" COHORT)
file(READ "${ROOT}/code/renderervk/vk.h" VKH)
file(READ "${ROOT}/code/renderervk/vk.c" VKC)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "temporal structural policy: missing ${why}: ${needle}")
	endif()
endfunction()

function(forbid_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(NOT found EQUAL -1)
		message(FATAL_ERROR "temporal structural policy: forbidden ${why}: ${needle}")
	endif()
endfunction()

function(require_count haystack regex expected why)
	string(REGEX MATCHALL "${regex}" matches "${${haystack}}")
	list(LENGTH matches count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "temporal structural policy: ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

# Backend-neutral, transactional owner. The exact usage is pinned by its three
# component tokens because the macro deliberately spans source lines.
require_text(TARGETS "caps->independentBlend" "enabled independent-blend proof")
require_text(TARGETS "caps->maxColorAttachments < 3" "three-target limit gate")
require_text(TARGETS "caps->maxTextureDimension2D" "2D dimension preflight")
require_count(TARGETS "RAL_TEXTURE_USAGE_COLOR_ATTACHMENT" 1 "single color-attachment usage operand")
require_count(TARGETS "RAL_TEXTURE_USAGE_SAMPLED" 1 "single sampled usage operand")
require_count(TARGETS "RAL_TEXTURE_USAGE_TRANSFER_SRC" 1 "single transfer-source usage operand")
forbid_text(TARGETS "RAL_TEXTURE_USAGE_TRANSFER_DST" "unrequested target transfer-destination usage")
forbid_text(TARGETS "RAL_TEXTURE_USAGE_STORAGE" "unrequested target storage usage")
require_text(TARGETS "Ral_TextureFormatSupports( backend, RAL_FORMAT_R16G16_SFLOAT" "velocity format/usage preflight")
require_text(TARGETS "Ral_TextureFormatSupports( backend, RAL_FORMAT_R8_UNORM" "validity format/usage preflight")
require_text(TARGETS "candidate.velocity = Ral_CreateTexture" "candidate-first velocity create")
require_text(TARGETS "candidate.validity = Ral_CreateTexture" "candidate-first validity create")
require_text(TARGETS "candidate.validity == candidate.velocity" "distinct texture wrappers")
require_text(TARGETS "candidate.validityView == candidate.velocityView" "distinct view wrappers")
forbid_text(TARGETS "ral_vulkan_bridge" "backend-specific Vulkan bridge dependency")
forbid_text(TARGETS "Ral_GetTextureImageHandle" "backend-specific native image inspection")
forbid_text(TARGETS "Ral_GetTextureViewHandle" "backend-specific native view inspection")
require_text(TARGETS "targets->validity && targets->validity != targets->velocity" "aliased texture cleanup deduplication")
require_text(TARGETS "targets->validityView && targets->validityView != targets->velocityView" "aliased view cleanup deduplication")
require_text(TARGETS "Ral_DestroyTextureView( targets->velocityView );\n\tif ( targets->validity" "all views destroyed before textures")
require_text(TARGETS "DestroyHandles( targets );\n\t*targets = candidate;" "publish only after complete candidate")

# Shipping exact-three PRESERVE constructor. Aux attachments have explicit zero
# write masks and remain structurally unavailable to ordinary rendering.
require_text(COHORT "candidate.formats[0] = sceneFormat;" "scene attachment first")
require_text(COHORT "candidate.formats[1] = RAL_FORMAT_R16G16_SFLOAT;" "velocity attachment second")
require_text(COHORT "candidate.formats[2] = RAL_FORMAT_R8_UNORM;" "validity attachment third")
require_text(COHORT "candidate.blends[0] = *sceneBlend;" "scene blend exact copy")
require_text(COHORT "candidate.blends[1].colorWriteMask = 0;" "velocity write preserve")
require_text(COHORT "candidate.blends[2].colorWriteMask = 0;" "validity write preserve")
require_text(COHORT "!caps->independentBlend || caps->maxColorAttachments < 3" "shipping factory capability decline")
require_text(COHORT "VK_TemporalPreserveContractBuild( sceneFormat" "shipping factory exact contract")
require_text(COHORT "candidate = exactCreate( &exact, layout, contract.formats, contract.count" "shipping factory exact create")
require_text(COHORT "*outPipeline = candidate;" "shipping factory output-atomic publication")

require_text(VKH "VK_TEMPORAL_PIPELINE_PRESERVE = 0" "append-only preserve slot")
require_text(VKH "VK_TEMPORAL_PIPELINE_WRITE" "reserved write slot")
require_text(VKH "VK_TEMPORAL_PIPELINE_INVALIDATE" "reserved invalidate slot")
require_text(VKH "ral_temporal_handle[ VK_TEMPORAL_PIPELINE_COHORT_COUNT ]" "distinct cohort ownership")
require_text(VKH "float    worldLightParams[4];                    // offset 592, 16 B\n} vkUniform_t;" "unchanged 608-byte draw-uniform tail")
forbid_text(VKH "temporalCurrentMvp" "unconditional temporal uniform payload")
forbid_text(VKH "temporalPreviousMvp" "unconditional temporal uniform payload")
require_text(VKC "VK_TemporalPreservePipelineCreate( backend, base, layout," "shipping wrapper delegates to tested factory")
require_text(VKC "sceneFormat, vk_attachment_format_to_ral( vk.depth_format ), debugName," "shipping wrapper exact depth format")
require_text(VKC "vk_ral_create_pipeline_from_gpinfo_exact, outPipeline" "shipping wrapper exact translator seam")

# Pin every slot lifecycle while keeping generation and binding on the ordinary
# render-pass-indexed handles. No temporal sibling may be selected by production.
require_text(VKC "for ( j = 0; j < VK_TEMPORAL_PIPELINE_COHORT_COUNT; j++ )\n\t\tpipeline->ral_temporal_handle[j] = NULL;" "all-slot allocation initialization")
require_text(VKC "for ( k = 0; k < VK_TEMPORAL_PIPELINE_COHORT_COUNT; k++ ) {\n\t\t\tif ( vk.pipelines[i].ral_temporal_handle[k] != NULL ) {\n\t\t\t\tRal_DestroyPipeline( vk.pipelines[i].ral_temporal_handle[k] );\n\t\t\t\tvk.pipelines[i].ral_temporal_handle[k] = NULL;" "all-slot full destroy")
require_text(VKC "for ( j = 0; j < VK_TEMPORAL_PIPELINE_COHORT_COUNT; j++ ) {\n\t\t\tif ( vk.pipelines[i].ral_temporal_handle[j] != NULL ) {\n\t\t\t\tRal_DestroyPipeline( vk.pipelines[i].ral_temporal_handle[j] );\n\t\t\t\tvk.pipelines[i].ral_temporal_handle[j] = NULL;" "all-slot dynamic rewind")
require_text(VKC "const qboolean built = worldPass ? ( pipeline->ral_handle[ pass ] != NULL )" "ordinary-only generation predicate")
require_text(VKC "ralpipe = vk.pipelines[ pipeline ].ral_handle[ vk.renderPassIndex ];" "ordinary-only bind selection")
require_count(VKC "ral_temporal_handle" 7 "cohort handles occur only in inert lifecycle sites")

# Token authority is global: whitespace or function-pointer indirection must not
# create a hidden allocation, factory call, or bind path in another product TU.
file(GLOB PRODUCT_C "${ROOT}/code/renderervk/*.c")
foreach(path IN LISTS PRODUCT_C)
	get_filename_component(name "${path}" NAME)
	file(READ "${path}" PRODUCT_SOURCE)
	if(name STREQUAL "tr_temporal_motion_targets.c")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsInit" 1 "target Init definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsEnsure" 1 "target Ensure definition token count")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsRelease" 1 "target Release definition token count")
	elseif(name STREQUAL "vk_temporal_motion_materialization.c")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsInit" 1 "A2b target Init authority")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsEnsure" 1 "A2b target Ensure authority")
		require_count(PRODUCT_SOURCE "R_TemporalMotionTargetsRelease" 1 "A2b target Release authority")
	else()
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionTargetsInit" "target Init authority in ${name}")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionTargetsEnsure" "target Ensure authority in ${name}")
		forbid_text(PRODUCT_SOURCE "R_TemporalMotionTargetsRelease" "target Release authority in ${name}")
	endif()
	if(name STREQUAL "vk.c")
		require_count(PRODUCT_SOURCE "vk_temporal_build_preserve_pipeline" 1 "preserve wrapper definition-only token count")
		require_count(PRODUCT_SOURCE "VK_TemporalPreservePipelineCreate" 1 "single wrapper-to-factory token count")
	elseif(name STREQUAL "vk_temporal_pipeline_cohort.c")
		require_count(PRODUCT_SOURCE "VK_TemporalPreservePipelineCreate" 1 "factory definition token count")
		forbid_text(PRODUCT_SOURCE "vk_temporal_build_preserve_pipeline" "preserve wrapper authority in cohort definition TU")
	else()
		forbid_text(PRODUCT_SOURCE "vk_temporal_build_preserve_pipeline" "runtime preserve-builder authority in ${name}")
		forbid_text(PRODUCT_SOURCE "VK_TemporalPreservePipelineCreate" "runtime preserve-factory authority in ${name}")
	endif()
	if(NOT name STREQUAL "vk.c")
		forbid_text(PRODUCT_SOURCE "ral_temporal_handle" "cohort-handle authority outside vk.c in ${name}")
	endif()
endforeach()

forbid_text(TARGETS "Ral_BeginRendering" "motion-target pass activation")
forbid_text(COHORT "Ral_CmdBindPipeline" "pipeline bind activation")
forbid_text(VKC "temporal_segment" "temporal segment activation")
forbid_text(VKC "VK_DYN_PASS_TEMPORAL" "temporal render-pass activation")
forbid_text(VKC "USE_TEMPORAL_MOTION" "temporal shader product mapping")
forbid_text(VKC "temporalCurrentMvp" "unconditional temporal uniform payload")
forbid_text(VKC "temporalPreviousMvp" "unconditional temporal uniform payload")
require_text(BUILD "AUX_SOURCE_DIRECTORY(code/renderervk RENDERER_VK_SRCS)" "renderer product source ownership")
require_text(BUILD "ADD_EXECUTABLE(tr_temporal_motion_targets_test" "target owner host test")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_pipeline_cohort_test" "pipeline cohort host test")

message(STATUS "inert temporal motion structural prerequisite policy: PASS")
