file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.h" VKH)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_backend.c" BACKEND)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_motion_recording.c" RECORD)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_motion_recording.h" RECORD_H)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_motion_sequence.c" SEQUENCE)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_entmat_runtime.c" RUNTIME)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text source needle why)
	string(FIND "${${source}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2c3 policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text source needle why)
	string(FIND "${${source}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2c3 policy forbidden ${why}: ${needle}")
	endif()
endfunction()

# Full authority and fail-atomic non-consuming generation preflight.
foreach(field IN ITEMS token frameId worldIndex width height topologyEpoch planGeneration
		geometryBufferSize uniformItemSize requiredCapacity
		rawEntMatCapacity
		rawEntMatAllocationGeneration payloadAllocationGeneration
		payloadLayoutGeneration targetAllocationGeneration
		pipelineLayoutAllocationGeneration materializationGeneration
		pipelineTableGeneration frameIndex)
	require_text(RECORD_H "${field}" "authority field ${field}")
endforeach()
require_text(RECORD "VK_TemporalEntMatRuntimePeekFrameReceipt" "non-consuming payload receipt preflight")
require_text(RECORD "preflightReceipt.capacity != authority->requiredCapacity" "exact payload capacity")
require_text(RECORD "runtimeReceipt.payloadAllocationGeneration !=\n\t\t\t\tpreflightReceipt.payloadAllocationGeneration" "post-begin receipt identity recheck")
require_text(RECORD "pipelineTable->layoutAllocationGeneration !=\n\t\t\t\tauthority->pipelineLayoutAllocationGeneration" "table/layout identity")
require_text(RECORD "VK_TemporalGenericPipelineTablePreflightSlot" "per actual slot atomic preflight")
require_text(RECORD "pipelineReceipt.tableGeneration !=\n\t\t\t\towner->authority.pipelineTableGeneration" "preflight table generation identity")
require_text(RECORD "!pipelineReceipt.recipeOwnerEpoch" "preflight recipe owner identity")
require_text(RECORD "!pipelineReceipt.factoryAllocationGeneration" "preflight factory identity")
require_text(RECORD "pipelines[0] == pipelines[1] || pipelines[0] == pipelines[2]" "distinct exact3 candidates")
require_text(RECORD "owner->primaryCommandCount == 1" "exactly one primary command receipt")
require_text(RECORD "owner->receipt.ready = qtrue;" "CPU-only ready publication")
require_text(RECORD "VK_TemporalMotionDrawSequenceAppend( &owner->drawSequence" "absolute-slot ordered receipt")
require_text(RECORD "owner->receipt.drawSequence = owner->drawSequence" "ordered sequence publication")
require_text(RECORD "absoluteEntMatSlot >= owner->authority.requiredCapacity" "preserve/exact absolute slot bound")
require_text(SEQUENCE "pipelineReceipt->recipeEntryGeneration" "recipe generation in sequence digest")
forbid_text(RECORD "Ral_Cmd" "command recording authority")
forbid_text(RECORD "Ral_BeginRendering" "pass authority")
forbid_text(RECORD "Ral_CmdBindPipeline" "temporal bind authority")

# Capacity expansion is active-exact-only; OFF/NONE/CONFLICT retain 1024.
require_text(VKC "temporalCapacityRequested =\n\t\tR_TemporalBatchRequestValidateExact( temporalRequest )\n\t\t&& temporalRequest->enabled && vk_entmat_active()" "exact-enabled capacity request")
require_text(VKC "if ( temporalCapacityRequested\n\t\t\t&& !vk_entmat_ensure_temporal_ring( temporalRequiredSlots ) ) {\n\t\ttemporalCapacityRequested = qfalse;" "fail-closed active ring-wide capacity preparation")
require_text(VKC "if ( !temporalCapacityRequested )\n\t\tvk_entmat_ensure_buffer( 1024u );" "OFF 1024 current-slot floor")
require_text(VKC "vk.geometry_buffer_size\n\t\t\t/ (uint64_t)vk.uniform_item_size" "physical capacity proof")
require_text(VKC "required64 <= TEMPORAL_MOTION_PAYLOAD_MAX_SLOTS" "65536 ceiling")
foreach(field IN ITEMS token frameId worldIndex width height topologyEpoch planGeneration)
	require_text(VKC "recordAuthority.${field} = temporalRequest->${field};" "product-authored exact request ${field}")
endforeach()
require_text(VKC "vk_entmat_begin_frame();\n\tvk_temporal_bound_pipeline_slot = UINT32_MAX;" "post-fence cursor/one-shot reset")
require_text(VKC "vk.tess[i].uniform_read_offset = ~0U;" "initial fresh-uniform sentinel")
require_text(VKC "vk.cmd->uniform_read_offset = ~0U;" "per-frame fresh-uniform sentinel")
require_text(VKH "uint32_t        entMatLastUniformOffset;" "duplicate uniform guard state")
require_text(VKC "VK_TemporalEntMatPlanUniformSlot(" "fresh/reuse slot planning")
require_text(VKC "firstInstance = entMatPlan.slot;" "duplicate uniform ordinary-slot reuse")
require_text(VKC "&& vk_temporal_motion_recording.primaryCommandActive\n\t\t\t&& !entMatPlanValid ) {" "active primary invalid slot-plan gate")
require_text(VKC "VK_TemporalMotionRecordingPoison( &vk_temporal_motion_recording );" "active primary invalid slot-plan poison")
require_text(VKC "&& VK_TemporalMotionRecordingIsActive( &vk_temporal_motion_recording )\n\t\t\t&& vk_temporal_motion_recording.primaryCommandActive" "OFF hot-path helper-call guard")

# Product order: Begin before acquire; actual pipeline one-shot; Append before
# infallible mapped entMat copies and slot publication.
string(FIND "${VKC}" "void vk_begin_frame(" frame_pos)
string(SUBSTRING "${VKC}" ${frame_pos} 65000 FRAME)
string(FIND "${FRAME}" "VK_TemporalMotionRecordingBegin(" begin_pos)
string(FIND "${FRAME}" "Ral_AcquireNextImage" acquire_pos)
if(begin_pos LESS 0 OR acquire_pos LESS begin_pos)
	message(FATAL_ERROR "A2c3 policy: recording Begin must precede acquire")
endif()
require_text(VKC "vk_temporal_bound_pipeline_slot = pipeline;\n\tralpipe = vk_gen_pipeline( pipeline );" "actual final pipeline one-shot author")
require_text(VKC "const uint32_t temporalPipelineSlot = vk_temporal_bound_pipeline_slot;" "draw consumes one-shot")
require_text(VKC "vk_temporal_bound_pipeline_slot = UINT32_MAX;" "draw clears one-shot")
string(FIND "${VKC}" "void vk_draw_geometry(" draw_function_pos)
string(SUBSTRING "${VKC}" ${draw_function_pos} 12000 DRAW_BODY)
string(FIND "${DRAW_BODY}" "if ( temporalPrepared && !VK_TemporalMotionRecordingConsumeAt(" append_pos)
string(FIND "${DRAW_BODY}" "memcpy( dst, item->mvp, 64 );" copy_pos)
string(FIND "${DRAW_BODY}" "vk_entmat_publish_shadow_range(" publish_pos)
string(FIND "${DRAW_BODY}" "vk.cmd->entMatSlot = slot + 1;" increment_pos)
string(FIND "${DRAW_BODY}" "vk_issue_geometry_draws( indexed, firstInstance );" draw_pos)
if(append_pos LESS 0 OR copy_pos LESS append_pos OR publish_pos LESS copy_pos
		OR increment_pos LESS publish_pos
		OR draw_pos LESS increment_pos)
	message(FATAL_ERROR "A2c3 policy: prevalidated append < entMat copy < CPU-shadow publish < slot++ < ordinary draw order drift")
endif()

require_text(VKC "vk.renderPassIndex != RENDER_PASS_MAIN" "MAIN-only stage adapter")
require_text(VKC "RDF_TEMPORAL_PRIMARY" "primary marker gate")
require_text(VKC "|| backEnd.refdef.needScreenMap" "original screenmap command exclusion")
require_text(VKC "backEnd.viewParms.portalView != PV_NONE" "portal exclusion")
require_text(VKC "backEnd.viewParms.stereoFrame != STEREO_CENTER" "stereo exclusion")
require_text(VKC "RDF_NOWORLDMODEL" "worldless exclusion")
require_text(VKC "&& !shader->entityMergable" "merged entity identity exclusion")
require_text(VKC "VK_TemporalGenericRecipeTableGetSlotReceipt(" "admitted recipe without exact3 poison detection")
require_text(BACKEND "vk_temporal_motion_begin_primary_command();" "draw-surfs command begin hook")
require_text(BACKEND "vk_temporal_motion_end_primary_command( temporalPrimaryCommand );" "draw-surfs command finish hook")
require_text(RUNTIME "R_TemporalMotionPayloadBeginFrame" "runtime generation-bound begin")
require_text(RUNTIME "R_TemporalMotionPayloadAppendAt" "runtime absolute-slot append")

require_text(BUILD "ADD_EXECUTABLE(vk_temporal_motion_recording_test" "host test registration")
require_text(BUILD "vk_temporal_motion_recording_source_policy_contract" "policy registration")
message(STATUS "A2c3 inert temporal recording policy: PASS")
