cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT is required")
endif()
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_vert.tmpl" VERT)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/gen_frag.tmpl" FRAG)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/shaders.manifest.mjs" MANIFEST)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/compile.mjs" COMPILE)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/shaders/spirv/temporal_generic_catalog.inc" GENERATED_CATALOG)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.h" VKH)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_shader_cohort.c" COHORT)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_catalog.c" GENERIC_CATALOG)
file(READ "${ROOT}/CMakeLists.txt" CMAKE_TEXT)
foreach(needle
    "layout(std430, set = 3, binding = 1) readonly buffer TemporalPayloads"
    "TemporalPayloadRecord temporal = temporalPayloads.temporalPayload[gl_InstanceIndex]"
    "gl_Position = mvp * vec4(in_position, 1.0)"
    "layout(location = 10) out vec4 temporalCurrentClip"
    "layout(location = 11) out vec4 temporalPreviousClip"
    "layout(location = 10) in vec4 temporalCurrentClip"
    "layout(location = 11) in vec4 temporalPreviousClip"
    "temporalCurrentClip.xy / temporalCurrentClip.w"
    "temporalPreviousClip.xy / temporalPreviousClip.w"
    "currentUv - previousUv"
    "out_temporal_velocity = vec2( 0.0 )"
    "out_temporal_validity = 0.0")
  string(FIND "${VERT}\n${FRAG}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "missing temporal shader authority: ${needle}")
  endif()
endforeach()
if(FRAG MATCHES "gl_FragCoord[^\n]*(velocity|currentUv|currentNdc)")
  message(FATAL_ERROR "raster coordinates must not author temporal motion")
endif()
string(FIND "${FRAG}" "void wiredTemporalWriteAux( float coverageConfidence )" helper_start)
if(helper_start EQUAL -1)
  message(FATAL_ERROR "temporal helper missing")
endif()
string(SUBSTRING "${FRAG}" ${helper_start} -1 HELPER_TAIL)
string(FIND "${HELPER_TAIL}" "
#endif

#ifdef USE_DF" helper_len)
if(helper_len EQUAL -1)
  message(FATAL_ERROR "cannot isolate temporal fragment helper")
endif()
string(SUBSTRING "${HELPER_TAIL}" 0 ${helper_len} HELPER)
string(REGEX MATCHALL "out_color[ \t]*=[ \t]*base" scene_writes "${FRAG}")
list(LENGTH scene_writes scene_write_count)
if(NOT scene_write_count EQUAL 1)
  message(FATAL_ERROR "scene result must have exactly one shared out_color = base write")
endif()
string(REGEX MATCHALL "out_color" scene_result_tokens "${FRAG}")
list(LENGTH scene_result_tokens scene_result_token_count)
if(NOT scene_result_token_count EQUAL 2)
  message(FATAL_ERROR "out_color authority must be exactly one declaration plus the canonical scene write")
endif()
if(FRAG MATCHES "out_color[ \t]*(\\.|\\+=|-=|\\*=|/=|\\+\\+|--)")
  message(FATAL_ERROR "out_color gained component, compound or increment authority")
endif()
string(FIND "${FRAG}" "out_color = base;" scene_write_pos)
string(FIND "${FRAG}" "wiredTemporalWriteAux( wiredTemporalAtestConfidence( color0.a ) );" temporal_call_pos)
if(scene_write_pos EQUAL -1 OR temporal_call_pos EQUAL -1 OR NOT scene_write_pos LESS temporal_call_pos)
  message(FATAL_ERROR "temporal auxiliary write must follow the shared scene result")
endif()
if(HELPER MATCHES "out_color|discard")
  message(FATAL_ERROR "temporal helper must not mutate scene color or fragment coverage")
endif()
if(HELPER MATCHES "layout[ \t]*\\([^)]*(set|binding)")
  message(FATAL_ERROR "temporal fragment helper gained descriptor-layout authority")
endif()
foreach(needle
    "wiredTemporalAtestConfidence( float alpha )"
    "abs( alpha - alpha_test_value ) / span"
    "( alpha_test_value - alpha )"
    "( alpha - alpha_test_value )"
    "out_temporal_validity = clamp( coverageConfidence, 0.0, 1.0 )"
    "wiredTemporalWriteAux( 1.0 )")
  string(FIND "${FRAG}" "${needle}" atest_confidence_pos)
  if(atest_confidence_pos EQUAL -1)
    message(FATAL_ERROR "ATEST temporal confidence gate missing: ${needle}")
  endif()
endforeach()
string(REGEX MATCHALL "layout\\(std430, set = 3, binding = 1\\) readonly buffer TemporalPayloads" temporal_payload_decls "${VERT}")
list(LENGTH temporal_payload_decls temporal_payload_decl_count)
if(NOT temporal_payload_decl_count EQUAL 1)
  message(FATAL_ERROR "temporal vertex payload must have exactly one set3/binding1 declaration")
endif()
foreach(needle
    "temporalOutcome != 1u"
    "!wiredTemporalFinite4( temporalCurrentClip )"
    "!wiredTemporalFinite4( temporalPreviousClip )"
    "temporalCurrentClip.w <= 1.0e-6"
    "temporalPreviousClip.w <= 1.0e-6"
    "!wiredTemporalFinite2( currentNdc )"
    "!wiredTemporalFinite2( previousNdc )"
    "!wiredTemporalFinite2( velocity )"
    "currentNdc * 0.5 + vec2( 0.5 )"
    "previousNdc * 0.5 + vec2( 0.5 )"
    "currentUv - previousUv")
  string(FIND "${HELPER}" "${needle}" helper_pos)
  if(helper_pos EQUAL -1)
    message(FATAL_ERROR "temporal math gate missing: ${needle}")
  endif()
endforeach()
if(HELPER MATCHES "gl_FragCoord|currentNdc\\.y[ \t]*=[ \t]*-|previousNdc\\.y[ \t]*=[ \t]*-|vec2\\([ \t]*0\\.5[ \t]*,[ \t]*-0\\.5")
  message(FATAL_ERROR "temporal helper gained raster/Y-flip authority")
endif()
string(REGEX MATCHALL "currentUv" current_uv_uses "${HELPER}")
string(REGEX MATCHALL "previousUv" previous_uv_uses "${HELPER}")
list(LENGTH current_uv_uses current_uv_count)
list(LENGTH previous_uv_uses previous_uv_count)
if(NOT current_uv_count EQUAL 2 OR NOT previous_uv_count EQUAL 2)
  message(FATAL_ERROR "temporal UV gained component access or reassignment")
endif()
if(HELPER MATCHES "currentUv\\.y|previousUv\\.y|currentUv[ \t]*(=|\\+=|-=|\\*=|/=)|previousUv[ \t]*(=|\\+=|-=|\\*=|/=)")
  # The two exact declarations are the sole legal assignments; remove them
  # before applying the mutation scan so later full/component rewrites fail.
  string(REPLACE "vec2 currentUv = currentNdc * 0.5 + vec2( 0.5 );" "" UV_MUTATION_SCAN "${HELPER}")
  string(REPLACE "vec2 previousUv = previousNdc * 0.5 + vec2( 0.5 );" "" UV_MUTATION_SCAN "${UV_MUTATION_SCAN}")
  if(UV_MUTATION_SCAN MATCHES "currentUv\\.y|previousUv\\.y|currentUv[ \t]*(=|\\+=|-=|\\*=|/=)|previousUv[ \t]*(=|\\+=|-=|\\*=|/=)")
    message(FATAL_ERROR "temporal UV gained a Y flip or reassignment")
  endif()
endif()
if("${VERT}\n${FRAG}" MATCHES "noperspective")
  message(FATAL_ERROR "temporal clips must use smooth interpolation")
endif()
string(REGEX MATCHALL "gl_Position[ \t]*=" glpos_writes "${VERT}")
list(LENGTH glpos_writes glpos_count)
if(NOT glpos_count EQUAL 1 OR VERT MATCHES "gl_Position[ \t]*=[^\n]*temporal")
  message(FATAL_ERROR "ordinary jittered raster position authority drifted")
endif()
foreach(needle "temporalGenericPairs" "temporalGenericShaderEntries.length !== 76" "temporalGenericPairs.length !== 40")
  if(NOT MANIFEST MATCHES "${needle}")
    message(FATAL_ERROR "manifest temporal SSOT missing: ${needle}")
  endif()
endforeach()
string(REGEX MATCHALL "VK_TEMPORAL_PAIR\\(" pair_rows "${GENERATED_CATALOG}")
list(LENGTH pair_rows pair_count)
if(NOT pair_count EQUAL 40)
  message(FATAL_ERROR "generated catalog must own exactly 40 compatible pairs")
endif()
string(REGEX MATCHALL "VK_TEMPORAL_BLOB\\([^\n]+_temporal_(motion|write|invalidate)" temporal_blob_rows "${GENERATED_CATALOG}")
list(LENGTH temporal_blob_rows temporal_blob_count)
if(NOT temporal_blob_count EQUAL 76)
  message(FATAL_ERROR "generated catalog must own exactly 76 temporal blobs")
endif()
if(VKC MATCHES "(vert|frag)_tx[012][A-Za-z0-9_]*_temporal_(motion|write|invalidate)")
  message(FATAL_ERROR "definition-only temporal generic blobs must not be eagerly materialized")
endif()
if(NOT COMPILE MATCHES "generated shader outputs are stale" OR NOT COMPILE MATCHES "temporal_generic_catalog.inc")
  message(FATAL_ERROR "--check freshness authority missing")
endif()
if(NOT VKH MATCHES "WIRED_ADVANCED_FOG_UBO_OFFSET[ \t]+608u" OR NOT VKH MATCHES "WIRED_ADVANCED_FOG_UBO_SIZE[ \t]+32u")
  message(FATAL_ERROR "fog UBO constants drifted")
endif()
if(COHORT MATCHES "VK_TEMPORAL_FOG_PUSH" OR COHORT MATCHES "candidate[.]numPushRanges[ \t]*=[ \t]*1u")
  message(FATAL_ERROR "temporal generic cohort regained fog push ownership")
endif()
if(NOT COHORT MATCHES "candidate.numSetLayouts = 4u" OR NOT COHORT MATCHES "candidate.numSetLayouts = 2u")
  message(FATAL_ERROR "generic/IQM recipe shape missing")
endif()
if(NOT CMAKE_TEXT MATCHES "code/render/ral/backends/vulkan/renderer/vk_temporal_shader_cohort.c")
  message(FATAL_ERROR "cohort TU not product-linked")
endif()
file(GLOB PRODUCT_TUS "${ROOT}/code/render/ral/backends/vulkan/renderer/*.c")
foreach(tu IN LISTS PRODUCT_TUS)
  if(tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_shader_cohort.c" OR
     tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_pipeline_factory.c")
    continue()
  endif()
  file(READ "${tu}" text)
  if(text MATCHES "VK_TemporalShaderRecipeBuild")
    message(FATAL_ERROR "runtime recipe authority leaked into ${tu}")
  endif()
endforeach()
foreach(runtime_token "Ral_Create" "Ral_Cmd" "BeginRendering" "Cvar" "R_TemporalMotionPayloadEnsure" "R_TemporalMotionPayloadGetBindGroup" "vkCreateShaderModule" "vkCreatePipelineLayout")
  if(COHORT MATCHES "${runtime_token}" OR GENERIC_CATALOG MATCHES "${runtime_token}")
    message(FATAL_ERROR "definition-only cohort contains runtime authority: ${runtime_token}")
  endif()
endforeach()
foreach(tu IN LISTS PRODUCT_TUS)
  if(tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_catalog.c" OR
     tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_pipeline_factory.c" OR
     tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_recipe_table.c")
    continue()
  endif()
  file(READ "${tu}" text)
  if(tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c")
    string(REGEX MATCHALL "VK_TemporalGenericCatalogSelect" product_selects "${text}")
    list(LENGTH product_selects product_select_count)
    if(NOT product_select_count EQUAL 1)
      message(FATAL_ERROR "vk.c must own exactly one generation-bound A2c2b selector call")
    endif()
    continue()
  endif()
  if(text MATCHES "VK_TemporalGenericCatalogSelect")
    message(FATAL_ERROR "temporal generic selector gained a product caller in ${tu}")
  endif()
endforeach()
file(GLOB_RECURSE ALL_PRODUCT_C "${ROOT}/code/render/ral/backends/vulkan/renderer/*.c")
foreach(tu IN LISTS ALL_PRODUCT_C)
  if(tu MATCHES "/shaders/spirv/shader_data.c$" OR tu STREQUAL "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_catalog.c")
    continue()
  endif()
  file(READ "${tu}" text)
  if(text MATCHES "(vert|frag)_tx[012][A-Za-z0-9_]*_temporal_(motion|write|invalidate)")
    message(FATAL_ERROR "embedded temporal generic blob gained product authority in ${tu}")
  endif()
endforeach()
message(STATUS "vk temporal shader source policy: PASS")
