file(READ "${ROOT}/code/renderervk/vk_temporal_generic_recipe_table.h" HEADER)
file(READ "${ROOT}/code/renderervk/vk_temporal_generic_recipe_table.c" CORE)
file(READ "${ROOT}/code/renderervk/vk_temporal_generic_catalog.c" CATALOG)
file(READ "${ROOT}/code/renderervk/vk.c" VKC)
file(READ "${ROOT}/code/renderervk/vk.h" VKH)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
file(READ "${ROOT}/tests/README.md" README)

function(require_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2c1 policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2c1 policy forbidden ${why}: ${needle}")
	endif()
endfunction()
function(require_count var regex expected why)
	string(REGEX MATCHALL "${regex}" hits "${${var}}")
	list(LENGTH hits count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "A2c1 policy ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

require_text(HEADER "uint32_t specializationWords[VK_GENERIC_TOTAL_SPEC_COUNT];" "owned 16-word specialization")
require_text(HEADER "bindings[VK_TEMPORAL_RECIPE_MAX_VERTEX_BINDINGS]" "owned bindings")
require_text(HEADER "attributes[VK_TEMPORAL_RECIPE_MAX_VERTEX_ATTRIBUTES]" "owned attributes")
require_text(HEADER "vkTemporalGenericRecipeReceipt_t" "public identity receipt")
require_text(HEADER "vkTemporalGenericRecipeView_t" "self-contained rehydration view")
require_text(HEADER "VK_TemporalGenericRecipeBuildView" "synchronous rehydration API")
string(FIND "${HEADER}" "typedef struct {\n\tuint32_t ownerEpoch;\n\tuint32_t slot;\n\tuint32_t entryGeneration;\n\tuint32_t catalogId;\n\tvkTemporalGenericKey_t key;" record_start)
string(FIND "${HEADER}" "} vkTemporalGenericRecipe_t;" record_end)
if(record_start LESS 0 OR record_end LESS record_start)
	message(FATAL_ERROR "A2c1 policy cannot isolate pointer-free recipe")
endif()
math(EXPR record_len "${record_end}-${record_start}")
string(SUBSTRING "${HEADER}" ${record_start} ${record_len} RECORD)
foreach(token IN ITEMS "*" "VkShaderModule" "VkPipelineLayout" "VkPipeline "
		"ralPipeline" "vkTemporalShaderBlob" "Spirv" "pName")
	forbid_text(RECORD "${token}" "native/pointer ownership in recipe")
endforeach()
require_text(CORE "isfinite(rs->depthBiasConstantFactor)" "finite raster validation")
require_text(CORE "isfinite(ms->minSampleShading)" "finite MSAA validation")
require_text(CORE "isfinite(ds->minDepthBounds)" "finite depth validation")
require_text(CORE "PositiveZero( cb->blendConstants[i] )" "canonical blend constants")
string(FIND "${CORE}" "if ( !owner ) return qfalse;" prepare_owner)
string(FIND "${CORE}" "owner->armed = qfalse;" prepare_disarm)
string(FIND "${CORE}" "if ( !capacity || !AuthorityValid( authority ) || !ops" prepare_validate)
if(prepare_owner LESS 0 OR prepare_disarm LESS prepare_owner
		OR prepare_validate LESS prepare_disarm)
	message(FATAL_ERROR "A2c1 policy Prepare must disarm before argument validation")
endif()
require_text(CORE "owner->records[input->slot].valid = qfalse;" "reject/replacement invalidation")
require_text(CORE "owner->lastEntryGeneration == UINT32_MAX" "entry saturation")
require_text(CORE "owner->ownerEpoch == UINT32_MAX" "epoch saturation")
require_text(CORE "if ( !owner->records ) return qtrue;" "OFF eviction no-op")
require_text(CORE "RepairViewPointers( outView );" "post-copy self-pointer repair")
require_text(CORE "VK_GenericTemporalSpecializationValidate( &candidate.gp" "rehydrated specialization validation")
require_text(CATALOG "matches != 1u" "unique reverse pair")
require_text(CATALOG "id != VK_TEMPORAL_GENERIC_CATALOG_COUNT" "exact 40 count")
forbid_text(CATALOG "memcmp(" "padding-sensitive catalog key comparison")

string(FIND "${VKC}" "static qboolean vk_temporal_capture_generic_main_recipe" helper_start)
if(helper_start LESS 0)
	message(FATAL_ERROR "A2c1 policy cannot isolate product helper")
endif()
string(SUBSTRING "${VKC}" ${helper_start} -1 HELPER_TAIL)
string(FIND "${HELPER_TAIL}" "static ralPipeline_t *vk_ral_create_pipeline_from_gpinfo_exact" helper_end)
if(helper_end LESS 0)
	message(FATAL_ERROR "A2c1 policy cannot find helper terminator")
endif()
string(SUBSTRING "${HELPER_TAIL}" 0 ${helper_end} HELPER)
string(FIND "${HELPER}" "base->pStages[0].module" vs_lookup)
string(FIND "${HELPER}" "base->pStages[1].module" fs_lookup)
string(FIND "${HELPER}" "VK_TemporalGenericCatalogIdentify" identify)
string(FIND "${HELPER}" "VK_TemporalGenericRecipeTableCapture" capture)
if(vs_lookup LESS 0 OR fs_lookup LESS vs_lookup OR identify LESS fs_lookup OR capture LESS identify)
	message(FATAL_ERROR "A2c1 policy live VS/FS provenance must precede capture")
endif()
require_text(HELPER "base->layout != vk.pipeline_layout" "generic layout proof")
require_text(VKC "if ( renderPassIndex == RENDER_PASS_MAIN\n\t\t\t\t&& vk.pipelines[ def_index ].ral_handle[ renderPassIndex ] != NULL\n\t\t\t\t&& vk_temporal_generic_recipe_table.armed )\n\t\t\tvk_temporal_capture_generic_main_recipe( def_index, &create_info );"
	"armed MAIN/non-NULL publication call guard")
require_count(VKC "vk_temporal_capture_generic_main_recipe\\(" 2 "one helper and call")
require_count(VKC "VK_TemporalGenericRecipeTablePrepare\\(" 1 "sole product prepare")
require_count(VKC "VK_TemporalGenericRecipeTableCapture\\(" 1 "sole product capture")
require_count(VKC "VK_TemporalGenericRecipeTableGet\\(" 1 "sole product recipe read")
require_count(VKC "VK_TemporalGenericRecipeTableGetSlotReceipt\\(" 3 "materialize/reconcile/draw admission receipt reads")
require_text(VKC "if ( !VK_TemporalGenericPipelineTableSlotReady(\n\t\t\t&vk_temporal_generic_pipeline_table, pipelineSlot ) ) {\n\t\tvkTemporalGenericRecipeReceipt_t recipeReceipt;\n\t\tif ( VK_TemporalGenericRecipeTableGetSlotReceipt(\n\t\t\t\t&vk_temporal_generic_recipe_table, pipelineSlot, &recipeReceipt ) ) {\n\t\t\tVK_TemporalMotionRecordingPoison( &vk_temporal_motion_recording );" "third recipe receipt read is draw-admission poison only")
require_count(VKC "VK_TemporalGenericRecipeBuildView\\(" 1 "sole synchronous product rehydration")
require_count(VKC "VK_TemporalGenericRecipeTableDisarm\\(" 2 "begin/end disarm")
require_count(VKC "VK_TemporalGenericRecipeTableEvictRange\\(" 4 "destroy/rewind/slot/backfill rollback eviction")
require_count(VKC "VK_TemporalGenericRecipeTableRelease\\(" 2 "disable/full reset release")
require_text(VKC "authority.token = temporalRequest->token;" "token authority")
require_text(VKC "authority.frameId = temporalRequest->frameId;" "frame authority")
require_text(VKC "authority.planGeneration = temporalRequest->planGeneration;" "plan authority")
require_text(VKC "materializationReceipt.allocationGeneration" "A2b receipt authority")
string(FIND "${VKC}" "void vk_begin_frame(" frame_start)
string(FIND "${VKC}" "void vk_end_frame(" frame_end)
if(frame_start LESS 0 OR frame_end LESS frame_start)
	message(FATAL_ERROR "A2c1 policy cannot isolate begin-frame")
endif()
math(EXPR frame_len "${frame_end}-${frame_start}")
string(SUBSTRING "${VKC}" ${frame_start} ${frame_len} FRAME)
string(FIND "${FRAME}" "VK_TemporalMotionMaterializationEnsureAfterFence(" materialize)
string(FIND "${FRAME}" "VK_TemporalMotionMaterializationGetReceipt(" receipt)
string(FIND "${FRAME}" "VK_TemporalGenericRecipeTablePrepare(" prepare)
string(FIND "${FRAME}" "Ral_AcquireNextImage" acquire)
if(materialize LESS 0 OR receipt LESS materialize OR prepare LESS receipt OR acquire LESS prepare)
	message(FATAL_ERROR "A2c1 policy materialize < receipt < prepare < acquire drift")
endif()

require_text(VKC "if ( vk_temporal_generic_recipe_table.armed )\n\t\tVK_TemporalGenericRecipeTableDisarm( &vk_temporal_generic_recipe_table );\n\tif ( vk.frame_count++ )"
	"stereo-safe guarded begin disarm")
require_text(VKC "vk.frame_count = 0;\n\tif ( vk_temporal_generic_recipe_table.armed )\n\t\tVK_TemporalGenericRecipeTableDisarm( &vk_temporal_generic_recipe_table );"
	"guarded end disarm")
require_text(VKC "VK_TemporalGenericRecipeTableRelease(" "disable/reset release")
require_count(VKC "if \\( vk_temporal_generic_recipe_table\\.records \\)" 5
	"OFF guards for three evictions and two releases")
require_count(VKC "if \\( vk_temporal_generic_recipe_table\\.armed \\)" 2
	"OFF guards for begin/end disarm")
string(FIND "${VKC}" "if ( vk_temporal_generic_recipe_table.records )\n\t\t(void)VK_TemporalGenericRecipeTableEvictRange(\n\t\t\t&vk_temporal_generic_recipe_table, 0, vk.pipelines_count" destroy_evict)
string(FIND "${VKC}" "Ral_DestroyPipeline( vk.pipelines[i].ral_handle[j] );" destroy_handle)
if(destroy_evict LESS 0 OR destroy_handle LESS destroy_evict)
	message(FATAL_ERROR "A2c1 policy eviction must precede ordinary destroy")
endif()
string(FIND "${VKC}" "if ( vk_temporal_generic_recipe_table.records )\n\t\t(void)VK_TemporalGenericRecipeTableEvictRange(\n\t\t\t&vk_temporal_generic_recipe_table, vk.pipelines_world_base" rewind_evict)
string(FIND "${VKC}" "memset( &vk.pipelines[i], 0" rewind_memset)
if(rewind_evict LESS 0 OR rewind_memset LESS rewind_evict)
	message(FATAL_ERROR "A2c1 policy rewind eviction must precede memset")
endif()
require_text(VKC "if ( vk_temporal_generic_recipe_table.records )\n\t\t(void)VK_TemporalGenericRecipeTableEvictRange(\n\t\t\t&vk_temporal_generic_recipe_table, vk.pipelines_count,\n\t\t\tvk.pipelines_count + 1u );"
	"guarded slot reuse eviction")
foreach(token IN ITEMS "PipelineFactoryEnsure" "Ral_CreateGraphicsPipeline"
		"Ral_CreateShaderModule" "vkCreateShaderModule" "Ral_BeginRendering"
		"Ral_Cmd" "PayloadAppendAt" "PayloadGetBindGroup" "Cvar")
	forbid_text(CORE "${token}" "GPU/runtime authority in recipe core")
endforeach()
require_text(VKH "_Static_assert( sizeof( vkUniform_t ) == 608" "W-41 payload size")
forbid_text(VKH "vkTemporalGenericRecipeTable" "recipe owner in VK_Pipeline/vk state")

# Only the owner implementation/header and the single vk.c product adapter may
# mention this authority. Bare-token scanning catches whitespace/function-pointer
# call bypasses as well as storage smuggled into another product header.
file(GLOB PRODUCT_C "${ROOT}/code/renderervk/*.c")
file(GLOB PRODUCT_H "${ROOT}/code/renderervk/*.h")
foreach(path IN LISTS PRODUCT_C PRODUCT_H)
	if(path STREQUAL "${ROOT}/code/renderervk/vk_temporal_generic_recipe_table.c"
			OR path STREQUAL "${ROOT}/code/renderervk/vk_temporal_generic_recipe_table.h"
			OR path STREQUAL "${ROOT}/code/renderervk/vk.c")
		continue()
	endif()
	file(READ "${path}" product_source)
	forbid_text(product_source "VK_TemporalGenericRecipeTable" "recipe call authority outside vk.c")
	forbid_text(product_source "vkTemporalGenericRecipeTable" "recipe owner storage outside vk.c")
endforeach()
require_text(BUILD "AUX_SOURCE_DIRECTORY(code/renderervk RENDERER_VK_SRCS)" "product source ownership")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_generic_recipe_table_test" "host target")
require_text(README "vk_temporal_generic_recipe_table_contract" "README registration")
message(STATUS "A2c1 active-only generic recipe capture policy: PASS")
