file(READ "${ROOT}/code/renderervk/vk_temporal_motion_materialization.c" MAT)
file(READ "${ROOT}/code/renderervk/vk_temporal_motion_materialization.h" MAT_H)
file(READ "${ROOT}/code/renderervk/tr_temporal_motion_payload.c" PAYLOAD)
file(READ "${ROOT}/code/renderervk/tr_temporal_motion_payload.h" PAYLOAD_H)
file(READ "${ROOT}/code/renderervk/tr_temporal_motion_targets.c" TARGETS)
file(READ "${ROOT}/code/renderervk/vk_temporal_pipeline_factory.c" FACTORY)
file(READ "${ROOT}/code/renderervk/vk.c" VKC)
file(READ "${ROOT}/code/renderervk/vk.h" VKH)
file(READ "${ROOT}/code/renderervk/vk_temporal_shader_cohort.h" SHADER_COHORT_H)
file(READ "${ROOT}/code/renderervk/tr_init.c" INIT)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2b policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2b policy forbidden ${why}: ${needle}")
	endif()
endfunction()
function(require_count var regex expected why)
	string(REGEX MATCHALL "${regex}" hits "${${var}}")
	list(LENGTH hits count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "A2b policy ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

require_text(PAYLOAD_H "uint32_t layoutAllocationGeneration;" "payload layout generation")
require_text(PAYLOAD "owner->layoutAllocationGeneration == UINT32_MAX" "payload layout generation saturation")
require_text(PAYLOAD "owner->layoutAllocationGeneration = nextLayoutGeneration;" "payload layout publication")
require_text(PAYLOAD "layoutGeneration = owner->layoutAllocationGeneration;" "payload release generation preservation")
require_text(PAYLOAD "R_TemporalMotionPayloadGetLayout" "output-atomic layout getter")
require_text(FACTORY "generation = owner->allocationGeneration;" "pipeline-layout release generation preservation")

string(FIND "${TARGETS}" "targets->ready && targets->backend == backend" target_hit)
string(FIND "${TARGETS}" "caps = Ral_GetCaps( backend );" target_caps)
if(target_hit LESS 0 OR target_caps LESS target_hit)
	message(FATAL_ERROR "A2b policy: exact target hit must precede capability queries")
endif()
require_text(TARGETS "AliasesLiveTexture( targets, candidate.velocity )" "live velocity alias rejection")
require_text(TARGETS "AliasesLiveView( targets, candidate.velocityView )" "live velocity-view alias rejection")
require_text(TARGETS "DestroyCandidate( &candidate, targets );" "live-safe candidate cleanup")

foreach(field IN ITEMS backend device borrowedSets payload worldIndex width height topologyEpoch planGeneration fog)
	require_text(MAT_H "${field}" "aggregate key field ${field}")
endforeach()
require_text(MAT "owner->ready = qfalse;" "failed-attempt receipt invalidation")
string(FIND "${MAT}" "resourceEqual = ResourceKeyEqual" resource_equal)
string(FIND "${MAT}" "owner->allocationGeneration == UINT32_MAX" aggregate_max)
string(FIND "${MAT}" "R_TemporalMotionTargetsEnsure( &owner->targets" target_ensure)
string(FIND "${MAT}" "VK_TemporalPipelineLayoutEnsure( &owner->pipelineLayout" layout_ensure)
string(FIND "${MAT}" "owner->payloadLayout = payloadLayout;" aggregate_publish)
if(resource_equal LESS 0 OR aggregate_max LESS resource_equal
		OR target_ensure LESS aggregate_max OR layout_ensure LESS target_ensure
		OR aggregate_publish LESS layout_ensure)
	message(FATAL_ERROR "A2b policy: semantic refresh/max/targets/layout/publish order drift")
endif()
require_text(MAT "if ( resourceEqual )" "semantic-only refresh branch")
require_text(MAT "owner->pipelineLayout.allocationGeneration" "pipeline-layout generation receipt")
require_text(MAT "owner->targets.allocationGeneration" "target generation receipt")
require_text(MAT "view.velocityView = owner->targets.velocityView;"
	"generation-bound velocity sampling view")
require_text(MAT "view.validityView = owner->targets.validityView;"
	"generation-bound validity sampling view")
require_text(MAT "VK_TemporalPipelineLayoutRelease( &owner->pipelineLayout" "layout-first release")
require_text(MAT "R_TemporalMotionTargetsRelease( &owner->targets );" "target release")

foreach(token IN ITEMS "PipelineFactoryEnsure" "GenericPipelineFactoryEnsure"
		"IqmPipelineFactoryEnsure" "vkCreateShaderModule" "Ral_CreateShaderModule"
		"Ral_BeginRendering" "Ral_Cmd" "PayloadBeginFrame" "PayloadAppendAt"
		"PayloadGetBindGroup" "VK_TemporalPipelineLayoutAcquire")
	forbid_text(MAT "${token}" "activation authority")
endforeach()

require_text(VKC "VK_TemporalEntMatRuntimeEnsureAfterFence(" "A2a-first Ensure")
require_text(VKC "temporalRequest->width == (uint32_t)vk.renderWidth" "physical width equality")
require_text(VKC "temporalRequest->height == (uint32_t)vk.renderHeight" "physical height equality")
require_text(VKC "input.borrowedSets[0] = vk.set_layout_uniform;" "ordinary set0 borrowing")
require_text(VKC "vk_ral_get_bindless_layout()" "RAL bindless set1 borrowing")
require_text(VKC "input.borrowedSets[2] = vk.set_layout_engine_resources;" "ordinary set2 borrowing")
require_text(VKC "#if FEAT_FOG_SYSTEM\n\t\t\t\tinput.fog = qtrue;\n#else\n\t\t\t\tinput.fog = qfalse;" "build-exact fog shape")
require_text(VKH "#define WIRED_FOG_PUSH_OFFSET          64" "ordinary fog push offset")
require_text(VKH "#define WIRED_FOG_PUSH_SIZE            32" "ordinary fog push size")
require_text(SHADER_COHORT_H "#define VK_TEMPORAL_FOG_PUSH_OFFSET 64u" "temporal fog push offset")
require_text(SHADER_COHORT_H "#define VK_TEMPORAL_FOG_PUSH_SIZE 32u" "temporal fog push size")
require_text(VKC "_Static_assert( WIRED_FOG_PUSH_OFFSET == VK_TEMPORAL_FOG_PUSH_OFFSET" "compiled fog offset ABI equality")
require_text(VKC "_Static_assert( WIRED_FOG_PUSH_SIZE == VK_TEMPORAL_FOG_PUSH_SIZE" "compiled fog size ABI equality")
require_text(VKC "VK_TemporalMotionMaterializationNeedsIdle(" "replacement idle query")
require_text(VKC "VK_TemporalMotionMaterializationEnsureAfterFence(" "sole production materialization")

string(FIND "${VKC}" "void vk_begin_frame(" frame_start)
string(SUBSTRING "${VKC}" ${frame_start} 30000 FRAME)
string(FIND "${FRAME}" "VK_TemporalEntMatRuntimeEnsureAfterFence(" a2a_ensure)
string(FIND "${VKC}" "R_TemporalMotionTargetsEnsure" forbidden_direct_target)
string(FIND "${FRAME}" "VK_TemporalMotionMaterializationEnsureAfterFence(" a2b_ensure)
string(FIND "${FRAME}" "Ral_AcquireNextImage" acquire)
if(a2a_ensure LESS 0 OR a2b_ensure LESS a2a_ensure OR acquire LESS a2b_ensure
		OR NOT forbidden_direct_target EQUAL -1)
	message(FATAL_ERROR "A2b policy: A2a < aggregate < acquire order or target authority drift")
endif()

string(FIND "${VKC}" "static void vk_temporal_entmat_release_after_idle(" release_start)
string(FIND "${VKC}" "void vk_temporal_motion_release_before_ral_shutdown(" release_end)
if(release_start LESS 0 OR release_end LESS release_start)
	message(FATAL_ERROR "A2b policy: cannot isolate centralized release")
endif()
math(EXPR release_len "${release_end}-${release_start}")
string(SUBSTRING "${VKC}" ${release_start} ${release_len} RELEASE)
string(FIND "${RELEASE}" "VK_TemporalMotionMaterializationReleaseAfterIdle(" release_layout)
string(FIND "${RELEASE}" "VK_TemporalEntMatRuntimeReleaseAfterIdle(" release_entmat)
string(FIND "${RELEASE}" "Ral_WaitIdleAndDrainDeferred" release_drain)
if(release_layout LESS 0 OR release_entmat LESS release_layout OR release_drain LESS release_entmat)
	message(FATAL_ERROR "A2b policy: layout/targets < A2a/payload < deferred drain order drift")
endif()
string(FIND "${INIT}" "vk_temporal_motion_release_before_ral_shutdown();" pre_ral_release)
string(FIND "${INIT}" "vk_ral_textures_shutdown( code != REF_LEVEL_ONLY );" ral_shutdown)
if(pre_ral_release LESS 0 OR ral_shutdown LESS pre_ral_release)
	message(FATAL_ERROR "A2b policy: temporal release must precede borrowed RAL layout shutdown")
endif()
require_text(INIT "if ( code != REF_LEVEL_ONLY )" "level-only retention gate")

file(GLOB PRODUCT_C "${ROOT}/code/renderervk/*.c")
foreach(path IN LISTS PRODUCT_C)
	get_filename_component(name "${path}" NAME)
	file(READ "${path}" SRC)
	if(name STREQUAL "vk_temporal_motion_materialization.c")
		require_count(SRC "VK_TemporalMotionMaterializationEnsureAfterFence" 1 "aggregate Ensure definition")
	elseif(name STREQUAL "vk.c")
		require_count(SRC "VK_TemporalMotionMaterializationEnsureAfterFence" 1 "sole aggregate product call")
	else()
		forbid_text(SRC "VK_TemporalMotionMaterializationEnsureAfterFence" "aggregate authority in ${name}")
	endif()
endforeach()

require_text(BUILD "AUX_SOURCE_DIRECTORY(code/renderervk RENDERER_VK_SRCS)" "product source ownership")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_motion_materialization_test" "aggregate host test")
message(STATUS "A2b inert temporal materialization policy: PASS")
