file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_entmat_adoption.h" OWNER_H)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_entmat_adoption.c" OWNER_C)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.h" VKH)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(found EQUAL -1)
		message(FATAL_ERROR "temporal entMat adoption policy: missing ${why}: ${needle}")
	endif()
endfunction()

function(forbid_text haystack needle why)
	string(FIND "${${haystack}}" "${needle}" found)
	if(NOT found EQUAL -1)
		message(FATAL_ERROR "temporal entMat adoption policy: forbidden ${why}: ${needle}")
	endif()
endfunction()

function(require_count haystack regex expected why)
	string(REGEX MATCHALL "${regex}" matches "${${haystack}}")
	list(LENGTH matches count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "temporal entMat adoption policy: ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

require_text(OWNER_H "#define VK_TEMPORAL_ENTMAT_MAX_SLOTS 4u" "bounded command-slot owner")
require_text(OWNER_H "void *nativeBuffer;\n\tsize_t size;\n\tralBuffer_t *adopted;\n\tuint32_t allocationGeneration;" "exact raw allocation identity")
require_text(OWNER_H "qboolean consumerDetached;" "release retry completion receipt")
require_text(OWNER_H "qboolean releasing;" "partial-release state")
require_text(OWNER_H "consumerRebind" "transactional consumer publication callback")
require_text(OWNER_H "consumerDetach" "borrowed wrapper detach callback")
require_text(OWNER_H "ReleaseAfterIdle" "explicit idle-authority teardown")

require_text(OWNER_C "frameIndex >= frameCount || owner->releasing" "Reset validates before configuring and blocks release")
require_text(OWNER_C "!slot->resetAfterFence || slot->begun" "Ensure requires completed-fence grant")
require_text(OWNER_C "allocationGeneration == 0 || allocationGeneration == UINT32_MAX" "reserved generation rejection")
require_text(OWNER_C "nativeBuffer != slot->nativeBuffer || size != slot->size" "same-generation exact identity")
require_text(OWNER_C "allocationGeneration < slot->allocationGeneration" "stale generation rejection")
require_text(OWNER_C "owner->slots[i].nativeBuffer == nativeBuffer" "cross-slot native alias rejection")
require_text(OWNER_C "WrapperIsLive( owner, candidate )" "cross-slot wrapper alias rejection")
require_text(OWNER_C "(void *)candidate == nativeBuffer" "raw handle cannot masquerade as adopted wrapper")
require_text(OWNER_C "return ops->consumerRebind( ops->userData, frameIndex,\n\t\t\t\tslot->adopted, slot->allocationGeneration );" "exact-key idempotent consumer refresh")
require_text(OWNER_C "if ( !ops->consumerRebind( ops->userData, frameIndex, candidate," "candidate consumer publication")
require_text(OWNER_C "slot->adopted = candidate;" "candidate owner publication")
require_text(OWNER_C "if ( oldWrapper ) ops->destroy( ops->userData, oldWrapper );" "old wrapper destruction")
string(FIND "${OWNER_C}" "candidate = ops->adopt" adopt_pos)
string(FIND "${OWNER_C}" "if ( !ops->consumerRebind( ops->userData, frameIndex, candidate," rebind_pos)
string(FIND "${OWNER_C}" "slot->adopted = candidate;" publish_pos)
string(FIND "${OWNER_C}" "if ( oldWrapper ) ops->destroy" destroy_pos)
if(adopt_pos LESS 0 OR rebind_pos LESS adopt_pos OR publish_pos LESS rebind_pos OR destroy_pos LESS publish_pos)
	message(FATAL_ERROR "temporal entMat adoption policy: candidate/rebind/publish/old-destroy order drift")
endif()
require_text(OWNER_C "owner->releasing = qtrue;" "release transaction begins")
require_text(OWNER_C "slot->ready && !slot->consumerDetached" "successful detach skip on retry")
require_text(OWNER_C "slot->consumerDetached = qtrue;" "detach completion publication")
require_text(OWNER_C "!owner->configured || owner->releasing" "Get fails closed during partial release")
require_text(OWNER_C "owner->slots[frameIndex].consumerDetached" "Get rejects detached consumer slot")
string(FIND "${OWNER_C}" "ops->consumerDetach" detach_pos)
string(FIND "${OWNER_C}" "for ( i = owner->frameCount; i > 0; --i )" reverse_pos)
if(detach_pos LESS 0 OR reverse_pos LESS detach_pos)
	message(FATAL_ERROR "temporal entMat adoption policy: every detach must precede reverse wrapper teardown")
endif()

foreach(token
		"Ral_CreateBuffer" "Ral_AdoptBuffer" "R_TemporalMotionPayload"
		"Ral_CreateGraphicsPipeline" "Ral_DestroyPipeline" "ralPipeline_t"
		"VkPipeline" "VkShaderModule" "Ral_Cmd" "Ral_BeginRendering"
		"Cvar_" "cvar_t" "r_temporal" "vk_bind_" "vk_draw_")
	forbid_text(OWNER_H "${token}" "runtime/resource authority in owner header")
	forbid_text(OWNER_C "${token}" "runtime/resource authority in owner implementation")
endforeach()

# Product ownership is source-glob based. Only the A2a runtime seam may call or
# store this owner; draw/bind/pass code remains outside its authority.
file(GLOB PRODUCT_C "${ROOT}/code/render/ral/backends/vulkan/renderer/*.c")
foreach(path IN LISTS PRODUCT_C)
	get_filename_component(name "${path}" NAME)
	file(READ "${path}" PRODUCT_SOURCE)
	if(name STREQUAL "vk_temporal_entmat_adoption.c")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionInit" 1 "Init definition count")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionResetAfterFence" 1 "Reset definition count")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionEnsure" 1 "Ensure definition count")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionBeginFrame" 1 "Begin definition count")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionGet" 1 "Get definition count")
		require_count(PRODUCT_SOURCE "VK_TemporalEntMatAdoptionReleaseAfterIdle" 1 "Release definition count")
	elseif(NOT name STREQUAL "vk_temporal_entmat_runtime.c")
		forbid_text(PRODUCT_SOURCE "VK_TemporalEntMatAdoption" "production call/storage authority in ${name}")
		forbid_text(PRODUCT_SOURCE "vkTemporalEntMatAdoption" "production type/storage authority in ${name}")
	endif()
endforeach()
file(GLOB PRODUCT_H "${ROOT}/code/render/ral/backends/vulkan/renderer/*.h")
foreach(path IN LISTS PRODUCT_H)
	get_filename_component(name "${path}" NAME)
	if(NOT name STREQUAL "vk_temporal_entmat_adoption.h"
			AND NOT name STREQUAL "vk_temporal_entmat_runtime.h")
		file(READ "${path}" PRODUCT_HEADER)
		forbid_text(PRODUCT_HEADER "VK_TemporalEntMatAdoption" "product header authority in ${name}")
		forbid_text(PRODUCT_HEADER "vkTemporalEntMatAdoption" "product header storage/type authority in ${name}")
	endif()
endforeach()

# W-41: ordinary draw payload and the existing raw entMat lifecycle stay exact.
require_text(VKH "vec4_t advancedFogColorDensity;                   // offset 608, 16 B\n\tvec4_t advancedFogTypeFarEnabled;                 // offset 624, 16 B\n\tvec4_t emissionRadiance;                          // offset 640, 16 B\n} vkUniform_t;" "intentional 656-byte ordinary draw UBO lighting tail")
require_text(VKC "void vk_entmat_ensure_buffer( uint32_t requiredSlots )" "raw entMat bounded-capacity owner")

require_text(BUILD "AUX_SOURCE_DIRECTORY(code/render/ral/backends/vulkan/renderer RENDERER_VK_SRCS)" "renderer product source ownership")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_entmat_adoption_test" "compiled owner contract")
require_text(BUILD "vk_temporal_entmat_adoption_source_policy_contract" "source-policy registration")

message(STATUS "A2a-only temporal entMat adoption owner policy: PASS")
