cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_resolve_readback.h" H)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_resolve_readback.c" C)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_ral_textures.c" RALTEX)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/tr_backend.c" BACKEND)
file(READ "${ROOT}/tests/vk_temporal_resolve_readback_test.c" TEST)
file(READ "${ROOT}/tests/ral-temporal-projection-check.sh" HARNESS)
file(READ "${ROOT}/tests/make-temporal-iqm-fixture.py" IQM_FIXTURE)
file(READ "${ROOT}/tests/README.md" README)
file(READ "${ROOT}/code/client/cl_input.c" CLIENT_INPUT)
file(READ "${ROOT}/code/cgame/cg_characters.c" CG_CHARACTERS)
file(READ "${ROOT}/code/cgame/cg_players.c" CG_PLAYERS)
file(READ "${ROOT}/code/cgame/cg_local.h" CG_LOCAL)
file(READ "${ROOT}/code/qcommon/common.c" COMMON)
file(READ "${ROOT}/code/server/sv_main.c" SERVER)
file(READ "${ROOT}/code/server/sv_init.c" SERVER_INIT)
file(READ "${ROOT}/code/game/g_main.c" GAME_MAIN)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text variable needle why)
	string(FIND "${${variable}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "H3c policy missing ${why}: `${needle}`")
	endif()
endfunction()
function(forbid_text variable needle why)
	string(FIND "${${variable}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "H3c policy forbidden ${why}: `${needle}`")
	endif()
endfunction()
function(require_order variable first second why)
	string(FIND "${${variable}}" "${first}" first_pos)
	string(FIND "${${variable}}" "${second}" second_pos)
	if(first_pos EQUAL -1 OR second_pos EQUAL -1 OR NOT first_pos LESS second_pos)
		message(FATAL_ERROR "H3c policy order drift ${why}")
	endif()
endfunction()
function(require_count variable regex expected why)
	string(REGEX MATCHALL "${regex}" hits "${${variable}}")
	list(LENGTH hits count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "H3c policy ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()
function(extract_between variable begin end output)
	string(FIND "${${variable}}" "${begin}" begin_pos)
	if(begin_pos EQUAL -1)
		message(FATAL_ERROR "H3c policy cannot find span begin: ${begin}")
	endif()
	string(SUBSTRING "${${variable}}" ${begin_pos} -1 tail)
	string(FIND "${tail}" "${end}" end_pos)
	if(end_pos EQUAL -1)
		message(FATAL_ERROR "H3c policy cannot find span end: ${end}")
	endif()
	string(SUBSTRING "${tail}" 0 ${end_pos} span)
	set(${output} "${span}" PARENT_SCOPE)
endfunction()

require_text(RALTEX "temporal-resolve-arm" "explicit two-capture arm command")
require_text(C "RAL_MEMORY_HOST_COHERENT" "same-slot coherent staging")
require_text(H "VK_TEMPORAL_RESOLVE_READBACK_CORE_MAX 256u" "ratified bounded core")
require_text(H "VK_TEMPORAL_RESOLVE_READBACK_APRON_MIN 4u" "minimum bilinear apron")
require_text(H "VK_TEMPORAL_RESOLVE_READBACK_APRON_MAX 512u" "bounded diagnostic apron")
require_text(H "VK_TEMPORAL_RESOLVE_READBACK_APRON_DIVISOR 4u" "extent-relative apron")
require_text(C "apronW = width / VK_TEMPORAL_RESOLVE_READBACK_APRON_DIVISOR;" "horizontal motion footprint")
require_text(C "apronH = height / VK_TEMPORAL_RESOLVE_READBACK_APRON_DIVISOR;" "vertical motion footprint")
require_text(C "captureW = coreW + 2u * apronW;" "scaled horizontal capture")
require_text(C "captureH = coreH + 2u * apronH;" "scaled vertical capture")
require_text(C "RAL_BUFFER_TRANSFER_DST | RAL_BUFFER_MAP_READ" "WebGPU-valid readback capability")
require_text(C "copy.aspects = aspects;" "explicit portable copy plane publication")
require_text(C "g.currentColorOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "current color plane")
require_text(C "g.previousColorOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "previous color plane")
require_text(C "g.previousDepthOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "R32 history-depth color plane")
require_text(C "g.velocityOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "velocity color plane")
require_text(C "g.validityOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "validity color plane")
require_text(C "g.resolvedOffset, RAL_TEXTURE_ASPECT_COLOR, &g" "resolved color plane")
require_text(C "RestoreCopiedProducts( commandBuffer, products );" "checked-copy failure restore")
require_text(TEST "failCopyAttempt = 3" "mid-copy rejection mutation")
require_text(TEST "eventAspects[9 + i] == expectedAspects[i]" "copy plane mutation matrix")
require_text(C "TransitionReadback( commandBuffer, slot->buffer, slot->bytes" "typed copy/host state transition")
require_text(C "Ral_BufferMapBegin( slot->buffer, &mapRequest, &mapTicket )" "fence-bounded typed map")
require_text(C "Ral_BufferMapUnmap( slot->buffer, &mapTicket )" "map closure before GPU reuse")
require_text(C "owner->slots[i].buffer == candidate" "cross-slot buffer alias rejection")
require_text(C "ProductProtectedSet" "complete borrowed product alias cohort")
require_text(C "VK_TemporalResolveTicketValidateRecordedExact" "canonical H3 ticket validation")
require_text(C "slot->ticket.resolve.committedWriteExpected.source.\n\t\t\t\tstoreOwnerAllocationGeneration ) return qfalse;" "single-bind zero-generation precondition")
require_text(C "expected.committedWriteExpected.source.storeOwnerAllocationGeneration =\n\t\tstoreGeneration;" "canonical Store-generation-only binding")
require_text(C "VK_TemporalResolveTicketEqualExact( &expected, boundResolve )" "bound H3 whole-ticket fieldwise identity")
require_text(C "slot->ticket.resolve = *boundResolve;" "output-atomic bound ticket publication")
require_text(C "if ( !submitted ) {\n\t\tmemset( &slot->ticket, 0, sizeof( slot->ticket ) );\n\t\tslot->state = VK_TEMPORAL_RESOLVE_READBACK_READY;\n\t\treturn qtrue;\n\t}" "exact diagnostic cancellation acknowledgement")
require_text(C "canonicalRecorded.content.submitted = qfalse" "exact submit-bit demotion before parse")
require_text(C "ProductExact( &t->resolve.products, &slot->products )" "fence-time product provenance")
require_text(C "r.validityOther == 0u" "canonical R8 validity gate")
require_text(C "r.acceptedNonzeroVelocity > 0u" "nonzero reprojection witness")
require_text(TEST "content.acceptedInfluence == 1" "synthetic nonzero blend influence")
require_text(C "r.planesPopulated = qtrue" "submitted full-plane copy authority")
require_text(TEST "creates == 1 && maps == 0" "no map during allocation/preparation")
require_text(C "VK_TemporalResolveReadbackFloatToHalfRne" "software binary16 RNE")
require_text(C "jitterTexel[0] = jitterDelta[0] * (float)extent[0];" "shader-exact jitter texel conversion")
require_text(C "motionTexel[0] = velocity[0] * (float)extent[0];" "shader-exact motion texel conversion")
require_text(C "unjittered[0] = (float)pixel[0] - motionTexel[0];" "shader-exact texel subtraction")
require_text(C "result[0] = unjittered[0] + jitterTexel[0];" "shader-exact texel addition")
require_text(C "volatile float fractionX = previousTexel[0] - baseX;" "shader-exact texel fraction")
require_text(C "LinearizeDepthPrecise(" "shader-exact depth round points")
require_text(C "static float MixExpanded(" "precise expanded interpolation")
require_text(C "VK_TemporalResolveReadbackPreviousTexel(" "division-free texel reprojection")
forbid_text(C "currentUv" "normalized color-path coordinates")
forbid_text(C "Ral_MapBuffer(" "persistent legacy map")
forbid_text(C "Ral_UnmapBuffer(" "persistent legacy unmap")
require_text(C "r.acceptedMatches == r.accepted" "precise expanded oracle acceptance")
require_text(C "distance <= 1u" "ratified one-step contraction tolerance")
require_text(C "VerifyZeroFallback" "nonfinite current zero fallback")
require_text(C "VerifyCurrentFallback" "exact current fallback")
require_text(C "width > INT32_MAX || height > INT32_MAX" "signed copy-coordinate bound")
foreach(encoding IN ITEMS DEPTH_D16 DEPTH_X8_D24 DEPTH_D24_S8
		DEPTH_D32 DEPTH_D16_S8 DEPTH_D32_S8)
	require_text(C "VK_TEMPORAL_RESOLVE_${encoding}" "depth decode matrix")
endforeach()
foreach(step IN ITEMS
		"Ral_CmdTransitionTexture( commandBuffer, products->currentColor"
		"Ral_CmdTransitionTexture( commandBuffer, products->previousColor"
		"Ral_CmdTransitionTexture( commandBuffer, products->previousDepth"
		"Ral_CmdTransitionTexture( commandBuffer, products->velocity"
		"Ral_CmdTransitionTexture( commandBuffer, products->validity"
		"Ral_CmdTransitionTexture( commandBuffer, products->resolvedTarget"
		"VK_ACCESS_TRANSFER_WRITE_BIT" "VK_ACCESS_HOST_READ_BIT")
	require_text(C "${step}" "typed copy/barrier trace")
endforeach()
forbid_text(C "VK_TemporalResolveTicket_t ) == 0" "whole-ticket padding comparison")
forbid_text(C "FLT_EPSILON" "float epsilon oracle")

require_text(VKC "vk_temporal_resolve_readback.initialized\n\t\t\t&& vk_temporal_resolve_readback.capturesRemaining" "literal OFF hot-path gate")
extract_between(VKC "static qboolean vk_temporal_resolve_readback_copy_depth("
	"qboolean vk_temporal_resolve_prepare_authority( void )" DEPTH_COPY)
foreach(step IN ITEMS
		"ralTextureAspectFlags_t resourceAspects = RAL_TEXTURE_ASPECT_DEPTH"
		"resourceAspects |= RAL_TEXTURE_ASPECT_STENCIL"
		"Ral_TextureGetResourceState( depth, &priorState, &priorQueue )"
		"Ral_PublishAdoptedTextureState( depth, &priorState, priorQueue )"
		"priorQueue != RAL_QUEUE_GRAPHICS"
		"priorState.usage == RAL_RESOURCE_USAGE_UNDEFINED"
		"priorState.usage == RAL_RESOURCE_USAGE_COPY_SOURCE"
		"transition.before = priorState"
		"transition.after.usage = RAL_RESOURCE_USAGE_COPY_SOURCE"
		"transition.sourceQueue = transition.destinationQueue = RAL_QUEUE_GRAPHICS"
		"Ral_CmdTransitionResources( commandBuffer, &batch )"
		"copy.aspects = RAL_TEXTURE_ASPECT_DEPTH"
		"Ral_CmdCopyTextureToBuffer( commandBuffer, depth"
		"transition.after = priorState"
		"temporal resolve readback depth restore transition failed")
	require_text(DEPTH_COPY "${step}" "portable device-depth copy")
endforeach()
foreach(raw IN ITEMS "VkImageMemoryBarrier" "VkBufferImageCopy"
		"qvkCmdPipelineBarrier" "qvkCmdCopyImageToBuffer"
		"Ral_SetTextureLayout" "Ral_GetCommandBufferHandle"
		"Ral_GetTextureImageHandle" "Ral_GetBufferHandle")
	forbid_text(DEPTH_COPY "${raw}" "raw device-depth copy authority")
endforeach()
require_text(VKC "depthEncoding !=\n\t\t\t\tvk_temporal_resolve_readback_depth_encoding( vk.depth_format )" "immutable depth encoding join")
require_text(VKC "vk_temporal_resolve_frame.readbackRecorded" "record/submit lifecycle latch")
require_order(VKC "VK_TemporalResolveReadbackReleaseAfterIdle(" "VK_TemporalResolveReleaseAfterIdle(" "child before H3 parent")
foreach(mapping IN ITEMS
		"case VK_FORMAT_D16_UNORM: return VK_TEMPORAL_RESOLVE_DEPTH_D16;"
		"case VK_FORMAT_X8_D24_UNORM_PACK32: return VK_TEMPORAL_RESOLVE_DEPTH_X8_D24;"
		"case VK_FORMAT_D24_UNORM_S8_UINT: return VK_TEMPORAL_RESOLVE_DEPTH_D24_S8;"
		"case VK_FORMAT_D32_SFLOAT: return VK_TEMPORAL_RESOLVE_DEPTH_D32;"
		"case VK_FORMAT_D16_UNORM_S8_UINT: return VK_TEMPORAL_RESOLVE_DEPTH_D16_S8;"
		"case VK_FORMAT_D32_SFLOAT_S8_UINT: return VK_TEMPORAL_RESOLVE_DEPTH_D32_S8;")
	require_text(VKC "${mapping}" "exact Vulkan depth mapping")
endforeach()
require_text(VKC "depthEncoding == VK_TEMPORAL_RESOLVE_DEPTH_D16_S8\n\t\t\t|| depthEncoding == VK_TEMPORAL_RESOLVE_DEPTH_D24_S8\n\t\t\t|| depthEncoding == VK_TEMPORAL_RESOLVE_DEPTH_D32_S8" "exact combined depth/stencil transition set")

require_count(VKC "VK_TemporalResolveReadbackArm\\(" 1 "Arm call inventory")
require_count(VKC "VK_TemporalResolveReadbackPrepareAfterFence\\(" 1 "Prepare call inventory")
require_count(VKC "VK_TemporalResolveReadbackRecord\\(" 1 "Record call inventory")
require_count(VKC "VK_TemporalResolveReadbackBindStoreExpected\\(" 1 "Store bind call inventory")
require_count(VKC "VK_TemporalResolveReadbackResolveSubmit\\(" 2
	"single publish and centralized diagnostic-cancel call inventory")
require_text(VKC "temporal resolve readback diagnostic cancel failed" "all-or-fatal diagnostic cancellation")
require_count(VKC "VK_TemporalResolveReadbackCompleteAfterFence\\(" 2 "fence/idle collect inventory")
require_count(VKC "VK_TemporalResolveReadbackHasLive\\(" 2 "lifecycle query inventory")
require_count(VKC "VK_TemporalResolveReadbackReleaseAfterIdle\\(" 1 "release inventory")
file(GLOB PRODUCT_C "${ROOT}/code/render/ral/backends/vulkan/renderer/*.c")
foreach(path IN LISTS PRODUCT_C)
	if(NOT path MATCHES "/vk\\.c$" AND NOT path MATCHES "/vk_temporal_resolve_readback\\.c$")
		file(READ "${path}" OTHER_PRODUCT)
		forbid_text(OTHER_PRODUCT "VK_TemporalResolveReadback" "extra product authority in ${path}")
	endif()
endforeach()

string(FIND "${VKC}" "void vk_begin_frame(" begin_start)
string(FIND "${VKC}" "void vk_end_frame(" end_start)
if(begin_start EQUAL -1 OR end_start EQUAL -1)
	message(FATAL_ERROR "H3c policy cannot isolate frame functions")
endif()
math(EXPR begin_len "${end_start}-${begin_start}")
string(SUBSTRING "${VKC}" ${begin_start} ${begin_len} BEGIN_FRAME)
string(SUBSTRING "${VKC}" ${end_start} -1 END_FRAME)
require_text(BEGIN_FRAME "if ( !vk_slot_wait( vk.cmd_index, &wait_result, &reset_result ) )" "worker wait/reset receipt")
require_order(BEGIN_FRAME "slotFenceCompleted = qtrue;" "vk_temporal_resolve_readback_collect_slot(" "completed slot before H3c collect")
require_order(BEGIN_FRAME "vk_temporal_resolve_readback_collect_slot(" "vk_temporal_resolve_ensure_after_fence(" "collect before H3 ensure/prepare")
require_order(BEGIN_FRAME "vk_temporal_resolve_ensure_after_fence(" "vk_ral_begin_command_exact( vk.cmd->ral_cmd, \"vk_begin_frame\" );" "H3 ensure/prepare before exact RAL BeginCB")
require_order(BACKEND "vk_temporal_recursive_record();" "if ( r_bloom->integer )" "UI H4/H3c before bloom")
require_order(END_FRAME "vk_temporal_recursive_record();" "if ( r_bloom->integer && backEnd.doneSurfaces )" "no-2D H4/H3c before bloom")
string(FIND "${END_FRAME}" "submitResult = Ral_Submit" submit_start)
if(submit_start EQUAL -1)
	message(FATAL_ERROR "H3c policy missing RAL submit seam")
endif()
string(SUBSTRING "${END_FRAME}" ${submit_start} -1 SUBMIT_TAIL)
require_text(SUBMIT_TAIL "vk_temporal_resolved_hdr_resolve_submit(" "successful submit authority before H3/H3c promotion")
require_text(SUBMIT_TAIL "submitResult == ralSuccess ? qtrue : qfalse" "exact submit result passed to promotion")

string(FIND "${VKC}" "static qboolean vk_temporal_resolve_record_or_copy(" record_start)
string(FIND "${VKC}" "// SHADER_MODULE_BL macro retired." record_end)
math(EXPR record_len "${record_end}-${record_start}")
string(SUBSTRING "${VKC}" ${record_start} ${record_len} RECORD_FUNCTION)
require_order(RECORD_FUNCTION "VK_TemporalResolvedHdrRouteSource(" "VK_TemporalResolveReadbackRecord(" "resolved route before H3c record")
require_text(RECORD_FUNCTION "vk_temporal_resolve_readback.initialized\n\t\t\t\t\t&& vk_temporal_resolve_readback.capturesRemaining" "record OFF gate")

string(FIND "${VKC}" "static qboolean vk_temporal_history_prevalidate_submit(" prevalidate_start)
string(FIND "${VKC}" "static qboolean vk_temporal_content_matches_feedback_source(" prevalidate_end)
string(FIND "${VKC}" "static qboolean vk_temporal_resolved_hdr_resolve_submit(" publish_start)
string(FIND "${VKC}" "void vk_temporal_scene_color_attachment_published(" publish_end)
if(prevalidate_start EQUAL -1 OR prevalidate_end EQUAL -1
		OR publish_start EQUAL -1 OR publish_end EQUAL -1)
	message(FATAL_ERROR "H3c policy cannot isolate H4 submit functions")
endif()
math(EXPR prevalidate_len "${prevalidate_end}-${prevalidate_start}")
math(EXPR publish_len "${publish_end}-${publish_start}")
string(SUBSTRING "${VKC}" ${prevalidate_start} ${prevalidate_len} PREVALIDATE_FUNCTION)
string(SUBSTRING "${VKC}" ${publish_start} ${publish_len} PUBLISH_FUNCTION)
require_text(PREVALIDATE_FUNCTION "VK_TemporalResolveResolveSubmit(" "cached exact H3 producer prepromotion")
require_text(PUBLISH_FUNCTION "vkTemporalResolveTicket_t promoted =\n\t\t\tvk_temporal_resolve_frame.prevalidated;" "cached H3 promotion publication")
require_text(PUBLISH_FUNCTION "VK_TemporalResolveReadbackResolveSubmit(" "H3c promotion from cached H3 ticket")

string(FIND "${VKC}" "static qboolean vk_temporal_history_store_feedback(" feedback_start)
string(FIND "${VKC}" "void vk_temporal_recursive_record(" feedback_end)
if(feedback_start EQUAL -1 OR feedback_end EQUAL -1)
	message(FATAL_ERROR "H3c policy cannot isolate H4 Store feedback function")
endif()
math(EXPR feedback_len "${feedback_end}-${feedback_start}")
string(SUBSTRING "${VKC}" ${feedback_start} ${feedback_len} FEEDBACK_FUNCTION)
require_order(FEEDBACK_FUNCTION "VK_TemporalResolveBindStoreExpected(" "VK_TemporalResolveReadbackBindStoreExpected(" "H3 bind before H3c diagnostic bind")
require_order(FEEDBACK_FUNCTION "VK_TemporalResolveReadbackBindStoreExpected(" "R_TemporalHistoryBuildPendingWrite(" "diagnostic bind before pending write")
require_order(FEEDBACK_FUNCTION "R_TemporalHistoryBuildPendingWrite(" "VK_TemporalHistoryStoreRecord(" "pending preflight before Store commands")
require_order(FEEDBACK_FUNCTION "VK_TemporalHistoryStoreRecord(" "R_TemporalBackendStageHistoryWrite(" "Store commands before exact stage")
require_text(FEEDBACK_FUNCTION "vk_temporal_resolve_readback_cancel_recorded();" "diagnostic-only cancellation on bind/Store/stage failure")

require_text(TEST "eventCount == 22" "exact ordered command trace")
require_text(TEST "expectedRestoreDst" "exact restore destination stages")
require_text(TEST "aliasCreate = owner.slots[0].buffer" "cross-slot buffer alias mutation")
require_text(TEST "creates == 1 && maps == 0" "prepare remains unmapped")
require_text(TEST "owner.slots[0].ticket.resolve.content.submitted = qfalse" "content-submit mutation")
require_text(TEST "VK_TemporalResolveReadbackBindStoreExpected(" "Store bind host matrix")
require_text(TEST "storeOwnerAllocationGeneration = 43u" "same/different generation rebind rejection")
require_text(TEST "VK_TemporalResolveReadbackDecodeDepth" "six-format decoder matrix")
require_text(TEST "VK_TemporalResolveReadbackHalfWithinOneStep" "binary16 boundaries")
require_text(TEST "VK_TemporalResolveReadbackPreviousTexel(" "division-free texel witness")
require_text(TEST "out[0] == 3.0f && out[1] == 6.0f" "exact texel arithmetic witness")
require_text(TEST "memset( memory, 0, (size_t)readbackTicket.totalBytes )" "zero-content rejection mutation")
require_text(TEST "content.planesPopulated && !content.ready" "copy-authority/content-validity split")
require_text(TEST "content.zeroFallbackExpected == 1u" "zero fallback witness")
require_text(TEST "content.centerCurrentColor[3] == 0x3c00u" "center color sample")
require_text(TEST "content.centerDepthRaw == 0u" "center raw depth sample")
require_text(TEST "content.centerVelocity[0] == 0x1400u" "center velocity sample")
require_text(TEST "content.centerValidity == 255u" "center validity sample")
require_text(C "r.centerCurrentColor" "fence-complete center color copy")
require_text(C "r.centerDepthRaw" "fence-complete center depth copy")
require_text(C "r.centerVelocity" "fence-complete center velocity copy")
require_text(C "r.centerValidity" "fence-complete center validity copy")
require_text(VKC "temporal-resolve-sample schema=1" "bounded raw sample log")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_resolve_readback_test" "focused host registration")
require_text(HARNESS "ral_dump live temporal-resolve-arm" "runtime explicit arm")
require_text(HARNESS "motion-materialization=" "H3/motion authority schema")
require_text(HARNESS "FAIL temporal resolve/main activation join" "activation cross-receipt join")
require_text(HARNESS "FAIL temporal resolve/history content join" "history cross-receipt join")
require_text(HARNESS "FAIL temporal resolve/routed HDR join" "routed producer cross-receipt join")
require_text(HARNESS "copied_hdr_pat" "exact fallback-copy receipt validation")
require_text(HARNESS "PASS ral-temporal analyzer self-test" "runtime self-mutation gate")
require_text(HARNESS "sv_fps 20; timescale 0.025; fixedtime 1; cl_run 1; print sv_fps; print timescale; print fixedtime; print cl_run; print g_spawnProtect; wait 512; noclip; wait 64; echo Q3_RAL_TEMPORAL_REQUESTED" "synthetic fixed-tick stationary authority")
require_text(HARNESS "set sv_pure 0\\nset g_spawnProtect 0\\nset activeAction" "spawn-shell exclusion in map bootstrap")
require_order(HARNESS "set g_spawnProtect 0" "set activeAction" "spawn-shell exclusion before map action")
require_text(HARNESS "cvar_receipts(\"g_spawnProtect\",[\"0\"],\"2\")" "spawn-shell exclusion receipt")
require_text(HARNESS "spawn-protect" "spawn-shell mutation gate")
require_text(GAME_MAIN "{ &g_spawnProtect,            \"g_spawnProtect\",            \"2\", CVAR_SERVERINFO | CVAR_ARCHIVE, 0, qfalse }" "spawn-shell cvar registration/default")
require_text(HARNESS "log renderer.assets debug" "fixture loader provenance channel")
require_text(HARNESS "fixedtime 0; timescale 1; print fixedtime; print timescale" "synthetic timing cleanup")
require_text(HARNESS "camera-input" "stationary-camera provenance mutation")
require_text(HARNESS "assets-log" "fixture asset-channel mutation")
require_text(HARNESS "WIRED_RENDERER" "current renderer override")
require_text(HARNESS "window-extent schema=3 requested=1280x720 logical=1280x720 pixels=" "deterministic harness extent receipt")
require_text(HARNESS "iqm-generator" "fixture generator provenance")
require_text(HARNESS "iqm-model" "fixture model provenance")
require_text(HARNESS "iqm-character-manifest" "fixture character provenance")
require_text(HARNESS "iqm-texture" "fixture texture provenance")
require_text(HARNESS "FAIL temporal IQM finite scene sample" "fixture scene sample gate")
require_text(HARNESS "FAIL temporal IQM center depth" "fixture depth gate")
require_text(HARNESS "FAIL temporal IQM center velocity" "fixture motion gate")
require_text(IQM_FIXTURE "channel_scale = (0.0, 1.0, 0.0" "bounded lateral root translation")
require_text(IQM_FIXTURE "struct.pack(\"<iI20f\", -1, 1 << 1" "root Y channel mask")
require_text(IQM_FIXTURE "positions = (0.0, -64.0, -32.0," "camera-facing fixture plane minimum")
require_text(IQM_FIXTURE "0.0, 64.0, -32.0," "camera-facing fixture plane maximum")
require_text(IQM_FIXTURE "0.0, 0.0, 96.0)" "camera-facing fixture plane apex")
require_text(IQM_FIXTURE "struct.pack(\"<6I\", 0, 1, 2, 2, 1, 0)" "two-sided fixture winding")
require_text(IQM_FIXTURE "\"  model = { parts = { \\\"body\\\" }, skins = {} },\\n\"" "character body manifest")
require_text(CG_LOCAL "qboolean CG_ParseIQMAnimations( const char *modelName, clientInfo_t *ci );" "shared embedded animation declaration")
require_text(CG_PLAYERS "qboolean CG_ParseIQMAnimations( const char *modelName, clientInfo_t *ci )" "shared embedded animation producer")
require_text(CG_CHARACTERS "if ( !ci->iqmModel || !CG_ParseIQMAnimations( charName, ci ) )" "manifest IQM embedded animation authority")
require_order(CG_CHARACTERS "if ( !ci->iqmModel || !CG_ParseIQMAnimations( charName, ci ) )" "memcpy( ci->animations, mf.animations" "embedded animation before manifest fallback")
require_text(HARNESS "IQM h5a_fixture: mapped 36/36 animations from embedded data" "embedded animation runtime receipt")
require_text(COMMON "CVAR_FLOAT( \"timescale\", \"1\", CVAR_CHEAT | CVAR_SYSTEMINFO" "timescale registration")
require_text(COMMON "CVAR_BOOL( \"fixedtime\", \"0\", CVAR_CHEAT" "fixedtime registration")
require_text(COMMON "if ( com_fixedtime->integer ) {\n\t\tmsec = com_fixedtime->integer;\n\t} else if ( com_timescale->value )" "fixedtime precedence")
require_text(COMMON "if ( msec < 1 && com_timescale->value) {\n\t\tmsec = 1;" "minimum common tick")
require_text(SERVER_INIT "CVAR_INT(    \"sv_fps\",               \"20\"" "default server cadence")
require_text(SERVER "int frameMsec = (1000 / sv_fps->integer) * com_timescale->value;" "scaled integer server tick")
require_text(SERVER "sv.timeResidual += msec;" "server residual accumulation")
require_text(SERVER "while ( sv.timeResidual >= frameMsec )" "server residual consumption")
forbid_text(HARNESS "g_speed" "unconsumed speed cvar injection")
require_text(README "vk_temporal_resolve_readback_contract" "documented H3c contract")

message(STATUS "vk temporal resolve readback policy: PASS")
