cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT required")
endif()
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk.c" VKC)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_pipeline_table.c" CORE)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_pipeline_table.h" HEADER)
file(READ "${ROOT}/code/render/ral/backends/vulkan/renderer/vk_temporal_generic_catalog.c" CATALOG)
file(READ "${ROOT}/CMakeLists.txt" BUILD)
file(READ "${ROOT}/tests/README.md" README)

function(require_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2c2b policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text var needle why)
	string(FIND "${${var}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2c2b policy forbidden ${why}: ${needle}")
	endif()
endfunction()

require_text(HEADER "vkTemporalGenericPipelineFactoryOwner_t factory;" "one canonical exact3 owner per slot")
require_text(HEADER "moduleRegistryGeneration" "module registry identity")
require_text(CORE "VK_TemporalPipelineLayoutAcquire( layoutOwner )" "table guard lease")
require_text(CORE "VK_TemporalGenericPipelineFactoryEnsure" "sole exact3 creation authority")
require_text(CORE "VK_TemporalGenericPipelineTableGetSlotReceipt" "output-atomic activation receipt seam")
require_text(CORE "candidate == guard->ordinary" "ordinary alias rejection")
require_text(CORE "candidate == guard->retainedOrdinary" "retained ordinary alias rejection")
require_text(CORE "slot->ordinaryPipeline == candidate" "cross-slot ordinary alias rejection")
require_text(CORE "slot->factory.pipelines[j] == candidate" "cross-slot alias rejection")
require_text(CORE "VK_TemporalGenericPipelineFactoryRetire" "batched retirement")
require_text(CORE "factoryOps->drain( backend )" "single shared deferred drain")
require_text(CORE "VK_TemporalGenericPipelineFactoryFinalizeAfterDrain" "lease finalization after drain")
require_text(CORE "VK_TemporalCachedMainRebuild" "executable cached MAIN transaction")
require_text(CORE "*ordinaryPipeline = NULL;" "candidate publication isolation")
require_text(CORE "materializeResult == VK_TEMPORAL_CACHED_MAIN_READY" "fresh exact3 success gate")
require_text(CORE "ops->destroy( oldPipeline );" "old MAIN retirement after exact3")
require_text(CORE "*ordinaryPipeline = oldPipeline;" "ordinary rollback")
require_text(CORE "*depthFade = oldDepthFade;" "depth-fade rollback")
require_text(CORE "*pipelineCreateCount = oldCreateCount;" "create-count rollback")
require_text(CATALOG "BlobEqual( record->blob, entry->ordinaryVertex )" "exact VS pointer-size resolution")
require_text(CATALOG "BlobEqual( record->blob, entry->ordinaryFragment )" "exact FS pointer-size resolution")
require_text(CATALOG "vertexMatches != 1u || fragmentMatches != 1u" "unique inverse lookup")

foreach(token IN ITEMS "Ral_Cmd" "BeginRendering" "vkCmd" "Cvar" "qvkCreateShaderModule"
		"vk_shader_blob_record" "PayloadAppendAt" "PayloadGetBindGroup")
	forbid_text(CORE "${token}" "draw/module/runtime authority in pipeline table")
endforeach()

require_text(VKC "candidate.records = vk_shader_blob_table;" "complete current registry view")
require_text(VKC "candidate.ready = qtrue;" "ready registry publication")
require_text(VKC "candidate.complete = qtrue;" "complete registry publication")
require_text(VKC "VK_TemporalGenericCatalogResolveOrdinaryModules" "inverse module resolution")
require_text(VKC "VK_TemporalGenericRecipeBuildView" "pointer-repaired synchronous recipe view")
require_text(VKC "VK_TemporalGenericPipelineTableEnsureSlot" "product exact3 table ensure")
require_text(VKC "vk_temporal_cached_main_materialize" "cached MAIN materialization adapter")
require_text(VKC "retainedOrdinaryPipeline" "retained ordinary routed into alias guard")
require_text(VKC "VK_TemporalCachedMainRebuild(" "product cached MAIN transaction call")
require_text(VKC "VK_TemporalGenericRecipeTableMarkAttempted" "decline retry suppression")
require_text(VKC "if ( factoryAttempted ) deferredWork = qtrue;" "one-shot deferred cleanup without deterministic retry drain")
require_text(VKC "topologyGeneration, NULL, &factoryAttempted" "natural recipe failure classification")

string(FIND "${VKC}" "void vk_begin_frame(" frame_start)
string(FIND "${VKC}" "void vk_end_frame(" frame_end)
if(frame_start LESS 0 OR frame_end LESS frame_start)
	message(FATAL_ERROR "A2c2b policy cannot isolate begin-frame")
endif()
math(EXPR frame_len "${frame_end}-${frame_start}")
string(SUBSTRING "${VKC}" ${frame_start} ${frame_len} FRAME)
string(FIND "${FRAME}" "VK_TemporalMotionMaterializationEnsureAfterFence(" a2b)
string(FIND "${FRAME}" "VK_TemporalGenericRecipeTablePrepare(" recipe_prepare)
string(FIND "${FRAME}" "VK_TemporalGenericPipelineTablePrepare(" table_prepare)
string(FIND "${FRAME}" "vk_temporal_reconcile_generic_main_pipelines(" reconcile)
string(FIND "${FRAME}" "Ral_AcquireNextImage" acquire)
if(a2b LESS 0 OR recipe_prepare LESS a2b OR table_prepare LESS recipe_prepare
		OR reconcile LESS table_prepare OR acquire LESS reconcile)
	message(FATAL_ERROR "A2c2b policy post-fence A2b < recipe < exact3 < reconcile < acquire drift")
endif()

string(FIND "${VKC}" "VK_TemporalGenericPipelineTableReleaseRangeAfterIdle(" range_release)
string(FIND "${VKC}" "VK_TemporalGenericRecipeTableEvictRange(" recipe_evict)
if(range_release LESS 0 OR recipe_evict LESS range_release)
	message(FATAL_ERROR "A2c2b policy exact3 children must retire before recipe eviction")
endif()
require_text(VKC "vk_temporal_pipeline_table_release_after_idle( reason );" "exact3-before-A2b central release")
require_text(VKC "vk_temporal_pipeline_table_release_after_idle(\n\t\t\t\t\t\t\"A2b-resource-replacement\" );" "layout replacement child release")
require_text(VKC "if ( vk_temporal_generic_pipeline_table.slots\n\t\t\t&& VK_TemporalGenericPipelineTableSlotReady" "cold-OFF alloc guard")

forbid_text(VKC "ral_temporal_handle[VK_TEMPORAL_PIPELINE_PRESERVE] =" "double-owned structural alias")
forbid_text(VKC "ral_temporal_handle[VK_TEMPORAL_PIPELINE_WRITE] =" "double-owned structural alias")
forbid_text(VKC "ral_temporal_handle[VK_TEMPORAL_PIPELINE_INVALIDATE] =" "double-owned structural alias")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_generic_pipeline_table_test" "host target")
require_text(README "vk_temporal_generic_pipeline_table_contract" "README registration")
message(STATUS "A2c2b active-only generic exact3 pipeline table policy: PASS")
