cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

set(H "${ROOT}/code/renderervk/vk_temporal_main_activation.h")
set(C "${ROOT}/code/renderervk/vk_temporal_main_activation.c")
set(VK "${ROOT}/code/renderervk/vk.c")
set(BACKEND "${ROOT}/code/renderervk/tr_backend.c")
set(SEQUENCE_H "${ROOT}/code/renderervk/vk_temporal_motion_sequence.h")
set(SEQUENCE_C "${ROOT}/code/renderervk/vk_temporal_motion_sequence.c")
set(READBACK_H "${ROOT}/code/renderervk/vk_temporal_motion_readback.h")
set(READBACK_C "${ROOT}/code/renderervk/vk_temporal_motion_readback.c")
set(RESOLVE_H "${ROOT}/code/renderervk/vk_temporal_resolve.h")
set(RESOLVE_C "${ROOT}/code/renderervk/vk_temporal_resolve.c")
set(RESOLVE_AUTH_H "${ROOT}/code/renderervk/vk_temporal_resolve_authority.h")
set(RESOLVE_AUTH_C "${ROOT}/code/renderervk/vk_temporal_resolve_authority.c")
set(TEST "${ROOT}/tests/vk_temporal_main_activation_test.c")
foreach(path IN ITEMS "${H}" "${C}" "${VK}" "${SEQUENCE_H}" "${SEQUENCE_C}")
	if(NOT EXISTS "${path}")
		message(FATAL_ERROR "missing ${path}")
	endif()
endforeach()
file(READ "${H}" HT)
file(READ "${C}" CT)
file(READ "${VK}" VKT)
file(READ "${BACKEND}" BACKENDT)
file(READ "${SEQUENCE_H}" SEQUENCE_HT)
file(READ "${SEQUENCE_C}" SEQUENCE_CT)
file(READ "${READBACK_C}" READBACK_CT)
file(READ "${RESOLVE_C}" RESOLVE_CT)
file(READ "${RESOLVE_AUTH_C}" RESOLVE_AUTH_CT)
file(READ "${TEST}" TESTT)

function(require_text haystack needle why)
	string(FIND "${haystack}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text haystack needle why)
	string(FIND "${haystack}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "forbidden ${why}: ${needle}")
	endif()
endfunction()
function(require_count haystack needle expected why)
	string(LENGTH "${haystack}" before_len)
	string(REPLACE "${needle}" "" stripped "${haystack}")
	string(LENGTH "${stripped}" after_len)
	string(LENGTH "${needle}" needle_len)
	math(EXPR removed "${before_len} - ${after_len}")
	math(EXPR actual "${removed} / ${needle_len}")
	if(NOT actual EQUAL expected)
		message(FATAL_ERROR "${why}: expected ${expected}, got ${actual}")
	endif()
endfunction()

require_text("${HT}" "ordinary end -> exact3 begin/end ->" "bounded segment topology contract")
require_text("${HT}" "later segments load them" "clear-once auxiliary contract")
forbid_text("${HT}${CT}" "ExpectedSchedule" "precomputed mixed-family schedule")
forbid_text("${HT}${CT}" "kindBits" "precomputed mixed-family kind stream")
require_text("${HT}" "temporalIqmSequenceVerifier_t iqmVerifier" "compact borrowed IQM verifier")
require_text("${HT}" "MAIN activation receipt must not embed per-event storage" "receipt size ABI gate")
require_text("${HT}" "ordered absolute-slot/exact3 sequence agree" "per-draw final correlation contract")
require_text("${CT}" "recordingReceipt->ready" "final CPU receipt gate")
require_text("${CT}" "owner->temporalSegments + owner->iqm.temporalSegments > 0" "no empty combined target publication")
require_text("${CT}" "p[0] != p[1]" "exact3 distinct-handle gate")
require_text("${CT}" "r->tableGeneration == owner->authority.pipelineTableGeneration" "table generation gate")
require_text("${CT}" "candidate.clearAuxiliary = owner->auxiliaryInitialized ? qfalse : qtrue" "first-clear then load")
require_text("${CT}" "TaggedAppend( &taggedCandidate, VK_TEMPORAL_MAIN_EVENT_GENERIC" "online generic tagged append")
require_text("${CT}" "TaggedAppend( &taggedCandidate, VK_TEMPORAL_MAIN_EVENT_IQM" "online IQM tagged append")
require_text("${CT}" "owner->prepared, plan->absoluteEntMatSlot, plan->kind," "generic tagged ordinal/record/recipe operands")
require_text("${CT}" "GenericFamilyDigest(" "generic tagged full family digest")
require_text("${CT}" "plan->ordinal, plan->recordIndex, plan->kind," "IQM tagged ordinal/record/recipe operands")
require_text("${CT}" "IqmFamilyDigest( plan->sequenceDigest, &plan->entry," "IQM tagged full family digest")
require_text("${CT}" "R_TemporalIqmSequenceEntryEqual( &a->entry, &b->entry )" "full IQM plan operand immutability")
require_text("${CT}" "candidate.entry = entry" "plan-owned full immutable IQM entry")
require_text("${CT}" "candidate.payloadGroup = owner->iqm.content.payload.group" "plan-owned payload bind group")
require_text("${CT}" "facts->geometryBackend != (uintptr_t)factory->backend" "geometry/factory backend cohort")
require_text("${CT}" "facts->bindless.setIdentity" "bindless set identity cohort")
require_text("${CT}" "facts->bindless.setGeneration != factory->bindless.setGeneration" "bindless set generation cohort")
require_text("${CT}" "R_TemporalIqmSequenceVerifierBegin( &verifier, sequence )" "pre-command immutable IQM verifier")
require_text("${CT}" "R_TemporalIqmSequenceVerifierPeek(" "observed facts checked without consumption")
require_text("${CT}" "R_TemporalIqmSequenceVerifierCommit(" "post-command verifier advance")
require_text("${CT}" "R_TemporalIqmSequenceVerifierFinish( &verifierCandidate )" "finish-time IQM completeness")
require_text("${CT}" "owner->iqmVerifier.cursor != owner->iqm.prepared" "verifier/receipt ordinal join")
require_text("${CT}" "owner->iqmVerifier.expected == iqmSequence" "canonical borrowed sequence pointer join")
require_text("${CT}" "owner->iqmVerifier.expected, iqmSequence" "finish-time full sequence equality")
require_text("${HT}" "alive and byte-immutable through" "Bind-to-Finish borrowed sequence lifetime")
require_text("${CT}" "TaggedValid( &owner->taggedSequence )" "pre-publication tagged self-validation")
require_text("${CT}" "ActivationReceiptValid( &owner->pendingReceipt )" "pending/submit receipt self-validation")
require_text("${CT}" "ActivationReceiptValid( &owner->receipt )" "committed receipt self-validation")
require_text("${CT}" "content->payload.layout != factory->payloadLayout" "payload/factory layout cohort")
require_text("${CT}" "factory->topologyGeneration != owner->authority.topologyEpoch" "MAIN topology cohort")
require_text("${CT}" "factory->sceneFormat != pass->sceneFormat" "MAIN scene format cohort")
require_text("${CT}" "factory->reversedDepth != pass->reversedDepth" "MAIN depth convention cohort")
require_text("${CT}" "currentFactory->payloadOwner == payloadOwner" "finish-time exact payload owner identity")
require_text("${CT}" "VK_TemporalIqmPayloadContentRevalidate( content, payloadOwner )" "pre-command owner-aware payload ABA gate")
require_text("${CT}" "&owner->iqm.content, payloadOwner )" "finish-time owner-aware payload ABA gate")
require_text("${CT}" "ops->revalidateGeometry( context, &entry->facts, &geometry )" "live geometry receipt callback")
require_text("${CT}" "GeometryMatchesFacts( &geometry, &entry->facts )" "live geometry/full facts exact join")
require_text("${CT}" "ops->revalidateBindless( context, &entry->facts, &bindless )" "live bindless receipt callback")
require_text("${CT}" "VK_BindlessPublicationReceiptExact( &entry->facts.bindless, &bindless )" "live bindless full receipt exact join")
require_text("${CT}" "owner->iqmRevalidateContext = revalidateContext" "Bind-pinned live revalidation context")
require_text("${CT}" "owner->iqmRevalidateOps = *revalidateOps" "Bind-pinned live revalidation operations")
require_text("${CT}" "RevalidateIqmEntry( &entry, owner->iqmRevalidateContext," "Plan reuses only Bind-pinned live cohort")
foreach(needle IN ITEMS
	"geometry->key.backend == (ralBackend_t *)facts->geometryBackend"
	"geometry->key.nativeVertexBuffer == (void *)facts->rawVertexBuffer"
	"geometry->key.nativeIndexBuffer == (void *)facts->rawIndexBuffer"
	"geometry->key.vertexBytes == facts->vertexBufferBytes"
	"geometry->key.indexBytes == facts->indexBufferBytes"
	"geometry->key.modelAllocationGeneration == facts->modelAllocationGeneration"
	"geometry->key.geometryGeneration == facts->geometryGeneration"
	"geometry->key.contentDigest == facts->modelContentDigest"
	"geometry->vertex == (ralBuffer_t *)facts->ralVertexBuffer"
	"geometry->index == (ralBuffer_t *)facts->ralIndexBuffer"
	"geometry->allocationGeneration == facts->geometryAllocationGeneration"
	"geometry->ready == qtrue")
	require_text("${CT}" "${needle}" "full live geometry receipt field join")
endforeach()
require_count("${TESTT}" "for ( mutation = 1; mutation <= 12; ++mutation )" 2
	"geometry live mutation matrix must cover Bind and Plan")
require_count("${TESTT}" "for ( mutation = 1; mutation <= 21; ++mutation )" 2
	"bindless live mutation matrix must cover Bind and Plan")
require_text("${TESTT}" "staleLive.geometryMutation = mutation" "geometry live mutation exercised")
require_text("${TESTT}" "staleLive.bindlessMutation = mutation" "bindless live mutation exercised")
require_text("${TESTT}" "sourceDrawSurfOrdinal++" "absolute draw-surf ordinal mutation")
require_text("${TESTT}" "Omission and duplicate observation fail closed" "IQM completeness mutations")
require_text("${TESTT}" "owner.iqmVerifier.cursor == 0" "Peek does not consume")
require_text("${TESTT}" "owner.iqmVerifier.cursor == 1" "Commit advances exactly once")
require_text("${TESTT}" "OracleTaggedAppend( &genericFirstOracle" "independent fixed G-I-G lane oracle")
require_text("${TESTT}" "OracleTaggedAppend( &iqmFirstOracle" "independent fixed I-G lane oracle")
require_text("${TESTT}" "changed.sourceDrawSurfOrdinal = 17" "valid source ordinal lane mutation")
require_text("${TESTT}" "variant.factory.allocationGeneration++" "valid factory lane mutation")
require_text("${TESTT}" "RunMixedGenericIqmGeneric" "independent mixed-order lane oracle")
require_text("${TESTT}" "A two-entry IQM sequence proves G-I-G-I success" "mixed omission/reorder/duplicate matrix")
require_text("${TESTT}" "owner.pendingReceipt.taggedSequence.lane0 = 0" "pending lane-zero mutation")
require_text("${TESTT}" "owner.receipt.taggedSequence.lane1 = 0" "committed lane-zero mutation")
require_text("${CT}" "VK_TemporalMainActivationReceiptExact" "canonical downstream exact receipt API")
require_text("${CT}" "r->slot == pipelineSlot" "exact pipeline-slot receipt")
require_text("${CT}" "owner->requireDepthStencilStore = qtrue" "pre-segmentation depth+stencil STORE requirement")
require_text("${CT}" "candidate.stencilStoreRequired = owner->requireDepthStencilStore" "stencil STORE requirement receipt")
require_text("${CT}" "memset( &owner->drawSequence, 0" "per-transaction sequence reset")
require_text("${CT}" "absoluteEntMatSlot >= owner->authority.requiredCapacity" "absolute entMat capacity gate")
foreach(field IN ITEMS entryGeneration recipeOwnerEpoch recipeEntryGeneration factoryAllocationGeneration catalogId)
	require_text("${CT}" "r->${field}" "exact pipeline receipt ${field}")
endforeach()
require_text("${CT}" "p[0] && p[1] && p[2]" "all exact3 candidates nonnull")
require_text("${CT}" "p[0] != p[1] && p[0] != p[2] && p[1] != p[2]" "all exact3 candidates distinct")
require_text("${CT}" "ops->preflight( preflightContext, pipelineSlot" "atomic receipt+pipeline preflight")
require_text("${CT}" "candidate.absoluteEntMatSlot = absoluteEntMatSlot" "absolute entMat slot authority")
require_text("${CT}" "VK_TemporalMotionDrawSequenceAppend( &drawCandidate" "output-atomic activation ordered draw digest")
require_text("${CT}" "VK_TemporalMotionDrawSequenceEqual( &recordingReceipt->drawSequence" "recording/activation digest equality")
require_text("${CT}" "owner->pendingReceipt = candidate" "authored candidate publication")
require_text("${CT}" "owner->submissionPending = valid" "submission-pending gate")
require_text("${CT}" "if ( submitted && ActivationReceiptValid( &owner->pendingReceipt ) )" "self-valid successful-submit promotion")
require_text("${CT}" "VK_TemporalMainActivationPeekPendingReceipt" "durable readback candidate accessor")
require_text("${SEQUENCE_CT}" "pipelineReceipt->factoryAllocationGeneration" "factory generation in ordered digest")
require_text("${SEQUENCE_CT}" "words[0] = absoluteEntMatSlot" "absolute slot in ordered digest")
require_text("${SEQUENCE_CT}" "words[1] = pipelineSlot" "pipeline slot in ordered digest")
require_text("${SEQUENCE_CT}" "words[2] = (uint32_t)outcome" "outcome in ordered digest")
require_text("${SEQUENCE_CT}" "words[3] = pipelineReceipt ? pipelineReceipt->tableGeneration : 0" "table generation in ordered digest")
require_text("${SEQUENCE_CT}" "words[4] = pipelineReceipt ? pipelineReceipt->entryGeneration : 0" "entry generation in ordered digest")
require_text("${SEQUENCE_CT}" "words[5] = pipelineReceipt ? pipelineReceipt->recipeOwnerEpoch : 0" "recipe owner in ordered digest")
require_text("${SEQUENCE_CT}" "words[6] = pipelineReceipt ? pipelineReceipt->recipeEntryGeneration : 0" "recipe entry in ordered digest")
require_text("${SEQUENCE_CT}" "words[7] = pipelineReceipt ? pipelineReceipt->factoryAllocationGeneration : 0" "factory generation in ordered digest")
require_text("${SEQUENCE_CT}" "words[8] = pipelineReceipt ? pipelineReceipt->catalogId : 0" "catalog identity in ordered digest")
require_text("${SEQUENCE_CT}" "words[9] = sequence->count + 1u" "sequence position domain")

foreach(token IN ITEMS "Ral_BeginRendering" "Ral_EndRendering" "Ral_CmdBind" "Ral_CmdDraw"
		"qvkCmd" "VK_TemporalGenericPipelineFactoryEnsure" "R_TemporalMotionPayloadGetBindGroup"
		"r_temporalInputTest" "Cvar_")
	forbid_text("${CT}" "${token}" "GPU/runtime/cvar authority in pure A2c4a contract")
	forbid_text("${SEQUENCE_CT}" "${token}" "GPU/runtime/cvar authority in draw digest")
endforeach()
require_text("${READBACK_CT}" "VK_TemporalMainActivationReceiptExact(" "readback full activation join")
require_text("${RESOLVE_AUTH_CT}" "receipt.activation = *activation" "resolve authority carries full activation receipt")
require_text("${RESOLVE_AUTH_CT}" "VK_TemporalMainActivationReceiptExact( activation, activation )" "resolve authority full self-validation")
require_text("${RESOLVE_CT}" "VK_TemporalMainActivationReceiptExact(" "resolve submit full activation join")
file(GLOB PRODUCT_C "${ROOT}/code/renderervk/*.c")
file(GLOB PRODUCT_H "${ROOT}/code/renderervk/*.h")
foreach(path IN LISTS PRODUCT_C PRODUCT_H)
	if(path STREQUAL C OR path STREQUAL H OR path STREQUAL VK
			OR path STREQUAL READBACK_C OR path STREQUAL READBACK_H
			OR path STREQUAL RESOLVE_C OR path STREQUAL RESOLVE_H
			OR path STREQUAL RESOLVE_AUTH_C OR path STREQUAL RESOLVE_AUTH_H)
		continue()
	endif()
	file(READ "${path}" text)
	forbid_text("${text}" "VK_TemporalMainActivation" "product call before A2c4b in ${path}")
	forbid_text("${text}" "vkTemporalMainActivation" "product storage before A2c4b in ${path}")
endforeach()

require_text("${VKT}" "VK_TemporalMainActivationBegin(" "sole product begin authority")
require_text("${VKT}" "VK_TemporalMainActivationPlanDraw(" "per-draw product plan authority")
require_text("${VKT}" "VK_TemporalMainActivationCommitDraw(" "post-draw commit authority")
require_text("${VKT}" "VK_TemporalMainActivationFinish(" "CPU receipt correlation")
require_text("${VKT}" "VK_TemporalMainActivationResolveSubmit(" "submit result gate")
require_text("${VKT}" "VK_TemporalMainActivationRequiresDepthStencilStore(" "initial attachment STORE gate")
require_text("${VKT}" "VK_TemporalGenericPipelineTablePreflightSlot(" "atomic product exact3 preflight")
require_text("${VKT}" "submitResult == ralSuccess ? qtrue : qfalse" "successful-submit promotion")
foreach(api IN ITEMS VK_TemporalMainActivationBindIqm
	VK_TemporalMainActivationPlanIqmDraw VK_TemporalMainActivationCommitIqmDraw
	VK_TemporalMainActivationFinishIqm)
	string(REGEX MATCHALL "${api}[(]" iqm_product_calls "${VKT}")
	list(LENGTH iqm_product_calls iqm_product_count)
	if(NOT iqm_product_count EQUAL 1)
		message(FATAL_ERROR "Stage4 IQM product authority drifted ${api}: ${iqm_product_count}")
	endif()
endforeach()
require_text("${VKT}" "if ( !VK_TemporalMainActivationCommitIqmDraw("
	"post-emission IQM commit gate")

# Sequence construction and payload authoring are additionally allowed only in
# vk.c's active-only pre-scan checkpoint. Verifier/Bind/command authority stays
# central-definition-only until the atomic IQM command slice lands.
file(GLOB_RECURSE SHIPPING_SURFACE "${ROOT}/code/*.c" "${ROOT}/code/*.h")
foreach(path IN LISTS SHIPPING_SURFACE)
	if(path STREQUAL "${ROOT}/code/renderervk/tr_temporal_iqm_motion.c"
			OR path STREQUAL "${ROOT}/code/renderervk/tr_temporal_iqm_motion.h"
			OR path STREQUAL "${ROOT}/code/renderervk/vk_temporal_iqm_payload_authoring.c"
			OR path STREQUAL "${ROOT}/code/renderervk/vk_temporal_iqm_payload_authoring.h"
			OR path STREQUAL VK
			OR path STREQUAL C OR path STREQUAL H)
		continue()
	endif()
	file(READ "${path}" iqm_surface)
	foreach(api IN ITEMS R_TemporalIqmSequenceBuild
		R_TemporalIqmSequenceVerifierBegin R_TemporalIqmSequenceVerifierPeek
		R_TemporalIqmSequenceVerifierCommit
		R_TemporalIqmSequenceVerifierFinish VK_TemporalIqmPayloadAuthorBegin
		VK_TemporalIqmPayloadAuthorWrite VK_TemporalIqmPayloadAuthorSeal
		VK_TemporalIqmPayloadAuthorCancel vkTemporalIqmPayloadAuthor_t
		R_TemporalIqmSequenceExact R_TemporalIqmSequenceEntryExact
		R_TemporalIqmSequenceEntryEqual
		VK_TemporalIqmPayloadContentReceiptExact
		VK_TemporalIqmPayloadContentRevalidate
		vkTemporalIqmPayloadContentReceipt_t)
		forbid_text("${iqm_surface}" "${api}" "premature Stage4 author/verifier authority in ${path}")
	endforeach()
endforeach()
require_text("${VKT}" "qboolean vk_temporal_motion_seal_primary( void )"
	"idempotent pre-postprocess seal seam")
require_text("${VKT}" "if ( vk_temporal_motion_seal_attempted )"
	"single seal attempt per command buffer")
string(FIND "${BACKENDT}" "static void RB_TransitionToUI( void )" transition_start)
string(FIND "${BACKENDT}" "static const void *RB_StretchPic" transition_end)
if(transition_start EQUAL -1 OR transition_end LESS_EQUAL transition_start)
	message(FATAL_ERROR "cannot isolate RB_TransitionToUI")
endif()
math(EXPR transition_length "${transition_end} - ${transition_start}")
string(SUBSTRING "${BACKENDT}" ${transition_start} ${transition_length} transition_body)
string(FIND "${transition_body}" "vk_temporal_motion_seal_primary();" seal_pos)
string(FIND "${transition_body}" "vk_temporal_recursive_record();" recursive_pos)
string(FIND "${transition_body}" "if ( r_bloom->integer )" bloom_pos)
if(seal_pos EQUAL -1 OR recursive_pos LESS_EQUAL seal_pos
		OR bloom_pos LESS_EQUAL recursive_pos)
	message(FATAL_ERROR "UI path must seal then run the shared H4 transaction before bloom")
endif()

string(FIND "${VKT}" "void vk_temporal_recursive_record( void )" recursive_start)
string(FIND "${VKT}" "// SHADER_MODULE_BL macro retired." recursive_end)
if(recursive_start EQUAL -1 OR recursive_end LESS_EQUAL recursive_start)
	message(FATAL_ERROR "cannot isolate shared H4 recursive transaction")
endif()
math(EXPR recursive_length "${recursive_end} - ${recursive_start}")
string(SUBSTRING "${VKT}" ${recursive_start} ${recursive_length} recursive_body)
string(FIND "${recursive_body}" "vk_temporal_resolve_prepare_authority();" prepare_pos)
string(FIND "${recursive_body}" "vk_temporal_history_store_prepare()" history_pos)
string(FIND "${recursive_body}" "vk_temporal_resolve_record_or_copy();" producer_pos)
string(FIND "${recursive_body}" "vk_temporal_history_store_feedback(" feedback_pos)
if(prepare_pos EQUAL -1 OR history_pos LESS_EQUAL prepare_pos
		OR producer_pos LESS_EQUAL history_pos OR feedback_pos LESS_EQUAL producer_pos)
	message(FATAL_ERROR "shared H4 order must be authority -> Prepare -> Producer -> Store")
endif()

message(STATUS "vk temporal main activation policy: PASS")
