cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED ROOT)
	message(FATAL_ERROR "ROOT is required")
endif()

file(READ "${ROOT}/code/renderervk/vk.c" VKC)
file(READ "${ROOT}/code/renderervk/vk_ral_textures.c" RALTEX)
file(READ "${ROOT}/code/renderervk/vk_temporal_motion_readback.c" READBACK)
file(READ "${ROOT}/code/renderervk/vk_temporal_motion_readback.h" READBACK_H)
file(READ "${ROOT}/code/renderervk/vk_temporal_main_activation.c" ACTIVATION)
file(READ "${ROOT}/tests/vk_temporal_motion_readback_test.c" TEST)
file(READ "${ROOT}/tests/ral-temporal-projection-check.sh" HARNESS)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text haystack needle why)
	string(FIND "${haystack}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2c4c policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text haystack needle why)
	string(FIND "${haystack}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2c4c policy forbidden ${why}: ${needle}")
	endif()
endfunction()

require_text("${RALTEX}" "temporal-motion-arm" "explicit diagnostic arm command")
require_text("${RALTEX}" "vk_temporal_motion_readback_arm();" "sole arm authority")
require_text("${ACTIVATION}" "VK_TemporalMainActivationPeekPendingReceipt" "authored pre-submit candidate accessor")
require_text("${READBACK}" "RAL_MEMORY_HOST_COHERENT" "coherent fence-delayed mirror")
require_text("${READBACK}" "VK_TEMPORAL_READBACK_MAX_ROI" "bounded ROI")
require_text("${READBACK}" "memset( slot->mapped, 0x7f, (size_t)totalBytes );" "noncanonical R8/NaN-half stale-copy poison")
require_text("${READBACK}" "owner->slots[i].buffer == candidate" "cross-slot buffer alias rejection")
require_text("${READBACK}" "TicketMatchesSlot( slot, frameIndex, &slot->ticket )" "ticket/slot geometry identity")
require_text("${READBACK}" "!fenceProven" "explicit completed-fence proof")
require_text("${READBACK}" "slot->state != VK_TEMPORAL_READBACK_SUBMITTED" "fence-only content read")
require_text("${READBACK}" "VK_TemporalMainActivationReceiptExact(\n\t\t\t\t&slot->ticket.activation, resolvedActivation )" "full candidate/final submit identity")
require_text("${READBACK}" "validity[i] == 255" "canonical validity decoding")
require_text("${READBACK}" "receipt.nonzeroInvalidVelocity == 0" "invalid velocity zero gate")
require_text("${READBACK}" "SnapshotIqmPayload( pendingActivation, &ticket )" "record-bound IQM payload snapshot")
require_text("${READBACK}" "SnapshotIqmPayload( &ticket->activation, &snapshot )" "fence-bound IQM payload resnapshot")
require_text("${READBACK}" "payload->recordBytes != TEMPORAL_IQM_RECORD_SIZE" "exact IQM record size")
require_text("${READBACK}" "payload->recordCapacity != TEMPORAL_IQM_MAX_RECORDS" "fixed IQM record capacity gate")
require_text("${READBACK}" "payload->descriptorRange < (uint64_t)activation->iqm.entityCount\n\t\t\t\t* TEMPORAL_IQM_RECORD_SIZE" "IQM descriptor range gate")
require_text("${READBACK_H}" "iqmCurrentPaletteHash" "current palette hash receipt")
require_text("${READBACK_H}" "iqmPreviousPaletteHash" "previous palette hash receipt")
require_text("${READBACK_H}" "iqmRasterMvpBits[16]" "raster MVP receipt")
require_text("${TEST}" "iqmRecord.currentBones[0][0] = 3.0f" "same-ticket payload mutation rejection")
require_text("${HARNESS}" "FAIL temporal IQM previousPalette2/currentPalette1 chain" "runtime palette chain proof")
require_text("${HARNESS}" "factory=([1-9][0-9]*):([1-9][0-9]*):([1-9][0-9]*) payload-layout=" "runtime factory generation receipt")
require_text("${HARNESS}" "owner=([1-9][0-9]*) slot-generation=([1-9][0-9]*) prepare=([1-9][0-9]*) content=" "runtime payload generation receipt")
foreach(needle IN ITEMS
		"Ral_CmdTransitionTexture( commandBuffer, view->velocity"
		"Ral_CmdTransitionTexture( commandBuffer, view->validity"
		"Ral_CmdCopyTextureToBuffer( commandBuffer, view->velocity"
		"Ral_CmdCopyTextureToBuffer( commandBuffer, view->validity"
		"VK_ACCESS_TRANSFER_WRITE_BIT"
		"VK_ACCESS_HOST_READ_BIT"
		"VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL")
	require_text("${READBACK}" "${needle}" "typed copy/barrier/restore step")
endforeach()
foreach(needle IN ITEMS "qvkCmdCopy" "qvkCmdPipelineBarrier" "Ral_BeginRendering"
		"Ral_CmdBindPipeline" "Ral_CmdDraw" "Cvar_")
	forbid_text("${READBACK}" "${needle}" "GPU/pass/draw/cvar authority")
endforeach()

# Completed slot fence precedes collect; all rendering scopes close before
# candidate snapshot/copy; EndCB follows it. Submit resolves activation first.
string(FIND "${VKC}" "vk_frame_t_after_fence = ri.Microseconds();" fence_pos)
string(FIND "${VKC}" "slotFenceCompleted = qtrue;" fence_grant_pos)
string(FIND "${VKC}" "vk_temporal_motion_readback_collect_slot(\n\t\t\t(uint32_t)vk.cmd_index, slotFenceCompleted );" collect_pos)
if(fence_pos LESS 0 OR fence_grant_pos LESS 0 OR collect_pos LESS fence_pos)
	message(FATAL_ERROR "A2c4c policy fence-before-collect order drift")
endif()
require_text("${VKC}" "vk_temporal_motion_readback.initialized && slotFenceCompleted" "successful-wait collect guard")
require_text("${VKC}" "wait_result == VK_SUCCESS && reset_result == VK_SUCCESS" "worker wait+reset success receipt")
require_text("${VKC}" "if ( !vk_slot_wait( vk.cmd_index, &wait_result, &reset_result ) )" "main-thread worker receipt validation")
string(FIND "${VKC}" "void vk_end_frame( void )" endframe_pos)
if(endframe_pos LESS 0)
	message(FATAL_ERROR "A2c4c policy missing vk_end_frame")
endif()
string(SUBSTRING "${VKC}" ${endframe_pos} 50000 END_FRAME)
string(FIND "${END_FRAME}" "// Diagnostic A2c4c readback." record_pos)
string(FIND "${END_FRAME}" "VK_CHECK( qvkEndCommandBuffer( vk.cmd->command_buffer ) );" endcb_pos)
if(record_pos LESS 0 OR endcb_pos LESS record_pos)
	message(FATAL_ERROR "A2c4c policy closed-scope record-before-EndCB order drift")
endif()
string(FIND "${END_FRAME}" "VK_TemporalMainActivationResolveSubmit(" resolve_activation_pos)
string(FIND "${END_FRAME}" "VK_TemporalMotionReadbackResolveSubmit(" resolve_readback_pos)
if(resolve_activation_pos LESS 0 OR resolve_readback_pos LESS resolve_activation_pos)
	message(FATAL_ERROR "A2c4c policy activation-before-readback submit order drift")
endif()
require_text("${VKC}" "if ( VK_TemporalMotionReadbackIsArmed( &vk_temporal_motion_readback )\n\t\t\t&& vk_temporal_entmat_ring_is_ready() )" "OFF copy and exact ring-ready guard")
require_text("${VKC}" "VK_TemporalMotionReadbackReleaseAfterIdle(" "idle-only release")
require_text("${BUILD}" "ADD_EXECUTABLE(vk_temporal_motion_readback_test" "host contract registration")

message(STATUS "vk temporal motion readback policy: PASS")
