file(READ "${ROOT}/code/renderervk/vk.c" VKC)
file(READ "${ROOT}/code/renderervk/tr_cmds.c" CMDS)
file(READ "${ROOT}/code/renderervk/tr_scene.c" SCENE)
file(READ "${ROOT}/code/renderervk/tr_temporal_input.c" INPUT)
file(READ "${ROOT}/code/renderervk/tr_backend.c" BACKEND)
file(READ "${ROOT}/code/renderervk/vk_temporal_entmat_runtime.c" RUNTIME)
file(READ "${ROOT}/code/renderervk/vk_temporal_entmat_runtime.h" RUNTIME_H)
file(READ "${ROOT}/code/renderervk/tr_temporal_batch_request.c" REQUEST)
file(READ "${ROOT}/code/renderervk/vk.h" VKH)
file(READ "${ROOT}/CMakeLists.txt" BUILD)

function(require_text text needle why)
	string(FIND "${${text}}" "${needle}" pos)
	if(pos EQUAL -1)
		message(FATAL_ERROR "A2a policy missing ${why}: ${needle}")
	endif()
endfunction()
function(forbid_text text needle why)
	string(FIND "${${text}}" "${needle}" pos)
	if(NOT pos EQUAL -1)
		message(FATAL_ERROR "A2a policy forbidden ${why}: ${needle}")
	endif()
endfunction()
function(require_count text needle expected why)
	string(REGEX MATCHALL "${needle}" hits "${${text}}")
	list(LENGTH hits count)
	if(NOT count EQUAL expected)
		message(FATAL_ERROR "A2a policy ${why}: expected ${expected}, got ${count}")
	endif()
endfunction()

require_text(REQUEST "TEMPORAL_BATCH_REQUEST_CONFLICT" "sticky conflict state")
require_text(REQUEST "request->state = TEMPORAL_BATCH_REQUEST_CONSUMED;" "consume-once publication")
require_text(INPUT "pendingPlan.generation" "pending generation provenance")
require_text(INPUT "pendingWidth == diagnostic->width" "pending width provenance")
require_text(INPUT "R_TemporalBatchRequestPublish" "queued authored publication")
require_text(CMDS "R_TemporalBatchRequestConsume" "issue snapshot")
require_text(CMDS "memset( &cmdList->temporalRequest, 0" "issue clear before early returns")
require_text(CMDS "cmd->temporalRequestToken = backEndData->commands.temporalRequest.token;" "draw-buffer token")
require_text(CMDS "&& backEndData->commands.temporalRequest.token == 0" "no normal-frame double reset")
require_text(SCENE "R_TemporalCommandBatchReset();" "next-frame defensive reset")
require_text(BACKEND "cmd->temporalRequestToken == temporalRequest->token" "matching draw-buffer delivery")
require_text(VKC "R_TemporalBatchRequestValidateExact( temporalRequest )" "exact seam validation")
require_text(VKC "vk_entmat_ensure_buffer();" "pre-command raw ensure")
require_text(VKC "if ( !ri.CL_IsMinimized() && !vk.cmd->swapchain_image_acquired )" "acquire follows ensure")
require_text(VKC "VK_CHECK( qvkBeginCommandBuffer" "command begin follows ensure")
require_text(VKC "replacingRawParent" "first-slot retention guard")
require_text(VKC "vk_temporal_entmat_release_after_idle( \"raw-buffer-grow\" );" "child release before old raw")
require_text(VKC "vk_temporal_entmat_release_after_idle( \"full-shutdown\" );" "full shutdown child release")
require_text(VKC "vk_shutdown_entmat_buffers();" "unconditional raw teardown")
require_text(VKH "uint32_t        entMatAllocationGeneration;" "raw allocation generation")
require_text(VKC "TEMPORAL_MOTION_PAYLOAD_MAX_SLOTS" "portable capacity ceiling")
string(FIND "${VKC}" "vk_entmat_ensure_buffer();" ensure_call_first)
math(EXPR ensure_call_tail_start "${ensure_call_first} + 27")
string(SUBSTRING "${VKC}" ${ensure_call_tail_start} -1 ENSURE_CALL_TAIL)
string(FIND "${ENSURE_CALL_TAIL}" "vk_entmat_ensure_buffer();" ensure_call_second)
if(ensure_call_first LESS 0 OR NOT ensure_call_second EQUAL -1)
	message(FATAL_ERROR "A2a policy: expected exactly one pre-command entMat ensure call")
endif()

string(FIND "${VKC}" "void vk_begin_frame(" frame_start)
string(SUBSTRING "${VKC}" ${frame_start} 18000 FRAME_BODY)
require_text(FRAME_BODY "if ( R_TemporalBatchRequestValidateExact( temporalRequest )\n\t\t\t&& !temporalRequest->enabled\n\t\t\t&& vk_temporal_motion_has_live() )" "conjoined exact-disabled A2a/A2b live-owner teardown gate")
require_text(FRAME_BODY "if ( R_TemporalBatchRequestValidateExact( temporalRequest )\n\t\t\t&& temporalRequest->enabled && vk_entmat_active()\n\t\t\t&& vk.cmd->entMatBuf != VK_NULL_HANDLE\n\t\t\t&& vk.cmd->entMatAllocationGeneration\n\t\t\t&& vk.cmd->entMatAllocationGeneration != UINT32_MAX )" "conjoined exact-enabled entity-SSBO allocation gate")
require_text(FRAME_BODY "( (uint64_t)vk.cmd->entMatSize\n\t\t\t\t% (uint64_t)ENTITY_MATRIX_SLOT_BYTES ) == 0\n\t\t\t\t&& capacity64 > 0\n\t\t\t\t&& capacity64 <= TEMPORAL_MOTION_PAYLOAD_MAX_SLOTS" "exact slot modulo and portable ceiling gate")
string(FIND "${FRAME_BODY}" "vk_frame_t_after_fence" frame_fence)
string(FIND "${FRAME_BODY}" "vk_entmat_ensure_buffer();" frame_ensure)
string(FIND "${FRAME_BODY}" "VK_TemporalEntMatRuntimeEnsureAfterFence" frame_runtime)
string(FIND "${FRAME_BODY}" "Ral_AcquireNextImage" frame_acquire)
string(FIND "${FRAME_BODY}" "qvkBeginCommandBuffer" frame_begin_cb)
if(frame_fence LESS 0 OR frame_ensure LESS frame_fence
		OR frame_runtime LESS frame_ensure OR frame_acquire LESS frame_runtime
		OR frame_begin_cb LESS frame_acquire)
	message(FATAL_ERROR "A2a policy: post-fence < entMat/runtime < acquire < BeginCB order drift")
endif()
string(FIND "${VKC}" "void vk_entmat_ensure_buffer" ensure_start)
string(SUBSTRING "${VKC}" ${ensure_start} 7000 ENSURE_BODY)
string(FIND "${ENSURE_BODY}" "vk_temporal_entmat_release_after_idle( \"raw-buffer-grow\" );" grow_release)
string(FIND "${ENSURE_BODY}" "vk_ral_unregister_buffer( vk.cmd->entMatBuf )" grow_unregister)
string(FIND "${ENSURE_BODY}" "qvkDestroyBuffer( vk.device, vk.cmd->entMatBuf" grow_destroy)
if(grow_release LESS 0 OR grow_unregister LESS grow_release OR grow_destroy LESS grow_unregister)
	message(FATAL_ERROR "A2a policy: runtime release/drain must precede old raw unregister/destroy")
endif()
string(FIND "${VKC}" "void vk_shutdown(" shutdown_start)
string(SUBSTRING "${VKC}" ${shutdown_start} 15000 SHUTDOWN_BODY)
string(FIND "${SHUTDOWN_BODY}" "vk_wait_idle();" shutdown_idle)
string(FIND "${SHUTDOWN_BODY}" "vk_temporal_entmat_release_after_idle( \"full-shutdown\" );" shutdown_release)
string(FIND "${SHUTDOWN_BODY}" "vk_shutdown_entmat_buffers();" shutdown_raw)
if(shutdown_idle LESS 0 OR shutdown_release LESS shutdown_idle OR shutdown_raw LESS shutdown_release)
	message(FATAL_ERROR "A2a policy: device idle < runtime release/drain < raw teardown order drift")
endif()
require_text(RUNTIME "Ral_AdoptBuffer" "real adoption callback")
require_text(RUNTIME "Ral_GetBufferHandle" "native identity validation")
require_text(RUNTIME "R_TemporalMotionPayloadEnsure" "payload rebind")
require_text(RUNTIME "R_TemporalMotionPayloadDetachEntityBuffer" "detach-before-wrapper")
foreach(token IN ITEMS "R_TemporalMotionPayloadBeginFrame" "R_TemporalMotionPayloadAppendAt"
		"R_TemporalMotionPayloadGetBindGroup" "R_TemporalMotionTargets"
		"VK_TemporalPipelineLayout" "VK_TemporalPipelineFactory" "Ral_Cmd"
		"Ral_BeginRendering" "vk_bind_" "vk_draw_")
	forbid_text(RUNTIME "${token}" "activation authority")
	forbid_text(RUNTIME_H "${token}" "activation API")
endforeach()
require_text(BUILD "ADD_EXECUTABLE(tr_temporal_batch_request_test" "request test registration")
require_text(BUILD "ADD_EXECUTABLE(vk_temporal_entmat_runtime_test" "runtime test registration")
message(STATUS "temporal entMat A2a production integration policy: PASS")
