name: build

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '*.txt'
      - '.gitignore'
      - 'docs/*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  linux-x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -y install cmake ninja-build libcurl4-openssl-dev \
          mesa-common-dev libxxf86dga-dev libxrandr-dev libxxf86vm-dev \
          libasound-dev libsdl3-dev

    - name: Configure
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

    - name: Verify QVMs
      run: |
        ls build/Release/baseq3/vm/cgame.qvm  && echo "cgame  QVM: OK"
        ls build/Release/baseq3/vm/qagame.qvm && echo "qagame QVM: OK"
        ls build/Release/baseq3/vm/ui.qvm     && echo "ui     QVM: OK"

    - uses: actions/upload-artifact@v4
      if: github.event_name == 'release' || github.event_name == 'push'
      with:
        name: linux-x86_64
        path: |
          build/q3now.x86_64
          build/q3now-ded.x86_64
          build/Release/baseq3/*.so
          build/Release/baseq3/vm/*.qvm
        if-no-files-found: warn
        retention-days: 5

  macos-aarch64:
    name: macOS aarch64
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install cmake ninja sdl3 molten-vk

    - name: Configure
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --parallel

    - name: Verify QVMs
      run: |
        ls build/Release/baseq3/vm/cgame.qvm  && echo "cgame  QVM: OK"
        ls build/Release/baseq3/vm/qagame.qvm && echo "qagame QVM: OK"
        ls build/Release/baseq3/vm/ui.qvm     && echo "ui     QVM: OK"

    - name: Install & Package DMG
      run: make dmg Q3DIR=${{ runner.temp }}/q3now

    - uses: actions/upload-artifact@v4
      if: github.event_name == 'release' || github.event_name == 'push'
      with:
        name: macos-aarch64-dmg
        path: build/*.dmg
        if-no-files-found: error
        retention-days: 5
